### ISSUE TITLE
Support for share-less members

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1021]
#51 introduced recovery shares for each member. However, there may be cases where only _some_ members are privileged enough to be able to recover a crashed service. In this case, only these members should be handed recovery shares. 

Notes:
- When adding a new member, only members that have a public encryption key should be handed recovery shares. Other members should not be counted in the total number of shares generated.
- It should be possible to determine from the Lua constitution whether a member has been given a recoverable key share. 
- If a share-less member is added or removed, there is no need for CCF to issue new share, not re-key the ledger.

**Comment by achamayou** [comment]
It should also be possible to determine in a vote if a member that is proposed for addition (and probably for removal as well) will receive/has a share.

**Comment by achamayou** [comment]
There is no immediate requirement for this, let's re-open if/when needed.

**Comment by achamayou** [comment]
This is necessary to support the operating member governance model, particularly in models where this only a single high-privileged member in charge of recovery (share threshold is effectively one).
