### ISSUE TITLE
Add install procedure in user docs

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1026]
Now that we produce regular releases of an installable version of CCF, we should update our documentation to tell our users how to install and build CCF applications instead of relying on a checkout of this repo.

**Comment by achamayou** [comment]
@jumaffre I think it's not so much instead as it is in addition to, we want to keep the section that essentially explains how to work on/contribute to CCF itself, but have that be clearly separate from how to use CCF to build an application.

The Open Enclave doc splits that between "Getting Started" and "Contributing", which I think is quite a good way to go: https://github.com/openenclave/openenclave#getting-started
