### ISSUE TITLE
Include demo app in CCF install

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1028]
As discussed with @eddyashton, it is currently not easy to test that an install of CCF works successfully (including that the environment is setup correctly) without having to build an application from source, sign it, etc. 

It would be much better for users of the framework to be able to 1) download and install the latest release of CCF, 2) Setup their environment and 3) Test that they can successfully run a CCF network, issuing transactions, etc. This is currently not possible as no application is bundled with the install. 

We could provide a much better user experience by including a demo application in the CCF install. A good candidate for this seems to be our logging application. For now, it seems that the C++ version would be the most appropriate (i.e. closest to what most users are likely to deploy) but the generic JavaScript engine application clearly is the long-term winner here.

I believe that it would be OK to include the signed version of the enclave application (using the signing key checked-in the CCF repo), as well as the virtual version.

**Comment by jumaffre** [comment]
@achamayou commented on #1029: 

> I think the docker image with an authless logging app we talked about yesterday is what we want. We can include both an SGX and a virtual build on there.
We do test the install in our release pipeline, I think that should be sufficient.

I feel like we should discuss these things a little more to make sure the UX is clear for every stakeholder we have (contributors to CCF, app developers, people interested in running a network to get a feel for it, etc.).

**Comment by achamayou** [comment]
Link to #493

**Comment by achamayou** [comment]
We bundle the js_generic runtime now, which I think is a good sample. What we probably need is better documentation for how to use that however: #1386

**Comment by jumaffre** [comment]
@achamayou Do we bundle the same logging JS app as well?
