### ISSUE TITLE
Proposal completion is not atomic

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1031]
The introduction of a `FAILED` state for member proposals has opened up a possible buggy state, where a proposal has been partially applied. Member proposals produce a list of `ProposedCalls`, which call the hardcoded funcs in `member_frontend`. These functions are called, making changes to the KV, iff the proposal gets enough votes to pass the governance script. If one of these proposed calls _fails_ by returning `false`, then we change the proposal's state to `FAILED`, halt further execution, and send a response to the user (a `HTTP 200 OK` containing the proposal state). Any writes made in this proposed call (or prior proposed calls!) will still be applied to the KV, alongside the recorded vote and state change. This is a bad state - proposals should be applied atomically.

A few early thoughts on solutions:
1) `ProposedCall`s don't get to return false, they can only fail by throwing exceptions. This is close to the old behaviour. The vote returns an error response and makes no writes. Only the 'final' voter gets the exception message, their vote is not recorded.
2) `ProposedCall`s are reduced to a form where they cannot fail. Perhaps they are split into a precondition check and some writes. More simply, I think they all become writes, which will be applied blindly on the state at which their proposal is completed. Any checking of preconditions or error reporting must be done by the proposal script and/or votes.
3) We build a richer KV interface that allows a subset of writes to be dropped, so that we can change the proposal state to `FAILED` while not applying any writes from the `ProposedCall`s. This also fixes some potential issues with our conflict-retry logic, where we currently clear the view but this may lose writes from the framework level (ie - client signatures).

**Comment by achamayou** [comment]
1. sounds attractive because it's consistent with what would happen if the vote evaluation itself did fail: an attempt at voting was made, but could not successfully complete. In some cases that means recording the vote, in others that's recording and proposal execution because the vote would pass, but the behaviour is essential the same: the vote and all its side effects are rolled back.

**Comment by achamayou** [comment]
As discussed, let's go with 1.

**Comment by achamayou** [comment]
Addressing this bug can be done without API impact, so it's moved to post 1.0.

**Comment by achamayou** [comment]
So although this would be easier with sub-transaction support, I think we could implement the following flow specifically for `apply()`:

1. try apply()
2. on catch exception
  a. tx.reset() (yes, we'd have to add it back)
  b. record_voting_history() once more
  c. write the ballot again to proposals_info.ballots
  d. write the votes again to proposals_info.final_votes and vote failures to proposals_info.vote_failures
  e. write the exception message to proposals_info.failure

Which sounds like a lot of steps, but is really just setting aside two writes to a single key each under `gov.history` and `gov.proposals_info` to re-apply them with an additional message on top. Am I missing something?

**Comment by achamayou** [comment]
Following discussion, the consensus seems to have shifted closer to option 1:

> ProposedCalls don't get to return false, they can only fail by throwing exceptions. This is close to the old behaviour. The vote returns an error response and makes no writes. Only the 'final' voter gets the exception message, their vote is not recorded.

**Comment by eddyashton** [comment]
Summary of more recent thoughts on this:

<details>
  <summary>Why I don't like a `.reset()` approach</summary>
  
![image](https://user-images.githubusercontent.com/6000239/140948122-a1fb7849-849b-4e73-8cfe-ae0176acf693.png)
</details>

Then I thought we could do sub-transactions, but I was wrong.
It seemed like the sub-transaction model could be implemented pretty easily, because the JS interface for a specific invocation is exactly where we want to draw the boundary, and we already explicitly shim calls to the KV at that point. So if we replaced `kv.put` with an implementation which put all writes in a local list, they could be trivially dropped if any proposal completion failed. _But_, if those proposals call some _other_ APIs (eg `ccf.node.transitionServiceToOpen`), _those_ would not use these shims, so would either not use the sub-transaction or would need a more deeply-implemented sub-transaction. So that still seems out.

And that leaves us with option 1.
