### ISSUE TITLE
Commitability should not be determined by HTTP response status

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1037]
Currently we decide whether to call `kv::commit()` (ie - whether to try and keep a transaction's KV changes) by looking at the HTTP response status. We keep `200 OK`s, and drop everything else (returning the response at this point, without injecting commit headers).

This has 2 big failings:
- Unnecessarily restrictive on accepted statuses. All `2xx` statuses should be considered successes (and our empty responses should become `204 No Content`?)
- Imposes restrictions on supported apps. If an app wants to log data from requests that return errors, it should be able to

`RpcContext::response_is_error` should be extended to handle these cases.

**Comment by achamayou** [comment]
I think we should leave the application free to explicitly apply/rollback, regardless of the HTTP status code (or indeed, whatever application-specific status mechanism is used in WebSockets).

**Comment by eddyashton** [comment]
Yes, I think we should do something like:

```
class RpcContext
{
  ...
  std::optional<bool> apply_results;
  
  bool response_is_error() const
  {
    if (apply_results.has_value())
    {
      return !apply_results.value();
    }
    
    return is_2xx(status);
  }

  void set_apply_results(bool should_apply)
  {
      apply_results = should_apply;
  }
}

[App code]
rpc_ctx->set_apply_results(true);
rpc_ctx->set_response_status(404);
```

So to keep the API simple, by default we will apply any `2xx`s, but app code can override this when it wants to do something else.

**Comment by achamayou** [comment]
I wonder if ->set_apply_writes(true) is more precise?
