### ISSUE TITLE
Only results of first client are uploaded to cimetrics

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1046]
As per https://github.com/microsoft/CCF/pull/1043, we now make use of several clients to test forwarding on multiple backups. However, we only upload the results of the first node to cimetrics are we currently do not aggregate the results of all performance clients.

See #848 for work to be done before resolving this.

**Comment by achamayou** [comment]
Yes, that's currently a problem, as discussed previously we want to follow the approach outlined in #848 which consists of a lighter runner, and a separate, richer analysis pass in a more efficient environment.

**Comment by achamayou** [comment]
Let's address that in #848
