### ISSUE TITLE
Node status endpoint should cover recovery status

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#1052]
The more general point raised by #1045 is that there should be a node status rpc, which reveals its state, public recovery progress and private recovery progress. The tests can then make use of it to become more robust to timeouts, and it's a useful thing for operators to have.

**Comment by eddyashton** [comment]
We currently have a `getCommit` RPC that we're using as a proxy for this kind of node-status query, but it is a) used for multiple unrelated things, and b) requires significant interpretation by clients.

I think it should be replaced by 2 separate RPCs, and one of them is the subject of this issue:
- `/node/getStatus`: Returning an object with as much detail as possible (current recovery stage, current known consensus index, whether this node is the primary, what other nodes it knows about, what state it thinks they're in, etc)

The other is simpler, hopefully replacing some client-side commit reasoning
- '/[all?]/getTxStatus?view=V&index=I`: Returning `Pending`, `Committed`, or `Lost`. This will suffer from the known Raft issue (a new leader doesn't know what the global commit index is), but that's separate and affects existing uses of `global_commit` in just the same way.

**Comment by eddyashton** [comment]
The other existing RPC I'd forgotten about is `/nodes/getSignedIndex`, which tells us some of the node's joining state. We should look at consolidating these, and/or peppering this throughout our tests in the hopes it shines some light on the occasional failures.

**Comment by eddyashton** [comment]
Linking this to #1014 - that talks about _join_ status, while this talks about _recovery_ status, but it makes sense to combine these into a single API endpoint since the responses and intent are generally similar, and this simplifies client logic (single call rather than decision tree of calls).
