### ISSUE TITLE
BFT: Transactions that abort should not cause a view-change

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#1065]
There is a problem when a transaction can be aborted by a user the backup replicas still need to execute said transaction to ensure that it was aborted correctly (the execution was honest). Today when a primary is aborted at the primary it will not be replicated to the back-ups and the backups will cause a view-change because they will expected to see said transaction.

**Comment by olgavrou** [comment]
Is this the same as #763 ?

**Comment by achamayou** [comment]
BFT isn't prioritised in the main repo for now.
