### ISSUE TITLE
User self-registration change requests

### ISSUE THREAD

**Issue by jazzybluesea** [microsoft/CCF#1086]
For user self-registration to work, CCF node/quote.h needs to be changed as follows.

1. Validation of the report_data size removed or changed to check OE_REPORT_DATA_SIZE.

If this change is made the user self-registration will work.

This was using CCF 0.9.2

**Comment by jazzybluesea** [comment]
Update bug after retesting with the latest build.

**Comment by achamayou** [comment]
@jumaffre is that fixed by #1098?
