### ISSUE TITLE
Member CLI to handle encrypted recovery share

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1096]
When a member retrieves their encrypted recovery shares, they need to decrypt the share (using their private encryption key and the network public encryption key) before submitting the decrypted share to CCF. In the e2e Python infra, we currently perform the decryption using `pynacl`. 

However, we should provide a tool for members to do this for the command line. 

Several options:
- Write a small Python script which would use `pynacl`. However, members would have to install the dependencies/create a venv before running it. 
- Use an OTS tool (e.g. https://github.com/danderson/gobox). However, this would involve some manipulation on the member side: extract the encrypted share from the RPC response and write it to file, etc. 
- Write our own binary that handles the decryption (à la now-defunct `memberclient`). This means another binary to build/ship/maintain but we could simplify the whole recovery share submission process for members: the CLI would retrieve the encrypted share, decrypt it, and submit it for recovery in one step.

**Comment by achamayou** [comment]
step-cli has been added to the build image now (https://github.com/microsoft/CCF/pull/1214), we just need to document its usage, and possibly convert the tests to use it, although that's less urgent.

**Comment by jumaffre** [comment]
This was very much in progress before I found out about some limitations of the step CLI. Now that a new version has been rolled out, I will be able to tidy my changes up and PR it for 0.11.
