### ISSUE TITLE
"Malformed ledger file" error after restarting a node

### ISSUE THREAD

**Issue by grcignav** [microsoft/CCF#1097]
**Describe the bug**
After a node goes down, the operator attempts to start a new node with the same ledger file. But the process won't start if it detects any corruption, even if the file is mostly correct., The process has to be re-started with a new ledger file. 

**To Reproduce**
1. Run start_test_network.sh and wait for nodes to come up. Record the command that was used to launch node2.
2. `kill -9` on node2's pid to simulate failure
3. Observe that the ledger file has data in it
4. Start up node2 with the same command as before (for simplicity, increment the port number), passing in the same ledger file as before. 
5. ERROR: Process does not start
 
`2020-04-23T00:34:54.751415Z        100 [info ] ../src/host/main.cpp:521             | Creating new node - joining existing network at 127.186.101.53:50566
2020-04-23T00:34:54.787486Z        100 [info ] ../src/host/main.cpp:545             | Created new node
terminating with uncaught exception of type std::logic_error: Malformed ledger file`

**Expected behavior**
CCF should either accept the existing file and clean it up, or ignore the incomplete part. If possible, CCF should continue to write ledger history to the file provided after it re-joins the network.

**Environment information**
CCF 0.9.1

**Additional context**

**Comment by jumaffre** [comment]
@grcignav Many thanks for raising this bug and describing the steps to reproduce it.

`start` and `join` nodes currently do not make use of the existing content of the ledger file passed at startup via `--ledger-file`. Indeed, they expect the ledger file to be empty. #1114 adds a check to make sure that the ledger file does not exist when a new node starts in `start` or `join`. Of course, the ledger file is still useful for `recover` nodes.

Longer term, joining nodes should be able to use a local ledger to catch up quickly. I've raised https://github.com/microsoft/CCF/issues/1115 to cover that work.

**Comment by grcignav** [comment]
Hi @jumaffre Thanks for the info. 

It makes sense that we can't use the ledger file in `start` or `join` modes. But I have also observed this message `malformed ledger file` in `recover` mode as well, especially when kill -9 is used. In that case recovery can't proceed. Is is possible to read only up to the last completely written entry and disregard incomplete data at the end?
