### ISSUE TITLE
Joiner could make use of the ledger file to catch up quickly

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1115]
As raised in https://github.com/microsoft/CCF/issues/1097, joining nodes currently do not make use of the existing content of the ledger file passed via `--ledger-file`.

To catch up quickly and reduce the amount of network traffic between the primary and the joining node, the joining node could make use of a ledger file retrieved out-of-band by operators. The joining node would have to restore ledger entries as far as it can but without going too far that the consensus doesn't know about that state.

**Comment by achamayou** [comment]
That probably needs to happen in a way that's similar to the recovery: validate signatures, truncate to last valid, then compare with the network, truncate further if necessary, and start consensus from there.

**Comment by achamayou** [comment]
This is nice to have, but snapshots essentially solve the same problem better, so let's do that first.
