### ISSUE TITLE
Raft election test failure

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#1134]
here: 

https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=7924&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=efdbc34d-c6b6-5dc6-e05c-1751d4c47c20

and here:

https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=7918&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=efdbc34d-c6b6-5dc6-e05c-1751d4c47c20

**Comment by olgavrou** [comment]
> Waiting for transaction to be committed by all nodes
> 50: 2020-05-04 07:27:59.964 | INFO     | infra.clients:log_request:147 - [127.78.54.96:45609] GET /nodes/tx {'view': 4, 'seqno': 20} (node 1 (node))
**> 50: 2020-05-04 07:27:59.975 | DEBUG    | infra.clients:log_response:160 - {'status': 500, 'result': None, 'error': 'Should not believe 4 occurred in view 4, ahead of the current committed view 2', 'commit': None, 'term': None, 'global_commit': None}**
> 50: 2020-05-04 07:27:59.975 | INFO     | infra.remote:stop:455 - [127.78.54.96] closing
> 50: 2020-05-04 07:28:00.007 | INFO     | infra.remote:stop:455 - [127.83.120.69] closing
> 50: 2020-05-04 07:28:00.071 | INFO     | infra.ccf:stop_all_nodes:294 - All remotes stopped...
> 50: Traceback (most recent call last):
> 50:   File "/mnt/build/2/s/tests/election.py", line 133, in <module>
> 50:     run(args)
> 50:   File "/mnt/build/2/s/tests/election.py", line 101, in run
> 50:     commit_index, current_term, network.get_joined_nodes()
> 50:   File "/mnt/build/2/s/tests/election.py", line 30, in **wait_for_index_globally_committed**
> 50:     ), f"tx request returned HTTP status {r.status}"
> 50: AssertionError: tx request returned HTTP status 500
> 41/51 Test #50: election_tests_raft ..............***Failed   16.86 sec
>

**Comment by olgavrou** [comment]
and here: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=7950&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=efdbc34d-c6b6-5dc6-e05c-1751d4c47c20

**Comment by achamayou** [comment]
The error message looks odd, I'm guessing target_view should be target_seqno here: https://github.com/microsoft/CCF/blob/95e7ea30e8a34771d463c42df2d316e8cf80260d/src/node/rpc/tx_status.h#L50

The fact that local_view > committed_view is systematically treated as an error is also definitely not right, this will always be the case between a node winning an election and it committing its first signature!

**Comment by achamayou** [comment]
Fixed by #1136

**Comment by eddyashton** [comment]
Here's another failure, after #1136:

https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=8010&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&s=d654deb9-056d-50a2-1717-90c08683d50a&t=efdbc34d-c6b6-5dc6-e05c-1751d4c47c20&l=7966

Happened _very_ early. Potentially triggered by an early election (1 became leader while 0 was verifying 2's quote), but claiming 3.3 is `INVALID` is very weird.

**Comment by jumaffre** [comment]
Closing as #1157 and #1158 fixes the issue that Eddy described.
