### ISSUE TITLE
Expand governance.py to validate node cert

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1160]
`governance.py` tests the `getQuotes` endpoint, by rerunning oesign and checking that the service's nodes are running a matching `mrenclave`. These quote responses return additional data about the executing platform, and the node cert that was attested in the quote. This test should also validate that this quoted cert matches the cert received via TLS/dumped to disk, to demonstrate the most-complete checks that a user may wish to do.

**Comment by eddyashton** [comment]
This is related to #683, which in turn depends on some OE work to install a validation tool. The only addition in this issue is that once we can take an enclave quote and (on non-SGX clients) verify it + extract the quoted fields, we should do so in `governance.py`.

**Comment by achamayou** [comment]
Will be possible with the new `oeverify` tool in the next OE release.
