### ISSUE TITLE
Diag logging for developers

### ISSUE THREAD

**Issue by archanak-msft** [microsoft/CCF#1166]
I am looking for a way to add custom logging statements (for example - "Parsing successfully completed" etc) in my code so that I can understand what's going on and also debug if something goes wrong.

Just wondering of CCF provided native logging support or integration with any existing distributed logging solutions?

**Comment by eddyashton** [comment]
Yes, you can add your own logging lines with the `LOG_INFO_FMT` macro:

```
LOG_INFO_FMT("Parsing successfully completed. x is {}, y is {}", x, y);
```

This will write a line to the node's stdout, prefixed with a timestamp and the filename+linenumber where this was called. This will let you track the precise execution path of a node while it executes your handlers. There's also `LOG_DEBUG_FMT` if you have diagnostics that should only be printed in Debug builds.

Note that this output stream is shared with the framework, so you may want to prefix your app's logging lines so you can easily grep for them. 

If you want machine-parseable logs, there's also an option to output these as JSON ([documented here](https://microsoft.github.io/CCF/master/operators/node_output.html)).

Sorry this wasn't called out in our docs - I'll add this now.
