### ISSUE TITLE
Doxygen is always run against master branch

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1194]
Since we moved to versioned documentation, it seems that Doxygen is always run against the `master` branch whereas it should be run against the target versioned branch.

Example:
- master: https://microsoft.github.io/CCF/master/developers/api.html 
vs.
- v0.10: https://microsoft.github.io/CCF/v0.10/developers/api.html

**Comment by achamayou** [comment]
$CWD in the setup() hook is the main repo, not the clones@tag that are created under $TMPDIR. If we find a way to run doxygen there, it will run on the right source, but then, we also need to find a way fix the breathe config to know about those, and I'm a little nervous about that. Let's see.
