### ISSUE TITLE
Expose CCF HTTP client to JS handlers

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1202]
It would be convenient for JS app developers to be able to issue HTTP requests to third party endpoints directly from their app. For this, we should expose our existing HTTP client inside the enclave (the one used for the join protocol) instead of the heavyweight libcurl.

**Comment by achamayou** [comment]
This requires asynchronous execution, which we're planning to build as part of the sharding work in AFT.

**Comment by achamayou** [comment]
Not going to introduce substantial new user APIs before the container re-design.
