### ISSUE TITLE
"Authorization" header support for endpoints

### ISSUE THREAD

**Issue by jazzybluesea** [microsoft/CCF#1203]
Currently when a Bearer token is in to an HTML request to a CCF node the server will nack with the following error:
```
Error parsing request: Unable to parse signature params from: Bearer eyJ0eXAiOiJKV...
```
In order to support access tokens from AAD. The server would have to change to allow such Bearer tokens in the HTML header.

Ideally, there could be some functions for decoding, validating such tokens.

**Comment by achamayou** [comment]
CCF needs to allow the header through when it's not a client signature, and the application can handle decoding as required.
