### ISSUE TITLE
Support for CKM_RSA_AES_KEY_WRAP algorithm

### ISSUE THREAD

**Issue by jazzybluesea** [microsoft/CCF#1204]
For secure key release, the key to be released is encrypted in a public key using the algorithm named [CKM_RSA_AES_KEY_WRAP](http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/cos01/pkcs11-curr-v2.40-cos01.html#_Toc370634387).

The request is to add this functionality to the current set of encryption libraries available in the CCF infrastructure for a CCF application to use.

**Comment by jumaffre** [comment]
This might be useful: https://crypto.stackexchange.com/a/68702

**Comment by letmaik** [comment]
The idea here would be to implement a subset of the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API). Initially for a specific instance of key wrapping. CKM_RSA_AES_KEY_WRAP is not supported directly by the Web Crypto API (to be investigated if it can be done with a combination of operations), but the [CKM_RSA_PKCS_OAEP](http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/cos01/pkcs11-curr-v2.40-cos01.html#_Toc408226895) algorithm is a good replacement and is supported as "RSA-OEAP" algorithm in Web Crypto.

The subset to implement is as follows:
- [`CryptoKey`](https://developer.mozilla.org/en-US/docs/Web/API/CryptoKey) to represent the key to be wrapped and the wrapping key
- [`SubtleCrypto.importKey`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey) to import the key to be wrapped and the wrapping key as `CryptoKey`, with the following parameter restrictions:
  - `format`: pkcs8 only
  - `keyData`: `ArrayBuffer` only
  - `algorithm`: { name: RSA-OEAP, hash: SHA-256} only

- [`SubtleCrypto.wrapKey`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/wrapKey) to wrap a key, with the following parameter restrictions:
  - `format`: pkcs8 only
  - `wrapAlgo`: RSA-OAEP only
- [`Crypto`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto) to get access to the `SubtleCrypto` object
- [`globalThis.crypto`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto) to get access to the Web Crypto API (`Crypto` object)

All Crypto API functions that would normally return a `Promise` will return the value directly instead, as CCF does not support async functions.

**Comment by letmaik** [comment]
After more consideration we decided to not implement Web Crypto API for now as it complicates things unnecessarily without clear benefit for the use cases we have. We'll implement RSA-OAEP key wrapping as custom function in the `ccf.*` namespace, loosely following the `wrapkey` API of the Web Crypto API.
