### ISSUE TITLE
The write-set passed to KV commit-hooks doesn't clearly distinguish deletions

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1208]
Commit hooks take a `Write` argument, which is something like `std::map<K, VersionV<V>>`. The `VersionV` contains a version, and the written value, but the interpretation of these is not always clear.

It appears that this always contains either `{0, v}` for actual writes, or `{NoVersion, V{}}` for deletions. I'm not sure that all of our hooks are correctly checking whether the entry is a deletion, and this remains error-prone for future hooks. Additionally, we could tell the hook _what_ value was deleted, instead of just the key and a default-constructed value.

I think we should either:
- replace `VersionV<V>` with `std::optional<V>` (since the _version_ in this struct is meaningless) with `std::nullopt` indicating a deletion
- pass a list of deleted keys, or map of deleted {key, values}, as a separate argument from the `Write`

**Comment by achamayou** [comment]
The first change sounds like an obvious win. The second is less clearly beneficial today because we presumably don't need that feature now and it potentially extends the lifetime of the value.
