### ISSUE TITLE
Add support for zero-copy serialisers in the KV

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1217]
As of #1216, we can write serialisers for a Key (or Value) that match the following signature:

```
struct MySerialiser
{
  static std::vector<uint8_t> to_serialised(const K& k) { ... }
  static K from_serialised(const std::vector<uint8_t>& bytes) { ... }
};
```

This involves an unavoidable copy in either direction for the return value. In some circumstances, in particular if we have pre-serialised RPC inputs like flatbuffers, it would be much neater to avoid this copy.

We should explore changes to this API (and the surround `experimental::TxView`) to support zero-copy returns, returning pointers (perhaps `std::span`?) into the raw serialised representation.

**Comment by achamayou** [comment]
Not going to add substantial new user APIs before container re-design.
