### ISSUE TITLE
Pass domain argument through to cchost

### ISSUE THREAD

**Issue by kapilvgit** [microsoft/CCF#1228]
**Is your feature request related to a problem? Please describe.**
Currently the --domain argument is not passed through to cchost

**Describe the solution you'd like**
Pass --domain argument through to cchost

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by achamayou** [comment]
@kapilvgit, I guess you mean when using `./start_test_network.sh`?

**Comment by kapilvgit** [comment]
Yes that's right.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by achamayou** [comment]
@kapilvgit fix is in master now.

**Comment by kapilvgit** [comment]
Thanks!
