### ISSUE TITLE
Lua end to end PBFT test failure

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#1230]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=8814&view=ms.vss-test-web.build-test-results-tab&runId=44556&resultId=100045&paneView=attachments

Overwhelmingly likely caused or revealed by https://github.com/microsoft/CCF/pull/1227, which switched to using a "local" commit RPC and therefore tightened the "sync check" assertion.

**Comment by eddyashton** [comment]
Here's another repro, with the more detailed assert:
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=8911&view=ms.vss-test-web.build-test-results-tab&runId=44874&resultId=100044&paneView=attachments

**Comment by eddyashton** [comment]
And again, with identical versions:
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=8958&view=ms.vss-test-web.build-test-results-tab&runId=44970&resultId=100044&paneView=attachments

**Comment by achamayou** [comment]
@ashamis I think this is an existing bug revealed by the stricter check, rather than a problem with the check itself. One of the nodes is consistently failing to catch up and is stuck at 2.46 when other nodes all reach 2.62.
