### ISSUE TITLE
Identify signature transactions in the ledger

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1237]
For historical queries and general auditability of the ledger, it may be convenient to identify signature transactions in the ledger. For example, a node or 3rd-party audit tool would be able to ask the ledger for: "get entry at seqno `V` and the next signature", without being aware of the seqno at which the next signature was recorded.

We expect the usefulness of such feature to become more apparent while the historical query feature is being implemented.

Link to #1135 and #1207

**Comment by eddyashton** [comment]
Just to clarify the advantage here for historical queries:

To serve version N, we need to have transaction N and the signature after N.
We can ask the host for N directly. To get the signature after N, we  currently fetch versions N+1, N+2... until we find a signature.
If we could identify signature transactions in advance (and the ranges they cover? and query this from the enclave?), then we could skip this linear search and fetch the required transactions only.

**Comment by achamayou** [comment]
Having them be flagged as such in the chunk index (tag with MSB?) ought to be enough. On loading a block, the host can read the index, and create a list of signature indices. Looking them up is a simple binary search and the range is the value at index - 1 to the value at index.

**Comment by achamayou** [comment]
Now that we are modifying the serialiser to produce the size prefix for entries, including flags to indicate for example the presence of custom claims, it should be quite straightforward to set another flag in the same size prefix hinting at whether the transaction contains a signature or not.

**Comment by achamayou** [comment]
No longer necessary as a result of #3041.
