### ISSUE TITLE
Log level should be checked as part of attestation

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#1240]

**Comment by jumaffre** [comment]
Is this the log level on the host side? AIUI, on the enclave side, since the log level is determined at compile time, an enclave with a different log level will present a different `MRENCLAVE`.

**Comment by ashamis** [comment]
> Is this the log level on the host side? AIUI, on the enclave side, since the log level is determined at compile time, an enclave with a different log level will present a different `MRENCLAVE`.

I am closing this as per @jumaffre comment this work is already done.
