### ISSUE TITLE
replay_new_view_pbft test failure

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#1244]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=8876&view=logs&j=2f246a49-43ac-5250-d63c-293adb2ef928&t=2bd49aea-a0ec-5c63-8430-09adb0b47aca

looks like the test timed out and needs more time to run 

40: 2020-06-04 10:00:39.694 | SUCCESS  | infra.logging_app:verify_last_tx:152 - Verifying last logging tx
40: 2020-06-04 10:00:39.697 | INFO     | infra.clients:log_request:153 - [127.61.78.28:33111] GET /users/LOG_get_pub {'id': 40} (node 0 (user 0))
40: 2020-06-04 10:00:39.818 | DEBUG    | infra.clients:log_response:166 - {'status': 200, 'result': {'msg': 'Public message at index 40'}, 'error': None, 'seqno': 487, 'view': 3, 'global_commit': 485}
40: 2020-06-04 10:00:39.818 | INFO     | infra.clients:log_request:153 - [127.61.78.28:33111] GET /nodes/tx {'view': 3, 'seqno': 487} (node 0 (node))
40: 2020-06-04 10:00:39.960 | DEBUG    | infra.clients:log_response:166 - {'status': 200, 'result': {'status': 'COMMITTED'}, 'error': None, 'seqno': 489, 'view': 3, 'global_commit': 487}
40: 2020-06-04 10:00:39.963 | INFO     | infra.clients:log_request:153 - [127.61.78.28:33111] GET /users/LOG_get {'id': 40} (node 0 (user 0))
40: 2020-06-04 10:00:40.080 | DEBUG    | infra.clients:log_response:166 - {'status': 200, 'result': {'msg': 'Private message at index 40'}, 'error': None, 'seqno': 491, 'view': 3, 'global_commit': 489}
40: 2020-06-04 10:00:40.080 | INFO     | infra.clients:log_request:153 - [127.61.78.28:33111] GET /nodes/tx {'view': 3, 'seqno': 491} (node 0 (node))
39/59 Test #40: replay_new_view_pbft .............***Timeout 240.00 sec
test 41
      Start 41: lua_txregulator_test_raft

41: Test command: /usr/bin/unbuffer "python3" "/mnt/build/1/s/samples/apps/txregulator/tests/txregulatorclient.py" "-b" "." "--label" "lua_txregulator_test_raft" "-l" "info" "-g" "/mnt/build/1/s/src/runtime_config/gov.lua" "--worker-threads" "0" "--consensus" "raft" "--app-script" "/mnt/build/1/s/samples/apps/txregulator/app/txregulator.lua" "--datafile" "/mnt/build/1/s/samples/apps/txregulator/dataset/sample_data.csv"
41: Environment variables: 
41:  PYTHONPATH=/mnt/build/1/s/tests:
41:  DEFAULT_ENCLAVE_TYPE=virtual
41: Test timeout computed to be: 240
41: 2020-06-04 10:00:40.517 | INFO     | infra.ccf:_setup_common_folder:249 - Creating common folder: /mnt/build/1/s/build/workspace/lua_txregulator_test_raft_common
41: 2020-06-04 10:00:40.517 | INFO     | infra.proc:ccall:12 - rm -rf /mnt/build/1/s/build/workspace/lua_txregulator_test_raft_common
41: 2020-06-04 10:00:40.522 | INFO     | infra.proc:ccall:12 - mkdir -p /mnt/build/1/s/build/workspace/lua_txregulator_test_raft_common
41: 2020-06-04 10:00:40.525 | INFO     | infra.proc:ccall:12 - cp /mnt/build/1/s/src/runtime_config/gov.lua /mnt/build/1/s/build/workspace/lua_txregulator_test_raft_common
41: 2020-06-04 10:00:40.529 | INFO     | infra.proc:ccall:12 - ln -s /mnt/build/1/s/build/keygenerator.sh /mnt/build/1/s/build/workspace/lua_txregulator_test_raft_common
41: 2020-06-04 10:00:40.532 | INFO     | infra.proc:ccall:12 - ./keygenerator.sh --name=member0 --curve=secp384r1 --gen-enc-key [cwd: /mnt/build/1/s/build/workspace/lua_txregulator_test_raft_common]
41: 2020-06-04 10:00:40.557 | INFO     | infra.pro

**Comment by eddyashton** [comment]
Another instance here:
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=8911&view=ms.vss-test-web.build-test-results-tab&runId=44872&paneView=attachments&resultId=100032

**Comment by eddyashton** [comment]
Another instance here, looks like a timeout in a non-SAN build:
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=9180&view=ms.vss-test-web.build-test-results-tab&runId=45578&resultId=100032&paneView=attachments
