### ISSUE TITLE
Commit a ledger chunk early

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1276]
Follow-up from #1135 

Now that the ledger is split into different chunks that get committed (i.e. we are sure that they will never be written to/truncated) when 1) they have grown enough that they contain a signature that has passed the chunking threshold and 2) the last index they contain has been globally committed by the underlying consensus. 

However, if a chunk has not yet passed the threshold, it may be nice to let operators force a new chunk to be created so that on the next global commit, that chunk is committed. For example, this would be useful if the system is not under heavy load for some time and operators want to backup all existing ledger chunks so far.

**Comment by achamayou** [comment]
@jumaffre this seems like a subset of #3155?

**Comment by jumaffre** [comment]
@achamayou I hadn't see your comment until now. Yes, I'll close this issue as it's already tracked by #3155.
