### ISSUE TITLE
The ledger contains the exact same data over sequential transactions

### ISSUE THREAD

**Issue by rschust** [microsoft/CCF#129]
When running a test, after the setting up a network, the nodes table should be populated, therefore, readable by ledger.py.

When reading the ledger, we can see identical node entries appearing on sequential transactions, without any property being changed. This seems concerning, since the ledger should only be storing the delta between versions.

[test_nodes.py.txt](https://github.com/microsoft/CCF/files/3262349/test_nodes.py.txt)

**Comment by jumaffre** [comment]
There is a specific transaction that is run 1) when the leader starts up and 2) when a new node is added to the network to set the status of a node as `TRUSTED`. See https://github.com/microsoft/CCF/blob/master/src/node/nodestate.h#L291-L294 and https://github.com/microsoft/CCF/blob/master/src/node/rpc/nodefrontend.h#L36-L37. 

Are the nodes info retrieved exactly the same or is the node status slightly different? I would expect the nodes to be added as `PENDING` in the genesis transaction and then transitioned to `TRUSTED` within the first few transactions.

**Comment by rschust** [comment]
@jumaffre The entries are identical, node state included

**Comment by achamayou** [comment]
Cannot reproduce with a recent build.

**Comment by jumaffre** [comment]
Re-opening. As far as I could see, this is an issue with the Python ledger reader (`ledger.py`) as the requests do not seem duplicated in the ledger file itself.

**Comment by achamayou** [comment]
To clarify, I tested this by grepping for strings in the ledger.

**Comment by jumaffre** [comment]
I can confirm that this was an issue with the infra. See #918
