### ISSUE TITLE
Discuss handler installation API

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1296]
NB: All terminology in this issue is in-flux. I'm just trying to describe a distinction, not mandate that we consolidate on "transaction" vs "command".

We've established that there are several different types of RPC that CCF provides:
- Read-write transactions. These use a `kv::Tx`, and (sometimes) call `TxView::put`.
- Read-only transactions. These use a `kv::Tx`, but never call `TxView::put` (only `TxView::get`).
- Non-KV commands. These don't have any impact on the KV. They read node-local state like the current commit point, metrics, etc.
- Historical queries.

I think we should distinguish these types of RPC when they are installed, so we can call them with different signatures and potentially take different execution paths when handling them. This issue is for sketching and discussing possible C++ API designs.

Currently:
```
install("foo", [this](ccf::RequestArgs& args){}, ReadWrite::Write)
  .set_http_get_only();
```

We have some adapters for the lambda, so most 'real' handlers look like:
```
install(
  "foo",
  json_adapter([this](kv::Tx& tx, json&& params){}),
  ReadWrite::Write)
    .set_http_get_only();
```

This proposes that we have different `install` functions taking different lambda types:
```
install_transaction(
  "foo"
  [this](kv::Tx& tx, json&& params){} ...);

install_read_only_transaction(
  "foo"
  [this](kv::ReadOnlyTx& tx, json&& params){} ...); // ReadOnlyTx is a proposed new type, with no put or remove

install_command(
  "foo"
  [this](json&& params){} ...); // Takes no Tx! Hopefully we didn't even construct one
```

2 related points:
1) I think we should make  (_method_, _verb_, _lambda_) the most-critical, set-at-construction fields, and do a _build-then-install_ pattern instead of _install-then-modify_:
```
make_handler("foo", HTTP_GET, [this](ccf::RequestArgs& args) {}).
  .install();
```
This lets us do validation of the _final_ handler, and gives us flexibility in dispatch (removes the ability to modify how we select the handler, after its been installed)

2) We'd like to support some kind of wildcarding in path dispatch, related to the OpenAPI doc. Very strawman, but the idea is to give something like:
```
install(
  "foo/{userId}/bar",
  [this](..., const ParsedArgs& ?from_path?) { ... }
  ... );
```

**Comment by eddyashton** [comment]
We currently have a `ReadWrite::MayWrite` state, with the `x-ccf-read-only` header on individual requests. This is currently unused. Its also awkward to support. I think it should be removed - clients can change the verb/URI as easily as a single header.

**Comment by achamayou** [comment]
I support removing MayWrite, which is unused and probably too niche.

I do like:

```
make_handler("foo", HTTP_GET, [this](ccf::RequestArgs& args) {}).
  .install();
```

For the reasons you have spelled out (path and verb as "key", different handler types). Users with warnings for unused values will even get a warning if they forget to call install() (but not if they don't, because it'll probably be void).

`make_rpc()` (only internal for the foreseeable future), `make_read_only_tx()` and `make_read_write_tx()`?

**Comment by eddyashton** [comment]
I think I prefer `_handler`, or possibly `_endpoint`, to `_tx`.

I'm trying to get my head around the multiple kinds of read-only, and work out where these collapse. Currently we have a `ReadWrite` hint governing whether an RPC is forwarded. By default we infer this from the verb (`GET` => `Read`), but its overridable. For the proposed `read_only_tx`, which gets a read-only `TxView`, I think we always set `ReadWrite` to `Read` but still allow any verb. Perhaps this dictates `ReadWrite`, and it does not need to be overridable?

For example:
```
make_read_write_tx(
  "/foo",
  HTTP_GET,
  [](kv::WriteTx& tx) {
    ...
  })
  .install();
```
This is a valid writing transaction - maybe it logs every `GET` sent to the app in the kv.

```
make_read_only_tx(
  "/foo",
  HTTP_POST,
  [](kv::ReadOnlyTx& tx) {
    ...
  })
  .install();
```
This is a valid read-only transaction - if we're looking something up from a large, structured request, it should be `POST` not `GET`.

Its also possible to write a `HTTP_GET` which _could_ be read-only (it does no puts), but install it with `make_read_write_tx` . This is fine, we set the 'wrong' `ReadWrite` and unnecessarily forward. The app-writer can fix this.

The final square in this matrix is a `make_read_only_tx` handler that we want to set as `ReadWrite::Write`. It is type-enforced to only do `get`s from the KV, but it wants to always be forwarded and run on the primary? Does this exist?

So I think the new signatures/handler-types supercede the verb entirely, and we use them to determine "does this need to be forwarded". Its cheap to keep `ReadWrite` inferred-but-overridable, but it would be neat to remove the override if we can.

**Comment by achamayou** [comment]
This has now reached a happy conclusion.
