### ISSUE TITLE
Distribute snapshots between nodes

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1304]
As a primary generates snapshots at a regular interval, the latest snapshot gets passed on to new node on join. However, existing nodes should also be given snapshots so that snapshots on the primary are not lost if the machine on which the primary runs on dies.

**Comment by achamayou** [comment]
Snapshots, like ledger chunks, are flat files. The operator can back them up and replicate them with existing filesystem infrastructure. They are outside the CCF trust boundary, there is no obvious benefit to implementing this in CCF itself.
