### ISSUE TITLE
replay_new_view_pbft and suspend_nodes_pbft tests occasionally fail

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1306]
Observed here: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=9511&view=logs&j=ee9484ec-b476-577b-aa0e-d5ddfcbcd149&t=e2c1a4cf-16d0-5038-f9f6-343f9806d38b&l=3564 

The cause of the issue seems to be `CCFConnectionException` while verifying that some entries were committed.

**Comment by achamayou** [comment]
Thought to be fixed, let's keep an eye on the Daily.
