### ISSUE TITLE
Enclave-host compatibility check

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1307]
We currently do not check whether a given enclave and host are compatible. For example, a recent enclave could write a new message on the ring buffer that is not supported by the host, which would cause the CCF node to crash, possibly long after the node has been started.

Instead, we should enforce that such situations can never occur. To do so, we should make sure that the version of `cchost` is recorded in the binary (so that `cchost --version` returns the release tag + commit). 

We should also record the version of CCF that an enclave was built against. It is not clear whether i) this should be recorded as a metadata to the enclave or ii) included in, e.g., `libccf.enclave.a`. If i), `cchost` could enforce this check without spinning up the enclave. If ii), the enclave would have to be spinned up to retrieve this and compare it to the version of `cchost`.

**Comment by jumaffre** [comment]
As discussed with @achamayou, there are two approaches to this:

- The first approach is a `==` comparison between the `cchost` version and the enclave version. This guarantees that the same version of Open Enclave is used for both (so the `oe_create_xxx_enclave()` API is in sync), that the ecalls used are the same and that all ring buffer messages are the same. This should be achieved ahead of the enclave creation so we would either a) try to embed the CCF version in the enclave metadata (not clear how to do this) or b) use `ccf_version` in the enclave as well and read the symbols from the enclave before loading the enclave (preferable). Option b) should be preferable for simplicity. This method is too strict (perhaps two enclave/host pairs across two different CCF versions are compatible but we would prevent such combinations) but easy to implement. 

- The second is to have a more complex scheme where we (CCF devs) maintain an internal version number on the host and the enclave and update it whenever a breaking change is introduced. This would allow us to provide compatibility across different hosts and enclaves at the cost of higher complexity.

The first approach (strict equality) seems preferable for now as it gives us what we want (prevent breakages between enclave and host at runtime) at minimum cost. The cost of upgrading the enclave or the host is also cheap enough.

**Comment by achamayou** [comment]
Let's go with the strict approach for now and for the foreseeable future. We can revisit this if:

1. There is a clear backwards compatibility story for Open Enclave OCalls
2. There is demand for difference cchost and enclave release cycles
