### ISSUE TITLE
RPC Endpoints need to be able to delegate commands directly to a Consensus

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#134]
In a PBFT configuration, RPC endpoints would pass commands directly to the consensus. The consensus will then distribute the commands among the nodes, and decide when to issue a batch to the frontends.

**Comment by jumaffre** [comment]
I believe that https://github.com/microsoft/CCF/pull/263 implements this: the `Frontend` passes the command to PBFT (via the client proxy) which will eventually call back the `Frontend` for execution (before sending the `Pre_prepare` message).

**Comment by achamayou** [comment]
As @jumaffre points out, this is done.
