### ISSUE TITLE
Couple host node connections to enclave channel manager

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1342]
The node-to-node channels created in the enclave and the node-to-node TCP connections on the host are currently handled independently:
- A new TCP connection is created from the local hook on the `ccf.nodes` table when a new node is added as `TRUSTED` while the TCP connection is closed on the global hook on the same table when a node is `RETIRED`.
- A new node-to-node channel is created when the first message is sent on that channel (most likely a Raft Append Entries message). n2n channels are never closed. 

Instead, the two modules should be coupled so that the channel manager is in charge of creating/deleting enclave n2n channels and notify the host to create/delete channel. In particular, Raft should also notify the channel manager to close a n2n channel (and the associated TCP connection) whenever a node is removed from its list of nodes (i.e. rollback of non-committed tx or node deletion gets globally committed).

This is related to https://github.com/microsoft/CCF/issues/486#issuecomment-649581017

**Comment by lynshi** [comment]
What is the expected behavior when a rollback occurs while a new node is joining so that the new node configuration is not committed? Does that joining node retry the join attempt or is the operator responsible for detecting the situation and restarting the node?

**Comment by jumaffre** [comment]
@lynshi Very good point. We've identified this before (some of it is touched on in https://github.com/microsoft/CCF/issues/1014). Ideally, we also want the joining node to check whether the join transaction has been committed (using the [`/tx` endpoint](https://microsoft.github.io/CCF/master/users/issue_commands.html#checking-for-commit)). Does this answer your point?

**Comment by lynshi** [comment]
Thanks @jumaffre for the clarification! I think steps 1 and 2 in #1014 will be great additions; A `status` endpoint gives the operator more information to help orchestrate, while crashing for join failures lets us delegate node restarts to the platform (e.g. Kubernetes will just restart the node for us). The joining node performing a check to ensure it has successfully joined will be helpful as well.

**Comment by jumaffre** [comment]
@lynshi Excellent. We'll prioritise these two features 👍 I'll use the rest of this issue to discuss different design solutions so feel free to ignore those.

**Comment by jumaffre** [comment]
@lynshi Just to confirm: this issue has now been fixed on `master` and the fix will be in the next release (most likely end of this month). The improvements discussed in #1014 are still to be implemented and we will update/close #1014 as we go.
