### ISSUE TITLE
Single Format/Lint entry point

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#1350]
There ought to be a single run-ci-checks (or perhaps scripts/run-ci-checks?) that takes care of all of https://github.com/microsoft/CCF/blob/master/.azure-pipelines-templates/checks.yml, to make life easier for contributors trying to submit PRs.

Spotted by @letmaik

**Comment by eddyashton** [comment]
Assuming we're adding a `-f` option to this to fix incompatible files (where possible), we should avoid running `check-format.sh -f src/`. This touches _every_ C++ file, requiring a total rebuild. We should either update `check-format.sh` to only touch the unformatted files, or call it twice and pass only the unformatted files the second time, with `-f`.

**Comment by achamayou** [comment]
Discussed with @letmaik, the best course of action seems to be to have -f on a best effort basis, since not all steps can reformat. You're right that we should avoid touching files that don't need reformatting.
