### ISSUE TITLE
Improve proposal and voting samples for new users

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1352]
The membership proposals are generally simple, and the most complicated step for new users isn't the scripting logic but the formatting of the proposal object in JSON. We should add Python scripts to generate these proposals. They essentially exist in `consortium.py` already, but we should extract them to dump proposals to file so they can be used more generally (while still being tested by all of our infra.

As a minor extension these generators should also produce sample accepting votes, which include validation that the proposal's params match the proposed value (ie - when generating a proposal that says "add Bob as a new user", create a ballot that returns true iff the proposal has a single `new_user` call with Bob's key).

Additionally, the proposal endpoint could do some schema validation of proposal params, so that (most) type errors are caught at proposal time rather than after a successful vote.

- [x] Factor generation of proposal and vote objects out of `consortium.py`
- [x] Add a CLI frontend to this proposal generation
- [x] Build more interesting sample votes which validate, don't simply `return true`
- [x] Use these sample votes in the infra
- [x] In the infra, dump proposals and votes to file to test more of the CLI flow and to leave a a permanent record of proposals
- [x] Point at the generator CLI in the docs
- [x] Accept strings rather than byte-arrays for Pem values in proposals (related to #278)
- [x] Put proposal IDs into path rather than params, so we generate a complete vote sample which is independent of the proposal ID (ie - `POST /gov/vote/5 {"ballot": ...}` rather than the current `POST /gov/vote {"id": 5, "ballot": ...}`) (sort of #583, but perhaps we should track this feature independently)

**Comment by eddyashton** [comment]
I believe we should document this for 0.12. Schema validation can wait until later.

**Comment by achamayou** [comment]
Agreed, particularly since we intend to migrate the governance to Javascript.
