### ISSUE TITLE
Update evercrypt code

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#1362]
Update the evercrypt do when https://github.com/FStarLang/FStar/pull/2073 has been committed.
This fixes the merkle tree serialization + deserialization + append memory issue

**Comment by wintersteiger** [comment]
https://github.com/FStarLang/FStar/pull/2073 has been merged and the new snapshot should be available shortly. project-everest/hacl-star#328 will be extended with more/better proofs about serialization, but we don't have to wait for that.

**Comment by achamayou** [comment]
Done in #1576, thank you @wintersteiger!
