### ISSUE TITLE
Add a simpler hello_world sample and documentation for js_generic

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1386]
We currently have implementations of the logging app for both the `lua_generic` and `js_generic` apps. The thing these miss, and that's missing from the `Registering the Lua Application`, is the link between these runtimes and the dispatch to the installed runtime endpoints. We should add this documentation as a baseline, and extend it with further detail as we improve the `js_generic` app.

Specifically, I think we should have a tutorial flow that does:

```
start_test_network.sh ...
curl https://NODE/gov/propose {"set_js_app": {"GET hello_world": "return 'hello world'"}}
curl https://NODE/gov/vote ...

curl https://NODE/app/hello_world
```

This "installing an endpoint on the same server" behaviour is critical but not clear from the docs. From there, we can add tutorials explaining how the JS app does KV-access, body and query parsing, returns a response body.

**Comment by achamayou** [comment]
https://microsoft.github.io/CCF/master/developers/js_app.html addresses this issue in my opinion, to be revisited once we add support for dynamic endpoints (#1565).
