### ISSUE TITLE
Determine policy for required headers in HTTP signatures

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1389]
The spec for HTTP signatures is still a draft, and the current version appears to have changed the set of mandated headers from when we first adopted it:

https://tools.ietf.org/html/draft-cavage-http-signatures-12#section-2.1.6

I'm going to remove the `Date` from our signatures, since it no longer matches the spec's suggested `(created)` format. We should explore what other frameworks are doing with regards to required fields in the signature. We may want to make this endpoint-determined eventually, but currently that seems like overkill. I think we're looking at `(request-target) digest`, but we should check how awkward is it to produce the 'empty digest' in client code.

**Comment by eddyashton** [comment]
The short response is that I believe requiring `(request-target) digest` is sufficient for our current needs - in particular this covers the important details for all of our governance operations. At the framework level it would be nice to make this required list endpoint-specific, but we don't have demand for this currently.

The clearest server description I've found from another framework is [Oracle's](https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/signingrequests.htm#five). They require the `Date` header to be present and signed. The related [AWS](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html) scheme _requires_ `Host`, `Content-type`, and `x-amz-*` (and a `(request-target)` equivalent elsewhere), and _recommends_ signing all headers. [This](https://food.ibm.com/ift/docs/signature-header/) suggests IBM Food Trust is also using this scheme, but has no further details.

The only thing I'm not completely sure about is the `Date` header. It seems like it would be useful auditability after the fact - all signed governance requests give us approximate timestamps of the network's transitions. However, while we're not able to verify the `Date`s are current while verifying the signature (inside the enclave), I think this gives us false assurance. CCF will accept signatures with garbage `Date`s. This means the signed date headers don't even give us the replay protection that they're intended for in other services. On top of that, the draft spec has moved away from the `Date` header in favour of a custom-formatted `(created)` pseudo-header. This would be another bit of awkward construction/parsing in our signing code, for no clear benefit (counterpoint - we may need to do this on the server-side to parse signatures from standard-compliant tools anyway, but not _yet_, and not in our own bash client). On balance, I don't think its sensible for the _framework_ to require signatures over the `Date` header.

**Comment by achamayou** [comment]
@eddyashton interestingly, Azure also allows x-ms-date, because some libraries set Date without exposing it, which makes it difficult to include in the signature: https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key#specifying-the-date-header

The minimalist approach seems best here, since it is not possible to provide a meaningful guarantee about the validity of the date/timestamp in enclave.
