### ISSUE TITLE
Forwarded transactions check caller validity separately from transaction execution

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#139]
When an RPC is sent to a follower and forwarded, `valid_caller` is called only on the follower and not on the leader which later executes the transaction. The caller may be invalid by the time the transaction is executed.

When processing a forwarded transaction the leader should check that the caller is still valid and allowed to execute transactions.

**Comment by achamayou** [comment]
@eddyashton as discussed, there is effectively no way to disable users at the moment, so that needs to be added first. The issue still stands of course.

**Comment by jumaffre** [comment]
Addressed by #446
