### ISSUE TITLE
Some KV tables are forever growing

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1401]
Some KV tables, e.g. `ccf.nodes`, `ccf.members`, grow as more actors are added to the service (nodes, members, etc.) but are not freed when these actors are retired (actor is only marked as `RETIRED`). This gives a live CCF service auditing properties (e.g. "which nodes have already been retired?") at the cost of memory growth inside the enclave.

**Comment by achamayou** [comment]
Addressing this will require converting some queries, such as the list of proposal, to historical queries.

**Comment by jumaffre** [comment]
Once this is done, `POST /gov/proposals/{proposal_id}/withdraw` can be turned into `DELETE /gov/proposals/{proposal_id}.

**Comment by jumaffre** [comment]
Closing this issue as remaining work is covered by other issues or WIP PRs.

- Users and members are now removed from the store when they are retired (in fact, the concept of retiring a member/user no longer exists) - #2320.
- For retired proposals, the work will be done as part of the new JS governance work (w/ the two proposals and proposals info tables) - #2286 
- For nodes, the work will be covered in #2320, post 1.0.
