### ISSUE TITLE
Maintain list of Root CAs and demonstrate their usage from JS Code

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#1402]
The end-user scenario we aim to support is the use of MAA tokens as a mechanism for application authentication and/or authorisation. This ticket specifically covers the provision and maintenance of a root cert authority, which can be used to validate MAA tokens by the application code before it examines the claims they contain.

That MAA root CA is understood to contain an SGX quote. The validity of the root CA is to be decided by validating that quote, and examining its claims. Specifically, comparing MRSIGNER to a stable value, although that logic may change in future revisions.

- [x] obtain sample MAA root cert and confirm that it contains quote
  - The first cert in https://shareduks.uks.attest.azure.net/certs contains a quote under X509 extension OID 1.2.840.113556.10.1.1.
- [ ] confirm whether the collateral is included in the cert.
  - unclear, need to check with OE
- [x] confirm whether the MRSIGNER method is appropriate
  - all claims are exposed, the exact method can be chosen by the governance script.
- [x] confirm the format of the quote
  - The cert is generated with OE's `oe_generate_attestation_certificate` which contains an OE-style report.

The governance mechanism is a straightforward choice to provision and maintain this root CA. It's an existing flow, part of the total order of transactions, auditable to all actors, and offers a choice of mechanisms to validate new root CAs when submitted. In particular, the constitution is an appealing location for the validation to take place, since it isn't expected that a meaningful multi-member vote should take place on root CA renewal.

Several functional elements are missing from CCF to allow the constitution to handle this workflow:

- [x] a root CA table (for now, hard-coded in CCF, later dynamically created)
- [x] a procedure to add/update entries in that table. A Lua function similar to raw_puts, inlined in the constitution is probably the easiest choice (in that case, it would not be part of CCF but of the sample).
- [x] a call that takes a root CA certificate, extracts the quote, validates it and returns a table of claims (including, but not necessarily limited to MRSIGNER) to its Lua caller
- [x] replicate oe_verify_attestation_certificate for MAA's custom format as an intermediate solution

When those are added, an end-to-end sample, run as an automated test will be used to lock in the functionality, and document its usage for applications wishing to make use of it. Using MAA certs may not be practical, in which case we should strive to find a way to create logically equivalent certs embedding quotes, for the purpose of the automated test.

**Comment by achamayou** [comment]
In time, what we really want is #1202, but this is a tactical change that allows the same result for application needs at the moment.

**Comment by yentsanglee** [comment]
The issue here is that MAA uses OID 1.2.840.113556.10.1.1 to embed an SGX quote while OE uses the same OID to embed an OE report. There was an agreement for MAA to use **1.3.6.1.4.1.311.105.3** going forward but I am not sure 
1. when will MAA starts generating certificate with the new OID
2. OE SDK has to be extended to recognize the MAA OID (issue [3313](https://github.com/openenclave/openenclave/issues/3313))

**Comment by letmaik** [comment]
@yentsanglee That sounds fine. We've unblocked ourselves for now by replicating `oe_verify_attestation_certificate_with_evidence` for MAA in CCF, see https://github.com/microsoft/CCF/pull/1448/files#diff-188832f366b21971bc3e0f52f1d22790. It would be great though if the cert situation progresses continously so that we can switch to an OE function and remove our hack.

**Comment by letmaik** [comment]
Quoting from #1546:
> the MAA service recently changed to use oe_generate_attestation_certificate to generate signing certificates, so oe_verify_attestation_certificate should now work.

**Comment by letmaik** [comment]
@achamayou I think we can close this issue and deal with any remaining tasks in follow-up issues.

**Comment by achamayou** [comment]
@letmaik agreed, thank you for taking care of this.
