### ISSUE TITLE
Unclear commands for the test network and non working end to end demo

### ISSUE THREAD

**Issue by dhuynh95** [microsoft/CCF#1412]
Hello,

I am still a beginner with CCF, and I have tried running examples, but some things are still unclear to me.

### Test network

I have setup a VM with Intel SGX on an Azure Confidential Computing machine. I have built CCF following https://microsoft.github.io/CCF/master/quickstart/build.html#building-ccf-from-source.

I am able to run the command:
`../start_test_network.sh --package ./liblogging.enclave.so.signed`

Nonetheless the commands in https://microsoft.github.io/CCF/master/users/issue_commands.html#issuing-commands are unclear to me. Could the documentation be made more explicit to guide people to issue commands ?

### End to end demo

Moreover I have tried running the end to end demo available at https://microsoft.github.io/CCF/master/developers/demo.html

Nonetheless when running `python ../tests/e2e_scenarios.py --scenario ../tests/simple_logging_scenario.json`, I receive the following error:

![image](https://user-images.githubusercontent.com/36925557/87686098-69088d00-c784-11ea-9874-75f8c1ff1830.png)

I believe this is due to the fact that no governance script is provided, so I tried providing a governance script by running instead `python ../tests/e2e_scenarios.py --scenario ../tests/simple_logging_scenario.json -g ../src/runtime_config/gov.lua`, which then provides me the following errror:

![image](https://user-images.githubusercontent.com/36925557/87686331-aa993800-c784-11ea-9094-96c162972d31.png)

This is less clear to me. Could you tell me how to make this example work ?

Thank you.

**Comment by achamayou** [comment]
Hi @dhuynh95, thank you for trying CCF and for taking the time to provide feedback.

I am not entirely sure what we can do to improve https://microsoft.github.io/CCF/master/users/issue_commands.html#issuing-commands, that demonstrates how to send commands as standard HTTP requests to the framework using curl:

```
curl https://<ccf-node-address>/users/log/private --cacert networkcert.pem --key user0_privk.pem --cert user0_cert.pem --data-binary @request.json -H "content-type: application/json" -i
```

And the contents of request.json is spelled out just above the command in the example. You could use another HTTP client of course, but curl is quite widespread. Can you tell us what you find unclear in particular? We'd love to make the documentation more approachable.

The commands are calls into user application logic, so while we provide some samples, the expectation is that you will define your own, and call into it as useful for your particular scenario.

**Comment by dhuynh95** [comment]
Could you give more details about how to create the different .pem files used for the curl ? 

I did create the json file, but as I am still new to this, and it was not explicitly mentionned, I did not know how to create the pem files to do the curl.

Also could you detail a little bit more the code you used ? I see that the `start_test_network.sh` calls the `start_network.py`, but there does not seem to be much more details about what it does. So if we could have some documentation where we see in detail how we can start a network, how to define its application logic, and how to call it from outside, it would be great I think.

Thank you for your time.

**Comment by achamayou** [comment]
@dhuynh95 we provide a helper script to do this, you can find usage samples for users (https://microsoft.github.io/CCF/master/users/index.html#using-apps) and for members (https://microsoft.github.io/CCF/master/members/adding_member.html#generating-member-keys-and-certificate) in the documentation.

The start_test_network.sh script is a facility to get a network up and running rapidly. The sample Python code that it calls should be fairly readable, but the sequence is also documented in detail here: https://microsoft.github.io/CCF/master/operators/start_network.html#starting-a-new-network

**Comment by eddyashton** [comment]
@dhuynh95 Thanks for the comments. I'll update the docs to clarify these things, in particular to do a simpler walkthrough than the outdated scenario runner.

To answer your questions directly:

The .pems are created by running `start_test_network`, under `workspace/test_network_common` (so if you're in `CCF/build`, this is `CCF/build/workspace/test_network_common`).

The member and user certs are created by calling `keygenerator`, and then these were passed to the nodes on startup to specify the members and users who can currently talk to this service. So if you're calling a `/gov` endpoint, you can use `member0_[cert|privk].pem` to create a TLS connection _as_ member 0, and if you're calling an `/app` endpoint you'd use `user0_[cert|privk}.pem` to call _as_ user 0.

`networkcert.pem` is the service's identity, generated by the first CCF node in the service. We use this as the Certificate Authority in curl to authenticate the server identity. Only this CCF service (which hold's the corresponding private key within its enclaves) can successfully complete the TLS challenge to initiate these connections.

**Comment by eddyashton** [comment]
@dhuynh95 We've updated the introductory docs. In particular, the [end-to-end demo](https://microsoft.github.io/CCF/master/developers/demo.html) now recommends using curl rather than the outdated JSON scenario client.

I hope this clears up your questions. Please feel free to open further issues if anything else is unclear - we're always looking for feedback to improve our docs!
