### ISSUE TITLE
[Docker container] Failure in setup in installing open enclave dependencies 

### ISSUE THREAD

**Issue by atbagga** [microsoft/CCF#1425]
Following the instructions here - 
https://microsoft.github.io/CCF/master/quickstart/index.html

and it keeps failing with below error on command 
```
./run.sh ccf-dev.yml
```

TASK [openenclave : Install Open Enclave dependencies] ****************************************************************************************************************************************************************
   fatal: [localhost]: FAILED! => {"changed": false, "msg": "async task did not complete within the requested time - 600s"}

PLAY RECAP ************************************************************************************************************************************************************************************************************localhost                  : ok=19   changed=4    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by achamayou** [comment]
Hello @atbagga, could you make sure you have the latest master and try again? This looks like a failure in a step that would try to install all Open Enclave dependencies and build Open Enclave itself, that can be slow on machine with fewer cores or less memory and time out as you experienced.

The latest playbook pulls a binary install of Open Enclave and should be much quicker. If you are still hitting problems, you can pass '-vvv' to the script to get more detailed error output as well.

**Comment by atbagga** [comment]
Thanks @achamayou That resolved the issue. 
I had to pull the latest code in docker container the code already checked out in the container  isn't the latest.

 Close the issue or keep it open till the container is updated if you like.

**Comment by achamayou** [comment]
@atbagga Which container do you mean? I’m not aware of any containers that include a source checkout. The app-dev container includes the release artifacts and is produced on every release, it will be refreshed on the next release.

The ccf-dev playbook is meant to be used if you are setting up an environment to work on ccf itself, you would typically pick it up from a source checkout. If you are already in a container such as app-dev (meant for building a ccf app as opposed to working on the framework itself), then you should already have all the dependencies you need without running a playbook.
