### ISSUE TITLE
Errors encountered on running end-to-end tests

### ISSUE THREAD

**Issue by josh-richardson** [microsoft/CCF#143]
After having created a Microsoft VM with SGX support, and having cloned the CCF repository and successfully installed the requirements as specified in `README.md`, we attempted to run the end-to-end test as specified here: https://microsoft.github.io/CCF/demo.html

After executing ` python ../tests/e2e_scenarios.py --scenario ../tests/simple_logging_scenario.json -g ../src/runtime_config/gov.lua --label test1` in the newly created `build` directory of the cloned CCF repository, we see the following log output:

```
2019-06-11 23:57:18.477 | INFO     | infra.remote:stop:326 - [127.102.23.245] closing
2019-06-11 23:57:18.547 | ERROR    | infra.remote:log_errors:52 - /tmp/ccf_0/out: [fail]../src/node/rpc/nodefrontend.h:32 -  - Quote could not be verified OE_INVALID_PARAMETER
2019-06-11 23:57:18.547 | ERROR    | infra.remote:log_errors:52 - /tmp/ccf_0/out: [fail]../src/host/rpcconnections.h:179 -  - Cannot close id 3: does not exist
2019-06-11 23:57:18.547 | ERROR    | infra.remote:log_errors:57 - /tmp/ccf_0/err contents:
2019-06-11 23:57:18.547 | ERROR    | infra.remote:log_errors:58 - 
2019-06-11 23:57:18.547 | INFO     | infra.remote:stop:326 - [127.220.236.151] closing
2019-06-11 23:57:18.595 | INFO     | infra.ccf:stop_all_nodes:235 - All remotes stopped...
Traceback (most recent call last):
  File "../tests/e2e_scenarios.py", line 90, in <module>
    run(args)
  File "../tests/e2e_scenarios.py", line 68, in run
    network.wait_for_node_commit_sync()
  File "/tmp/CCF/tests/infra/ccf.py", line 284, in wait_for_node_commit_sync
    assert [commits[0]] * len(commits) == commits, "All nodes at the same commit"
AssertionError: All nodes at the same commit
```

This error is reproducible across multiple Azure VMs, and on a fresh installation of 18.04 on bare metal. Is this a bug in the CCF end to end test, or are we going wrong somewhere? Documentation on this seems to be quite sparse, and doesn't seem to be up to date with the latest command line parameters & switches. We do have a video of the entire process if this would be useful in debugging.

**Comment by achamayou** [comment]
@josh-richardson it looks like quote verification is failing for these nodes, so it would be good to check that the Intel PSW and driver are setup correctly and up to date. The playbooks under getting_started should help with that.

On bare metal, outside Azure, we wouldn't expect the quote verification to work. You will want to pass -DDISABLE_QUOTE_VERIFICATION=OFF to cmake on those machines. I notice that this isn't documented under https://microsoft.github.io/CCF/getting_started.html#build-switches and I will fix that.

Could you tell me what command line parameters and switches you have found to be incorrectly documented? I am keen to fix that. If you could share the video, I'd definitely take a look to see if I can spot anything.

Unfortunately, the SGX part of our CI pipeline is running on private executors at the moment (https://msr-gryffindor.visualstudio.com/COCO/_build?definitionId=82), and until a CI providers offers an SGX pool, we don't have a better solution. They are created using the exact files from the getting_started directory though, so I would expect that if you use that, you should be able to reproduce running the tests.

We have a public pipeline (https://circleci.com/gh/microsoft/CCF/tree/master), but that is running with virtual enclaves, not on SGX.

**Comment by achamayou** [comment]
@josh-richardson a likely reason quote verification is failing in your test on Azure machines is you aren't passing "-q" to the Python test (which results in the test picking up the quote files, and including them in the genesis for the nodes): https://github.com/microsoft/CCF/blob/master/cmake/common.cmake#L171

It is counter-intuitive that the default behaviour for the nodes is to expect quote verification, but that the test runner doesn't set them up unless you pass a flag. We don't see that in our CI because our cmake setup handles it, but we will change that behaviour in the test runner now, thank you for bringing that up.

**Comment by jumaffre** [comment]
https://github.com/microsoft/CCF/issues/146 has now been completed and you should not need to pass the `-q` flag to the python utility anymore, i.e. `python ../tests/e2e_scenarios.py --scenario ../tests/simple_logging_scenario.json -g ../src/runtime_config/gov.lua --label test1` should just work fine now (as of https://github.com/microsoft/CCF/commit/de6ae7bda44de6a8f8f581725ed1efc84fd8ab9d). 

If you decide to disable quote verification by passing `-DDISABLE_QUOTE_VERIFICATION=OFF` to cmake, you will need to pass `--ignore-quote` to the above command as CCF nodes will not output quotes. 

@josh-richardson Thanks for reporting this and feel free to let us know if you have any other issues.
