### ISSUE TITLE
Use type annotations in Python code

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1433]
See https://docs.python.org/3/library/typing.html.

This would make it easier for new developers/contributors to navigate the Python tests, and for new users to use the ccf Python package.

**Comment by achamayou** [comment]
I agree that this would be a very good investment for the ccf package, where it would help document and make safe the interface we expose. I'm less convinced it's worth the effort for the testcases themselves.

**Comment by letmaik** [comment]
I'm reopening this as there are still a lot of functions (possibly non-public) in the ccf package without annotations and it makes extending the code harder than necessary.

**Comment by achamayou** [comment]
@letmaik can you please open specific issues when you come across internal code without type hints that you find unclear?

I'm afraid we are not realistically going to prioritise the effort required to get every line of internal and test Python code to type-check.
