### ISSUE TITLE
Switch default behaviour for expecting quote

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#146]
As it stands, we need to explicitly pass `-q` (a.k.a. `--expect-quote`) to our python test infrastructure to explicitly tell python to copy the quote from the remote node to the local/build directory where the quote will be used to create `nodes.json`. 

However, we should expect most of our users to run these tests on a SGX machine, i.e. where a quote is produced. So we should switch the default behaviour for expecting quote, so that we need to explicitly pass a flag to specify to _not_ expect a quote (for example, on virtual builds).

See https://github.com/microsoft/CCF/issues/143

**Comment by achamayou** [comment]
This will also align the behaviour of the test runner with that of cmake, ie. expect a quote by default, but accept a flag to disable checking optionally.
