### ISSUE TITLE
Host-side fairness in libuv processing

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1462]
The jobs in our host-side uv loop are currently greedy, executing all available work before yielding. This leads to some resource hogging and queuing behaviour, which can delay the sending of tick messages.

We should instead have caps on all of these tasks, limiting the amount of work we do each loop and thus bounding the time between ticks. This issue lists the systems where we should introduce this cap, and an initial plan for how the cap should be measured:

- [x] `HandleRingbuffer` shouldn't run a `while` loop, it should only run `max_messages` a single time.
- [x] TCP connections. We should cap the amount we read from each connection, by reducing the allocated size in `on_alloc` in `tcp.h`.

**Comment by achamayou** [comment]
Ideally we'd prefer max_bytes than max_messages, because it's a better proxy for work/memory consumption in enclave. We may not be able to be that precise (could be more like the smallest number of messages that exceeds max_bytes), but it should still be the idea, I think.
