### ISSUE TITLE
Retired Leader Node Still Participates in Consensus

### ISSUE THREAD

**Issue by lynshi** [microsoft/CCF#1485]
**Describe the bug**
After a proposal to retire leader node X has been accepted, node X still participates in the consensus as evidenced by the `/node/signed_index` endpoint. Node X's signed index continues to increase and keep up with the network signed index.

**To Reproduce**
1. Start a 3 node CCF network.
2. Submit and accept a proposal to retire the leader node (e.g. node 0).
3. Make an arbitrary write transaction to increase the network commit.
4. Make a request to `/node/signed_index` on node 0, which shows that its signed index is still the same as the global signed index.
5. Make a request to `/node/network_info` on any other CCF node. The response shows node 0 is not listed as part of the network nodes, but the primary is still node 0.

**Expected behavior**
The retired node immediately stops participating in the consensus and is removed from the network.

**Environment information**
CCF version: 0.11.7

**Comment by eddyashton** [comment]
Some quick triage notes:
- I think we should revisit #177 as a fix for this - afaict the only missing complexity is tracking when an _active_ node's removal is _committed_
- I thought this issue may have arisen from the changes in channel handling in #1377 but it looks like its been around longer
- Even if we can implement the full node shutdown, we should take a look at how decoupled our _Raft_ and _service_ node sets/states are, and see if there's a cleaner way for one to drive the other

**Comment by lynshi** [comment]
Adding on to this, after any node has been retired (including non-leaders), a query directly to the retired node on `/node/signed_index` returns a response with `'state': 'partOfNetwork'` which is misleading.

**Comment by achamayou** [comment]
- [ ] Generalise retire_node_test in reconfiguration.py to cover this situation
- [ ] If primary, close all channels, which ought to make the test pass
- [ ] If secondary, keep track of nodes removed in current term, and reject traffic/close channels from them
- [ ] Shut down node cleanly on removal
