### ISSUE TITLE
KV threading issues

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1491]
This ticket lists known issues with the key-value store that may hinder our implementation of multi-threading inside the enclave. 

For conciseness, I'm opening this unique ticket with a list of known issues rather than individual tickets for each - we can create such tickets to discuss/fix specific issues when required.

- [x] 1. Map `roll`'s tail is read when serialising the write set of a transaction _without taking a lock on the map_. https://github.com/microsoft/CCF/blob/05e0805db3a8accb63d6467a5a6be33e523e32ac/src/kv/untyped_map.h#L397

- [ ] 2. When deserialising append entries messages, a new entry is appended to the history _non-atomically_ with `apply_views`. In other words, another transaction could write to the history between the state of the KV being updated and the history being updated. Note that this is unlikely to happen in practice (even in a multi-threaded scenario) as transactions are deserialised by the consensus one-by-one. https://github.com/microsoft/CCF/blob/05e0805db3a8accb63d6467a5a6be33e523e32ac/src/kv/store.h#L579

**Comment by achamayou** [comment]
I don't think I understand what the impact of 2. would be, considering that the history is never accessed by read-only transactions (the only kind that could execute on backup). What's the possible user impact?

**Comment by achamayou** [comment]
@jumaffre I don't believe #2 is a problem, because the consensus would not allow a write during a deserialise. So it would only be a read, which wouldn't have a consistent view of the KV and the history. But then that's not a guarantee we make, nor one any read relies on, so I don't think there's an issue here?

**Comment by jumaffre** [comment]
@achamayou Only reading this now. I agree. Closing this issue.
