### ISSUE TITLE
Dynamic creation of KV tables

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1501]
Currently all KV tables must be statically declared at compile time. They are actually created at runtime, after the store is created, during node startup, but we expect this to happen before any transactions run. This is unnecessarily rigid, and in particular is awkward for dynamic runtime apps (eg - `lua_generic` and `js_generic`). We want these to be able to create tables they need on-demand, so that when new endpoints are added to the app they may talk to new tables.

This involves changes to the KV API (Txs must be created with reference to a Store, where they may create tables), how we access Maps (through a Tx, probably always?), and how we serialise (may need to explicitly indicate map creation when serialising a write set).

**Comment by achamayou** [comment]
@eddyashton created #1663 to track the last two items, which do not need to be done in 0.14, where we just want to enable dynamic table creation for users.

**Comment by eddyashton** [comment]
Documentation added in #1674, followup work covered in #1663.
