### ISSUE TITLE
cchost interval options should be clearer 

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1504]
As CLI options to `cchost`, we currently use:
1. `sig-max-ms` and `sig-max-tx` to specify the interval at which signature transactions are created
2. `ledger-chunk-min-bytes` to specify the size at which we aim to chunk the ledger 
3. `snapshot-max-tx` to specify the interval at which snapshot are generated

However, the use of min/max can be a little confusing for operators (it certainly is for me!). For example, `sig-max-ms/tx` specify the interval at which signature transactions are emitted. However, because of transaction concurrency, it is likely that the interval between two signature transactions is _slightly_ greater than `sig-max-tx`. In a similar way, `ledger-chunk-min-bytes` refers to the size that operators will want each chunk to be but in practice, we will only chunk once we have passed this threshold _and_ a signature has been emitted.

These slight differences are really just rounding errors and I believe that using `sig-ms-interval`, `sig-tx-interval`, `ledger-chunk-bytes` and `snapshot-tx-interval` would be simpler/less confusing from the perspective of operators. Of course, our documentation should state what the differences between the CLI values and the actual behaviour is.

**Comment by achamayou** [comment]
Sounds good, as discussed, the intention is for those values to be maximums (ie. `sign at least this often`) but due to technical constraints (concurrency, transaction atomicity) it isn't possible to guarantee them exactly. I agree the replacement terminology is likely to be better understood.
