### ISSUE TITLE
Node RPC port should default to 443

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1506]
As CCF nodes are now full-fledged HTTPS servers, we should default the RPC port to 443 when none is specified. 

This will interfere with the current behaviour where port 0 is selected when none is passed in.

**Comment by achamayou** [comment]
We can manually pass 0 in our test infra though?

**Comment by jumaffre** [comment]
> We can manually pass 0 in our test infra though?

Yep, and we will do that. But it would be nice to default to 443 for the `start_test_network.sh` script.

**Comment by achamayou** [comment]
I'm not sure 443 is the right default for `sandbox.sh` considering that it's more likely to be run on dev environments by users that aren't likely to be privileged. Something unprivileged like 8000 may be preferable there.

As far as `cchost` itself is concerned, I agree that 443 is a good choice.
