### ISSUE TITLE
Table lookup failures in Lua runtime are non-obvious

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1517]
In Lua, to operate on a KV table, you do `tables.foo.put`. If `foo` doesn't exist, you get the generic Lua error:

`Script failed: Failed to run Lua code: [string "?"]:3: attempt to index a nil value (field '?')`

We should avoid this error everywhere we can - where this is actually lookup on a table defined in C++, we should have a lookup function that returns a useful error (ie - in this case, `Table foo does not exist`).

As we expand the JS support, we should make sure we fix this kind of thing there as well.

**Comment by achamayou** [comment]
Lua has been removed, the JS runtime produces user-friendly exceptions.
