### ISSUE TITLE
code_update_test fails on CI

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1526]
The `code_update_test` has recently started failing: https://dev.azure.com/MSRC-CCF/CCF/_test/analytics?definitionId=3&contextType=build 

Example of failed test run: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=11867&view=results

**Comment by jumaffre** [comment]
Another instance: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=12709&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=efdbc34d-c6b6-5dc6-e05c-1751d4c47c20&l=16050

**Comment by achamayou** [comment]
Not enough information to investigate.
