### ISSUE TITLE
BFT tx encryptor variant is dead code

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1538]
We should remove the BFT variant of the encryptor as it is now unused.

It is also unsafe to use as it may use the same IV for two different entries as the IV only depends on the `version` and `node id` (IV would be re-used on rollbacks).

**Comment by ashamis** [comment]
We need the BFT variant of the encryptor for when we are re-executing requests by the backups. 

I added https://github.com/microsoft/CCF/issues/1567 to see if we can combine the two.
