### ISSUE TITLE
Remove maa.h

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1546]
`src/node/maa.h`

This file was added in #1448 to support the custom report format that MAA uses in its certs and which OE does not support in its `oe_verify_attestation_certificate` function. OE and MAA will align on this and OE will gain support for MAA certs (or arrive at some non-MAA specific solution) in a future release, see also https://github.com/openenclave/openenclave/issues/3313.

Once OE's `oe_verify_attestation_certificate` supports MAA certs, the `maa.h` file can be removed again and the call to `verify_maa_root_ca_certificate()` replaced by `oe_verify_attestation_certificate()`. The signatures are the same (at least, currently).

**Comment by gkostal** [comment]
@letmaik , the MAA service recently changed to use `oe_generate_attestation_certificate` to generate signing certificates, so `oe_verify_attestation_certificate` should now work.

**Comment by letmaik** [comment]
@gkostal That's good news! Thanks for pushing this through.
