### ISSUE TITLE
Upstreaming of export patch for QuickJS

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1551]
CCF currently uses a patch from https://www.freelists.org/post/quickjs-devel/Patch-Add-some-informations-to-get-more-informations-from-compiled-modules to access exported JS functions from C++.

This issue tracks the upstreaming of this patch to QuickJS mainline and subsequent removal in CCF.

A new thread on the QuickJS mailing list has been started: https://www.freelists.org/post/quickjs-devel/Merge-patch-to-access-module-exports-from-native-code

**Comment by achamayou** [comment]
I wonder how well the quickjs-devl mailing list works at the moment, I haven't received anything from it since early August.

**Comment by letmaik** [comment]
Works fine... I didn't know I have to subscribe to send a message, didn't get any error back. You should have received the post now.

**Comment by achamayou** [comment]
I have indeed.

**Comment by achamayou** [comment]
@letmaik could you perhaps ask about this again, it seems to have been forgotten?

**Comment by letmaik** [comment]
The mailing list seems to be dead, I don't think asking again makes much sense.

**Comment by achamayou** [comment]
Ok, there's not much point keeping this open then.

**Comment by achamayou** [comment]
Issues on GitHub do seem to receive answers: https://github.com/bellard/quickjs/issues, @letmaik can we please try again there?

**Comment by letmaik** [comment]
https://github.com/bellard/quickjs/issues/34

**Comment by achamayou** [comment]
Not heard anything back, presumably no appetite upstream for this feature.
