### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1564]
We should cull unused code. Please add anything else you find to this list.

- [x] Notification system (#1582)
- [x] user_code governance flow (#1611)
- [x] flatbuffers usage in benchmarks and flatbuffers dependency (#1593)
- [x] valijson
- [x] txregulator test
- [x] lua generic
- [x] mpscq commented out code
- [x] mod_mbedtls commented out code
- [x] flatbuffers
- [x] k6

**Comment by ashamis** [comment]
I am removing the following off the unused code list:
* BFT Tx Encryptor (#1538)
* BFT-specific paths in frontend/kv
They are needed for AFT and I am actively working on integrating back into said code

**Comment by achamayou** [comment]
The sig fwd test doesn't seem to be running any faster than the regular client sig test. We don't currently have much of a use case for client signatures, so I think we could just take it out.

**Comment by achamayou** [comment]
The batched test needs to be migrated to JS before we can removed lua_generic.

**Comment by letmaik** [comment]
With https://github.com/microsoft/CCF/pull/1905 it looks like this issue is complete?

**Comment by eddyashton** [comment]
Correct!
