### ISSUE TITLE
Dynamic endpoint installation

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1565]
Currently endpoints are defined in 2 ways - statically with `make_endpoint().install()`, and dynamically with the default handler. The latter lets us modify the endpoints at runtime, reading the handler script in each transaction. However we cannot declare additional properties for these handlers - whether they should be forwarded, what HTTP methods they support, their schema, etc. We would like to remove this barrier, and allow runtime-added endpoints to follow the same dispatch path as statically defined endpoints.

In short, this means putting more of the endpoint definition into the KV, and reading the endpoint definitions during transaction execution. This is likely the kind of data we want to cache in each node for efficiency, if we can find a safe way to ensure it matches the KV's current state.

This introduces an extra wrinkle in forwarded transactions. If the definition of the endpoint has changed between the follower's read (and decision to forward), and execution on the primary, we could produce unsound results (endpoint now says it needs a signature but was never verified, endpoint says NeverForward but was, etc). I believe we can handle these cases by passing a digest of the endpoint definition with the forwarded request - if the primary sees a different endpoint definition (in _any_ way) than the forwarded did, this is a try-again error that goes all the way back to the client.

**Comment by achamayou** [comment]
As discussed, it may be useful to distinguish a digest mismatch (ie. primary has different, likely newer definition), which is a 412 or similar, from a handler that's been removed altogether (404). The former probably calls for a re-try, whereas the latter is more likely to be final.

To support this, passing a (name, digest) should be enough.

**Comment by achamayou** [comment]
@eddyashton can you confirm the current dynamic endpoint implementation is correct even when transactions are forwarded?

**Comment by eddyashton** [comment]
We don't transmit digests as suggested above, but that was mostly to deal with the proposed cache. While implementing dynamic endpoints we gave up on these caches, and instead retrieve the endpoint data "normally" via the transaction (I think if we revisit caching this, we need a safe general solution). So most of the potential unsoundness is sidestepped.

But its still possible to forward something that you "shouldn't" have - ie you send it to a backup who sees an endpoint saying this request should be forwarded, but by the time the primary executes it the endpoint is changed to say no forwarding. You end up executing at a version that says "this shouldn't be forwarded", but this request _was_ forwarded. This sounds wrong but I'm struggling to gauge how severe it is.

**Comment by achamayou** [comment]
@eddyashton that does not sound like a problem, because it seems to me that it reduces to "between the call and the execution, the endpoint implementation may have changed". If you have asynchronous calls that can be updated, that's a fact of life. It's up to the user if they think this is a feature (transparent updates) or a bug (they can version symbols then).

I'm closing this because I think this item is complete, if we think there are issues with the current implementation, let's open them separately.
