### ISSUE TITLE
Combine the CFT and BFT encryptors

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#1567]
We currently have a BFT and CFT encryptors. We need to look into combining them so that we only have 1 encryptor, if this is at all possible.

**Comment by achamayou** [comment]
Historically, the Raft encryptor used node_id as part of its IV, which leads to node-dependent encryption output and doesn't work with execution on backups. The BFT encryptor doesn't, but @jumaffre has a concern about IV re-use, and there was probably a reason we kept both although I can't remember why now.

**Comment by jumaffre** [comment]
The current Raft encryptor is safe to use as it uses a monotonic ID for each encrypt operation (so safe across rollbacks and snapshots). Having a unique encryptor for both consensus is definitely better (it was touched on in https://github.com/microsoft/CCF/pull/1536) but requires some refactoring that I left out of this PR. 

The only thing we need to be aware of when using the BFT encryptor is the IV re-use across rollbacks, as per the below comment:
https://github.com/microsoft/CCF/blob/555952693535d24ceaaa71129784d10eff0b3d38/src/kv/encryptor.h#L31-L34
