### ISSUE TITLE
AFT: Create a method to describe which properties the consensus will support

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#1578]
We need to create a methodology on how to describe which consensus properties are being used. This should be user facing, consumed by AFT on startup.

**Comment by achamayou** [comment]
I think this will end up being a significant chunk of CCFConfig, and something we want to have in KV as well. The two things that come to mind are execution (local or everywhere) and commit level (CFT vs BFT) but I'm sure there's more switches that I haven't though of (identity: shared or distributed? perhaps something to control forwarding?)

**Comment by achamayou** [comment]
@ashamis so we're going with just two levels right now, CFT and in-progress BFT, right?

**Comment by ashamis** [comment]
Yes, I believe that's what we agreed on. Did I misunderstand something?

**Comment by achamayou** [comment]
Not at all, just making sure it’s recorded in the ticket :)
