### ISSUE TITLE
Expose response body in Python client similar to request body in JS endpoints

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1584]
Follow-up from https://github.com/microsoft/CCF/pull/1575.

In JS endpoints, the request body is a `Body` object which is similar to https://developer.mozilla.org/en-US/docs/Web/API/Body, except that it has a synchronous API and only offers `.text()`, `.json()`, and `.arrayBuffer()`.

In the Python client, for HTTP, the response content type determines the type that is returned, see `Response.from_requests_response()`, and for WS, given the lack of headers, an attempt is made to parse JSON with fall-back to return `bytes`.

It probably makes sense to align the handling of response bodies in the Python client to how JS endpoints handle request bodies. This gives the developer more control over how they access the body.

**Comment by achamayou** [comment]
@letmaik that's a very good point.

**Comment by letmaik** [comment]
Before I change the ~90 places to use the new API, is everyone ok with the following interface?

```py
class ResponseBody(abc.ABC):
    @abc.abstractmethod
    def data(self) -> bytes:
        pass
    
    @abc.abstractmethod
    def text(self) -> str:
        pass
    
    @abc.abstractmethod
    def json(self) -> Any:
        pass
```

Old: `assert r.body == "text"`
New: `assert r.body.text() == "text"`

**Comment by achamayou** [comment]
@letmaik lgtm, I suggest throwing in __str__() as an alias for text(), and adding a __repr__() that's either an alias for data() or something that includes it.
