### ISSUE TITLE
Investigate performance of proposals with large bodies

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1585]
In https://github.com/microsoft/CCF/pull/1575 the request timeout was increased from 3s to 10s to avoid intermittent timeout failures caused by https://github.com/microsoft/CCF/pull/1557.

3s should be enough to handle ~500KiB.

On top of that, in CI, timeouts were not happening in SGX, but in virtual enclaves and I wasn't able to reproduce them locally on a DC8 . A factor in this is that virtual enclave builds in CI don't run on DC8 but on D8S, which probably has different performance characteristics.

**Comment by achamayou** [comment]
The virtual debug build is heavily instrumented (ASAN and UBSan), and current efforts for managed application runtime are directed at containerised handlers, rather than optimising the JS interpreter, so we are not going to look at this in the foreseeable future.
