### ISSUE TITLE
Move all the build-your-JS-app docs to a new dedicated section in sphinx docs

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1622]
https://microsoft.github.io/CCF/master/developers/index.html

Existing text:
- tests/npm-app/README.md
- tests/npm-tsoa-app/README.md

**Comment by achamayou** [comment]
I'll flesh out the contribution guidelines (https://github.com/microsoft/CCF/blob/master/.github/CONTRIBUTING.md) to mention documentation, sorry if that was unclear.
