### ISSUE TITLE
Lua support needs improved documentation, error messages

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#163]
Our lua documentation is out-of-date, still mentioning the `msg_id` field which is no longer passed to handlers.

It also describes overriding the `__default` handler function _or_ individual functions matching the RPC method names. Our example apps only use the latter - perhaps the former can be removed.

When the API for these handlers changes, the lua apps will fail with obscure messages. We should look at improving this by adding validation of the arguments (number, named elements in a table, metaclass providing errors on missing lookup). It would also be useful to add explicit registration to find and report mismatches when the service starts, rather than when an out-of-date method is called.

**Comment by achamayou** [comment]
I have updated the documentation, but we should simplify the interface by having a single mechanism (__environment + named handlers I think), and update the testcases accordingly.
