### ISSUE TITLE
JS type representation and conversion for kv tables

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1634]
On the C++ side of the `js_generic` app, all of the tables are untyped - byte-vector to byte-vector*. We could represent this directly in JS, with all keys and values as `ArrayBuffer`s. However, this introduces some needlessly expensive conversions; a common use case will be `string` keys, and we should be able to use these with minimal copying. Converting from `ArrayBuffer` to `string` in JS is an [extremely manual process](https://developers.google.com/web/updates/2012/06/How-to-convert-ArrayBuffer-to-and-from-String).

To clarify, we'd like to write the following things in JS:

```
foo = tables.get("foo");
foo.put("hello", 123);
foo.get("hello"); // Returns 123, as a number
foo.put("hello2", "world"); // Tables can hold mixed types!
foo.get("hello2")); // Returns "world", as a string

// Sometimes we want to store/get arraybuffers
let k = Protobuf.Encode("I have no idea what this API is but it returns an ArrayBuffer");
let v = Protobuf.Encode("Some value");
foo.put(k, v);
let v_retrieved = Protobuf.Decode(foo.get(k));
```

The current plan to achieve this is to store these values with **Type Tags**. We need at least tags for `ArrayBuffer` and `String`, and then `JSON` is a helpful catch-all that gives us support for all other types (that we care about).

As a sketch, this would look something like:

```
enum JSTypeTag : uint8_t
{
  ArrayBuffer,
  String,
  JSON
};

static JSValue js_put(
    JSContext* ctx, JSValueConst this_val, int argc, JSValueConst* argv)
{
  auto table_view =
    static_cast<Table::TxView*>(JS_GetOpaque(this_val, view_class_id));

  std::vector<uint8_t> serialised_key;
  if (JS_IsString(argv[0])
  {
    serialised_key.push_back(JSTypeTag::String);
    serialised_key.insert( ...raw string bytes from string JSValue... );
  }
  else if (JS_IsArray(argv[0])
  {
    serialised_key.push_back(JSTypeTag::ArrayBuffer);
    serialised_key.insert( ...raw bytes from ArrayBuffer JSValue... );
  }
  else
  {
    serialised_key.push_back(JSTypeTag::JSON);
    auto JSONed_key = JS_JSONStringify(argv[0]);
    serialised_key.insert( ...raw string bytes from string JSONed key... );
  }

  // Do the same for the value in argv[1]
  serialised_value = ...;

  table_view->put(serialised_key, serialised_value);
}
```

And the symmetric operation (check the first byte for a know tag, call `JS_ToCStringLen` or `JS_NewArrayBuffer` or ... as appropriate) for `js_get`.

This is trying to be as efficient as we can. When we `get` an `ArrayBuffer`, it can point to memory owned in C++. When we work with strings, we only do the necessary copy in/out of the QuickJS context, and no additional encoding (ie - not wrapping in JSON quotes). We have JSON as a general fallback to support other types, but if that's insufficient we can also provide custom encoding for numbers.

\* This untyped-ness is true of all JS-defined tables, but is _not_ true of governance tables. When exposing a typed table like `ccf.members` (`MemberId` -> `MemberInfo`) to JS, we could insist that it obeys the tag-prefixing of other JS tables. This makes the C++ code which exposes the table, and the representation of these tables in the ledger, consistent. However I think it makes working with these tables in C++ much more awkward, as the knowledge of these type tags and their serialisation leaks throughout the code. Instead I think we should maintain the existing types and serialisation, and expose these tables to JS with more-restrictive `get`/`put` methods which enforce/return the appropriate types.

**Comment by eddyashton** [comment]
2 other options discussed:

- JS tables don't really need mixed types within a single table, so they could encode the intended types in the table key (name), ie - `tables.get("foo:string.num")`. So we know the types of C++-defined tables from the C++ types, and JS-defined tables from the table name. On the C++ side, we can inspect the table name and do some appropriate conversion for incoming/outgoing JSValues.
- Return an object with `.toString()`, `.toArrayBuffer()`, etc methods on it. This perhaps makes the JS code uglier, but explicit. When JS gives us data, we can accept several types and serialise it how we like, as long as we do the reverse serialisation when requested (and eventually, hopefully, apps convert to `ArrayBuffer` within JS).

**Comment by achamayou** [comment]
JS tables don't _need_ mixed types, but it would compliant with the Map interface, and quite convenient to implement optionals etc.

**Comment by letmaik** [comment]
Related:
- https://github.com/microsoft/CCF/issues/1530
- https://github.com/microsoft/CCF/issues/1678

PR:
- https://github.com/microsoft/CCF/pull/1714
