### ISSUE TITLE
JS app bundle & deploy_js_app proposal

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1642]
Deployment of JS apps is currently a bit fiddly, mostly because there are multiple low-level steps involved.

I propose to introduce the concept of a JS app bundle, which is a folder containing two things:
- `endpoints.json`
- `src/` (tree of .js files)

This folder can optionally be zipped up, at which point it becomes a JS app bundle archive. Both the folder and the zip file (useful for a developer/CI to deliver the built app to the operator for deployment) are accepted by CCF's Python package in a new proposal type `deploy_js_app` (this may or may not be a collection of existing low-level proposals).

An initial sketch of `endpoints.json` is here: https://github.com/microsoft/CCF/blob/master/tests/npm-tsoa-app/endpoints.json.

The idea of this bundle format is that it is simple enough for manually written code and also suits itself for more advanced scenarios like npm-based typescript apps with dependencies.

Does this make sense?

**Comment by achamayou** [comment]
As discussed with @eddyashton, this is an excellent idea, and adding support for this in the client-side governance infra is definitely a good short-term change.

It raises some interesting possibilities around identifying (by digest) and authenticating (by signature over that digest) code bundles, and whether that could and should be further integrated into our governance. This was explored, but requires further discussion. Consensus was that this discussion can take place after the governance has been migrated to JavaScript.

Tangentially, providing transparency into identifying and perhaps authenticating dependencies included in a bundle, and exposing that to governance would also be an interesting direction to explore. The approach we have opted to take with modules means no dependency sharing at all, and a complete re-upload of the app on update, so the review burden is maximal at the moment.
