### ISSUE TITLE
Failed public recovery entries will block further recoveries

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1652]
If a recovery fails (i.e. recovery shares are not successfully submitted), the ledger will contain a suffix of entries that are not covered by any recovery shares. This is because we don't issue new recovery shares on the new network until the old shares have been submitted (since the new ledger secrets encrypt the previous ones). If an operator retries a recovery with that ledger, the suffix will happily be deserialised (we only check the integrity of entries via the Merkle Tree at this point) but the recovery procedure will eventually fail.

Instead, when we recover a ledger, we should discard entries that belong to a new service but are not covered by recovery shares. For convenience of operators handling ledger files, we should also start a new ledger chunk when recovering a service, and possibly mark the "orphan" ledger chunks so that they are ignored by the new service.

Note that adding a new end-to-end test for this should be pretty trivial.

**Comment by achamayou** [comment]
In case it's any help to someone reading this, the reason the recovery procedure will eventually fail is that integrity checks of replicated entries are performed with the applicable ledger secret.
