### ISSUE TITLE
JS request body validation in C++ with OpenAPI

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1654]
## What
This issue tracks whether/when/how CCF should add built-in support for validation of JSON request bodies for JS endpoints in C++. 

Note that OpenAPI also allows specifying schemas for query params, url template params, and headers. For the purpose of keeping it simple, validating those is out of scope for now (though note that tsoa (see below) does validate all of them). 

## Status quo
Currently, CCF validates request bodies for C++ endpoints only.

For tsoa-based JS apps (see `test/npm-tsoa-app`), validation comes for free and is done by the JS framework.
For any other JS apps, validation is typically done manually in JS.

## Motivation
There is a more general question on whether validation should be done at all on C++ side.

Upsides:
- App devs can rely on a tested and fast validation mechanism without relying on a JS library or custom code.
- Since deployed OpenAPI schemas would always be used in validation (if not disabled), they are more likely correct.

Downsides:
- The request body is parsed twice (once via nlohmann for validation, once via quickjs for `request.json()`).
- The CCF team would have to maintain the validation code and deal with potential issues in valijson.
- To avoid double validation, a new per-endpoint attribute would have to be introduced to optionally disable C++ validation (e.g. if tsoa validation is used already).

## Challenges
The main challenge is that OpenAPI <= 3.0 uses a fork of JSON Schema that is incompatible with generic JSON Schema validator implementations. This is fixed in 3.1 (to be released) where a strict superset of JSON Schema 2019-09 is used (using the right compatible extension mechanisms).

There are no OpenAPI validators in C/C++, so using a JSON schema validator is the next best.

## Options
There are two options:
1. Convert OpenAPI 3.0 schemas to standard JSON Schema before validation
2. Move to OpenAPI 3.1

Option 1 is tricky because:
- No C/C++ libraries exist that do the schema conversion. There do exist [Python](https://pypi.org/project/py-openapi-schema-to-json-schema/) and [JavaScript](https://www.npmjs.com/package/@openapi-contrib/openapi-schema-to-json-schema) libraries.

Option 2 is tricky because:
- OpenAPI 3.1 is not out yet.
- Libraries that generate OpenAPI definitions don't support 3.1 yet.
- valijson (C++ validation library) doesn't support JSON Schema 2019-09 yet.

## Things to discuss
In this issue we should discuss the Motivation and Options.

**Comment by eddyashton** [comment]
Just to clarify: We don't currently explicitly validate in C++, we just throw schema-like errors if the given object doesn't convert successfully.

Writing `.set_params_schema<Foo>()` only sets what we _report_ as the schema, it doesn't introduce any validation against that schema. The expectation is that the handler then calls something like `body_as_json.get<Foo>()`, but there's no strong connection.

So while we could expose a C++ validator, it may make sense to make it an explicit opt-in conversion (ie - `call(ccf.parse_body_as(request.body, foo_schema))` in JS) for current compatibility. This makes it simpler to avoid double-validation, allows us to skip it if the handler is unhappy with the headers, etc.

**Comment by achamayou** [comment]
This seems like a slightly niche concern, it's not clear to me that it's best addressed by CCF itself.

For both C++ and JS, CCF recommends (and provides in the former case) a code-first approach, where the OpenAPI schema is generated, and validation happens automatically during parsing. This is both efficient and user-friendly. It comes with some limitations (some users may not wish to use TSOA, and the C++ schema mechanism comes with some restrictions on what types are supported).

Code that can't/doesn't want to use these mechanisms should be able to bring and use its own validation library, and publish its endpoint schema for inclusion in the broader application schema. We could go pick and recommend some of these libraries, but they would only ever be a "second best" choice, and not something we use ourselves.

I am fine with documenting publishing a per-endpoint schema and showing where validation logic might be called, but I am reluctant to build a dependency/provide further integration.

**Comment by letmaik** [comment]
@achamayou I agree with that. This issue is mostly about making an informed decision on the topic and have a written history.
