### ISSUE TITLE
Create Tx in ProgressTracker in the new style, from a Store

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1675]
As mentioned in #1674 - `progress_tracker.h` is (I believe) the last place in the code using an old-style, manually constructed `kv::Tx`. I'd like to replace this with `store.create_read_only_tx()`, but `Store` holds a `ProgressTracker` so it's hard for `ProgressTracker` to hold a `Store`. We can break the circular dependency with an abstract interface, but there may be a simpler solution.

Once this is done, we can enforce use of the 'new-style' `Tx` by hiding the constructor and making it visible only to the `Store` via `create_tx()`.

**Comment by achamayou** [comment]
ProgressTracker no longer does this and calls back to the store to verify signatures, this is resolved as far as I can tell.
