### ISSUE TITLE
Re-think "tables" global in JS apps

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1678]
The `tables` global exposed to JS apps is a bit awkward, mostly because it has a very "normal" name. Renaming to `ccfTables` will avoid conflicts with application code.

I think keeping it as a global makes sense, since it's equivalent to `localStorage`/`sessionStorage` in browsers.

**Comment by achamayou** [comment]
It might make sense to create a `ccf` global even (`ccf.maps`), since there may be more things we want to have in there.

**Comment by letmaik** [comment]
Possibly. And it would be good to decide on terminology. Store? maps? tables?

**Comment by achamayou** [comment]
We've settled on Maps and done more of the renaming already, tables suggested more potential complexity than our strictly key, value maps will ever support. If we also aim to be close to ES Maps, that's even more reason to go there in the JS app context.

**Comment by letmaik** [comment]
After internal discussion, we settled on `ccf.kv`.
