### ISSUE TITLE
Document minimal steps to run an end-to-end test

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1680]
For local developer testing it would be nice to have a dedicated page in the docs that contains the minimal commands necessary to spin up a one-node network to a state where sending app requests is possible, based only on the installed Debian package and the Python client. This can then be used as basis for CI scripts. The immediate use case for me would be to run a JS app.

**Comment by achamayou** [comment]
We have something that’s pretty close, except for the JS bit: https://microsoft.github.io/CCF/master/operators/deploy_app.html?#starting-a-test-network

**Comment by letmaik** [comment]
The `start_test_network.sh` script is not part of the Debian package (which is fine) but it's not clear from the docs that you  essentially have to create your own variation of that script which then uses the `/opt/ccf-../bin/start_network.py` script.

Does it make sense to extend the `start_network.py` script with an additional parameter to deploy a JS app bundle after startup?

**Comment by letmaik** [comment]
With https://github.com/microsoft/CCF/pull/1688 I'm now able to start a network with JS app deployed, from the CCF repo tree: 
```
cd build
../start_test_network.sh --package libjs_generic --js-app-bundle ../tests/npm-app/dist --node localhost --verbose
```

What are the downsides to including an install-variant `start_test_network.sh` script in the Debian package?

**Comment by letmaik** [comment]
Updated docs should be based on https://github.com/microsoft/CCF/pull/1695.

**Comment by jumaffre** [comment]
@letmaik I am currently updating the docs and will create a PR for this soon. I propose that we do not touch the docs regarding the new `sandbox.sh` until #1695 is merged and my PR is up?

**Comment by letmaik** [comment]
@jumaffre This seems related to https://github.com/microsoft/CCF/issues/1700 (maybe somehow the same). Probably makes sense to address both issues at once.

**Comment by jumaffre** [comment]
@letmaik Yes. I think these are slightly different issues that can be implemented together so I'll do both at once.

**Comment by achamayou** [comment]
Rolled into #1700
