### ISSUE TITLE
Garbled sequence diagram in doc

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#1681]
https://microsoft.github.io/CCF/master/users/issue_commands.html

![image](https://user-images.githubusercontent.com/4016369/94782821-af54ac00-03c3-11eb-8c49-4e692b39c87f.png)

**Comment by eddyashton** [comment]
This link renders correctly for me

![image](https://user-images.githubusercontent.com/6000239/94784247-cbf1e380-03c5-11eb-9915-204662612475.png)

**Comment by achamayou** [comment]
This happens only some of the time, bizarrely...
