### ISSUE TITLE
Benchmark jsrasign crypto & consider implementing Web Crypto API for JS apps

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1683]
[jsrasign](https://kjur.github.io/jsrsasign/api/) provides a superset (?) of the functionality of the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) implemented in pure JavaScript.

Previously I tried to add a sample using jsrasign but the operation I tried to use (I think public/private key generation) was too slow to be useful. This is expected as QuickJS does not jit JS code and crypto code can be quite expensive.

The goal of this issue is to benchmark a subset (tbd) of crypto operations in jsrasign and decide whether it makes sense for performance reasons to provide a fast C++ based implementation of the Web Crypto API as an alternative for app developers.

**Comment by achamayou** [comment]
@letmaik what subset of the API is necessary exactly?

**Comment by letmaik** [comment]
I'm reopening this once there is a concrete problem.
