### ISSUE TITLE
Update docs to use sandbox.sh

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1700]
From https://github.com/microsoft/CCF/pull/1695

**Comment by letmaik** [comment]
@jumaffre Do you want to take this one?

**Comment by jumaffre** [comment]
Yes, leave this with me. Slapping the `0.15` label on this so I don't forget to update it before the next release.

**Comment by achamayou** [comment]
The existing mentions of start_test_network have been converted for 0.14.2, but as pointed out in #1818, they aren't ideal, and we're missing a js app bundle sample use too.

**Comment by achamayou** [comment]
Still to be done:

- [ ] js app bundle sample
- [ ] describe using the sandbox for end to end tests
- [ ] describe using the sandbox for performance test with vegeta
