### ISSUE TITLE
Improve historical query support

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1705]
We have initial support for historical queries. This issue tracks the remaining tasks:

- [x] Retrieve secrets to decrypt historical entries, after snapshot recovery (#1648)
- [x] Additional validation of historical entries. Currently we check the signature over the target ledger entry, but don't check that the signing node is still an active participant at the point of the signature. We should work out if this is possible.
- [ ] Explore queries from snapshots. Currently we can query the state written _in_ specific target transactions, but not general state. Snapshots make it much cheaper to restore an entire historical store for arbitrary queries.

**Comment by eddyashton** [comment]
To validate signatures over historical queries, we need broader historical state. Specifically, we want to know the active nodes at the point the signature was produced. We discussed alternatives such as having each signature include a service-endorsed copy of the signer's public key, but this would still require additional historical state to know the expected service identity at each signature.

So we need to be able to replay a full KV state (as in every transaction, though we may only _keep_ specific tables), and to make this manageable we need to do it via snapshots. When asked for a historical query at N, we don't just need N and the signature over N, we also need the full range of transactions from the snapshot before N to the signature over the evidence of this snapshot. We need to check both signatures are globally committed (vs the node's knowledge of consensus commit), and check that both signatures are valid (they are produced by a known, active node, as decided in the reconstructed store), to trust the contents of the transaction at N.

**Comment by eddyashton** [comment]
After further discussion, we think that even snapshots don't get us out of this regression loop - we also need historical service identities (and the signatures over those, validated recursively) to fully verify a historical entry internally. Its possible we can store all service identities in the active KV as a workaround, or chain them in the same way we do with the ledger secrets, but this needs further thought.

However, there's a neater solution for all of this - we can now return receipts for historical transactions, and the caller can then verify the signatures in those receipts (rooted in a historical node or service they trust). This may not give them the same validation we could do online, but we believe is sufficient for current requirements,

**Comment by achamayou** [comment]
- [ ] Explore the perf impact of including the (endorsed) node cert in each signature, and (transitively) checking the signature against the current service identity. Once we have support for full-state/snapshot, we can keep that and remove the cert inclusion in the signature, and tighten it further by checking the node state at the time.

**Comment by eddyashton** [comment]
Trying to summarise the outstanding issue here. The problem is given a signature over some ledger entries, how do we trust the signature? Each signature contains the ID of the node that produced it, and we need to get the cert associated with that, then check that cert is endorsed by the service identity or a precursor service identity.

In the good path this is easy - its produced by a node in the current service, so we can take the node ID that's in the signature, look that up in our current KV to get the cert, and its implicitly endorsed by the current service.

For now this works even for retired nodes, because they are not truly deleted in the KV, but this will soon break. When they are deleted from the KV, we may need to look their cert up with another historical query or from a snapshot state. But this introduces a recursive issue - how do we trust the signatures over _them_.

This is even worse if we've been through disaster recovery - once we have a node cert, it may not be the _current_ service identity which endorsed it but a previous identity. So we may need some chaining of service identities like we have with ledger secrets, to efficiently find the full history.

As the comment above says, an intermediate solution may be to store the endorsed cert in every signature. We need to evaluate the cost of this, and it doesn't help us across disaster recoveries where (without historical ledger identities) we can't validate the endorsement of this cert.

A totally different approach is to return receipts with every historical entry (the API already supports this), and leave validation up to the caller. This would need to be clearly communicated, and places some trust burden on the caller, but would make the CCF operation far more efficient if its acceptable (and leaves the determination of how defensive to be up to the caller, in particular over things like checking the node state at the time of signature).

**Comment by eddyashton** [comment]
Removing the 1.0 label as we're not yet deleting retired nodes, so the existing scheme of looking up the signer's cert from the current KV (potentially retired) will continue to work.

**Comment by eddyashton** [comment]
Closing this, tracking remaining work in #3197.
