### ISSUE TITLE
Member recovery share encryption should support RSA encryption

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1720]
Recovery shares are currently encrypted in the `ccf.shares` table using members' encryption keys. These keys are asymmetric keys generated on the `25519` ECDH curve and the encryption algorithm is https://nacl.cr.yp.to/box.html, provided by Evercrypt.

If member keys (both for signature/identity and encryption) are stored in HSMs (e.g. [Azure Managed HSM](https://docs.microsoft.com/en-gb/azure/key-vault/managed-hsm/)), the keys and algorithms we use should be compatible with the capabilities of HSMs. 

In particular, managed HSMs only seem to support [asymmetric encryption using RSA](https://docs.microsoft.com/en-gb/azure/key-vault/keys/about-keys#wrapkeyunwrapkey-encryptdecrypt) so we should aim to support these too.

**Comment by jumaffre** [comment]
`mbedtls` seems to be our best choice to implement this: https://tls.mbed.org/api/rsa_8h.html#ad2dda710a8a517d02220632bcf0eda13 as Evercrypt doesn't seem to have support for this.

**Comment by achamayou** [comment]
This means we can also effectively remove the network encryption key.

**Comment by jumaffre** [comment]
For the records, the steps required to wrap/unwrap using `RSA-OAEP-256` with AKV are:

```bash
# Export VAULT_NAME and KEY_NAME first. Also assumes that a vault has already been created.
$ az login

$ az keyvault list # List vaults

$ az keyvault key list --vault-name $VAULT_NAME # List keys

$ az keyvault key create --vault-name $VAULT_NAME --name $KEY_NAME --kty "RSA" --ops wrapKey unwrapKey encrypt decrypt # Create RSA key for wrapping/unwrapping

$ export WRAPPED_VALUE=$(az keyvault key encrypt --vault-name $VAULT_NAME --name $KEY_NAME --algorithm RSA-OAEP-256 --value "sometext" | jq .result) # Wrap some value

$ az keyvault key decrypt --vault-name $VAULT_NAME --name $KEY_NAME --algorithm RSA-OAEP-256 --value $WRAPPED_VALUE
```

**Comment by achamayou** [comment]
@jumaffre I think that probably ought to be in the doc, under governance.

**Comment by jumaffre** [comment]
@achamayou Good point. I've raised https://github.com/microsoft/CCF/issues/1845 to complete this work independently as it also touches on unauthenticated governance.
