### ISSUE TITLE
Add offline receipt verification process to public documentation

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1746]
The new ["Audit" section ](https://microsoft.github.io/CCF/master/audit/index.html) of the public documentation still lacks details on how to verify receipts offline. We should add a section in the documentation for this once we properly support and test this.

**Comment by achamayou** [comment]
Dupe with #644

**Comment by jumaffre** [comment]
> Dupe with #644

@achamayou Good catch! Let's close this new issue and use #644 to track this work.
