### ISSUE TITLE
Nodes should shut down when voted out

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#177]
When a configuration change means that no active configuration contains the current node, we currently log that the node has been removed but don't actually shut it down (there's a related `TODO` at the bottom of `raft.h`).

There's no critical need for the node to exit at this point, but it would be nicer for usability if it did.

**Comment by achamayou** [comment]
We already have a handler for AdminMessage::stop, and we probably want to log this, so we could give raft an additional object, similar to the ledger and channel proxies (admin proxy?), which would send a termination event to the host. The host would log that, and send AdminMessage::stop like it does now on SIGTERM.

**Comment by achamayou** [comment]
As pointed out earlier, this is awkward during recovery, where nodes can be removed and added again by the replay process.

**Comment by achamayou** [comment]
There's no obvious way to do this at the moment or in the foreseeable future.
