### ISSUE TITLE
JS: Expose user details in Request object

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1775]
Currently JS apps have no access to any user details like the client certificate.

I suggest to extend the `Request` object with a new optional `user` field that is of `any` type. If CCF authentication is enabled (`require_client_identity`/`require_client_signature`) then it would be an object like `{certificate: ...}`.

The reason I don't want to strongly type the `user` field is that this can come in handy with JS-side authentication "middleware", when CCF-side authentication is disabled (I don't see a case when both would be enabled). For example, in tsoa [authentication middleware](https://tsoa-community.github.io/docs/authentication.html) can be provided which returns an arbitrary value. This value is typically set as `user` property in the [request object](https://github.com/lukeautry/tsoa/blob/2e1859f011ddd4e7c2290ea0b84a16f22a79ab44/packages/cli/src/routeGeneration/templates/koa.hbs#L106). In the case of JWT, it could be the decoded token.

**Comment by achamayou** [comment]
Connected with #2032
