### ISSUE TITLE
Minimal genesis startup & recovery

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#178]
Instead of the multi-stage startup sequence described in https://microsoft.github.io/CCF/start_network.html, involving a relatively large genesis, CCF should use a sequence closer to that described in the TR.

A first node should be given a genesis consisting of the following tables:

- members
- nodes
- governance
- whitelist

We no longer need or want:

- users
- app scripts
- nodes other than the starting node

The nodes table starts out empty, and is populated by the starting node with its own entry, including its quote.

```
./cchost --init --member member_cert0.pem --member member_cert1.pem
```

Additional nodes join incrementally:

```
./cchost --join remote_addr:remote_port
```

Starting a node in recovery mode remains:

```
./cchost --recover
```

The startnetwork, join and set_recovery_nodes rpcs in the management frontend are no longer needed in this sequence. get_signed_index and get_quotes can be made available on all frontends, and the management frontend can disappear.

This is connected to https://github.com/microsoft/CCF/issues/47, and effectively resolves some of the items it contains. Other steps such as changes to the nature of the quotes, or whether add nodes is initially free or not will be covered in other tickets.

**Comment by jumaffre** [comment]
As discussed with @achamayou @eddyashton and @olgavrou today, the new way to start nodes should be as follows (omitting additional parameters such as raft timeouts, signatures and ring buffer parameters):

- Starting the first node of a new network:
`./cchost --enclave-file=path --enclave-type={debug,simulate, virtual} --rpc-address=host:port --node-address=host:port --public-address=host:port --ledger-file=path start --network-cert=path.pem --member=member0.pem --member=member1.pem --member=member2.pem --gov=gov.lua `

The command outputs the new network certificate at the location specified by `--network-cert`.

- Starting a node to join an existing network:
`./cchost --enclave-file=path --enclave-type={debug,simulate, virtual} --rpc-address=host:port --node-address=host:port --public-address=host:port --ledger-file=path join --network-cert=path.pem --target-node-address=host:port`

The command takes the certificate of the network to join (via `--network-cert`) and the host:port of the node to contact to join the network (not necessarily the leader thanks to command forwarding). The log file of the joining node will display when the node has successfully joined the network.

- Starting a node in recovery node:
 `./cchost --enclave-file=path --enclave-type={debug,simulate, virtual} --rpc-address=host:port --node-address=host:port --public-address=host:port --ledger-file=path recover --network-cert=path.pem`

The implications of the startup scheme on the recovery are still to be finalised and we will see how much of the recovery can be unified with the classic startup protocol. In particular, it is not clear whether we still need a different join RPC for nodes that have already started in recovery (but not elected as the starting recovery node) or if we can just start other nodes like in the classic startup scheme.
