### ISSUE TITLE
JS: Return undefined for non-existing keys in <kvmap>.get

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1780]
Currently `<kvmap>.get(key)` throws an exception if the key doesn't exist. This is different to how all storage-related JS APIs behave, e.g. `Map` and `Storage`. It also makes things like `<kvmap>.get(key) || default_val` impossible. We should consider returning `undefined` instead.

**Comment by eddyashton** [comment]
I definitely think `undefined` is preferable here. As well as consistency with similar JS APIs, its equivalent to the C++ API (which returns a `std::optional`). Does anyone have an argument in favour of the current approach?

**Comment by achamayou** [comment]
+1 for compliance with ES standards, although as of ES2020 you probably want `<kvmap>.get(key) ?? default_val` rather than `||`.

**Comment by letmaik** [comment]
There is a similar inconsistency with `delete()` which always returns `undefined` and throws an exception if the key doesn't exist, whereas [`Map.delete()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/delete) returns "true if an element in the Map object existed and has been removed, or false if the element does not exist."
I suggest to change this method as well.
