### ISSUE TITLE
JS: Expose <kvmap>.keys()/values()/entries()

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1782]
[`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) returns `Iterator`s for those functions which probably makes sense for CCF as well, even though it'll be a bit tricky to implement.

**Comment by eddyashton** [comment]
I think we should aim for `forEach` initially, since we already have `foreach` in the C++ API. Building iterators is a chunk more work, and I think it exposes the inconsistencies in our API in a more dangerous way, where users will eventually expect something to work just like it does for `Map`.
