### ISSUE TITLE
Document "Verifying Quote" has incorrect jq parsing of the quote

### ISSUE THREAD

**Issue by syhamza** [microsoft/CCF#1792]
The document tries to parse quote response using `jq .raw` when instead it should be dong `jq '.quotes[0] .raw'`

**To Reproduce**
Just run curl command to get the quote from CCF node and it should fail.

**Expected behavior**
Running the curl command should create "ccf_node_quote.bin" but instead, it fails.

**Environment information**
Repro on all the environments.

**Additional context**

**Comment by eddyashton** [comment]
The response format of `/node/quote` changed recently, in #1761, but I believe the docs on both master and 0.14.1 are correct for their versions.

The instructions on [this page](https://microsoft.github.io/CCF/master/users/verify_quote.html) correctly parse the `/node/quote` response for me, on master:

```
$ curl https://127.0.0.1:8000/node/quote --cacert networkcert.pem | jq .raw | xxd -r -p > quote.bin
...

$ /opt/openenclave/bin/oeverify -r quote.bin -f LEGACY_REPORT_REMOTE
...
Evidence verification succeeded (0).
```

Before then (including in the 0.14.1 release) this endpoint returned a list, but the [versioned docs](https://microsoft.github.io/CCF/ccf-0.14.1/users/verify_quote.html) have the correct `jq .quotes[0].raw` parsing.

**Comment by syhamza** [comment]
Ah totally forgot about checking this in other versions. Thanks Eddy!!
