### ISSUE TITLE
Update code to use evercrypt public interface

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#180]
We should update CCF (e.g. `hash.cpp`) to use evercrypt's public interface.

**Comment by achamayou** [comment]
In particular we should stop making Hacl_* calls and deprecated EverCrypt_* calls.

**Comment by jumaffre** [comment]
This is now done and the https://github.com/microsoft/CCF/blob/master/3rdparty/update_evercrypt.sh script should be used from now onward to update evercrypt.
