### ISSUE TITLE
Remove old tsoa sample app

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1800]
`samples/apps/forum` replaces `tests/npm-tsoa-app`. Before doing this, we should review whether the new sample demonstrates all important things in a straight-forward way.

**Comment by letmaik** [comment]
The only aspect that the old sample shows which the forum sample doesn't show is non-JSON requests/responses. I think it's useful to keep this as it involves getting access to the original CCF request object and overriding the tsoa-generated OpenAPI definition for that endpoint. I wonder if there is a meaningful scenario to integrate this into the forum sample.

**Comment by achamayou** [comment]
Should we add an endpoint that returns all results for a user in a single aggregated CSV for example? That would show how to use something else than JSON.

**Comment by letmaik** [comment]
Yeah, that shows non-JSON responses, and then we need something similar for the request side.

**Comment by achamayou** [comment]
Submit a CSV? :)
