### ISSUE TITLE
Investigate JS app debugging

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1801]
End to end tests are great, but being able to debug JS code based on those tests would be even greater.

There is https://github.com/koush/vscode-quickjs-debug which relies on a fork of QuickJS.

**Comment by letmaik** [comment]
It may make more sense to instead push for https://github.com/microsoft/CCF/issues/1802 which would provide a much simpler (both for us and users) debugging experience. The general idea would be to advocate for separating code into two parts, the endpoint code (which should be as minimal as possible) and the service code (with the business logic). Debugging the service code should be sufficient then, leaving the rest to sandbox end-to-end tests without a debugging option.

**Comment by achamayou** [comment]
We have indeed gone for #1802, we will not investigate this further in the foreseeable future.
