### ISSUE TITLE
Provide guidance on unit testing JS apps

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1802]
This is distinct from end to end testing of the REST endpoints. The idea is to test JavaScript components directly.

**Comment by achamayou** [comment]
Is this equivalent to providing mocks/stubs for the arguments and globals we pass to JS handlers?

**Comment by letmaik** [comment]
Well, that's the question. Since devs would very likely want to use test frameworks like mocha (which depend on node.js) it seems pretty unrealistic to run unit tests in CCF directly somehow. Mocks/re-implementations would probably be the more straight-forward option and would also allow easier integration with JS debuggers and coverage measurement tools.

I don't think the actual endpoint handlers have to be unit tested (as that would be an integration test and should probably be done with the sandbox). The meat of the business logic should be in a separate application layer and be independently testable. tsoa advocates for the same split and calls this "controllers" (which are the endpoint handlers) vs "models", where the latter defines services that do certain things. And those only have a dependency on the ccf globals, not the request object. Providing node.js implementations of the ccf globals is not hard. Providing an emulation of the whole ccf http request layer is much harder.

**Comment by achamayou** [comment]
#2331 is complete now.
