### ISSUE TITLE
"Starting a Test Network" doc page without parent

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1818]
https://microsoft.github.io/CCF/master/quickstart/test_network.html

There is no navigation on the left.

There are links to it from https://microsoft.github.io/CCF/master/developers/run_app.html and https://microsoft.github.io/CCF/master/members/accept_recovery.html.

I think the instructions should also be changed to not refer to a build tree but rather an installation tree.

**Comment by achamayou** [comment]
Agreed, I intend to replace this page with one called "Sandbox" which will go under "Build Apps".

**Comment by achamayou** [comment]
So that's now under Build Apps, as https://microsoft.github.io/CCF/master/developers/run_app.html, and refers to an installation tree. There's more to be done, as tracked under #1700, but this particular issue is complete as far as I can tell.
