### ISSUE TITLE
Log in-enclave OE messages

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#1831]
Open Enclave now offers a mechanism to register a custom in-enclave logger, so logs can be captured and displayed without adding syscalls we've got turned off: https://github.com/openenclave/openenclave/blob/v0.12.0/samples/log_callback/README.md

We ought to implement a handler that sends messages over the ringbuffer like our logger does now.

**Comment by letmaik** [comment]
I'm afraid the log callback mechanism does not serve our purposes as it can only be used to influence what happens once the message reaches the host. This is why the callback must be registered on the host.

**Comment by achamayou** [comment]
Indeed, I'd failed to notice that. It's quite disappointing.
