### ISSUE TITLE
Separate client and web app registrations in forum sample

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1869]
When using Microsoft Identity Platform, apparently all clients accessing a web api, for example a static JS website, need to be registered separately. Currently, the forum sample uses a single app registration, which seems to work but is not how it's meant to be used. This becomes more important/necessary when the server part is accessing Microsoft APIs itself.

https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-access-web-apis#prerequisites

**Comment by achamayou** [comment]
I'm a little confused by this, are we planning to access Microsoft APIs from the server side of the forum app? If so, for what purpose?

**Comment by letmaik** [comment]
No, but you're still supposed to have two logical apps, one for the server, one for the client.

**Comment by letmaik** [comment]
I'll leave it as a single app and have added a note in https://github.com/microsoft/CCF/pull/1875. Technically, it should still be two apps, but practically it doesn't make a difference in this scenario.
