### ISSUE TITLE
Update HTTP signature

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1886]
As we now support the `hs2019` signature scheme (see https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-00) where the signature hashing algorithm is derived from the key specified by `keyId`, we should remove the `ecdsa-sha256` scheme, which is deprecated according to the RFC draft.

This involves removing or patching the Python http signature package which only supports the `ecdsa-sha256` scheme.

**Comment by eddyashton** [comment]
I think there are several more changes between the current `draft-ietf-httpbis` and whatever version of the `draft-cavage` document we initially implemented. An initial (incomplete) list of changes we should make for current compatibility:

- [ ] Use `Signature:` and `Signature-Input:` headers rather than `Authorization:`
- [ ] Normalize all headers as described in the spec

**Comment by achamayou** [comment]
The RFC has been substantially updated with a new format:

```
   Signature-Input: sig1=("@request-target" "host" "date"
       "cache-control" "x-empty-header" "x-example"); keyid="test-key-a";
       alg="rsa-pss-sha512"; created=1402170695; expires=1402170995
   Signature: sig1=:K2qGT5srn2OGbOIDzQ6kYT+ruaycnDAAUpKv+ePFfD0RAxn/1BUe\
       Zx/Kdrq32DrfakQ6bPsvB9aqZqognNT6be4olHROIkeV879RrsrObury8L9SCEibe\
       oHyqU/yCjphSmEdd7WD+zrchK57quskKwRefy2iEC5S2uAH0EPyOZKWlvbKmKu5q4\
       CaB8X/I5/+HLZLGvDiezqi6/7p2Gngf5hwZ0lSdy39vyNMaaAT0tKo6nuVw0S1MVg\
       1Q7MpWYZs0soHjttq0uLIA3DIbQfLiIvK6/l0BdWTU7+2uQj7lBkQAsFZHoA96ZZg\
       FquQrXRlmYOh+Hx5D9fJkXcXe5tmAg==:
```

https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-03

**Comment by achamayou** [comment]
Since clients, including the very popular https://github.com/joyent/node-http-signature seem not to track the drafts because they change too quickly, we will do the same and upgrade only once the final RFC is published.
