### ISSUE TITLE
/receipt should return structured output

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#1891]
The current `GET /receipt` endpoint returns a single binary blob, which is generated by `mt_get_path()`. Instead, the return value should be a JSON document containing the following:

1. signature over the root, as a base64-encoded string
2. list of digests, as hex-encoded strings
3. list of leaf component digests, as hex-encoded strings

Ideally, the endpoint would accept either a `{"view": ..., "seqno": ...}` `application/json`, or a query string like `/receipt?view=...&seqno=...`.

**Comment by letmaik** [comment]
The response should also contain the view and seqno.

**Comment by eddyashton** [comment]
Done in #2270.
