### ISSUE TITLE
Support declaration of multiple auth policies for each endpoint

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1904]
Following on from https://github.com/microsoft/CCF/pull/1898#discussion_r526373762 and related discussion.

### Problem outline

We will soon support at least 3 broad auth policies: TLS cert, HTTP signature, JWT bearer token. We'd like a single endpoint to accept several of these, and the default is likely to be supporting _any_ of these. We need a way to declare what auth policies an endpoint requires, and to retrieve the authenticated identity information afterwards, inside the endpoint.

As a related point, we currently duplicate authentication policies for members and users, and choose which applies at a frontend-wide level - this seems like a good opportunity to make this an explicit and per-endpoint property, as a step towards eventually abolishing the frontend.

We want these policies to be extensible in C++. App writers should be able to write their own custom AuthN policy, though they may not be able to cache the parsed identity info they produced on the way.

When multiple policies are acceptable for an endpoint, we should try them in order and halt after the first successful auth. We need a way for the endpoint to learn which policy was applied (and thus which identity is being used, and which user metadata should be used for additional authorization decisions).

A complication with the current code is that for cert-based auth we try to do the check early on backups, before forwarding. As an optimisation, we don't forward the caller's cert in this case. We either need to do this consistently, forwarding all of the constructed metadata, or re-parse it on the forwardee, or abandon backup-auth.

### Code sketches

This proposes that each policy is just a functor, setting all return state on some `AuthCtx` and maybe HTTP response errors on the original request context. I think this is simpler than making it a richer self-contained object and re-extracting those fields. I think this could be a `ReadOnlyTx` - separately we want a `Endpoint::set_record_all_requests(true)` decorator that would be used for signed governance transactions, but could be used for others regardless of the auth scheme to dump the raw request to the ledger.

These include some open questions. In particular I've not decided the best way to set error messages. Maybe the auth functor sets response code + www-auth header directly, potentially overwritten by later functors, and on success overwritten by the 'real' result?

```c++
// Populates auth if request is acceptable, based on current state read from tx
// Should perhaps be ReadOnlyTx?
using AuthPolicy = std::function<void(
  Tx& tx, const std::shared_ptr<enclave::RpcContext>& request, AuthCtx& auth)>;
```

Then here's what an auth policy looks like, associated with some string identifier
```c++
static constexpr auto user_cert_policy_name = "user-cert";
void require_user_cert(
  Tx& tx, const std::shared_ptr<enclave::RpcContext>& request, AuthCtx& auth)
{
  const auto caller_cert = request->session->caller_cert;
  auto users_view = tx.get_view(user_certs);
  const auto user = users_view->get(caller_cert);
  if (user.has_value())
  {
    auth.set_authorizing_policy_name(user_cert_policy_name);
    auth.set_caller_id(user.value());
    auth.set_caller_cert(caller_cert);
    // Set caller's user_data?
  }
  // Not recognised. Return or set a proposed error message/www-authenticate
  // header?
}

// Similarly require_member_cert, and require_node_cert?

static constexpr auto jwt_policy_name = "user-jwt";
void require_jwt(
  Tx& tx, const std::shared_ptr<enclave::RpcContext>& request, AuthCtx& auth)
{
  const auto jwt = json::parse(
    base64decode(separate_bearer(request.get_header("Authorization"))));
  // Check audience matches known value from kv
  // Check issuer matches known value from kv
  // Check signatures vs certs from kv
  if (good)
  {
    auth.set_authorizing_policy_name(jwt_policy_name);
    auth.set_jwt(jwt);
    // Set issuer's cert?
  }
}
```

The frontend iterates through the policies, detects that one has accepted the request and early-outs
```c++
for (const auto& auth_policy : endpoint.auth_policies)
{
  // Try to apply policy
  auth_policy(tx, request, auth);
  if (auth.get_authorizing_policy_name())
  {
    // Good, one of the policies passed!
    break;
  }
}
```

An endpoint lists multiple policies, trusts that one of these passed before it will be executed, can differentiate which policy passed.
```c++
auto my_endpoint = [this](ccf::EndpointContext& ctx) {
  const auto& auth = ctx.get_auth_context();
  if (auth.get_authorizing_policy_name() == user_cert_policy_name)
  {
    const auto caller = auth.get_caller_id();
    // Make authorization decisions based on caller ID and/or user_data
  }
  else if (auth.get_authorizing_policy_name() == jwt_policy_name)
  {
    const auto caller_jwt = auth.get_jwt();
    // Make authorization decisions based on claims in JWT
  }
};
make_endpoint("foo", HTTP_POST, my_endpoint)
  .add_auth_policy(require_user_cert)
  .add_auth_policy(require_jwt)
  .install();
```

**Comment by letmaik** [comment]
If we go for functor style, can we make it classes instead? I don't like the auth function explicitly setting the policy name, this should be done by CCF, depending on whether the function returns true or false. The name should be declared by the class through some function like `get_name()`.

**Comment by eddyashton** [comment]
Here's `AuthPolicy` as a class rather than a raw functor. 3 improvements I think from here:

1) `AuthPolicy` should also have a `set_unauthenticated_error` method, and when we have no successful auth and a non-empty list of policies, we let this policy set the error code + `www-authenticate` message on the request, and return this error.
2) `UserCertAuthPolicy` could be implemented in terms of some generic base `CertAuthPolicy`, so we just swap out the names and types of the members/nodes certs + IDs tables. The names may be different enough that we need adapters, at which point we may as well just implement them separately.
3) I'm still not happy with the `AuthCtx` as a bucket of partially filled-in fields, as the connection between "what string was set" and "what identity fields are available" is too vague. I think instead we should indicate success with `return std::make_unique<UserCertIdentity>(user_cert, user_id, user_data);`, and the endpoints can do a chain of dynamic cast chains on the `AuthIdentity*`, eventually getting a `UserCertIdentity*` with everything they need (and nothing else). This kind of abandons the lazy approach but I think that's sound - if we're treating this as an authorized identity, only one should be used.

```
class AuthPolicy {
public:
  virtual ~AuthPolicy(){};

  virtual bool authenticate(ReadOnlyTx &tx,
                            const std::shared_ptr<enclave::RpcContext> &request,
                            AuthCtx &auth) = 0;

  virtual std::string get_policy_name() const = 0;
};

class UserCertAuthPolicy : public AuthPolicy {
public:
  bool authenticate(ReadOnlyTx &tx,
                    const std::shared_ptr<enclave::RpcContext> &request,
                    AuthCtx &auth) override {
    const auto caller_cert = request->session->caller_cert;
    auto users_view = tx.get_view(user_certs);
    const auto user = users_view->get(caller_cert);
    if (user.has_value()) {
      auth.set_caller_id(user.value());
      auth.set_caller_cert(caller_cert);
      // Set caller's user_data?
      return true;
    }

    return false;
  }

  std::string get_policy_name() const override { return "user-cert"; }
};

// Similarly MemberCertAuthPolicy, and NodeCertAuthPolicy?

class JwtAuthPolicy : public AuthPolicy {
public:
  bool authenticate(ReadOnlyTx &tx,
                    const std::shared_ptr<enclave::RpcContext> &request,
                    AuthCtx &auth) override {
    const auto jwt = JwtVerifier::extract_token(...);
    if (jwt.has_value()) {
      auth.set_jwt(jwt.value());
      // Set issuer's cert?
    }

    return false;
  }

  std::string get_policy_name() const override { return "user-jwt"; }
};

for (const AuthPolicy& auth_policy : endpoint.auth_policies)
{
  if (auth_policy.authenticate(tx, request, auth))
  {
    auth.set_authorizing_policy_name(auth_policy.get_policy_name());
    break;
  }
}

auto my_endpoint = [this](ccf::EndpointContext &ctx) {
  const auto &auth = ctx.get_auth_context();
  if (auth.get_authorizing_policy_name() ==
      UserCertAuthPolicy::get_policy_name()) {
    const auto caller = auth.get_caller_id();
    // Make authorization decisions based on caller ID and/or user_data
  } else if (auth.get_authorizing_policy_name() ==
             JwtAuthPolicy::get_policy_name()) {
    const auto caller_jwt = auth.get_jwt();
    // Make authorization decisions based on claims in JWT
  }
};

make_endpoint("foo", HTTP_POST, my_endpoint)
    .add_auth_policy(UserCertAuthPolicy())
    .add_auth_policy(JwtAuthPolicy())
    .install();
```

**Comment by letmaik** [comment]
To clarify, if you have multiple auth policies in use for an endpoint and all fail, then which one is called for set_unauthenticated_error? The first/last? I don't think it matters much to be honest, as long as it's documented.

**Comment by eddyashton** [comment]
Incorporating 1 and 3 above:

```
/// Generic types
struct AuthIdentity {
  virtual ~AuthIdentity(){};
};

class AuthPolicy {
public:
  virtual ~AuthPolicy(){};

  virtual std::unique_ptr<AuthIdentity>
  authenticate(ReadOnlyTx &tx,
               const std::shared_ptr<enclave::RpcContext> &request) = 0;

  virtual void
  set_unauthenticated_error(std::shared_ptr<enclave::RpcContext> &request) = 0;
};


/// Policy examples
struct UserCertAuthIdentity : public AuthIdentity {
  Pem user_cert;
  UserId user_id;
  nlohmann::json user_data;
};

class UserCertAuthPolicy : public AuthPolicy {
public:
  std::unique_ptr<AuthIdentity>
  authenticate(ReadOnlyTx &tx,
               const std::shared_ptr<enclave::RpcContext> &request) override {
    const auto caller_cert = request->session->caller_cert;
    auto users_view = tx.get_view(user_certs);
    const auto user = users_view->get(caller_cert);
    if (user.has_value()) {
      return std::make_unique<UserCertAuthIdentity>(
          caller_cert, user.value(),
          tx.get_view(users)->get(user.value())->user_data);
    }

    return nullptr;
  }
};
// Similarly MemberCertAuthPolicy, and NodeCertAuthPolicy?

struct JwtAuthIdentity : public AuthIdentity {
  JwtVerifier::Token jwt;
  // Issuer's cert? kid? Other parsed metadata?
};

class JwtAuthPolicy : public AuthPolicy {
public:
  std::unique_ptr<AuthIdentity>
  authenticate(ReadOnlyTx &tx,
               const std::shared_ptr<enclave::RpcContext> &request) override {
    const auto jwt = JwtVerifier::extract_token(...);
    if (jwt.has_value()) {
      return std::make_unique<JwtAuthIdentity>(jwt.value());
    }

    return nullptr;
  }

  virtual void set_unauthenticated_error(
      std::shared_ptr<enclave::RpcContext> &request) override {
    request->set_response_status_code(HTTP_UNAUTHORIZED);
    request->set_response_header(www_authenticate, "Bearer", etc);
  }
};


/// Authentication code in frontend
if (!endpoint.auth_policies.empty()) {
  std::unique_ptr<AuthIdentity> authed_identity = nullptr;
  for (const AuthPolicy &auth_policy : endpoint.auth_policies) {
    authed_identity = auth_policy.authenticate(tx, request);
    if (authed_identity != nullptr) {
      break;
    }
  }

  if (authed_identity != nullptr) {
    request->set_authed_identity(std::move(authed_identity));
  } else {
    endpoint.auth_policies[0].set_unauthenticated_error(request);
    return;
  }
}


/// Something like this in the request or context
template <typename Identity>
Identity* get_authed_identity()
{
  return std::dynamic_cast<Identity*>(authed_identity.get());
}


/// Used in an endpoint
auto my_endpoint = [this](ccf::EndpointContext &ctx) {
  if (auto caller_identity = ctx.request->get_authed_identity<UserCertAuthIdentity>()) {
    // Make authorization decisions based on caller ID and/or user_data
  } else if (auto jwt_identity = ctx.request->get_authed_identity<JwtAuthIdentity>()) {
    // Make authorization decisions based on claims in JWT
  }
};

make_endpoint("foo", HTTP_POST, my_endpoint)
    .add_auth_policy(UserCertAuthPolicy())
    .add_auth_policy(JwtAuthPolicy())
    .install();
```

**Comment by eddyashton** [comment]
@letmaik: I think the first. The order they're specified already specifies the priority in which they'll be accepted, so I think extending this to the error reporting makes sense. I could also be convinced that when we accept multiple policies, if we can't set a standards-compliant set of headers describing them _all_, we shouldn't try describe _any_.

Or perhaps we can get really clever and say "signing auth was listed first so its probably a signing auth error, unless we noticed a `Bearer` token which didn't _quite_ parse, in which case we'll show you a `Bearer` auth error".
