### ISSUE TITLE
HTTP client hangs if Content-Length header is missing in response

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1909]
I noticed this while creating a self-hosted OpenID server for tests in https://github.com/microsoft/CCF/pull/1908.

It can be reproduced with https://github.com/microsoft/CCF/pull/1882 where I added the stand-alone CLI tool `tests/server_test.py`. Simply comment out the `Content-Length` line and then run:

Terminal 1:
```sh
cd build
python ../tests/tests/server_test.py
```

Terminal 2:
```sh
cd build
./cchost.virtual --enclave-file ./liblogging.virtual.so --enclave-type virtual --consensus cft --node-address 127.0.0.1:8001 --rpc-address 127.0.0.1:8002 http-test localhost:8860 --http-path /keys --ca-cert-file server_test_cert.pem
```

curl has no issues with it.

**Comment by eddyashton** [comment]
From the [http-parser](https://github.com/nodejs/http-parser) docs:

> http_parser needs to know where the end of the stream is. For example, sometimes servers send responses without Content-Length and expect the client to consume input (for the body) until EOF. To tell http_parser about EOF, give 0 as the fourth parameter to http_parser_execute(). Callbacks and errors can still be encountered during an EOF, so one must still be prepared to receive them.

But I don't think we can do this. We often have only a subrange of the total HTTP request - we can't guarantee we're always executing an EOF-terminated block. So I'm not sure how we tell the parser to execute all given bytes _or_ to the end of the current Content-Length _or_ to an EOF.

**Comment by achamayou** [comment]
Repro with llhttp (current master): https://github.com/achamayou/CCF/tree/content_length_issue

**Comment by achamayou** [comment]
We aren't exposing the HTTP client, nor are we planning to at this stage. BL containers will be able to use their own client if they want to.
