### ISSUE TITLE
JWT key auto-refresh: include connection failures in metrics

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1916]
Follow-up from https://github.com/microsoft/CCF/pull/1908.

[Expose connection failures](https://github.com/microsoft/CCF/issues/1486#issuecomment-731081498) to enclave to be able to record key refresh errors in those situations. This includes TLS errors like SAN mismatch.

**Comment by achamayou** [comment]
It seems like it would be more useful to log this instead.
