### ISSUE TITLE
Follow Microsoft (Azure) REST API Guidelines

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1918]
[Microsoft REST API Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md)

[Microsoft Azure REST API Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) -- extension of former

The goal is to allow CCF to be used to build Microsoft Azure REST API compliant services.

To get to that target state, a few things should happen (all of these likely happen in parallel and iteratively):
- Identify topics in the guidelines that are relevant to CCF
- Create and maintain a condensed CCF REST API Guidelines document
- Work through each CCF API and fix non-conformance, or add an exception with justification to the CCF REST API Guidelines document

The CCF guidelines document has a few purposes:
- Reference for users / collaborators / reviewers on why the API is the way it is
- Reference for CCF developers to validate APIs are conforming
- Developers of CCF won't have time to read through the whole Microsoft guidelines each time
- Only a subset of the Microsoft guidelines are relevant for CCF
- Some guidelines provide multiple options or recommendations; the CCF document has to decide on one
- CCF may require deviations from the Microsoft guidelines, in which case they have to be documented and justified
- Any topic that is ignored from the original guidelines has to be included with a short justification on why it is not relevant for CCF

Azure OpenAPI definitions: https://github.com/Azure/azure-rest-api-specs/tree/master/specification

### No-brainer / easy wins
- OData-style error responses #1919
- camelCase #1940
- Respect Accept: header for content negotiation in built-in endpoints #1942
- Don't expose internal /join endpoint in OpenAPI definition #1933
- Expose response schema for GET /config #1958

### Medium effort
- unified data models for POST/GET #1943
- Better example requests/responses in OpenAPI-generated docs #1931

### Challenging
- versioning #1930
- pagination #1938
- long-running operations for historical queries #1948

### No-brainer / easy wins
- Remove POST /proposals/{proposal_id}/complete #1952
- Add GET /proposals/{proposal_id}/votes #1950
- Use JSON objects as top-level request/response types in REST API #1944
- /quote(s) endpoints should not use empty strings for optional fields in REST API #1937
- Don't return 500 on input validation errors for built-in endpoints #1979

### Medium effort
- Re-organize /network, /network_info, /node/ids, /primary, /primary_info #1954
- Make JSON representation of proposal votes self-describing #1949

**Comment by achamayou** [comment]
Pinging @lynshi for input.

**Comment by lynshi** [comment]
> Pinging @lynshi for input.

Looks good to me so far! Let's sync offline next week about further specifics.

**Comment by achamayou** [comment]
As dicussed and agreed with @lynshi, CCF will take the following approach:

1. As a matter of policy, align with Azure guidelines whenever possible (corresponding work items are under the "REST API" label). Exceptions must be motivated (eg. why the LRO pattern isn't recommended for historical queries) and documented.
2. Expose the "built-in" endpoints under "/app" as a public C++ API, and allow their REST handler to be disabled. This is to allow services to completely control the versioning of the application endpoints they expose.

**Comment by achamayou** [comment]
We've addressed most of this, save for a few remaining issues that will stay open separately.
