### ISSUE TITLE
Add summary and description to OpenAPI definition for C++ endpoints

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1920]
The auto-generated OpenAPI doc lacks endpoint summaries and descriptions for C++ endpoints, and hence the docs lack them too. I think adding them would go a long way to help in understanding CCF's API.

Related to https://github.com/microsoft/CCF/issues/1918. The [Azure guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#api-definition) only say there must be an OpenAPI definition, but doesn't say how detailed it should be.

For inspiration, https://github.com/Azure/azure-rest-api-specs contains OpenAPI 2.0 (Swagger) definitions for all (most?) Azure services, for example [Service Fabric's data plane API](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/servicefabric/data-plane/Microsoft.ServiceFabric/stable/7.2/servicefabric.json).

**Comment by achamayou** [comment]
Several built-in endpoints (ie. included on all frontends, such as /api https://github.com/microsoft/CCF/blob/main/doc/schemas/app_openapi.json#L355) are still missing descriptions. We should at least cover those.

**Comment by achamayou** [comment]
All built-ins (ie. the common endpoint registry) have either a description or a summary. Work to standardise and document the API are taking place in CADL now, see #4669.
