### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1930]
Part of https://github.com/microsoft/CCF/issues/1918.

https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#versioning

API versioning here means supporting multiple versions of an API at the same time, using a version identifier given by the client.

CCF has built-in endpoints and app endpoints. Versioning for app endpoints is the responsibility of the app author, no problem there (kind of, see notes below). Versioning of built-in endpoints is likely only relevant if the service built with CCF wants to include those endpoints as part of its public API.

Since versioning of built-in endpoints is a major development effort we should wait until a use case surfaces.

Notes:
- Azure guidelines require versioning to be done with an `?api-version=1.2.3` query parameter. 
- Services built on top of CCF will have their own versioning relative to the versioning of CCF's built-in endpoints. It is not clear whether the built-in endpoints should live under a separate URL path and get their own API essentially (to avoid mixing built-in and app endpoint versioning; however, in that case CCF would be fully responsible to adhere to the versioning of Azure guidelines as if it is a deployed service with all the responsibilities of it), or whether an app should define some kind of mapping from CCF versioning to its own versioning (such that `?api-version=2020-02-02` is translated to version 2.3.4 of CCF's built-in endpoints etc.).
- CCF has an auto-generated *OpenAPI definition* that combines app-provided per-endpoint Operation definitions and built-in endpoint definitions. Serving different OpenAPI definitions based on the `api-version` query parameter would require some work in CCF and also some extensions to how `app.json` works (for app endpoints).
- API versioning of app endpoints with tsoa (TypeScript) using a query parameter is awkward, it is not clear how multiple schemas for a single endpoint can be maintained. Keep in mind that two API versions should result in two fully separate OpenAPI documents.

**Comment by achamayou** [comment]
As described in #1918, CCF will enable services to version application endpoints they expose by making it possible for them to disable/replace built-ins under "/app" and call them via C++ (or JavaScript), but will not itself version its endpoints.

"/gov" and "/node" endpoints are out of scope, and will neither be versioned, nor replaceable.
