### ISSUE TITLE
Don't expose internal /join endpoint in OpenAPI definition

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1933]
Part of https://github.com/microsoft/CCF/issues/1918.

~~Should be a simple matter of adding `.set_auto_schema(JoinNetworkNodeToNode)`.~~ see below, issue title changed.

The OpenAPI definition should describe the public REST API, which implies that special endpoints which cannot be called directly (/join) should not be included.

It probably makes sense to remove the existing hack used for the JWT endpoint and replace it with something like `set_openapi_visible(false)` as new endpoint property.

**Comment by achamayou** [comment]
/join is an internal RPC, one that’s called by a new node joining the network. There is no expectation that anything other than our code would ever make that call.

**Comment by letmaik** [comment]
Then it shouldn't be published in the OpenAPI schema, like the new internal RPC for JWT key refresh.

**Comment by achamayou** [comment]
Agreed.
