### ISSUE TITLE
/quote(s) endpoints should not use empty strings for optional fields in REST API

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1937]
https://github.com/microsoft/CCF/blob/7166b37c5846af4eddb90cb82e16e8feee3c0161/src/node/rpc/node_call_types.h#L46-L53

The fields `error` and `mrenclave` are not always set, e.g. `mrenclave` is not set if BFT is used or there was an error parsing the quote. Because of that, the type of those two should be `std::optional<std::string>`.

**Comment by achamayou** [comment]
Should they? An empty string isn't a valid mrenclave nor quote, so I don't think the current representation is problematic.

**Comment by letmaik** [comment]
Omitting the field or using `null` is more common in APIs.

**Comment by letmaik** [comment]
Looks like this is already happening:
https://github.com/microsoft/CCF/blob/1c82123c62788a9539295e767a8904b47c3ecc01/src/ds/json.h#L430-L433

Since an empty string is the default it would be omitted. Changing  to std::optional would just make it more explicit.
