### ISSUE TITLE
Use pagination for all endpoints returning potentially large collections

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1938]
Part of https://github.com/microsoft/CCF/issues/1918.

https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#981-server-driven-paging

"Return collections with server-side paging, even if your resource does not currently need paging." ([Azure guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#advice-for-new-services))

Scales with number of nodes:
- `/quotes`
- `/network_info` 

Scales with number of code versions:
- `/code`

**Comment by eddyashton** [comment]
Since we don't have ordered iteration over `kv::Map`s, its not easy to do this correctly while those collections might be changing. If you've received 10 nodes in the first page, and a node is added, there may be missing/repeated nodes on the remaining pages. We could get around this by caching the full collection on the node at the point of the first request, and pointing at this with the continuation URL, but this is flaky (node-local, memory use, requires some usage limit so is only a mitigation).

The guidelines don't seem to talk about this, how collection changes affect pagination. Maybe we just include an ETag so any collection changes mid-page-iteration result in an error from the server?

**Comment by letmaik** [comment]
> Stable order prerequisite: Both forms of paging depend on the collection of items having a stable order. The server MUST supplement any specified order criteria with additional sorts (typically by key) to ensure that items are always ordered consistently.
>
> Missing/repeated results: Even if the server enforces a consistent sort order, results MAY be missing or repeated based on creation or deletion of other resources. Clients MUST be prepared to deal with these discrepancies. The server SHOULD always encode the record ID of the last read record, helping the client in the process of managing repeated/missing results.

**Comment by lynshi** [comment]
Just an FYI - if you don't plan on support client-driven paging, the guidelines specify that an error response must be provided.

https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#162-feature-allow-list

**Comment by achamayou** [comment]
@lynshi for the reasons Eddy suggests, paginating reads from the current state will either need to be stateful, or will sometimes end up doing something that is counter intuitive for most users.

Historical reads on the other hand should be straightforward. For the time being, let's return an error on `quotes`, `network_info` and `code` if a user checks for pagination support. The number of entries returned by each of these endpoints is quite unlikely to even reach two digits in any event.

**Comment by letmaik** [comment]
> For the time being, let's return an error on `quotes`, `network_info` and `code` if a user checks for pagination support.

There is no way to check for support. You would simply get a 400 back if you received any unsupported filter/sorting parameter, and I think this is already the case now. The only thing that could be improved is the included error message, but it may not be worth the effort.

**Comment by achamayou** [comment]
>Services MUST provide an error response if a caller requests an unsupported feature found in the feature allow list. The error response MUST be an HTTP status code from the 4xx series, indicating that the request cannot be fulfilled.

Technically we comply, but we could return something a little friendlier like:

```
HTTP/1.1 400 Bad Request
Content-Type: application/json

{
  "error": {
    "code": "ErrorUnsupportedOrderBy",
    "message": "Ordering by name is not supported."
  }
}
```

I don't know that we want to suffer the performance hit of checking for all possible flags on every RPC though, so let's leave it that way.

**Comment by achamayou** [comment]
Until we have built-in endpoints that run historical queries, I don't think we will have anything we implement that meets the definition of "potentially large collections", so I am closing that for now.
