### ISSUE TITLE
Proposals: return representation of created item after POST or redirect

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1943]
Part of https://github.com/microsoft/CCF/issues/1918.

https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#741-post

> POST operations SHOULD support the Location response header to specify the location of any created resource that was not explicitly named, via the Location header.

or...

> Services MAY also return the full metadata for the created item in the response.

In CCF, some built-in endpoints don't follow this (there may be more but these were easy ones to spot):
- `POST /proposals` returns a small metadata object with `proposal_id`, `proposer_id` and `state`, whereas `GET /proposals/{proposal_id}` is missing the `proposal_id`, has a differently named `proposer` field, and includes the script and votes as well.
- `POST /proposals/{proposal_id}/votes` doesn't return the vote object but rather the proposal itself whereas `GET /proposals/{proposal_id}/votes/{member_id}` returns the vote.

There should only be a single data model for an "item" which is returned after a POST and for follow-up GETs.
A side-effect of this is code simplification at the possible expense of sending more data than needed in a given situation, although arguably that's a minor downside.

NOTE: Deferred until governance moves to JS.

**Comment by achamayou** [comment]
We've applied this principles to the JS gov now.
