### ISSUE TITLE
Make JSON representation of proposal votes self-describing

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1949]
Part of https://github.com/microsoft/CCF/issues/1918.

The guidelines are silent on how payloads should look like in detail, but we should avoid weird constructions that are just a result of using the default serialization of the internal types stored in the kv.

Currently, `GET /proposals/{proposal_id}` returns:
```json
    "votes": [
        [
            1,
            {
                "text": "string"
            }
        ]
    ]
```

It should be (modulo different field names):
```json
    "votes": [
        {
            "memberId": 1,
            "ballot": {
                "text": "string"
            }
        }
    ]
```

**Comment by achamayou** [comment]
That's something we can revisit when we move the governance to Javascript.

**Comment by achamayou** [comment]
Done
