### ISSUE TITLE
Add GET /proposals/{proposal_id}/votes

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1950]
If the proposal script/parameters are huge and someone is only interested in the votes, then they should be able to do `GET /proposals/{proposal_id}/votes`, given that `GET /proposals/{proposal_id}/votes/{member_id}` already exists and the votes collection is already exposed at `GET /proposals/{proposal_id}`.

NOTE: Deferred until governance is moved to JS.

**Comment by achamayou** [comment]
Done in JS
