### ISSUE TITLE
Expose response schema for GET /config

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1958]
Part of https://github.com/microsoft/CCF/issues/1918.

`GET /config` has no schema in its OpenAPI definition, likely because it has a flexible format, but there should be at least *some* structure, like the top-level being an object etc.

**Comment by letmaik** [comment]
If I understand the code correctly then the schema currently is:
```js
{
  "<node_id_1>": { "address": "<hostname_1>:<port_2>" },
  "<node_id_2>": { "address": "<hostname_2>:<port_2>" },
  ...
}
```
@achamayou How is this different from what's exposed in `/network_info`? See also https://github.com/microsoft/CCF/issues/1954?.

**Comment by achamayou** [comment]
Is the consensus internal state, rather than what the KV contains, and it doesn't execute a Tx. When using CFT that's quite similar if all goes well, in BFT it's quite different because it's only a local call as opposed to a proper transaction going through consensus.

**Comment by letmaik** [comment]
OK, then at least the schema should be the same as what's used by the other endpoints. I'm assuming it's called generically config because it may be extended in the future?

**Comment by achamayou** [comment]
Sorry, there's another important difference I failed to bring up, network_info is the RPC addresses to be used by users, whereas config is the node to node addresses nodes use to talk to each. config is an operator concern, not a user concern, we will likely extend it with other information such as evidence watermark etc.

**Comment by letmaik** [comment]
Just for clarification, the current structure doesn't allow returning config entries that are not specific to a node. Is /config only meant for per-node values? Do we expect some other field at the top level in the future? Either way, it may still make sense to put everything into a top-level `"nodes"` field.

**Comment by achamayou** [comment]
A config _is_ a list of nodes, but what can happen at least in CFT is that there are more than one active configuration active, so the schema should allow for that. This ought to be a relatively simple fix, I will pick it up.
