### ISSUE TITLE
Nodes attempt to forward requests to leader although the connection has been dropped

### ISSUE THREAD

**Issue by rschust** [microsoft/CCF#196]
When stopping the leader, the other nodes will attempt to reconnect and forward requests until the election timeout expires. It might be worth considering to initiate an RPC to other nodes once the TCP connection with the leader has been dropped, in order to check whether the other nodes also lost that connection, and if so, elect a new leader.

**Comment by jumaffre** [comment]
Another approach would be to mark the corresponding node-to-node channel as `CLOSED` when the TCP connection between 2 nodes is closed on the host (it will probably require a new ring buffer message type). That way, when a command is [forwarded by a follower](https://github.com/microsoft/CCF/blob/master/src/node/rpc/frontend.h#L471) to the (now-unreachable) leader, the forwarding will fail and return a `RPC_NOT_FORWARDED` JSON-RPC error.

**Comment by achamayou** [comment]
The randomness of the timeout is important for the elections to succeed quickly. If all the followers immediately run for election once they've contact with the leader, they will mostly fail to be elected, will rev up the term some more etc, so we must be careful with changes there.

**Comment by achamayou** [comment]
Tracked in #486.
