### ISSUE TITLE
Public ledger recovery progress monitoring

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1973]
We should expose information about progress of the public recovery on the `/node/state` endpoint, i.e. `current_public_recovery_seqno/target_public_recovery_seqno`. 

As we don't know the target `seqno` of the public recovery in advance, we should pass it down the enclave when starting a node in recovery mode (e.g. using the existing `CCFConfig` interface).

**Comment by achamayou** [comment]
`last_signed_seqno` in `/state` does this, but with recovery from snapshots, this has become less useful.
