### ISSUE TITLE
Getting compacted keys from a later primary does not work

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1986]
When a node joins, it is given the list of compacted ledger secrets from the current primary. This lets it replay the ledger/incoming append entries, and while doing so it calls `encryptor->compact` at each signature transaction, and tries to compact its own list of ledger secrets. This call to `record_compacted_keys` simply appends the given secret to the same list we received from the primary, so we end up with duplicates. If the primary told us secrets at versions `[1, 32, 46, 85]`, we'll end up with `[1, 32, 46, 85, 32, 46, 85]`. If we then become primary, this is the list we'll send to new joiners, and the duplicates will cause them to loop forever.

This is the cause of [this test failure](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=16293&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=63d660c3-6f76-573a-0154-fd0bcb096ded&l=13261) - node 8 gets stuck in a permanent loop adding to a container, eventually timing out or hitting a `bad_alloc`. This has a high repro rate on this seed, but is not 100%. We should add a reconfiguration suite which exhibits this crash consistently.

There's several things we should or could fix here:
- When we get a list of secrets from the primary, we should make sure that the versions they apply from are unique and ordered.
- When we `record_compacted_keys`, we should check if this is a secret we already know (if so, it should match!), rather than apppending out-of-order.
- `TxEncryptor::compact` should be rewritten to be clearer, and to remove the possibility of looping forever.
- We should add some logging on rekeying/key compaction, so that verbose logs show us the lifetime of a secret.
- The 'active' `encryption_keys` and compacted `ledger_secrets` could be combined into a single, ordered container. We want to keep the lookup on `get_encryption_key` cheap, but we can do this by looking at the final item first (which is always the secret we want on the hot path), and only running the `std::upper_bound` search if that fails.
- We should investigate what we're doing with very old ledger secrets. With snapshotting, we don't want to keep them around forever, but this might mean declaring that only snapshots created in the last N secrets can be used for joining (for anything older, the primary doesn't remember how you should decrypt it, and finding out by trawling backwards through the ledger is too expensive).

**Comment by eddyashton** [comment]
For a simple repro, add a rekey to the `reconfiguration` test_suite:
```
--- a/tests/suite/test_suite.py
+++ b/tests/suite/test_suite.py
@@ -46,6 +46,7 @@ suites["membership_recovery"] = suite_membership_recovery
 suite_reconfiguration = [
     reconfiguration.test_add_node,
     reconfiguration.test_retire_primary,
+    rekey.test,
     reconfiguration.test_add_node,
     election.test_kill_primary,
     reconfiguration.test_add_node,
```
```
ctest -VV -R reconfiguration_test_suite
```

This isn't 100% - I guess the new primary is sometimes a node who was present originally, rather than a joiner? But a more precise combination of `add`/`retire`/`rekey` should get a reliable repro.

**Comment by jumaffre** [comment]
As detailed on #2020 (`Rekey` section), I'm not sure we want to use the final ledger secret in the encryptor first and `std::upper_bound` if it fails. First, it's not clear what a failure case here is (the encryption will work if we use the wrong key, but the backups won't be able to decrypt the entry (which happens much later down the line). Also, transaction serialisation isn't guaranteed to happen in the same order as the global `seqno` order. 

Apart from this point, I'll look at implementing the changes to fix this next.
