### ISSUE TITLE
Ledger Secrets Management

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#2020]
This issue should summarise some of the recent discussions on ledger secret management (e.g. #1986). I've added tasks inline to cover the work that needs to be completed.

TL;DR: We need to fix #1986, pass the locally committed ledger secrets on join, and add support for historical queries after rekeys/snapshots.

## Ledger Rekey

Rekeying the ledger rotates the key used to encrypt the ledger entries. Rekey at `seqno` `N` writes new secret for all nodes in KV (in the `ccf.gov.secrets` table), including the primary node (encrypted with each node's encryption key) so that ledger secret are used from `N+1` onwards.

Because txs don't take a lock between commit (`apply_changes()`) and serialise, two parallel rekey txs may interleave commit and serialise, e.g. commit(tx0 at `N`) -> commit(tx1 at `N+1`) -> serialise(tx1 at `N+1`) -> serialise(tx0 at `N`). Because of this, the encryptor needs to keep track of the ledger secrets, along with the `seqno` at which they're applicable from.

When a node no longer needs to use a secret (i.e. global commit past the `seqno` of the _next_ ledger secret), it can safely discard it from the encryptor. More precisely, the node will no longer need to use the key for ledger encryption/decryption (\*) so the key can be removed from the main store's encryptor so that key lookup on encryption/decryption is as cheap as possible (it is based on binary search). However, the ledger secret needs to be kept saved to be passed on to new nodes on join (see `Sharing Ledger Secrets` section).

(\*): It may still be used for historical queries, but the historical query mechanism uses a different store/encryptor. See `Snapshots and Historical Queries` section below.

## Recovery

When recovering a service, the first recovery node creates a ledger secret that is used to integrity protect the entries in the public-only service. When the recovery is complete, the same secret is used to encrypt/decrypt private entries.

The history of ledger secrets is stored in the `ccf.gov.shares` table, at a unique key (`0`), where each ledger secret is recorded, encrypted with the next ledger secret. The history of ledger secrets is recovered when the public ledger is read. On private recovery, the latest ledger secret is decrypted from the recovery shares, which can decrypt the previous ledger secret, and so on.

In short, the historical ledger secrets can be recovered from the ledger by looking up entries backwards.

## Sharing Ledger Secrets

As mentioned above, on rekey, the primary writes the new ledger secret for each trusted node in the KV at the time in the `ccf.secrets` table, encrypted with each node's encryption public key.

However, new nodes will join the service at a later stage, after rekey(s) has/ve taken place, and thus won't have been included in the original rekey tx. To be able to catch-up, new nodes are given _all_ historical secrets (see `Snapshots` for caveats) by the primary node they join from in the `/node/join` RPC response. This means that the primary node needs to keep track of _all_ historical ledger secrets.

(Note: Technically, the primary node could only pass the very latest ledger secret to the new joiner, which could reconstruct the history of secrets from the `ccf.gov.shares` table. However, this would mean parsing the ledger backwards, which is unpractical with the current ledger replication protocol)

_Locally_ committed ledger secrets should be shared with new nodes on join. If only _globally_ committed ledger secrets were given to new nodes, if a rekey happened just before a new node was trusted (i.e. within the same commit "batch"), the new node wouldn't be given the new ledger secret via the rekey tx or the `/node/join` response.

- [x] 1. Currently, only (globally) committed ledger secrets are passed to new nodes on join. We should fix this and also make sure that new joiners check for global commit over the tx that added them as TRUSTED.

## Snapshots and Historical Queries

When joining from a snapshot, a node only needs the ledger secrets that are valid for the `seqno` the snapshot was taken.

It'd be tempting to say that nodes should always keep track of all historical ledger secrets. However, this isn't possible as nodes can recover from a snapshot, without a historical ledger at first, and may only have access to ledger secrets valid from the `seqno` of the snapshot

So a node may join the service from a primary that doesn't have the complete history of ledger secrets. As of CCF 0.16.0, the new node should join from a snapshot that's at least as recent as the snapshot the primary recovered from. Otherwise, the primary couldn't give the new node the ledger secrets. This is usually avoided with an effective snapshot management process, as operators should always use the latest snapshot on join/recover.

- [ ] 2. This is currently not enforced. As a temporary measure, we should check that a new node should only be allowed to join from a primary whose first known `seqno` is <= the `seqno` the new node is trying to join at.

### Recovering Historical Ledger Secrets

The scenario described in `2.` can be too limiting. Moreover, nodes started from snapshots also have to serve historical queries from a ledger they didn't replay and may not have the ledger secrets for. So a solution has to be found so that:
- Historical queries older than the snapshot at which a node was started from can be served.
- Nodes can join from a snapshot older than the primary's startup snapshot. 

To recover historical secrets from the ledger, a node should lookup its `ccf.gov.shares` table to find out at which `seqno` the previous ledger secret was written. It can then retrieve that entry from the ledger (using the existing historical query mechanism), decrypt that ledger secret with the latest one, and repeat the procedure until the ledger secret applicable at the target `seqno` is found.

- [x] 3. Add previous ledger secret `seqno` in ledger secret info (`ccf.gov.shares` table).

- [x] 4. Add mechanism to fetch historical secrets from the ledger (this is the largest task in this issue).

On join from a primary that doesn't have historical secrets for the new joiner, the primary can recover the ledger secrets from its historical ledger and then sends them to the new node. Note that the ledger recovery procedure takes some time but will run in parallel to the proposal/vote to trust the new node so the ledger secrets recovery procedure should be complete by the time the proposal completes.

**Comment by jumaffre** [comment]
As discussed today with @eddyashton, the changes described in 1. above have the following implications in a multi-threaded scenario:
- A new joiner only needs to be passed the ledger secrets valid up to the point that node was trusted (typically by the consortium, through a `trust_node` proposal). Ledger secrets that are refreshed between the `seqno` the node was trusted and the read-only `/node/join` endpoint execution do not need to be passed to the new joiner via the `/node/join` HTTP response: the new joiner will get those secrets from the KV hook on the `ccf.secrets` table as it replays append entries.
- To find out which historical ledger secrets to pass to a new joiner, the joinee should: 1) take a read dependency on the `ccf.shares` table (*) when a new node is added as trusted, 2) read the latest ledger secret from the `LedgerSecrets` object (through the KV's encryptor), 3) record the `latest_ledger_secret_seqno` at which this secret is applicable from as well as the hash of this secret in the `ccf.nodes` table (at the key of the new node)
- On `/node/join` the historical secrets up to `latest_ledger_secret_seqno` (read in the KV) should be passed to the joiner. The joinee should check that the hash of the ledger secret is also valid (i.e. secret was unchanged). 

- For "simpler" write endpoints that rely on looking up the ledger secrets (e.g. `update_recovery_shares` proposal), taking a read dependency on the `ccf.secrets` table (at the key of "our" node id) is necessary. Otherwise, a parallel rekey could update the ledger secrets under our feet.

(*) The `ccf.shares` table is currently keyed by version. It should be rekeyed by node id instead.

**Comment by achamayou** [comment]
@jumaffre unless I am missing something, addressing item 2. is just a matter of making sure that an appropriate error is returned in that situation. Is that correct?

**Comment by jumaffre** [comment]
@achamayou That's right. Picking up this now.
