### ISSUE TITLE
Distinction between node and proposal id in governance

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#203]
Right now when submitting a proposal we use --id to either mean the proposal id we want to vote on or the node id we are proposing a change to. 

e.g. 

`./memberclient vote --accept --id=0` means we are voting for proposal with id 0
`./memberclient accept_node --id=0` means we are making a new proposal to accept node with id 0

these should be made --proposal-id and --node-id

**Comment by rschust** [comment]
Handled on #260
