### ISSUE TITLE
Member frontend only supports certificate authentication on some endpoints

### ISSUE THREAD

**Issue by lynshi** [microsoft/CCF#2033]
**Describe the bug**
0.16.1 introduced functions for explicitly setting authentication policies on endpoints. In CCF itself, only `member_cert_auth_policy` is registered for some governance endpoints. This disables signature authentication.

**To Reproduce**
1. With a member client, submit a request to `/gov/ack/update_state_digest`.
2. The following error is returned:
```
401 {\"error\":{\"code\":\"InvalidAuthenticationInfo\",\"message\":\"Could not find matching member certificate\    "}}
```

**Expected behavior**
Signature authentication and certificate authentication should both work on all governance endpoints.

**Environment information**
CCF 0.16.1

**Additional context**
For `ack/update_state_digest`, only [`.add_authentication(member_cert_auth_policy)` is called](https://github.com/microsoft/CCF/blob/8d050636d6fa5b75e1769d9140f0fe1272904550/src/node/rpc/member_frontend.h#L1693).

**Comment by achamayou** [comment]
This is an oversight, I suspect the rationale behind the change was to allow unsigned access to all read-only governance RPCs, which is fine, but signed requests should still work across all governance RPCs to support using keys held offline.

**Comment by lynshi** [comment]
Should write/proposal endpoints still allow certificate authentication? We don't rely on it anymore, but just curious.

**Comment by achamayou** [comment]
@lynshi the signature must be present on writes and is stored for audit purposes. That was always the case, session cert auth was never enough for a member write operation.

**Comment by lynshi** [comment]
Right, forgot about that - thanks!
