### ISSUE TITLE
Test installed CCF is failing in Daily

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2067]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=17336&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=fe98d859-2537-5570-75af-de67d4290f3a

**Comment by jumaffre** [comment]
`test_install.sh`, which calls the `tutorial.py` script, relies on the JS logging app, which doesn't have the `/app/multi_auth` endpoint (only present in the C++ logging app). As we want to still include the call to `/app/multi_auth` in `tutorial.py`, I propose that `tutorial.py` should check whether the `/app/multi_auth` endpoint exists first, and only if it does call `GET /app/multi_auth`.
