### ISSUE TITLE
Add node RPC to check for existing host/port combination before adding the node

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#208]
If a node crashes and we try to add it again (same port + host combination), and the initial node is not removed from nodes configuration, we might end up having more than one node in the nodes table with different id and certs, but same host + port information.

The memberfrontend add_node RPC adds a new node into the nodes table. It should check that no other node exists with the same host + port combination before adding it, otherwise it should respond with a "node with same port and host already exists" error.

**Comment by rschust** [comment]
Solved on #218
