### ISSUE TITLE
Add python support for adding a new node

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#209]
On proposing the addition of a new node, we need to provide a nodes.json-like file that has the information needed in the correct format for it to be added into the kv. This happens nicely in the python scripts now when setting up a new network, but it does not exist standalone.

 There should be a python script that helps with this. It could take a json file written like so:
input.json example:
```
[{"host":"<host_ip>", "pubhost":"<pubhost_ip>", "raftport":"<raftport>", "tlsport": "<tlsport>",
"status":<status>, "quote":{{quote_file}}, "cert":{{cert_file}}
}]
```

where we have string templates to declare the files that need to be replaced with their content in the correct format. We can then process that json file and populate the file names with their content. That can then be used as an input when calling add_node. We could potentially add a common prefix that tells us about the full path of the file location.

**Comment by achamayou** [comment]
Effectively solved by #318, since adding a node no longer requires a manual RPC
