### ISSUE TITLE
Bind Proposal Ids to root of Merkle Tree when running BFT

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2136]
Follow-up to #1649 and #2087. Proposal Ids are bound to the state at the read version, and read version selection isn't deterministic in the presence of concurrent transactions. So a possible way to resolve that for BFT is to:

- [ ] Add a "flush" flag to the read version for backup re-execution, which will be useful for both signatures and proposals, since they both need to express not just KV state dependencies but also History state dependencies

~~Add a mechanism to capture non-deterministic values during primary execution, likely in a KV table, and to send them to secondaries for re-execution. That's one way to capture the merkle tree read version, and the mechanism would be generally useful once we add support for REST requests from CCF etc~~

**Comment by ashamis** [comment]
Discussing this with @achamayou  the current proposal is to have a pipeline execution stall for transactions that write to the proposals table on backups. This will ensure that the transaction will see the correct read version.
