### ISSUE TITLE
TX_FAILED_TO_REPLICATE when member ACK against a follower 

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#215]
When a member tries to `ACK` itself on a follower, the (Write) command fails with `TX_FAILED_TO_REPLICATE` as the command is (wrongly) executed on the follower which is not the leader:

```
$ ../build/memberclient ack --cert=member5_cert.pem --privk=member5_privk.pem - -host=10.1.0.4 --port=25000 --ca=networkcert.pem --sign
Unhandled exception: No result field: {"error":{"code":-32005,"message":"[TX_FAILED_TO_REPLICATE]: Transaction failed to replicate."},"id":0,"jsonrpc":"2.0"}. Aborting...

$ less out
...
[fail ] ../src/raft/raft.h:298               | Failed to replicate 1 items: not leader
```

Instead, the follower should not execute the command and reply to the client that the command needs to be run on the leader (as the `ACK` command is installed as `DoNotForward`). 

(Possibly related to https://github.com/microsoft/CCF/issues/214)

**Comment by eddyashton** [comment]
Had a look at this (actually only got as far as #214, but with no proposals it gives this error), its a good one.

`memberclient` sends client-signed requests. We store these signed requests (`frontend.h`, `verify_client_signature`, `client_sig_view->put`). So `memberclient` can't make any read-only requests. When you make a supposedly read-only request to the leader, the global signature still advances as we update the KV with this latest signed request. If you try it on a follower, you get `TX_FAILED_TO_REPLICATE`.

There's a comment just above the `put`:
```
// TODO(#important): Request should only be stored on the leader
```
If that's the design, this is an easy fix.

Similar issues would be caught by #61 and #62. It would be nice if the `TX_FAILED_TO_REPLICATE` response (or associated log message) had more detail, perhaps the names of the affected tables, but we're dealing with fully serialised data by this point.
