### ISSUE TITLE
memberclient does not support manual proposal completion

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#216]
The `memberclient` does not support manual proposal completion even though the member frontend supports such handler. 

Members should be able to run `./memberclient complete --id=<proposal_id> --cert=<member_cert> --privk=<member_privk> --sign -host=10.1.0.4 --port=25000 --ca=networkcert.pem` to force the completion of an active proposal.

**Comment by achamayou** [comment]
Forced completion is probably not the best name for this, since it doesn't really force completion, rather it re-runs the evaluation.

**Comment by rschust** [comment]
@jumaffre @achamayou Since we plan of abandoning memberclient, and ccf.py exposes vote_using_majority, would it make sense to close this issue?

**Comment by jumaffre** [comment]
Should we leave this open until `memberclient` is deprecated? We still mention it heavily in our documentation (e.g. https://microsoft.github.io/CCF/governance.html?highlight=memberclient) and this issue could serve as reference for some of the limitations of the CLI.

**Comment by achamayou** [comment]
It seems best to keep this open until the official client advertised in documentation does in fact support manual proposal completion.

**Comment by achamayou** [comment]
The memberclient has been superseded by scurl, and is on its way to deprecation once FTCP is removed, so this won't be added.
