### ISSUE TITLE
Randomise node for end-to-end tests

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#219]
As it stands, the end-to-end python tests always create a client against a given node, e.g. `with primary.user_client() as c:` or `follower.management_client() as c:`. However, CCF now supports command forwarding and most commands should produce the same results whether they are executed against the leader/primary or followers/backups.

We should add the ability to create a client against the python `Network` class that returns a random node from the network. This should help us detect issues like https://github.com/microsoft/CCF/issues/215 or https://github.com/microsoft/CCF/issues/214 in the future. 

When implementing this, we should also make sure that the results are reproducible, e.g. by printing the seed used to randomly create the network client.

**Comment by eddyashton** [comment]
I'm not sure a random node is the best choice here. Even if we log everything sufficiently to reproduce the node selection on a local test, it interacts badly with other randomness/other test setup. Put another way - if you want to reproduce a one-off CI failure, you need to find and set the random seed from the failing test, even if that has nothing to do with the failure.

I think we could get roughly the same coverage of "things that surprisingly only work on the primary" by simply changing all(/most) of the tests to communicate with a follower whenever we think the request is forwardable.

**Comment by achamayou** [comment]
But that won't get us things that may happen when you have interesting inter-leaves, and unless we got out of our way to alternatively send to leader and followers, it's hard to get to those.

I think we can have network.user_client(), which by default is on=Role.ANY but when you know you need one or the other you can do: network.user_client(on=Role.PRIMARY) or network.user_client(on=Role.FOLLOWER). If the seed has nothing to do with the failure, you will get the failure without passing it, and if it does, well...

**Comment by achamayou** [comment]
I'm convinced that this isn't practical, and I think we're better off investing further in expanding our test_suite scheme at least for now.
