### ISSUE TITLE
Certificate validity period is fixed

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#2190]
As discussed with @wintersteiger, the validity period of the node's certificates is currently hardcoded to a set date, which isn't great:
https://github.com/microsoft/CCF/blob/acc4ad227777431e111d164d305b4f60bb35efad/src/tls/key_pair.h#L581-L586

Instead, this should be set by the operator when at node startup, with perhaps a default sets by the host to the current date minus a few days.

**Comment by wintersteiger** [comment]
Let's keep this one open. The dates are still fixed after #2305 and we shouldn't forget to make them configurable or automatic.

**Comment by achamayou** [comment]
@wintersteiger I've created #2314 as a successor issue, this particular action item for 1.0 is now complete.
