### ISSUE TITLE
VM setup guide: DnsRecordInUse

### ISSUE THREAD

**Issue by jmandel** [microsoft/CCF#2195]
Following the setup guide from https://microsoft.github.io/CCF/main/build_apps/create_vm.html, during the `make_vm.sh` step I get the following error:

```
Deployment failed. Correlation ID: 80f5b90e-03d6-42ca-a447-291bd5058d75. {
  "error": {
    "code": "DnsRecordInUse",
    "message": "DNS record ccf-dev-vm.uksouth.cloudapp.azure.com is already used by another public IP.",
    "details": []
  }
}
```

There appear to be hard-coded values about `ccf-dev-vm` in the generated templates; would be good if documentation can explain how to avoid name collisions, or better yet if the generation process automated this.

**Comment by achamayou** [comment]
@jmandel thank you for spotting this, there are two options I can think of:

1. remove `hasDNSName: true`, and let the user refer to/connect to their VM by public IP.
2. generate `vm.json` from a template, and fill in a reasonably unique vm name, something like `ccf-dev-J2XozD4i`, or maybe `ccf-dev-$SUBSCRIPTION`, but I'm not sure how unique/confidential subscription names are.

**Comment by achamayou** [comment]
I have gone with 1. because I couldn't think of a good way to generate a unique but memorable name. Please do feel free to re-open the issue if this isn't satisfactory.
