### ISSUE TITLE
Store deserialise refactor

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#2208]
To find out which maps were changed when deserialising a ledger entry into the store, we currently rely on the `kv::ApplyResult` enum returned by the function. However, this is error prone if multiple maps of interest are touched by this ledger entry and is likely not to scale well in the future. 

Instead, we should return to the caller a list of all changes caused by the ledger entry.

**Comment by achamayou** [comment]
What is the use case for general inspection of maps touched by a transaction? How does this overlap with hooks? Why can't it be fulfilled by running a read on the store?

My current impression of apply result is that it is a limited internal notion, used almost entirely by consensus, one that's very performance sensitive. It is not clear to me at all that we should do something more expensive here to fulfill generic use cases when there are two generic mechanisms already.

**Comment by jumaffre** [comment]
As discussed, let's use hooks for the non-critical paths (historical queries and snapshot evidence verification).
