### ISSUE TITLE
Receipts change over time

### ISSUE THREAD

**Issue by lynshi** [microsoft/CCF#2248]
**Describe the bug**
The receipt for a transaction changes when the sequence number increases. Based on the [documentation here](https://microsoft.github.io/CCF/main/use_apps/verify_tx.html#transaction-receipts) and my previous understanding, receipts should be constant over the lifetime of the ledger.

**To Reproduce**
Given a 1-node CCF network,
1. Get the receipt for an existing transaction (`GET /app/receipt?commit=42`).
2. Verify the receipt (`POST /app/receipt/verify`). This passes.
3. Create a transaction that increments the sequence number (i.e. write to a KV store). 
4. Verify the previous receipt. Now, the response says `valid: False`.
5. Get a receipt for the original transaction again. The receipt is now different.

**Expected behavior**
The original receipt should always be valid, and subsequent retrievals should return the same receipt.

**Environment information**
CCF 0.18.1

**Comment by achamayou** [comment]
These problems are known issues of the current implementation, which only issues receipts based on the current tree. Instead, a historical tree snapshot must be used. I will address this as soon as #2233 is merged.

Separately from that, it is worth noting that there may be as many valid receipts for a transaction as there are signatures in the ledger that follow the transaction in question. The one we aim to consistently produce is the shortest one, ie. the one rooted in the very next signature, but the others are equally valid, if longer.

In some situations, for example after a catastrophic recovery (and therefore a network identity change), a user may explicitly want a longer receipt, rooted in the latest identity.

**Comment by lynshi** [comment]
Got it, so returned receipts can be expected to change over time as the Merkle tree is modified, since they're issued off the latest state. However, the known issue is that previously issued receipts should still be valid because they can be verified over the historical tree.

Given a receipt, is it possible to tell from which historical tree it was issued? Or will we also need to provide other metadata so CCF can figure out which historical tree to load?

**Comment by achamayou** [comment]
There is only one tree, it just gets compacted gradually to avoid taking all the memory. It's possible to load older views using historical queries however. We will default to returning receipts rooted in the next signature, which are stable in time.

Note that verifying receipts against the service, as opposed to independently offline, is not a particularly meaningful operation. If you trust the service, then asking for a tx status provides the same information. If you do not, then the value you can attribute to its answer is very unclear.

**Comment by wintersteiger** [comment]
When looking at the receipt verification yesterday, I had the same thought. The new Merkle trees support past/historic paths, so it wouldn't be hard to extract the shortest/oldest receipt as long as the tree hasn't been flushed or the flushed nodes have been loaded into memory somehow. Since we have partial serialisation, I guess partial de-serialisation or general un-flushing is worth considering too.

The receipts contain a Merkle path, which in turn contains the maximum leaf index of the tree at the time the path was extracted. This index identifies the point in time, i.e. the historical tree to load is the one that contains exactly that many indices (or more if the your implementation supports past root extraction).

**Comment by achamayou** [comment]
@wintersteiger yes, that's exactly what I am looking at the moment. There's a number of optimisations we can also with the current state, but first the historical case (ie. with compacted trees flushed out to disk) needs to be working.

**Comment by achamayou** [comment]
Fixed by #2270
