### ISSUE TITLE
Transaction ID should be returned in a single header

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#2256]
Currently we return 2 headers (view and seqno) - these should be combined into a single header. Other APIs which take these fields should be updated to take a single string.

**Comment by achamayou** [comment]
@lynshi your input on naming constraints, if any, would be most welcome.

**Comment by eddyashton** [comment]
We discussed this briefly last week - I think we're all happy with `x-ms-ccf-transaction-id`, so that's what I'll aim for initially.

We don't plan to make this configurable, since there isn't a need for it right now (and it introduces a subtle error class, and complicates receipts, and would need to be synced across client SDKs including the CCF Python client).

**Comment by achamayou** [comment]
Sounds good, let's go with that.
