### ISSUE TITLE
Add features to recovery test

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#226]
Our recovery test uses an uneventful network, potentially missing additional failure cases caused by historic configuration changes (eg - the Raft term history reconstruction).

We should add transaction volume and elections between later recoveries to fully test the recovery logic.

**Comment by achamayou** [comment]
This is now covered by the scenario tests, which can and a do select recovery interleaved with other tests: https://github.com/microsoft/CCF/blob/master/tests/e2e_scenarios.py
