### ISSUE TITLE
Committable suffix test failure with multiple threads

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2272]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=19818&view=logs&j=a45bc589-b130-5dc2-b16b-03ef91a336e9&t=e0a5b36f-0731-50ba-f64f-947055ee7ed0

One of the nodes seems to be unable to make progress:

48: Traceback (most recent call last):
48:   File "/mnt/build/3/s/tests/committable.py", line 118, in <module>
48:     run(args)
48:   File "/mnt/build/3/s/tests/committable.py", line 111, in run
48:     network.wait_for_node_commit_sync()
48:   File "/mnt/build/3/s/tests/infra/network.py", line 831, in wait_for_node_commit_sync
48:     assert expected == commits, f"Multiple commit values: {commits}"
48: AssertionError: Multiple commit values: ['8.45', '8.51', '8.51', '8.51']
48/86 Test #48: committable_suffix_test ...........***Failed   47.02 sec
test 49

**Comment by ashamis** [comment]
I am trying to repro this with a single threaded run.... will update with results

**Comment by achamayou** [comment]
Most recent occurence: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=26162&view=results

```
44: Traceback (most recent call last):
44:   File "/mnt/build/3/s/tests/committable.py", line 115, in <module>
44:     run(args)
44:   File "/mnt/build/3/s/tests/committable.py", line 108, in run
44:     network.wait_for_node_commit_sync()
44:   File "/mnt/build/3/s/tests/infra/network.py", line 895, in wait_for_node_commit_sync
44:     assert expected == commits, f"Multiple commit values: {commits}"
44: AssertionError: Multiple commit values: ['8.47', '8.55', '8.55', '8.55']
44/73 Test #44: committable_suffix_test ...........***Failed   46.93 se
```

**Comment by achamayou** [comment]
A couple of thoughts on this issue:

1. Unless I'm missing something, the primary un-suspension can cause one or more elections, depending on how long it's been out. In these cases, the current timeout (3 seconds) is far too short.
2. Dumping the consensus state of all the nodes when they turn out not to be in sync is an obvious improvement to audit.
