### ISSUE TITLE
Consolidate View and SeqNo typedefs

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#2282]
We currently have a lot of different typedefs for `View` and `SeqNo` (under `kv::`, `kv::Consensus`, etc), as well as some older terminology referring to `Version`, `Index`, and `Term`. As part of #697, the former should be consolidated into a single alias (`ccf::View`, `ccf::SeqNo`, from `ccf/tx_id.h`), and the latter should only be used inside the KV/Raft and not exposed beyond them.

**Comment by achamayou** [comment]
We should kill off all remaining usage of `Term` now that `TxView` is gone.

**Comment by eddyashton** [comment]
I'm making progress on this, with a few caveats:
- We were benefitting from a lot of direct conversions from `kv::Version` (signed so it can handle deletions) and `SeqNo` (unsigned). I think a lot of the uses of `Version` should actually be unsigned - wherever we use it to refer to an entire Tx for instance, it must be non-deleted. So I'm trending towards making these all unsigned, but maintaining a signed internal representation for deletions in the champ. This would be easier if we did #1992 first, but I think we need to do it this way round to smooth off the API ASAP.
- This already includes a lot of hairy guesswork of "is this KV or everything-else", so I'm avoiding removing `Term` and `Version` terminology for now. Once they're all unsigned and the distinction is drawn, it should be easier to rename `Term` to `View` in isolation.
