### ISSUE TITLE
Async CCFClient or async client methods

### ISSUE THREAD

**Issue by lynshi** [microsoft/CCF#2291]
**Is your feature request related to a problem? Please describe.**
[Based on the documentation](https://microsoft.github.io/CCF/main/use_apps/python_api.html#ccf.clients.CCFClient.call), `ccf.clients.CCFClient.call` makes synchronous HTTP requests. Further, [`wait_for_commit`](https://microsoft.github.io/CCF/main/use_apps/python_api.html#ccf.clients.CCFClient.wait_for_commit) blocks while polling.

**Describe the solution you'd like**
An async client or asynchronous methods on the client would allow non-blocking network operations.

**Comment by achamayou** [comment]
CCF has switched to using httpx for tests and in CCFClient (#2912), which does allow async requests.

As discussed in #2909, the CCFClient wrapper has become so thin that we intend to remove it altogether. Instead we recommend users directly interact with httpx to execute async requests.
