### ISSUE TITLE
JS API cleanup

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#2315]
From https://github.com/microsoft/CCF/pull/2313#issuecomment-799237637 by @achamayou :

1. We seem to have taken a rather random view to capitalising acronyms, so we have RsaOaep-like things and AESKW-like things. I don't particularly care which one we go with (although the latter makes more sense to me), but it's important to be consistent. DONE: https://github.com/microsoft/CCF/pull/2325
2. All the crypto calls like generate key, wrap etc should be under `ccf.crypto`, and we should perhaps have `ccf.conv` for the conversion calls.

**Comment by letmaik** [comment]
Regarding naming, I think PascalCase for acronyms is better, since it provides separation between two subsequent acronyms, like AES and KW -> AesKw. This is in line with the web crypto api: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/wrapKey. Currently we have the following outliers: `CCF`, `KVMap`, and `AESKWPParams`. These are TypeScript interfaces. There are no inconsistencies in the actual JS API.

**Comment by achamayou** [comment]
Ok let’s align on the web crypto API naming then.

**Comment by achamayou** [comment]
Only `CCF` remains, which I think is acceptable since it's a single, short acronym.
