### ISSUE TITLE
Update docs to use hex-digest IDs for users and members

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#2349]
Some of our documentation and proposal samples still uses the old numeric IDs for users and members:

![image](https://user-images.githubusercontent.com/6000239/112189879-5e987000-8bfc-11eb-8cf7-a8b742ba3da3.png)

These should be updated to use the current hex-digest IDs.

**Comment by achamayou** [comment]
Done as part of the JS gov migration
