### ISSUE TITLE
Update Lua to latest version (5.4.3)

### ISSUE THREAD

**Issue by psfoley** [microsoft/CCF#2384]
The latest version of Lua includes several bug/security fixes. Would it be possible to upgrade from 5.4.0 to 5.4.3, or is there a hard dependency on this version?

**Comment by achamayou** [comment]
@psfoley we will not update Lua because it's being replaced by quickjs and will be removed shortly, sometime in the next couple of weeks. All other 3rd party dependencies are kept up to date.

**Comment by psfoley** [comment]
Thank you @achamayou! Given that Lua will be removed soon, I'll close this issue
