### ISSUE TITLE
Performance drop on JWT benchmarks

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#2412]
We've recently taken a significant hit on some of our e2e benchmarks, which seems to only affect the tests which are using JWT for authentication; `ls_jwt_sgx_cft` and `ls_js_jwt_sgx_cft`.

![image](https://user-images.githubusercontent.com/6000239/113684889-95bb5680-96bd-11eb-81a3-4ea0a4ad6482.png)

This came in with the OE-0.15.0~rc1 update, but we haven't been able to isolate it to a specific regression in our crypto providers (#2409 shows slight slowdown in RSA verification, but not large enough to halve our e2e throughput).

This needs further investigation.

**Comment by achamayou** [comment]
This seems to have been caused by the OpenSSL upgrade, which is unavoidable for security reasons.
