### ISSUE TITLE
forum sample build fails. Reference to @microsoft/ccf-app not found

### ISSUE THREAD

**Issue by beejones** [microsoft/CCF#2418]
**Describe the bug**
Building the forum sample fails because the reference to @microsoft/ccf-app is not found. Removing @microsoft/ccf-app from package.json and reinstalling it from npmjs fixes the issue (npm i @microsoft/ccf-app)

**To Reproduce**
clone CCF and run the setup steps.
cd ~/samples/apps/forum
npm i
npm start

**Expected behavior**
The app builds and starts.

**Environment information**
CCF: v0.99.0
Azure confidential compute VM: 
Distributor ID:Ubuntu
Description:Ubuntu 18.04.5 LTS
Release:18.04
Codename:bionic

**Comment by letmaik** [comment]
The forum sample has to be modified slightly before it can be used stand-alone. This is described in [the docs](https://microsoft.github.io/CCF/main/build_apps/js_app_tsoa.html#dependencies) but it may be that you missed that note and we should probably add that to the README.md file in the sample folder as well.
If you want to build against the local version of `ccf-app` in the repository, then simply leave the path as it was (`file:..`) and run `npm install` inside the `js/ccf-app` folder.
