### ISSUE TITLE
Make `ccf` global injection in JS Context modular

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2448]
Split populate_global_ccf() per namespace, and enable the relevant namespaces only for different governance contexts

**Comment by letmaik** [comment]
I'm bumping against this in #2461 where the new `ccf.node.triggerHostProcessLaunch()` should be available in apps but not all the other `ccf.node.*` functions.

**Comment by achamayou** [comment]
That's not really what I had in mind when I wrote this, I expected namespace granularity would be the correct level of modularity. But your usecase shows that it isn't sufficient, and something more similar to KV access is needed instead (calling context x access level -> capability).

**Comment by achamayou** [comment]
As discussed, let's create `ccf.host.triggerSubprocess()` for this, separately from `ccf.node`.

**Comment by achamayou** [comment]
(very) related to #2961.

**Comment by achamayou** [comment]
Time is better spent working on the containerized API now.
