### ISSUE TITLE
`ledger.py` scripts improvements

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#2453]
- [ ] 1. `ledger.get_transaction(seqno)` currently walks through all transactions since the beginning of time. Instead, it could jump directly to the right chunk and verify the transaction from there. Note that this will require to find a good way to verify a chunk in isolation (e.g. reading the last signature tx from the previous chunk and re-started the Merkle tree from there). 
- [x] 2. When the primary node is retired, it will still emit signatures until its retirement is committed. This is currently not taken into account by the `ledger` module which considers a node retired once its retirement has appeared in the ledger. This causes the ledger verification to fails when the primary node is retired.

**Comment by achamayou** [comment]
2. isn't quite right, at the moment it's still "an arbitrary number of signatures until the retirement globally commits", not necessarily one. The tool should be able to hold off considering the node as retired until it has observed global commit moving past (via signatures).

**Comment by jumaffre** [comment]
@achamayou good point.

**Comment by jumaffre** [comment]
You're right. We'd need to also find the latest snapshot before that chunk. We haven't had any request to add this in the ledger tooling so I'll close this for now.
