### ISSUE TITLE
Inconsistent requirement of --constitution and --gov-script arguments

### ISSUE THREAD

**Issue by lynshi** [microsoft/CCF#2458]
**Describe the bug**
When using `start_network.py`, both the `--constitution` and `--gov-script` arguments are required, even though only one of the two should be required. The code makes assertions for both: https://github.com/microsoft/CCF/blob/f16909a0468b951069f87f6047aa08021caf3e0d/tests/infra/network.py#L362

Further, `cchost` seems to require `--gov-script`, even though using a JavaScript constitution should be enough: https://github.com/microsoft/CCF/blob/f16909a0468b951069f87f6047aa08021caf3e0d/src/host/main.cpp#L356

**Environment information**
CCF 0.99.0

**Comment by achamayou** [comment]
@lynshi this is a very transient state of affairs while both mechanisms are enabled, --gov-script will disappear shortly as the Lua governance engine is removed.

**Comment by lynshi** [comment]
Yep, I understand - just pointing it out in case you plan on a 0.99.1, in which case it would be nice to have it fixed (e.g. we'd have to preserve `--gov-script` even when we complete the JS migration). If we go straight to 1.0 with Lua removed then this is irrelevant.

**Comment by achamayou** [comment]
Fixed by #2465
