### ISSUE TITLE
Investigate "Invalid nonce, possible replay attack" messages in node-to-node channels

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#2492]
We've seen several instances of "Invalid nonce, possible replay attack" log failure messages in some of our tests, usually around node shutdown. It isn't clear how this can actually happen as nodes communicate over TCP, and this doesn't seem related to https://github.com/microsoft/CCF/issues/2358 as the replayed nonce is high enough that it has been emitted by the same node. 

Example output:
```bash
2021-04-16T06:13:50.801995Z 100 [fail ] ../src/host/node_connections.h:379 | Unknown node connection a5b94e30fe90df766103fc58d83131ddb8f4905961816e678893e8c426b66874

2021-04-16T06:13:50.829694Z -0.001 0 [fail ] ../src/node/channels.h:142 | Invalid nonce, possible replay attack, from:534f7ce567cc7611ab7785dd439ff4b2da63d9c7d68706b117ac4a49b373799d received:945500, last_seen:945505, recv_nonce.tid:0

2021-04-16T06:13:50.829697Z -0.001 0 [fail ] ../src/node/channels.h:407 | Failed to verify node message from 534f7ce567cc7611ab7785dd439ff4b2da63d9c7d68706b117ac4a49b373799d
```

**Comment by jumaffre** [comment]
I've got a local repro with the `committable_suffix_test`, which also happened on the instrumented CI: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=24134&view=logs&j=383d248c-4494-5797-d98f-6cef5140601e&t=bbcdfa66-260b-5619-96df-9537b476c35e&l=12083. Investigating now.

**Comment by jumaffre** [comment]
OK. I think I understand how this is happening: messages exchanged between two nodes can be processed out-of-order around election time. This is because nodes create outgoing host connections to other nodes (including the previous primary, which they already have an inbound connection to) when they become candidate. Because of this, if the previous primary was unreachable at the time of the election (e.g. flaky network or node suspended), messages sent on the outgoing channel can be received _after_ the messages sent after the election completes, because the primary's host can process incoming network messages in any order. 

This is roughly what happens in the `committable_suffix_test`. The primary `0` is suspended and node `2` becomes candidate, creating an outgoing host connection with `0`. Messages are then sent by `2` to `0`, incrementing the send nonce on that channel to `125`. When `0` resumes (let's assume it still is primary for simplification), node `2` becomes follower, closes its outgoing channel to `0` and sends some messages to `0` over the incoming host connection. These more recent messages get processed by `0` first, and when the older messages sent over the outgoing channel are eventually processed, they don't respect the monotonic nonce condition on the receiving node-to-node channel. 

Mandatory mermaid diagram:
![image](https://user-images.githubusercontent.com/42961061/116089879-2ec90600-a69b-11eb-913b-80b9fbe8309a.png)

The first solution that comes to mind would be to limit the number of host connections between nodes to one at any given time. I'll need to think about this a little more to check it is the best fix.

**Comment by wintersteiger** [comment]
That, or we could allow multiple channels too. I think I prefer the single host connection though.

**Comment by jumaffre** [comment]
@wintersteiger I also prefer the single host connection rather than two channels for each direction. I thought I had a quick fix for it in #2510 but some tests are still failing. Investigating this further now.

**Comment by wintersteiger** [comment]
I think we still need the `outgoing` flag, but we don't want the `ccf::add_node` ringbuffer message that `set_outgoing` sends. Also, we could check that `peer_hostname` and `peer_service` haven't changed, just to make sure.

**Comment by jumaffre** [comment]
As discussed with @wintersteiger, we believe that what happens is a legitimate scenario and that there's no immediate fix for this. In particular:
- With the current design of the node-to-node channels, we don't want to rely on an existing incoming connection when a node becomes candidate: nodes should manage the lifecycle of their node-to-node connections and keep them alive until they are not needed.
- There are already many ways replayed messages may be processed by CCF (e.g. malicious host) and we don't print a `LOG_FAIL` message for each of those.

The fix for this is simply to downgrade the `LOG_FAIL` message to `LOG_TRACE` (see https://github.com/microsoft/CCF/pull/2510). We may want to revisit this in the future if we find other limitations in the current node-to-node channel design.
