### ISSUE TITLE
It is difficult to audit historical governance changes, as accepted proposals are automatically removed

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#252]
When a governance proposal is successful, it is automatically removed from proposals table:

`memberfrontend.h : complete_proposal`
```
// if the vote was successful, remove the proposal
proposals->remove(id);
```

This means a member cannot discover the outcome of a proposal by querying the running service, they must examine the ledger and reconstruct the history.

The normal behaviour should be to retain all proposals, and add an enum indicating their current status (`Open`, `Accepted`, `Closed`). Where the proposer can currently unilaterally remove a proposal, they should only be able to close it to further votes.

To avoid large KV memory bloat, we may need to add a separate path to actually remove proposals. This could be only available to the proposer, or to any member, or we could require it to go through a governance process too.

Its also a sensible area to add request size limits - proposals should only be X characters at most, votes at most Y characters - and these limits are themselves subject to governance. This will lead to some very amusing governance deadlock situations, where the members make the rules so restrictive that they can't change the rules.

**Comment by olgavrou** [comment]
What is the difference between an accepted and a closed proposal? 

I think it would be a good idea to separate the closed proposals from the open ones, and if a member wants to look at the closed ones it should be a separate RPC. If the number of proposals increases, it will become difficult to find the ones that you want to vote on if you run "display proposals" and get all of them back.

**Comment by eddyashton** [comment]
An accepted proposal passed a quorum of votes, and the proposed changes were made. A closed proposal was abandoned, the proposer retracted it, it will no longer accept votes.

The RPCs which retrieve proposals are the general `query` and `read` RPCs - these will only return the full list if asked for. To retrieve only active proposals, we'd only need a small change to the `memberclient`'s `read_proposals` script - iterate through all proposals, only return those where status == Open.

**Comment by achamayou** [comment]
We ought to rename Closed to Rejected or something clearly distinct from Accepted.
