### ISSUE TITLE
Document all public helper _v1 interfaces

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2520]
Although they are contained in BaseEndpointRegistry and therefore relatively easy to scan once found, they are currently missing from documentation.

**Comment by eddyashton** [comment]
I think these APIs are already covered in the docs: https://microsoft.github.io/CCF/main/build_apps/api.html#_CPPv4N3ccf20BaseEndpointRegistryE

**Comment by achamayou** [comment]
Indeed they are, I grepped for them in the rst and did not consider the possibility we'd added the entire class. Oh well.
