### ISSUE TITLE
Rare non-deterministic memory leak reports

### ISSUE THREAD

**Issue by wintersteiger** [microsoft/CCF#2557]
Occasionally I see test failures because of memory leaks:

```
43: 10:33:52.024 | ERROR    | infra.remote:log_errors:86 - Contents of /data/cwinter/CCF/build/workspace/rotation_test_0/err:
43:
43: =================================================================
43: ==12445==ERROR: LeakSanitizer: detected memory leaks
43:
43: Direct leak of 16 byte(s) in 1 object(s) allocated from:
43:     #0 0x4d2473 in __interceptor_malloc (/data/cwinter/CCF/build/cchost+0x4d2473)
43:     #1 0x7f9e27e53219  (<unknown module>)
43:
43: Indirect leak of 30 byte(s) in 1 object(s) allocated from:
43:     #0 0x4bcdc0 in __interceptor_strdup (/data/cwinter/CCF/build/cchost+0x4bcdc0)
43:     #1 0x7f9e27e53274  (<unknown module>)
43:
43: SUMMARY: AddressSanitizer: 46 byte(s) leaked in 2 allocation(s).
```

This particular one was reported by the rotation_test. I believe this means that ASAN detected a memory leak in a 3rdparty or system library (or at least it thinks so). It's non-deterministic and infrequent and I don't have a way to reliably reproduce it. Grepping for `strdup` in 3rdparty says the only uses of `strdup` are in quickjs, but it could also be in OE I suppose.

**Comment by achamayou** [comment]
Do these failures occur on the main branch?

**Comment by wintersteiger** [comment]
I think so, but I didn't keep track of where/when they happen, so I can't swear by it.

**Comment by achamayou** [comment]
Ok, let's try to get a repro on main then, otherwise there's not a lot of benefit to this ticket.

**Comment by achamayou** [comment]
Let's re-open this if/when it's confirmed on main.
