### ISSUE TITLE
URL-encoded query parameters cause forwarding errors, and forwarding errors cause clients to hang

### ISSUE THREAD

**Issue by lynshi** [microsoft/CCF#2587]
**Describe the bug**
When passing a query parameter requiring URL encoding (e.g. `messsage=Hello%20World`), the following messages shows up in the primary's logs:
```
2021-05-11T20:07:23.185070Z -0.001 0   [fail ] ../src/node/rpc/forwarder.h:166      | Invalid forwarded request
2021-05-11T20:07:23.185130Z -0.001 0   [fail ] ../src/node/rpc/forwarder.h:254      | Failed to receive forwarded command
```

Additionally, no response is returned to the client when this happens, causing the client to hang.

**To Reproduce**
1. Start a multi-node CCF network with an endpoint accepting a string query parameter.
2. Call the endpoint on a secondary node, passing a value requiring URL-encoded characters for the string query parameter.

**Expected behavior**
1. The request is forwarded correctly to the primary.
2. In the event of forwarding errors, an HTTP error should be returned to the client.

**Environment information**
CCF 1.0

**Comment by achamayou** [comment]
Repro in #2588

As spotted by @eddyashton, this is happening because we first de-serialise a request, and re-serialise it in canonical form before forwarding it on when we do decide to forward it. That process does _not_ urlencode parts of the url that have been urldecoded.

**Comment by achamayou** [comment]
There are two plausible solutions:

1. Apply a url encode pass to the url when canonicalising. This may not be optimal when forwarding, but is clearly necessary for correctness when canonicalising for the purpose of signature verification.
2. Save the original request in full, which we don't do now (fragments go through the parser and populate various elements of the http rpc context but aren't saved), and re-forward that. That will lead to additional memory consumption in general though (when we don't need to forward), and does not help when checking signatures.

In the short term I think we want to look at 1. and create a patch for 1.0.

**Comment by achamayou** [comment]
Looked into 1., and it turns out it is not in fact correct because there _isn't_ a canonical way to encode a URL. Space generally encoded as `%20`, but `+` is also widely accepted.

I don't think we need to save the request in full, but saving the original URL does seems unescapable.

**Comment by achamayou** [comment]
Brain-dump of what seems like the right solution, to be picked up tomorrow:

1. Do not decode in endpoint, rather pass the raw query and fragment to the HttpRpcContext constructor
2. Decode there, keep encoded originals
3. In HttpRpcContext::canonicalise(), use the originals, do not forget to add fragment back (*)

(*) We do now, which is very incorrect and would break a signed request with a fragment in a most annoying way.

**Comment by achamayou** [comment]
A few refinements on this:

1. HttpRpcContext.get_serialised_request() should _not_ canonicalise the request. It does so for historical reasons, but this is incorrect when forwarding, because it results in some content being dropped on forwarded requests only:
  a. fragment
  b. unsigned headers
2. fragment is not part of signed content in any event, but should be forwarded nonetheless.
```
# Trim URL to just the ":path" pseudo-header
# https://tools.ietf.org/html/rfc7540#section-8.1.2.3
url=${url#*//} # Remove protocol
url=/${url#*/} # Remove domain name, restore leading slash
url=${url%\#*} # Remove fragment
If the header field name is `(request-target)` then generate the
       header field value by concatenating the lowercased :method, an
       ASCII space, and the :path pseudo-headers (as specified in
       HTTP/2, Section 8.1.2.3 [7]).  Note: For the avoidance of doubt,
       lowercasing only applies to the :method pseudo-header and not to
       the :path pseudo-header.
The ":path" pseudo-header field includes the path and query parts
      of the target URI (the "path-absolute" production and optionally a
      '?' character followed by the "query" production (see Sections 3.3
      and 3.4 of [RFC3986]).
```
