### ISSUE TITLE
js: Disable validity period checking in ccf.isValidX509CertChain

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#2603]
With OpenSSL as backend, the current time is used during chain validation, while for mbedTLS time is not checked. `ccf.isValidX509CertChain` should not check the time as this is a separate concern from chain validation. Checking details of individual certificates like time, but also CN or other things, is a potentially very customized policy and this should be done in a separate function.

**Comment by wintersteiger** [comment]
That function currently calls into `Verifier::verify_certificate`, which of course verifies everything. Are you saying that you want a new function that checks only the signatures and nothing else, or is this just about the expiry time (which can be disabled via the `ignore_time`  flag to `verify_certificate`)?

**Comment by letmaik** [comment]
I don't need this anymore so I would defer this until someone asks for it. The current behaviour, assuming OpenSSL, is a safe default.
