### ISSUE TITLE
Group options to `cchost`

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#2604]
There are a lot of options to `cchost`, and their order is mostly determined by when their feature was added. We should reorder these to highlight the more important args, and group them into different sections in the help (`Enclave`, `Node identity`, `Node config`, `BFT`).

**Comment by achamayou** [comment]
@eddyashton in light of #2612, I don't think this is as important, although we do need to think how to document the JSON config and having named sections would definitely be an excellent thing there.

**Comment by achamayou** [comment]
Part of #2612.
