### ISSUE TITLE
Investigate possible symbol conflicts in evercrypt and mbedtls

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#261]
This PR (https://github.com/microsoft/CCF/pull/257/files#diff-6d0d37a144e86c5baa1373d60d572068) fixes the problem of CCF crashing when PBFT is ON with this SAN message:

AddressSanitizer:DEADLYSIGNAL
=================================================================
==97801==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000008de1a8 bp 0x7ff9eddfe1c0 sp 0x7ff9eddfdec0 T8)
==97801==The signal is caused by a READ memory access.
==97801==Hint: address points to the zero page.
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.

This get's thrown by the call of the evercrypt method in the PBFT keypair.h implementation

> void EverCrypt_Ed25519_sign(uint8_t *signature, uint8_t *secret1, uint32_t len, uint8_t *msg)

**Comment by achamayou** [comment]
We do not use mbedtls with everest mods anymore, so we can close this for now.
