### ISSUE TITLE
Join protocol is not robust to primary retiring after Pending but before Trusted

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2610]
This one of the problems highlighted by #2606, the following sequence fails:

1. Joinee sends initial join RPC to Primary
2. Joinee receives Pending status
3. Joinee polls Primary
4. Transaction causes Joinee's state to advance to Trusted in KV and Primary to become Retired
5. Joinee continues to poll ex-Primary
6. ex-Primary fails to forward join RPC because node-to-node channel to new primary may not exist

The ex-Primary does not in fact need to forward the RPC in this case: it is a pure read. The secrets sequence it will return may be somewhat outdated at this point, but the new primary will have use the on-ledger distribution mechanism if a rekey has taken place.

As proposed by @eddyashton, the join handler can be modified to be NeverForward to solve this issue: when the node is primary it can successfully execute both write and read variants. When it isn't, it can execute the read variant and send a HTTP redirect if possible in the write case.

This should be testable by passing a combined Primary Retire + Trust Node proposal.

**Comment by jumaffre** [comment]
This will also involve extending the join client logic to follow HTTP re-directs.

**Comment by achamayou** [comment]
Yes, good point. I think we can fix and test the situation where only the second half of the join fails (ie. the read only operation) with the combined proposal.

To test the re-direction, we need instead to start the node by pointing it to an already retired primary.
