### ISSUE TITLE
Move cchost configuration from CLI/TOML to JSON configuration

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2612]
Implementing #2521, it has become increasingly apparent that we are stretching CLI11's abilities. For each interface, that we think would ideally be named, we need to specify a local address, a public address, a soft quota and a hard quota.

While this is all possible with comma separated values, like member info, it's not particularly readable. We suspect there may soon be a requirement for policy assigning certain frontends to certain interfaces (eg. /members is only accessible through the admin interface), which will add to the situation.

CLI11 doesn't have great options for nesting things further, and after discussion we've narrowed things to a couple of possibilities:

1. go to a JSON config file. This entails a one-time conversion from existing CLI or TOML configs, and would preclude the use of inline comments. On the plus side, this is a format we already handle, so we would be net negative in terms of code/dependencies, and passing on that config to the KV as a "node_cfg" akin to "user_data" would be trivial. This may become subject to a flexible policy validation step during join in the future (eg. a `validate_node_config()` defined in constitution).

2. stick with TOML for config, but lose the limited CLI, toml++ (https://marzer.github.io/tomlplusplus/) is a plausible option. This could be made completely compatible with the current config format, and while nesting isn't quite nice as in JSON it still works well enough for our purposes. There's no TCB impact, this remains host-side only, but it's another dependency. Because the config can be serialised to JSON, storage in the KV and policy still can be done, if somewhat more indirectly.

After discussion with @eddyashton, @jumaffre and @lynshi, we have decided to go for option 1.

**Comment by jumaffre** [comment]
List of remaining tasks once #3209 is merged (the PR is already too large):
- [ ] Merge `{"hostname": "...", "port": "..."}` to `host:port` (requires substantial refactoring)
- [ ] Size and time strings (+ remove unit from entry name)
- [ ] JSON schema

**Comment by jumaffre** [comment]
Closing this issue as most of the work is now done. Follow-up work is now in #3354.
