### ISSUE TITLE
Distinguish UNKNOWN/PENDING from INVALID in historical queries wrapper

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2640]
We have unfortunately not versioned `ccf::historical::adapter`, so I think we will:

1. rename `ccf::historical::adapter` to `ccf::historical::adapter_v1`
2. alias `ccf::historical::adapter` to `ccf::historical::adapter_v1`
3. add a `ccf::historical::adapter_v2` that returns different errors on UNKNOWN/PENDING and INVALID

**Comment by achamayou** [comment]
After discussion with @letmaik, the proposal is that we return either:

- 404 with `TransactionPendingOrUnknown` and `No-Cache`
- 404 with `TransactionInvalid`

**Comment by letmaik** [comment]
There is a further detail here, which is the cache-not-ready response:
https://github.com/microsoft/CCF/blob/ce877fcbb3451930fbb784dd8b054027d1f406da/include/ccf/historical_queries_adapter.h#L132-L146

Does it make sense to add this to the first 404 case?

**Comment by achamayou** [comment]
@letmaik do you mean set a Retry-After?

**Comment by letmaik** [comment]
No, it's just another case not captured in this issue but which clients have to consider.

**Comment by achamayou** [comment]
I don't understand, what's the other case not captured by this issue? The snippet you posted is for transaction that are valid, but which we are still fetching. It's a 200.

This issue is about adding nuance to the "not committed (yet)" case, to differentiate "not committed yet, as far as we know" from "can never commit". Am I missing something?

**Comment by letmaik** [comment]
Nevermind, 202 is fine for that case, even though I think the payload shouldn't be a plain-text string.

**Comment by achamayou** [comment]
@letmaik happy to look at alternative payload proposals.
