### ISSUE TITLE
Transition to trusted state upon join transaction

### ISSUE THREAD

**Issue by wintersteiger** [microsoft/CCF#2641]
The transition to the trusted state should happen when the join transaction is globally committed.

**Comment by achamayou** [comment]
Specifically, the motivation for this is to ensure that the full proposal + voting history for all nodes that received the ledger secrets in captured in the ledger. At the moment, the transaction setting nodes to "Trusted" can be rolled back, which would ultimately prevent the node from joining, but result in a ledger that does not capture the tie-breaker vote and decision to send the secrets.

**Comment by achamayou** [comment]
This is true in the two-transaction reconfiguration, but can't the case in the single transaction reconfiguration, since that transaction must commit in both configurations.

**Comment by achamayou** [comment]
#2899
