### ISSUE TITLE
JSON RPC error codes are manually duplicated in Lua

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#265]
We have a list of JSON RPC error codes. Some are standard and some are CCF-specific. Currently all Lua apps create an `error_codes` table in their `__environment` setup script which maps the same numbers to values accessible to Lua. These tables need to be manually kept in-sync.

It would be better if this was done automatically. Either `luageneric` or `txscriptrunner` should be able to inject the current error codes into the Lua environment via the `XX_ERROR_CODES` macro.

The error codes are also redefined in `jsonrpc.py`, but I don't see any easy way to keep these in sync. Perhaps the JSON clients shouldn't expect to know the error code _number_, which may need to change, but should look for the expected error name in the prefix of the error message.

**Comment by achamayou** [comment]
A solution might be to expose them through an RPC (which hopefully wouldn't fail!), and have the jsonrpc client initialise a map of those once, early on.
