### ISSUE TITLE
Provide details on HTTP parse failures rather than just close the connection

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2652]
Upon failing to parse an HTTP request, we currently close the connection. We do not want to log details, to avoid impacting confidentiality, but we could assemble an HTTP response with details and send it back. Users will hopefully be able to either interpret or report this response, suitably sanitised if necessary.

Additionally, we want to log failures to parse forwarded requests in a distinct way, so we can detect if our re-serialisation is causing problems in some contexts.

**Comment by eddyashton** [comment]
Forwarded requests will already log a distinct error message. If `http::Parser::execute()` throws, then on a normal request path this is caught in `HTTPEndpoint::recv_`, whereas in the forwarded path its caught in `Forwarder::recv_forwarded_command` (I think: `make_fwd_rpc_context` -> `make_rpc_context` -> `parser.execute`). So returning details of the parsing error in the normal path is straightforward, but doing this in the forwarded path may need some thought.
