### ISSUE TITLE
Add support for JWT `ES256` signature algorithm

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#2658]
Currently, only `RS256` is supported. `ES256` is ECDSA with SHA-256 and is the other commonly used JWT signing algorithm.

**Comment by achamayou** [comment]
@letmaik is there a particular use case for this?

**Comment by letmaik** [comment]
Not at this time.

**Comment by achamayou** [comment]
Closing for now, since there is no immediate demand for this.
