### ISSUE TITLE
Stop keeping track of destroyed node-to-node channels

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#2673]
We currently keep track of destroyed node-to-node channels (i.e. replace the `std::shared_ptr<Channel>` with `nullptr` in the channels map, instead of simply deleting the `NodeId` key). 

We should try to fix, considering what may potentially break in some end-to-end tests (e.g. code update, reconfiguration).

**Comment by achamayou** [comment]
Link #2672

**Comment by eddyashton** [comment]
This was done as part of #2801. In moving `NodeToNodeChannelManager` to its own file, we also removed the `destroy_channel` paths which filled the map with tombstone null pointers.
