### ISSUE TITLE
LTS compatibility test does not cope with release tags

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#2699]
When creating a new release from a release branch, the Azure DevOps environment does not know about the local branch (rightly so) but only the tag name (e.g. `ccf-1.0.4`). As we use the local branch name for many things (e.g. detect the major version number or detect whether we are on a release branch), this is effectively not right for release jobs.

The current workaround for the `1.x` branch is simply to hardcode the version number (see https://github.com/microsoft/CCF/pull/2698).

**Comment by achamayou** [comment]
That needs fixing for 2.x one way or another.
