### ISSUE TITLE
Initial memory allocation for PBFT Replica should be encapsulated by ePBFT

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#270]
Right now we pre-allocate all the memory we think an ePBFT replica will need before we create one:

int mem_size = 40 * 8192;
mem = (char*)malloc(mem_size);
mem = (char*)malloc(mem_size);
bzero(mem, mem_size);
bzero(mem, mem_size);

The size should be set somewhere (e.g. a configuration file similar to what oe does in oe_sign.conf) and the memory allocation should be done by ePBFT on replica initialization.

**Comment by ashamis** [comment]
This is not being used, it will deprecated in the future.
