### ISSUE TITLE
BFT Reconfiguration: state transitions on joiner in KV, in AFT, logging + testcase

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#2723]
Add new learner states and the 2-tx state transition logic to the consensus. Add more logging for debugging purposes and tests that exercise the new logic.

**Comment by wintersteiger** [comment]
Add new learner states and the 2-tx state transition logic to the consensus. Add more logging for debugging purposes and tests that exercise the new logic.

**Comment by wintersteiger** [comment]
Addressed by #2740
