### ISSUE TITLE
BFT Reconfiguration: Switch AFT to new config on local commit of UpToDate quorum (rewrite all nodes as Trusted)

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#2726]
Upon a promotion RPC, the primary checks whether there are enough up-to-date LEARNER and TRUSTED nodes in the next configuration, it promotes all LEARNERs to TRUSTED, on which the switch to the next configuration depends.

Questions: Unclear what happens when there are no learners (e.g. only retirements, see also #2731)

**Comment by achamayou** [comment]
Done in #2899 (the solution is: all nodes send ORCs, not just learners).
