### ISSUE TITLE
Old CLI11 version

### ISSUE THREAD

**Issue by maradionov** [microsoft/CCF#2774]
**Describe the bug**
Seems to me you use CLI11 without this fix: https://github.com/CLIUtils/CLI11/pull/491/files , so TOML files with lists don`t work

**To Reproduce**
Just use  toml file as config like this:
```
[start]
constitution = ["a","b","c"]
```
**Expected behavior**
Get ```'a' 'b' 'c'``` parsed names, but I get ```'a' '' 'b' '' 'c'```

**Environment information**
release 1.0.5 docker image

**Comment by eddyashton** [comment]
There is not a CLI11 release with this fix in - the last release was [v1.9.1](https://github.com/CLIUtils/CLI11/releases/tag/v1.9.1) on June 20th 2020, and this fix went in July 28th 2020. We'll update to a release with this fix in once it is available.

**Comment by achamayou** [comment]
https://github.com/CLIUtils/CLI11/releases/tag/v2.0.0
