### ISSUE TITLE
Better format for JSON byte arrays

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#278]
JSON lists of bytes are unreadable. Many of the large arrays we're passing around are really PEMs - these should be passed as strings. Where we have legitimate binary blobs (quotes), they could still be hex-encoded for easier reading/editing.

**Comment by eddyashton** [comment]
#1374 converts our byte-array certificates to JSON strings containing PEM-encodings, but doesn't touch quotes. We should hex- or base64-encode these as well.

**Comment by achamayou** [comment]
`/user_id` needs fixing, it returns a vector of bytes right now, where users expect a PEM string: https://github.com/microsoft/CCF/blob/master/doc/schemas/gov_openapi.json#L1141

**Comment by achamayou** [comment]
List of places in the API that still use vector of bytes that are effectively lists of integers in JSON:

- [ ] receipts
- [ ] ack/update_ack (digest)
- [ ] scripts, when using bytecode

**Comment by achamayou** [comment]
Remaining work captured in follow up tasks listed above.
