### ISSUE TITLE
Add second snapshot directory option to `cchost`

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#2784]
Since only the primary node generates snapshots but all nodes will want to make use of snapshots for historical queries (once #1705 is done) and to determine the longest ledger in a recovery scenario, operators should be able to give each node a shared volume for committed snapshot files. 

I can see two options for this:
1. snapshot-dir/read-only-snapshot-dir for consistency with the existing ledger-dir/read-only-ledger-dir scheme for the ledger files, leaving it up to the operator to copy committed files from one to the other.
2. Have `cchost` automatically copy committed snapshot files from one directory to the other (i.e. snapshot-dir/committed-snapshot-dir naming scheme). 

I prefer option 1. for consistency and because operators will have already built a similar monitor/copy process for committed ledger files. It also avoid having the single-threaded `cchost` copy potentially large snapshot files (unless we make use to [libuv's thread pool](http://docs.libuv.org/en/v1.x/fs.html)). I believe this is also @msftsettiy's preferred option.

**Comment by msftsettiy** [comment]
I agree with option 1.
