### ISSUE TITLE
Node certificate should include unique node ID in Common Name field

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#2794]
Nodes currently only include a generic "`Subject: CN = CCF Node`" in their x509 certificate. To be more precise here, we should also include their unique node ID.

**Comment by jumaffre** [comment]
It turns out that the subject name in x509 is limited to 64 characters, which is too short to include the `CN=` prefix as well as the SHA256 hex-encoded node ID (64 characters).

We could include a shorter hash (e.g. first 32 characters) but it seems inconsistent with the rest (we always use complete node IDs to refer to them, e.g. logs, KV). Thoughts?

**Comment by achamayou** [comment]
Since we don't have a way to include the full ID and CN is deprecated and largely unused anyway, I suggest we keep it the way it is.

**Comment by jumaffre** [comment]
Agreed. Other systems (e.g. docker, git) also use short ids (first 10 characters of the hash) but we haven't seen a use for those yet. The node ID for a given TLS server can already be queried with the `/node/network/nodes/self` RPC anyway, so I'll close this issue.
