### ISSUE TITLE
BFT: KV For-each does not always return results in a deterministic order

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#2814]
The CHAMP map is an unordered collection and thus if entries are added to it in a different order on different replicas and then the map is iterated over (via a foreach) the order in which the user code will observe the results could be different. If the client code depends on the ordering then the replicas will execute a request in a non-deterministic manner. We can see this issue occur with multithreading or in single threading if replicas have a mix of loading from different checkpoints and executing requests from the start of time.

There are multiple solutions including replacing the CHAMP map, presorting the results for a foreach before exposing them to the client code, etc.

**Comment by achamayou** [comment]
Next step: measure the impact of switching to the RB Map, on Coffee Lake and Ice Lake.

**Comment by jumaffre** [comment]
Useful snippet from the `map_bench` benchmark output, with dimensions selected for most speed impact. The RB map is about 50% slower for `put()`, 25% slower for `get()` and 100 times as slow (!) for `foreach()`. 

```
put:
===============================================================================
   Name (baseline is *)   |   Dim   |  Total ms |  ns/op  |Baseline| Ops/second
===============================================================================
       bench_rb_map_put * |     128 |     0.140 |    1092 |      - |   915587.2
      bench_champ_map_put |     128 |     0.064 |     500 |  0.459 |  1996879.9
===============================================================================
get:
===============================================================================
   Name (baseline is *)   |   Dim   |  Total ms |  ns/op  |Baseline| Ops/second
===============================================================================
       bench_rb_map_get * |     512 |     0.051 |     100 |      - | 10000000.0
        bench_rb_map_getp |     512 |     0.048 |      92 |  0.930 | 10756302.5
      bench_champ_map_get |     512 |     0.013 |      25 |  0.250 | 40000000.0
     bench_champ_map_getp |     512 |     0.004 |       8 |  0.082 |121904761.9
===============================================================================
foreach:
===============================================================================
   Name (baseline is *)   |   Dim   |  Total ms |  ns/op  |Baseline| Ops/second
===============================================================================
   bench_rb_map_foreach * |    1024 |    13.801 |   13477 |      - |    74195.3
  bench_champ_map_foreach |    1024 |     0.137 |     134 |  0.010 |  7458066.6
===============================================================================
```

I'll look at our existing end-to-end tests next.
