### ISSUE TITLE
Path-templated endpoint lookup is surprisingly slow

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#2913]
A blind spot in our perf tests is the impact of path-templated endpoints. These go through a much slower path than direct lookup, which is even worse for JS endpoints. We should build a perf test to measure the slowdown here, and find a fix.

Some low-hanging fruit from a quick code scan:
- Don't call `find_endpoint` twice, when we know the BFT path isn't active.
- Add a `foreach` variant that doesn't deserialise values, so we can avoid expensive deserialisation for values we don't use.

**Comment by achamayou** [comment]
We've applied obvious optimisations, the next step would be to construct a prefix tree for large applications.

**Comment by eddyashton** [comment]
This was mentioned a while ago but I don't think on GitHub, so just adding a link here for posterity:

[r3](https://github.com/c9s/r3) looks like a good library for handling that prefix trie dispatch for us.
