### ISSUE TITLE
CCF plugins

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#2935]
CCF does not have a plugin system currently. A consequence is that less often used components are part of the main distribution even though they shouldn't be, for example the JS bindings to Open Enclave, or various built-in endpoints. Not being able to opt-out of unused components is undesirable as it unnecessarily increases the TCB. On the other side, apart from forking CCF, there is no way to add more native functionality to CCF, for example additional JS bindings to native libraries within `js_generic`.

The goal is to eventually support at least the following two plugin types:

- [x] [JS FFI plugins](https://github.com/microsoft/CCF/issues/2970)
- [ ] Endpoint plugins
- [ ] Auth plugins (?)

There are a few questions to answer when implementing this:

- Format: Static vs. shared libraries
- Registration: Discovery and activation of plugins
- Compatibility: CCF version, compiler version and flags

To get there, the focus will initially be on JS FFI plugins. As a first step, there will merely be new build flags for enabling/disabling the Open Enclave JS bindings. After that, a separation into a proper plugin can be done. And eventually, the plugin should live in its own stand-alone folder, for now in this repository, but in the future in a separate one.

**Comment by achamayou** [comment]
Not going to add substantial new user APIs before container re-design.
