### ISSUE TITLE
Remove `cmake/lvi` folder?

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#2941]
https://github.com/microsoft/CCF/blob/main/cmake/lvi/README.md mentions:

> To use the OE-defined LVI mitigations requires this fix:
https://github.com/openenclave/openenclave/pull/3285

This PR is merged and is part of OE since a while. Can the duplicated scripts be removed?

**Comment by achamayou** [comment]
@letmaik as soon as an OE release including this change becomes available (ie. not yet), we can remove these scripts.

**Comment by achamayou** [comment]
It's because I cannot tell 2020 from 2021 apparently, mea culpa.
