### ISSUE TITLE
Inconsistent CMake between samples

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#2942]
The CMakeLists.txt of the `nobuiltins` sample is not self-contained (it misses `find_package(ccf REQUIRED)` etc.), as opposed to the logging sample. 

I see that the root CMakeLists.txt handles the samples differently, likely due to the above:

https://github.com/microsoft/CCF/blob/3713c7c9d3178f6cf8c1e07894818829f562e114/CMakeLists.txt#L237-L245

What is the value of not having the `nobuiltins` sample self-contained?

**Comment by achamayou** [comment]
That's also not obvious to me, I think this may be an unintentional omission, but @eddyashton may have a better idea.

**Comment by eddyashton** [comment]
I agree these should be consistent, not sure why they're not. I'd prefer if we could use the `add_subdirectory` approach for both (as it avoids duplicate calls to `add_ccf_app` and `sign_app_library` in the self-contained and project-wide CMake), but it looks like that conflicts with having a neatly self-contained sample app? I think having a self-contained CMake is more important, if we have to choose.
