### ISSUE TITLE
Document/remove `BETTER_EXCEPTIONS` in CMake

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#2944]
https://github.com/microsoft/CCF/blob/3713c7c9d3178f6cf8c1e07894818829f562e114/CMakeLists.txt#L15

I couldn't find where this env var is used. Is it actually used?

**Comment by achamayou** [comment]
This was once necessary to enable https://github.com/qix-/better-exceptions, although now that we use loguru, it may no longer be useful. I'll check.

**Comment by achamayou** [comment]
So, it doesn't do anything for us:

1. when using LOG.exception() with loguru, we get the fancy handler
2. elsewhere it doesn't help, because it's not set at runtime when executing tests.sh
