### ISSUE TITLE
Clarify or remove usage of CMake's `InstallRequiredSystemLibraries`

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#2945]
https://github.com/microsoft/CCF/blob/3713c7c9d3178f6cf8c1e07894818829f562e114/cmake/cpack_settings.cmake#L4

I can't see how this actually affects anything, in particular in relation to CPack. The `.deb` package doesn't seem to contain anything not explicitly defined.

**Comment by achamayou** [comment]
My recollection is that this was necessary to be able to link libcxx, but I may be wrong about this, and you're right that we should check.
