### ISSUE TITLE
CMake helpers `add_enclave_library_c`, `add_enclave_library`, `add_host_library` accept only a single source file

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#2959]
`files` captures a single source file and all additional arguments are thrown away. Can be fixed by using `cmake_parse_arguments`.

https://github.com/microsoft/CCF/blob/756d2178877ec382f0d7d5864da9cd3869e5953e/cmake/ccf_app.cmake#L228-L254

**Comment by letmaik** [comment]
Looking at this again, I think this is a non-issue. adding double quotes around the argument at the call-site (as all call-sites are doing it) captures all files properly in that single argument.

**Comment by letmaik** [comment]
I think it's still unfortunate as it's very easy to mess up and makes passing multiple lists of sources ugly, for example `"${CCF_IMPL_SOURCE};${CCF_GENERATED_DIR}/ccf_t.cpp"`. @achamayou What do you think?

**Comment by achamayou** [comment]
I agree this is incredibly unfortunate, and if using cmake_parse_arguments() in our (limited) cmake API surface fixes that, it seems like the right thing to do.
