### ISSUE TITLE
Change f on service opening

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#297]
Connected to #293

When running with PBFT f should start of as `f=0` so that all member rpc's are replicated across nodes. This means that PBFT trusts all the nodes before startup. 

Once all nodes are added and members audit the network and vote to open it, `f` can be set to the initial configuration value (>0) and PBFT can run its protocol as expected.

**Comment by jumaffre** [comment]
After discussing this with @ashamis, this will probably involve some changes in the ePBFT code as well as it is not yet clear/tested whether replication across all nodes will work with the current implementation of `f=0`.

**Comment by achamayou** [comment]
Not necessary, f isn't materialised.
