### ISSUE TITLE
Features to be removed after 3.x

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#2981]
- [x] 1. Snapshot evidence verification with ledger suffix
Reason: snapshots will include receipt from 2.x and all snapshots used to start 3.x nodes have to be 2.x snapshots (see https://microsoft.github.io/CCF/main/overview/release_policy.html#operations-compatibility).
- [x] 2. `ccf::historical::adapter_v1`
- [ ] 3. Ability for the Python infra to spin up 1.x nodes (including `docker_wrap.sh` script). This is only required for the LTS ledger compatibility test but could be removed if all LTS tests published a ledger/snapshot (e.g. Azure Blob Storage) which is then used by other (i.e. newer) LTS compatibility tests for ledger compatibility.

**Comment by achamayou** [comment]
@jumaffre I suggest rolling the remaining item into a "Features to be removed after 3.x" at this point.
