### ISSUE TITLE
Failed to build mbedtls on install

### ISSUE THREAD

**Issue by rengolin** [microsoft/CCF#2993]
**Describe the bug**
Following the [install doc](https://microsoft.github.io/CCF/main/build_apps/install_bin.html), I installed ansible and ran the `app-dev.yml` playbook. When building `mbedtls`, it fails with error:
```
make: *** No targets specified and no makefile found. Stop.
```

**To Reproduce**
```
cd getting_started/setup_vm/
./run.sh app-dev.yml
```

**Environment information**
Ubuntu 20.04.3
Intel W-2155 (no SGX)

**Additional context**
Full log:
```
  "changed": true,
  "cmd": "cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON .. make",
  "delta": "0:00:01.289875",
  "end": "2021-09-17 10:05:32.757398",
  "msg": "non-zero return code",
  "rc": 2,
  "start": "2021-09-17 10:05:31.467523",
  "stdout":
    -- The C compiler identification is GNU 9.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Found PythonInterp: /usr/bin/python (found version "3.8.10") 
    -- Found Perl: /usr/bin/perl (found version "5.30.0") 
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/mbedtls-mbedtls-2.16.10/build"
  "stderr":
    make: *** No targets specified and no makefile found. Stop.
```

**Comment by rengolin** [comment]
Other packages are installed, any reason why this needs to be built? Some specific version?

Now I'm building from source, and I installed `libmbedtls-dev` from packages and CCF's CMake didn't complain.

I'm guessing either it makes a difference and the CMake is wrong, or it doesn't and we could install from package inside ansible, too?

**Comment by achamayou** [comment]
We like to keep the version of mbedtls used in virtual build in sync (ie. same exact release) as the one we get from Open Enclave when using SGX, which is why we do not use `libmbedtls-dev`.

It is surprising that this fails to build, I will look into it now. Can I ask you which version of cmake you are running?

**Comment by rengolin** [comment]
Update: that is totally my fault. I have `CMAKE_GENERATOR=Ninja` on my environment, so CMake picked `ninja` instead of `make`. Perhaps this could set `CMAKE_GENERATOR` to force make files...
