### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [microsoft/CCF#30]
Would you like to add more error handling for return values from functions like the following?
- [fflush](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fflush.html "Flush a stream.") ⇒ [Ledger::truncate](https://github.com/Microsoft/CCF/blob/53352a545661165ffa27d4fa6790a7abc9a33ff9/src/host/ledger.h#L162)
- [ftello](https://pubs.opengroup.org/onlinepubs/9699919799/functions/ftello.html "Return a file offset.") ⇒ [Ledger constructor](https://github.com/Microsoft/CCF/blob/53352a545661165ffa27d4fa6790a7abc9a33ff9/src/host/ledger.h#L31)

**Comment by achamayou** [comment]
Thank you for reporting this, we will add better error messages.
