### ISSUE TITLE
Unify the consensus interface

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#300]
Related to https://github.com/microsoft/CCF/issues/57.

As it stands, we currently use `raft` as consensus when building with Raft (i.e. `-DPBFT=OFF`) and `pbft` along with the `NullReplicator` to stub out some of Raft functionalities when `-DPBFT=ON`. Instead, when PBFT is enabled, the `pbft` object should be the only consensus. 

This involves incorporating all of the `NullReplicator` into `pbft` and deleting it. Changes in `nodestate.h` will also be required to clean up the different branches that we have in the code.

**Comment by olgavrou** [comment]
Next steps:

- make frontend.h consensus agnostic
- revisit consensus_msg_pbft and consensus_msg_raft NodeMsgType's

**Comment by eddyashton** [comment]
Following #302, I think we should push common operations around determining the Leader into `Conensus`, as outlined [here](https://github.com/microsoft/CCF/pull/302#pullrequestreview-274794637).

**Comment by olgavrou** [comment]
- [ ] Pbft is now writing to the Ledger and using the raft/ledgerenclave.h file. Should be also made consensus agnostic
