### ISSUE TITLE
Record recovery root in store

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#3017]
On recovery, members vote to open the service once they are satisfied with the recovered state. However, there is currently no convenient way for members to find out (and vote for) the recovered state of the defunct service. Instead, the service should record the root of the recovered service (once the ledger has been truncated to the last signature) and members should create and vote for the `transition_service_to_open` proposal with the recovered root as a new proposal argument.

For convenience, the service could return the recovery root in a new member-only endpoint. If members have access to the defunct ledger, or have previous receipts, they can verify that they are happy with the recovered root before opening the service.

**Comment by achamayou** [comment]
@jumaffre we discussed this in connection with #3082, but it wasn't clear that it was necessary to couple that `transition_service_to_open` because the proposal id binds to the root already. Members who want to record an explicit ack can do so separately. What do you think?

**Comment by jumaffre** [comment]
The proposal id binds to the root but the relationship is very opaque to members. I agree that the ACK would be sufficient though, so I'm happy for you to close this issue if you're happy with it.
