### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ThomasPluck** [microsoft/CCF#3019]
**Describe the bug**
Python dependency issues when following documentation instructions to install CCF via binaries

**To Reproduce**
On a new Azure CC VM instance with Ubuntu 18.04,
```
git clone https://github.com/microsoft/ccf
ccf/getting_started/setup_vm/run.sh ccf/getting_started/setup_vm/app-dev.yml
wget https://github.com/microsoft/CCF/releases/download/ccf-${CCF_VERSION}/ccf_${CCF_VERSION}_amd64.deb
sudo apt install ./ccf_${CCF_VERSION}_amd64.deb
/opt/ccf/bin/sandbox.sh
```

**Expected behavior**
Output:
```
No package/app specified. Defaulting to installed JS logging app
Setting up Python environment...
Python environment successfully setup
[16:10:16.552] Starting 1 CCF node...
[16:10:16.552] Virtual mode enabled
[16:10:23.349] Started CCF network with the following nodes:
[16:10:23.350]   Node [0] = https://127.0.0.1:8000
...
```
**Environment information**
New Azure CC VM instance running Ubuntu 18.04 with Standard SSD and Standard DC1s_v2

**Comment by achamayou** [comment]
Hi @ThomasPluck, I'm afraid we only target Ubuntu 20.04 (https://microsoft.github.io/CCF/main/build_apps/install_bin.html#requirements). If you would like to add support for Ubuntu 18.04 in the playbooks, your contribution will be welcome, but since we do not maintain CI infrastructure for 18.04, it will remain a "best effort" rather than fully supported target.

**Comment by ThomasPluck** [comment]
Azure CC VM's by default only provide Ubuntu 16.04 and 18.04 - running `do-release-upgrade` before installing CCF fixes the issue!

**Comment by achamayou** [comment]
@ThomasPluck can I ask what you mean by "default"? When I create a DCs VM, I get 20.04 as the default image:

![image](https://user-images.githubusercontent.com/4016369/134505166-8d841404-fecb-4c41-850a-96d443b7a8cd.png)

**Comment by ThomasPluck** [comment]
Okay, perhaps this is where I am getting confused. The way I am making my VM is the following:

1) I go to portal.azure.com
2) I press the create resource button
3) In the next page there is a search bar where I type "Azure Confidential Computing"
4) I am then redirected to the form https://portal.azure.com/#create/microsoft-azure-compute.acc-virtual-machine-v2acc-virtual-machine-v2

![image](https://user-images.githubusercontent.com/26680070/134706407-3c2d8851-8560-4cd7-932b-cde6c90bf295.png)

I then fill out what I have to and opt for Ubuntu 18.04 (which I then `do-release-upgrade` as I did in my PR).

**Comment by achamayou** [comment]
@ThomasPluck I see, thank you for reporting this, I will try to find the right person internally to fix it. Ubuntu 20.04 should be in that list, and the option to select a custom image should be available as well.

If you go through the regular "Create VM" flow (https://ms.portal.azure.com/#create/Microsoft.VirtualMachine), that restriction doesn't exist and you will be able to select 20.04 straight away.

Apologies for the confusion!
