### ISSUE TITLE
Last N lines of node log should be printed when node does not cleanly shutdown

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#303]
The end-to-end framework does not currently print the last lines of the node's log (i.e. stdout) when the node crashes. Instead, if when the node process is not terminated cleanly by the infra, we should also print the last `N` lines of the node's log as well as everything in stderr.

As we do not keep the logs of the CI runs overnight, this will be helpful to debug what caused a node crash/what the state of the node was before the crash.

**Comment by achamayou** [comment]
It's also more immediate feedback when running the tests locally than having to find the logs etc.

**Comment by eddyashton** [comment]
Resolved in #313
