### ISSUE TITLE
Snapshot evidence receipt should include hash of snapshot as public custom claim

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#3031]
Follow-up from #2958 

Once #2998 is merged, snapshots will also include the receipt of their evidence. However, there is currently no convenient way to tie this receipt to the snapshot itself. In other words, the receipt could be for another transaction in the same service (assuming someone tampering with the snapshot file), and the initial snapshot verification would pass. 

To fix this, we should make use of public custom claims (once they're implemented, see #2565) so that the hash of the snapshot itself is added as a custom claim to the snapshot evidence transaction.

**Comment by achamayou** [comment]
See #3348
