### ISSUE TITLE
JS: Document API stability

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3038]
https://microsoft.github.io/CCF/main/overview/release_policy.html

This covers C++ only currently. For JS, some statements should be made as well.

I'd like to take an approach similar to how globals in Node.JS / W3C Web APIs work and are evolved, which roughly means there are no `v2` etc. suffixes. Evolving in JS is often doable in a backwards-compatible way as additional parameters can be added without breaking existing usage and/or `options` objects as last argument are used which are easier to evolve. So the promise would be that we never break old APIs, though we may deprecate and remove APIs and replace them with differently named ones, if it really is too awkward to extend/change behaviour of an existing API.

@eddyashton Does this make sense?

**Comment by eddyashton** [comment]
That sounds sensible to me. We can maintain functional compatibility without necessarily precise type/binary compatibility.
