### ISSUE TITLE
Create new class to capture history, kv and consensus

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#304]
Right now whenever another object needs to access the consensus or history (e.g. frontend needs history and consensus, history needs consensus) they access them via the kv. This means that kv (Store specifically) needs to hold and know about a lot of information it doesn't really need.

We can create a new class (DKV) that holds the triple {history, kv, consensus} and that is accessible via networkstate (same way we access network.tables right now).

Then the newly created Consensus class can be split up into Replicator (that only replicates) and be derived from it. So when we set Consensus in the DKV class it can in turn set Replicator in the KV and the KV doesn't need to know about everything in consensus.

**Comment by ashamis** [comment]
Hi @olgavrou  
has this been completed as part of the PR & merge #302?

**Comment by olgavrou** [comment]
@ashamis no this is a different CCF specific refactor that we had discussed with @achamayou related to not accessing history and consensus classes via the kv and not having the kv necessarily knowing about the full consensus instance but only what it needs, i.e. the replicator.

**Comment by achamayou** [comment]
The structure of the code has changed since this was raised, and will probably continue to change before we have time for an in-depth refactor, so I'm closing this for now.
