### ISSUE TITLE
Construction of replicatable batch can be separated from `Store::commit`

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#3114]
`Store::commit` currently does something like:

```
commit(new_tx)
{
  pending_txs.queue(new_tx);

  batch = build_contiguous_prefix(pending_txs);

  if (!batch.empty())
  {
    consensus.replicate(batch);
  }
}
```

Each call is really doing 2 things: extending a queue, and then flushing the queue to `replicate`. This is necessary because transactions may arrive at `commit` out-of-order (a transaction which has booked an earlier seqno is still serialising/whatevering), but must be passed to `replicate` (and the history) in-order. This works as long as a later transaction arrives to flush the queue, but as observed in #3104 it was possible to just queue a final entry, and never see it passed to consensus.

There's a quick fix for this in #3113.

A neater fix would be to separate out the flushing from the queuing. Since there are already cases where a call to `commit` doesn't actually begin replication, it is fine if no calls do, and instead we simply queue. We can flush on a periodic tick, or potentially during `commit` if we believe the queue has become too large. This is a fundamental change to the path that every transaction takes through the system. While there is a potential performance advantage in moving replication out of `commit` (responses can be sent to the client sooner), there is a corresponding additional latency (nothing begins replication until a tick arrives). In extreme cases, this could cause a user-visible delay in consensus commit, and even without that it may cause increased memory pressure (generally processing multiple transactions in a batch, where currently they are often flushed through individually and immediately). Beyond those performance concerns, this kind of change carries a risk to correctness, so must be carefully vetted.

We'll consider this as a useful simplification/improvement, but it is not a critical priority.

**Comment by achamayou** [comment]
We don't think the risk involved in that change is warranted by the extra readability of the code post-change.
