### ISSUE TITLE
Convert logging js app to be an npm-style app

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3141]
Context: In https://github.com/microsoft/CCF/pull/3139 a bug was fixed in the `ccf-app` npm package. The bug was not caught because tests for the historical query features only ran against the logging js app which is not using the ccf-app npm package.

Looking forward, there should only be a single supported way to develop JS/TS apps for CCF. Because of that, the logging app should be converted to an npm-style app. Doing this would exercise both the npm package and the underlying native bindings. Some things will not be tested within the logging app, so there is still a need for separate tests of those features. However, duplicating complex tests (like here for historical queries) should be avoided to reduce maintenance costs.

Given that the logging app is a sample, it probably makes sense to split it into multiple modules where the main module has the basic functionality and another module for all the advanced/extra things, just to not overwhelm people.

Note that transitioning the logging app to an npm-style app will likely have a slight impact on performance, since it will pull in some extra code from the `ccf-app` npm package. This is fine.

**Comment by achamayou** [comment]
We'll revisit samples on the other side of the container app redesign.
