### ISSUE TITLE
Support for late join after recovery

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#315]
It should be possible for a node to _late_ join a network that has crashed and successfully recovered (at least) once.

**Comment by achamayou** [comment]
This should be easy to test once the tests have been modularised, as discussed.

**Comment by achamayou** [comment]
Checked by the test_suite test, combining add_node and recovery.

**Comment by jumaffre** [comment]
This is not yet addressed. As it stands, a node joining late after recovery will only join the public network. I'll reopen.
