### ISSUE TITLE
Arbitrary ledger chunking and snapshot generation

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#3155]
The current ledger chunking logic is triggered when a ledger file size has reached a specific limit or when a snapshot will be generated for a `seqno` (always on a signature). This requires some additional logic to keep the chunking in sync between all nodes.

Instead, to be able to support the generation of snapshots at arbitrary points (e.g. at the end of the recovery procedure), it would be preferable to have a specific flag in the unprotected header of each KV entry that the host or the enclave on the primary node can flip to signal the ledger chunking on other nodes. 

Tasks:
- [x] Have the primary node set a flag in the KV entry when a new ledger chunk is created, which backup nodes should obey.
- [x] Create mechanism to force a snapshot at the next signature. 

Note that this may require #3026 first.

**Comment by jumaffre** [comment]
Notes from discussion with @wintersteiger.

Q. How to force a new ledger chunk?

- Should this be triggered via an operator/member RPC or process signal? What authorisation does it need (no DOS from arbitrary clients is acceptable)? Member RPC (expensive) or Operator RPC on specific interface?
- A new flag in ledger entry header should be set for the host to create a new chunk (so that ledger chunking is synced across nodes)
- At which ledger entry should this flat be set? All ledger chunks should end on a signature, so we would have to wait for the next signature. 
- Should we just wait for the next signature or force a new one? 

Q. How to force a new snapshot?

- Because nodes should starting from a snapshot should construct ledger chunks that are identical than the ones on the primary, - forcing a new snapshot should also force a new ledger chunk (but not the other way around).
- Similarly to forcing a new ledger chunk, how should the new snapshot be triggered? 
- Similarly to forcing a new ledger chunk, when should we force a new snapshot? Next signature as well?
- Would it be easier if snapshotter was in the kv::store? Not a blocker but would be nice (see #3026).

**Comment by wintersteiger** [comment]
The second part was done in #3544
