### ISSUE TITLE
Improve 2tx reconfiguration ORCs

### ISSUE THREAD

**Issue by wintersteiger** [microsoft/CCF#3157]
As discussed, this should be OK as long as i) nodes retry to send ORCs until they've seen their `TRUSTED`ness committed, ii) `orc_sets` (and other consensus state updated in `consensus->orc()` are flushed when a node becomes candidate. We should also try to add a test for this (end-to-end or unit test?) but it's OK to merge this PR as it is as long as the existing reconfiguration test is stable.

_Originally posted by @jumaffre in https://github.com/microsoft/CCF/pull/3097#discussion_r742005238_

**Comment by wintersteiger** [comment]
As identified in discussions, ORCs may have to be resubmitted/retried more aggressively than it is currently done. We should add tests to help us quantify that, as well as to check that there are no liveness problems.

**Comment by achamayou** [comment]
We aren't planning to use 2tx reconfig in the foreseeable future, so I will close this for now.
