### ISSUE TITLE
Nodes will not vote for new primaries in Raft if they do not know the requesting node

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#3167]
This looks like an unnecessary restriction. We believe it is safe to receive AppendEntries from an unknown node, since the header and contents are still useable (and often necessary to help this node catch up to their own joining point!). Presumably this is also true for a RequestVote.

This has an impact on liveness, since it means that a node that is catching up is _not_ a full member for consensus purposes, essentially they still count as a dead node, so the service doesn't have the fault tolerance that it may appear to have. So in the specific condition that a node is catching up, has not heard about their own join, and is counted as one of the necessary live nodes (eg - in a 3-node network), it's possible that a single node crash will kill the network.

We can add a test for this behaviour, and the fix (if safe) is simple - remove this early-out, and process RequestVotes from unknown nodes.

**Comment by jumaffre** [comment]
Another reason why it is safe to accept a RequestVote message from a not-yet-known in the KV node: to be able to receive the message in the first place, the two nodes must have established a secure channel between themselves, which can only happen if the two nodes are trusted and part of the service. In other words, a man-in-the-middle couldn't craft a malicious RequestVote message and have it processed by a catching-up node (or in fact any node).
