### ISSUE TITLE
Virtual-only build should not depend on OpenEnclave

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#319]
As is stands, a virtual-only build requires OpenEnclave to be installed as `oeedger8r` is required some interface files that the enclave relies on. Instead, the host and enclave should only depend on `ccf_v.h`. 

This will also require some changes to `oe_shim.h` so that all OE-specific calls are stubbed out properly.

**Comment by achamayou** [comment]
We’ve looked at this before, and we thought it’d take more code duplication than we’d like to have. If we think this is a big problem, let’s bring it up with the OE team and see what we can do about it.

**Comment by achamayou** [comment]
As discussed, we're going to keep this for the foreseeable future.
