### ISSUE TITLE
GenesisGenerator class should be more specific

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#320]
https://github.com/microsoft/CCF/pull/318 re-purposed `GenesisGenerator` to use it as a helper class to perform functions on the KV based on the network tables. However, the class is a little too general in scope and will require further thinking/refactoring.

No clear solution in mind yet - all ideas welcome.

**Comment by achamayou** [comment]
I think we should consider renaming GenesisGenerator to NetworkConfig or NetworkCfg. What is essentially is at this point is a class that exposes high level operations on the KV-stored config, including some we want for recovery or governance.

**Comment by achamayou** [comment]
Post #470, GenesisGen seems specific enough.
