### ISSUE TITLE
Node crash in multi-threaded run

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#3202]
The Threading pipeline is hitting failures in various tests, with the common symptom of a node terminating from a thrown exception:

```
39: infra.network.NodeShutdownError: Fatal error found during node shutdown
39/57 Test #39: reconfiguration_test_suite .......***Failed   86.37 sec
```

> https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=36261&view=logs&j=a45bc589-b130-5dc2-b16b-03ef91a336e9&t=643c4120-e5c7-597b-5ce9-cf0a315b4855&l=8632

```
40: infra.network.NodeShutdownError: Fatal error found during node shutdown
40/57 Test #40: full_test_suite ..................***Failed  130.08 sec
```

> https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=36488&view=logs&j=a45bc589-b130-5dc2-b16b-03ef91a336e9&t=643c4120-e5c7-597b-5ce9-cf0a315b4855&l=10011

```
49: Exception: ["Failure in js: NodeShutdownError('Fatal error found during node shutdown')"]
49/57 Test #49: e2e_logging_cft ..................***Failed  150.52 sec
```

> https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=36475&view=logs&j=a45bc589-b130-5dc2-b16b-03ef91a336e9&t=643c4120-e5c7-597b-5ce9-cf0a315b4855&l=19950

The common callstack before that tells us this was a `node_inbound` of size 129, and the resulting fatal error is the same size (probably the same error!):
```
[fail ] ../src/ds/messaging.h:173            | Exception while processing message <ccf::node_inbound:1097389895> of size 129
[fail ] ../src/ds/messaging.h:173            | Exception while processing message <AdminMessage::fatal_error_msg:1968599046> of size 22
```

**Comment by achamayou** [comment]
These issues have not occurred recently, possibly as a result of the upgrade to newer versions of Open Enclave that fixed thread local storage: https://github.com/openenclave/openenclave/releases/tag/v0.17.5
