### ISSUE TITLE
Does CCF support message body for GET request

### ISSUE THREAD

**Issue by divneil-intel** [microsoft/CCF#3212]
Hello,
I didn't get the right category for asking a question, so, filing under bug.
I would like to know if the CCF parses message body in GET request. 
For now, I have the understanding that it is not recommended to pass a message body in GET, because the server may choose to ignore it. So, wanted to confirm the behavior of CCF. Thanks to let me know.

**Comment by achamayou** [comment]
Hi @divneil-intel, CCF does not parse request payloads by default, though it does provide a commonly used json wrapper that can be used for that purpose.

You can always obtain the raw request body, regardless of the http verb, in the following way:

```
const std::vector<uint8_t>& content = ctx.rpc_ctx->get_request_body();
```

**Comment by eddyashton** [comment]
@divneil-intel If you are using the JSON wrapper (`json_adapter` on your endpoint handler), then this will not pass the body as the second argument to your handler for GET requests. But it can still be received with `ctx.rpc_ctx->get_request_body()`.

eg:

```
auto foo = [this](auto& ctx, nlohmann::json&& params)
{
  // params will be empty, due to the combination of HTTP_GET and json_adapter
  auto body = ctx.rpc_ctx->get_request_body();
  ...
};
make_endpoint("/foo", HTTP_GET, json_adapter(foo) ...).install();

auto bar = [this](auto& ctx, nlohmann::json&& params)
{
  // params will contain a JSON-parsing of the request body
  auto body = ctx.rpc_ctx->get_request_body(); // Can also retrieve raw body directly
  ...
};
make_endpoint("/bar", HTTP_POST, json_adapter(bar) ...).install();

auto baz = [this](auto& ctx)
{
  // No json_adapter means no attempt to parse body, can still be retrieved directly
  auto body = ctx.rpc_ctx->get_request_body();
  ...
};
make_endpoint("/baz", HTTP_GET, baz ...).install();
```

**Comment by divneil-intel** [comment]
Thanks @achamayou and @eddyashton for your quick response. It answers my question :).

I have a further question on the endpoints design (GET vs POST). I know it really depends on the context of the HTTP Server, so, I will try to be close as possible by referring the CCF example for this question.

- After some reading on the web, I get the understanding that sending payload with GET is not recommended. Even some client libraries drop the payload, so, what is the general recommendation when designing the CCF endpoint? From your above comment, I understand the CCF client is not dropping the payload. Can you pls confirm that client will continue to send it.

- From `smallbank.cpp` example, I get a feeling that the we should be using POST. Am I right to assume that it is to simplify the calling semantics of endpoints, that all are POST?
  ``
  make_endpoint("/SmallBank_balance", HTTP_POST, balance, user_sig_or_cert).install();
  ``

- What are the semantics of `make_read_only_endpoint()` with respect to verb usage and payload? 
  1. From `logging.cpp`, `make_read_only_endpoint("/log/private", HTTP_GET, .....)`, this API is taking in the GET verb, so, thought of confirming, is it to maintain API signature same as `make_endpoint()` or does it accept other verbs too?
  2. I believe this endpoint still allows to retrieve message body with `get_request_body()`?
  3. How is it different than `make_endpoint(..., HTTP_GET, .....)` ?

**Comment by achamayou** [comment]
> * After some reading on the web, I get the understanding that sending payload with GET is not recommended. Even some client libraries drop the payload, so, what is the general recommendation when designing the CCF endpoint? From your above comment, I understand the CCF client is not dropping the payload. Can you pls confirm that client will continue to send it.

The HTTP server component of CCF will continue to provide access to request payload for all HTTP verbs, including GET. We take the view that it is up to the application to decide what it wants to do with the request payload.

> * From `smallbank.cpp` example, I get a feeling that the we should be using POST. Am I right to assume that it is to simplify the calling semantics of endpoints, that all are POST?
>   `make_endpoint("/SmallBank_balance", HTTP_POST, balance, user_sig_or_cert).install();`

That's purely a historical quirk, a typical REST app would likely have balance as a GET. CCF used to support another protocol that did not have the concept of verb, and went through a transition period where all endpoints were automatically exposed as POST in HTTP. SmallBank was written before this transition and updated minimally since.

CCF is not opinionated about REST design, and aims to support all use cases.

> * What are the semantics of `make_read_only_endpoint()` with respect to verb usage and payload?
>   
>   1. From `logging.cpp`, `make_read_only_endpoint("/log/private", HTTP_GET, .....)`, this API is taking in the GET verb, so, thought of confirming, is it to maintain API signature same as `make_endpoint()` or does it accept other verbs too?

Yes, it accepts other verbs. If you want to make a read-only POST, you can, even if it's unlikely to be what you want in many cases.

>   2. I believe this endpoint still allows to retrieve message body with `get_request_body()`?

Yes.

>   3. How is it different than `make_endpoint(..., HTTP_GET, .....)` ?

The read-only aspect here refers to the Key-Value store. `make_endpoint` gives you read and write to the KV, so if your application handler needs to persist some state, that's what you should use. In typical usage, it's likely that GET correlates with read_only, but not necessarily. You could for example imagine a GET that logs usage to the KV (and therefore requires write access), or a POST implemented for compatibility that returns an error every time and is therefore read only.

**Comment by divneil-intel** [comment]
> > 1. How is it different than `make_endpoint(..., HTTP_GET, .....)` ?
> 
> The read-only aspect here refers to the Key-Value store. `make_endpoint` gives you read and write to the KV, so if your application handler needs to persist some state, that's what you should use. In typical usage, it's likely that GET correlates with read_only, but not necessarily. You could for example imagine a GET that logs usage to the KV (and therefore requires write access), or a POST implemented for compatibility that returns an error every time and is therefore read only.

So, am I correct to understand that `ctx.tx.rw()` will fail as the `tx` object won't be having `rw` method for read only endpoint.

**Comment by achamayou** [comment]
@divneil-intel it will fail to build, yes.

Since this isn't an issue as such, I am going to close it now, but please do feel free to open discussions under https://github.com/microsoft/CCF/discussions, we are very happy to answer your questions.

**Comment by divneil-intel** [comment]
Thanks Amaury for your help. I really appreciate you sticking around for all the questions. That was the last question I had  :)

**Comment by achamayou** [comment]
@divneil-intel you're welcome, please do feel free to open a discussion any time :)
