### ISSUE TITLE
Investigate election trigger when learner is catching up

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#3252]
When a new learner node is catching up, it will eventually observe its own addition to the store in state `Learner` and start being able to call for elections:

```bash
# Deserialises signature after addition in state Learner
[info ] ../src/consensus/aft/raft.h:565      | Election timer has become active
```

However, if its "learner-ness" is rolled back (see #3250), it will stop receiving append entries from the current primary and timeout:

```bash
2021-11-25T15:35:25.227097Z -0.001 0   [info ] ../src/consensus/aft/raft.h:1981     | Ignoring vote from ineligible voter n[84dc94876ca7b3b55ca613613944ecfb4c7606f7d30b1b458a602d5035e7195d]
2021-11-25T15:35:25.227130Z -0.001 0   [info ] ../src/consensus/aft/raft.h:1796     | Becoming candidate n[84dc94876ca7b3b55ca613613944ecfb4c7606f7d30b1b458a602d5035e7195d]: 3
```

It will become candidate even though it is not able to vote for itself. This is because a node starts ticking when it sees itself in the _latest_ configuration (e.g. the configuration may be in flight) but can only vote for a node that is in the _committed_ configuration. 

Question: Should the two configuration conditions be the same? 
In any case, a node should probably not transition to the `Candidate` state if it cannot vote for itself.

**Comment by achamayou** [comment]
2tx support has been removed.
