### ISSUE TITLE
Cannot run test scripts if build folder is outside of source tree

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3265]
Some scripts like `tests.sh` make assumptions on the location of the build folder by using relative paths, e.g. `../python/`. This prevents using a build folder that is somewhere else completely. A build folder outside the source tree can be useful for cases where a slow network disk is used for the source (persistent, backed up etc.) but a local fast disk (ephemeral) for the build and for running (performance) tests.

**Comment by achamayou** [comment]
@letmaik I suspect the work involved in changing this and ensuring there are no regressions is going to vastly outweigh the cost of creating a symlink for someone with that specific use case.
