### ISSUE TITLE
ePBFT backups should be able to catch up

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#328]
ePBFT nodes/backups should be able to catch up and replay past transactions when joining the network.

**Comment by olgavrou** [comment]
ePBFT backups should be able to catch up by having the primary replay the ledger to them, and they should apply those transactions until they are up to date with the primary.

**Comment by ashamis** [comment]
This does not require the primary replaying the ledger.

The ledger can be replayed from any node and then when it has been replayed and the backup has caught up it should be enough to just confirm that the merkle roots match

**Comment by ashamis** [comment]
- [ ] Copy ledger from a replica with the ledger (start with the primary) to the node that is attempting to catch up
- [ ]

**Comment by olgavrou** [comment]
Notes on the bullet points above regarding the [PR](https://github.com/microsoft/ePBFT/pull/83):

- ledger_reader_main.cpp is being refactored into 2 classes, one that actually reads the file and one that applies it
  - the second class (`LedgerReplay`) right now has very little dependencies on `Replica` but I think it will need to access it's internal state quite a bit when it starts actually executing requests 
- only writing and reading pre prepares with large messages for now, assuming f = 0 and one replica when I populate the ledger file
- operations are no-op now, but (in upcoming PRs) when the replay of the ledger is actually executed it would be nice to have proper requests (albeit small "fake" ones that just increment a counter) and check that the merkle tree roots match
