### ISSUE TITLE
CI: Instrumented build doesn't show useful SAN info

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3299]
```
 ==18==WARNING: invalid path to external symbolizer!
53: ==18==WARNING: Failed to use and restart external symbolizer!
53:     #0 0x7f385d41d56d  (libjs_v8.virtual.so+0x38fc56d)
53:     #1 0x7f385d40fd31  (libjs_v8.virtual.so+0x38eed31)
53:     #2 0x7f385edb7b7a  (libjs_v8.virtual.so+0x5296b7a)
53:     #3 0x7f385ee6628e  (libjs_v8.virtual.so+0x534528e)
...
```

**Comment by achamayou** [comment]
https://github.com/google/sanitizers/issues/313

Looks like you can try setting ASAN_OPTIONS=external_symbolizer_path=my/shiny/new/llvm-symolizer, or making sure the llvm symbolizer is in $PATH.

**Comment by letmaik** [comment]
Hm, weird, the ci image does contain `llvm-symbolizer-10` in $PATH (it's in /usr/bin).

**Comment by letmaik** [comment]
Ah, according to https://github.com/google/sanitizers/issues/1248#issuecomment-628276044 it has to be exactly `llvm-symbolizer`, how weird. I could swear though that it worked locally for me and I don't have that alias or any env vars set.

**Comment by letmaik** [comment]
I think the solution is:
```
ASAN_SYMBOLIZER_PATH=$(realpath $(which llvm-symbolizer-10))
# /usr/lib/llvm-10/bin/llvm-symbolizer
```

This satisfies clang < 13 in that it has to be named llvm-symbolizer exactly.

I'll try this out locally first and then I'll think of a good place to put it for CI.

**Comment by letmaik** [comment]
Hm, locally it does work without any options. With `ASAN_OPTIONS=verbosity=2` it prints `Using llvm-symbolizer found at: /usr/bin/llvm-symbolizer-10`.

Doing a test now... https://github.com/microsoft/CCF/pull/3329
