### ISSUE TITLE
CCF Logs to be collected by Azure

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#330]

**Comment by achamayou** [comment]
@olgavrou something we'll probably need to solve is the discrepancy in format between OE logs and our own, which currently go to the same file.

**Comment by achamayou** [comment]
Linking https://github.com/openenclave/openenclave/issues/2147

**Comment by achamayou** [comment]
@vrijesh could you give the new json logging feature introduced in #346 a try to check that it's what you need? This documented under https://microsoft.github.io/CCF/start_network.html#node-output

**Comment by achamayou** [comment]
OE log PR, for reference: https://github.com/openenclave/openenclave/pull/2172
