### ISSUE TITLE
Implement more bindings in `js_v8`

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3312]
Follow-up from https://github.com/microsoft/CCF/pull/3258.

- [x] `ccf.rpc`
- [ ] `ccf.host`
- [x] `ccf.crypto`
- [x] `ccf.generateAesKey()`
- [x] `ccf.generateRsaKeyPair()`
- [x] `ccf.isValidX509CertBundle()`
- [x] `ccf.isValidX509CertChain()`
- [x] `ccf.wrapKey()`

**Comment by eddyashton** [comment]
The fields added in #3498:

[ ] `request.path`
[ ] `request.url`
[ ] `request.route`
[ ] `request.query`
[ ] `request.method`
[ ] `request.hostname`

**Comment by achamayou** [comment]
Not going to add substantial new user APIs before container re-design.
