### ISSUE TITLE
Enable more JS test suites for `js_v8`

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3314]
(Follow-up from https://github.com/microsoft/CCF/pull/3258)

`js_v8` is currently tested against:
- `e2e_logging_cft` by adding a new configuration in the Python test file
- `modules_v8_test` by replicating the `modules_test` configuration in CMake
  - `test_npm_app` is disabled as some bindings are not implemented yet (see #3312)
- `ls_v8` and `ls_full_v8` perf tests by replicating `ls_js` & `ls_full_js` configurations in CMake

The following JS tests referenced by their CMake names are currently only run for `js_generic` and should be run for `js_v8` as well:

e2e tests:
- [ ] `modules_test`: `test_npm_app`
- [ ] `launch_host_process_test`
- [ ] `auth`
- [ ] `js_batched_stress_test`
- [ ] `code_update_test`

perf tests:
- [ ] `ls_js_jwt`

**Comment by achamayou** [comment]
See https://github.com/microsoft/CCF/issues/3298#issuecomment-1268060991
