### ISSUE TITLE
Atom leak in js_generic

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#3319]
js_generic complains that the `retry-after` Atom is being leaked, when running e2e_logging tests.

This is because we use js_free on the output of JS_GetOwnPropertyNames, which does free the top level enum but not the atoms it contains. Instead we ought to use:

```
static void js_free_prop_enum(JSContext *ctx, JSPropertyEnum *tab, uint32_t len)
{
    uint32_t i;
    if (tab) {
        for(i = 0; i < len; i++)
            JS_FreeAtom(ctx, tab[i].atom);
        js_free(ctx, tab);
    }
}
```

But that's unfortunately not exported.

We also should add to the remote.py shutdown logic to catch Atom leaks when they happen.

**Comment by achamayou** [comment]
See also https://github.com/theduke/quickjs-rs/issues/36

**Comment by letmaik** [comment]
In quickjs-libc.c there's an example which has the same code you posted (see `build_envp()`):
```
 done:
    for(i = 0; i < len; i++)
        JS_FreeAtom(ctx, tab[i].atom);
    js_free(ctx, tab);
```

**Comment by achamayou** [comment]
@letmaik yes many places use js_free_prop_enum(), but it's inlined in others, for historical reasons I assume.
