### ISSUE TITLE
Warning about unrecognized section type when LVI mitigations are enabled

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3330]
I just stumbled over this in the CI build:
```
[94/136] Building CXX object CMakeFiles/js_generic.enclave.dir/src/apps/js_generic/js_generic.cpp.o
/tmp/js_generic-4c4438.s: Assembler messages:
/tmp/js_generic-4c4438.s:1353: Warning: unrecognized section type
[95/136] Building CXX object CMakeFiles/ccf.enclave.dir/src/enclave/enclave_time.cpp.o
/tmp/enclave_time-db003c.s: Assembler messages:
/tmp/enclave_time-db003c.s:32: Warning: unrecognized section type
```
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=39010&view=logs&j=a5ac1ec3-7e68-514b-a9fd-ea59be2801da&t=03d36826-d8b2-5fb2-230e-08a18a01a911

This is probably known but I couldn't find an issue for this. I can reproduce it locally with an SGX build with LVI mitigations enabled. I'm assuming it's caused by the special compiler wrappers.

**Comment by achamayou** [comment]
Yes, this is has been a known annoyance for a long time.
