### ISSUE TITLE
`LOG_FATAL_FMT` is not fatal

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3334]
It simply throws an exception which may or may not be caught in upper levels.

This is in contrast to the description of the log level:

```
FATAL, // fatal errors that lead to a termination of the program/enclave
```

**Comment by achamayou** [comment]
It shouldn't even throw, and it should not try to terminate in a way that somehow works in any context or anything like that. FATAL is a log level, like DEBUG, or INFO, this is a logging and it logs at that level.

**Comment by eddyashton** [comment]
I corrected the comment on this recently, but the host-side implementation will still throw. We should remove that behaviour, and add a throw or abort if appropriate at each calling point.
