### ISSUE TITLE
Support for HTTP/2

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#3342]
CCF currently only supports HTTP/1.1. We should add support for additional client-server protocols to improve performance/allow for a wider range of apps and languages. 

_Note: Updated to reflect past HTTP/2 work_

TODO:
- [x] Experimental support (#4010 
- [x] `h2spec` compliance (#4757)
- [x] Configuration (#4787, #4790) 
- [ ] Merge HTTP/1.1 and HTTP/2 endpoints
- [ ] Support for Application-Layer Protocol Negotiation (ALPN) (https://datatracker.ietf.org/doc/html/rfc7540#section-3.3)
- [ ] Forwarding (possibly superseded by https://github.com/microsoft/CCF/issues/4670)

Useful links:
- RFC: https://datatracker.ietf.org/doc/html/rfc7540 
- https://http2-explained.haxx.se/
- https://nghttp2.org/documentation/

**Comment by eddyashton** [comment]
To support gRPC streamed requests, we need to allow a handler to view incoming data before the request is complete, probably as each DATA frame arrives. Similarly for long-lived streamed responses, we need to be able to send the start of a response (headers and perhaps initial DATA frames), without immediately terminating the response, and allow some other component to send further responses + eventually terminate the response. The only way I can see to support this, is to move incoming request concatenation much deeper in the parsing stack, in fact inside each handler after dispatch. Then we add a variant handler which doesn't do this gluing, and sees each chunk/frame as it arrives. Big API changes!

**Comment by jumaffre** [comment]
[`h2spec`](https://github.com/summerwind/h2spec) test failures as per `02e6cceaa` on `main` below. 140/146 tests are passing successfully so we should be able to hook this into the CI very soon.

```
Failures: 

Generic tests for HTTP/2 server
  3. Frame Definitions
    3.8. GOAWAY
      using source address 127.0.0.1:58954
      × 1: Sends a GOAWAY frame
        -> The endpoint MUST accept GOAWAY frame.
           Expected: Connection closed
                     PING Frame (length:8, flags:0x01, stream_id:0, opaque_data:h2spec)
             Actual: Timeout

Hypertext Transfer Protocol Version 2 (HTTP/2)
  4. HTTP Frames
    4.2. Frame Size
      using source address 127.0.0.1:59212
      × 3: Sends a large size HEADERS frame that exceeds the SETTINGS_MAX_FRAME_SIZE
        -> The endpoint MUST respond with a connection error of type FRAME_SIZE_ERROR.
           Expected: GOAWAY Frame (Error Code: FRAME_SIZE_ERROR)
                     Connection closed
             Actual: DATA Frame (length:66, flags:0x01, stream_id:1)

  5. Streams and Multiplexing
    5.1. Stream States
      5.1.1. Stream Identifiers
        using source address 127.0.0.1:37318
        × 2: Sends stream identifier that is numerically smaller than previous
          -> The endpoint MUST respond with a connection error of type PROTOCOL_ERROR.
             Expected: GOAWAY Frame (Error Code: PROTOCOL_ERROR)
                       Connection closed
               Actual: DATA Frame (length:66, flags:0x01, stream_id:5)

    5.4. Error Handling
      5.4.1. Connection Error Handling
        using source address 127.0.0.1:37330
        × 1: Sends an invalid PING frame for connection close
          -> The endpoint MUST close the TCP connection
             Expected: Connection closed
               Actual: GOAWAY Frame (length:28, flags:0x00, stream_id:0)

  7. Error Codes
    using source address 127.0.0.1:37802
    × 1: Sends a GOAWAY frame with unknown error code
      -> The endpoint MUST NOT trigger any special behavior.
         Expected: Connection closed
                   PING Frame (length:8, flags:0x01, stream_id:0, opaque_data:h2spec)
           Actual: Timeout

Finished in 13.7051 seconds
146 tests, 140 passed, 1 skipped, 5 failed
```

**Comment by jumaffre** [comment]
Closing this issue as the essential work for HTTP/2 has been covered and the rest of the work is now featured in https://github.com/microsoft/CCF/issues/4814.
