### ISSUE TITLE
certificate verify failed: certificate has expired

### ISSUE THREAD

**Issue by yingjun-wu** [microsoft/CCF#3352]
When I started the CCF node, I found an error problem is that the networkcert has expired, because it relies on the python ccf package (version 1.0.3) at startup, which is required to verify the validity of the tls certificate when the node started by ccf is connected Therefore, I started the node by manually turning off the self-verification of the tls certificate. However, what I want to ask is how do I update the expired networkcert.pem.

When I started the ccf node, the certificate expired by the command check is as follows：
```
openssl s_client -connect 127.0.0.1:8000
```
can get it:

```
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-ECDSA-AES128-GCM-SHA256
    Session-ID: B2EE33B8171**
    Session-ID-ctx: 
    Master-Key: D5F841199F80B2AC8963989DD658B861F7***
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1641368095
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: yes
```
Thank you

**Comment by achamayou** [comment]
Hi @yingjun-wu, which version of CCF are you using? Is it pre-1.x?

Recent versions support governance-driven re-endorsement: https://github.com/microsoft/CCF/blob/main/src/runtime_config/default/actions.js#L154,  but the LTS branch (release 1.x) has a harcoded end date in 2023 (https://github.com/microsoft/CCF/blob/release/1.x/src/crypto/openssl/key_pair.cpp#L244).

The update was made here https://github.com/microsoft/CCF/commit/b54a28d508aba0470ca40b10602470bdbd8f000c#diff-f750aa026b4296e98a71ec8e8259db636e187ff2643f5f0142dde9a5336db18a, and should have been picked up by 0.19.1 and later. Prior to that, the hardcoded expiry was 20211231235959, which is what I'm guessing you are hitting.

We detail our support policy under https://microsoft.github.io/CCF/main/overview/release_policy.html#support-policy, the current LTS branch is 1.x (latest 1.0.15), and pre-releases (2.0.0-devx, current -dev7) are being cut from main. Once 2.x becomes LTS, 2.0.x releases will be cut from a 2.x branch while development continues on main.

**Comment by yingjun-wu** [comment]
Thanks @achamayou  for the reply!

my version of ccf is a old version, and it is 0.15.2. So, How can i fix it?

**Comment by achamayou** [comment]
@yingjun-wu by upgrading to a supported release, I would suggest 1.0.15, which is the most recent LTS release.

**Comment by yingjun-wu** [comment]
OK, get it, thanks for your reply!
