### ISSUE TITLE
Component Detection failing in daily tests

### ISSUE THREAD

**Issue by rengolin** [microsoft/CCF#3370]
There seems to be a new auto-injected step in the daily build (by policy?) that fails on all builds: Component Detection.

This is the error on all of them:
```
##[warning]Could not parse Jtokens from file /__w/1/s/tests/npm-app/node_modules/resolve/test/resolver/malformed_package_json/package.json.
```

I'm not sure what it does or why it was auto-injected over the weekend, but if we don't need it (seems to be related to dotnet), but it tells us how to avoid running if we don't need it:
```
To opt out of this build task, you can create a build variable "skipComponentGovernanceDetection" and set it to "true".
```

It also tells us who to ask about it:
```
Please contact OpenSourceEngSupport@microsoft.com if you run into problems or have questions with this task. See http://aka.ms/cgdocs for more information.
```

**Comment by rengolin** [comment]
Huh, I didn't look far enough. This only seems to run on scheduled builds... and they used to pass.

Anyway, this isn't our doing and it weird that it's failing to parse its own json files??

**Comment by achamayou** [comment]
@rengolin it's weird, but it's also not causing the jobs to fail and there's nothing we can do about it, so I think we're just going to ignore it.
