### ISSUE TITLE
Until recovery is complete, transactions should only be able to read public tables

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#341]
It is currently possible to have a transaction try to read/write to private tables during recovery. These private tables will be empty/partially filled until the recovery is complete.

We should disallow this so that members (user frontend is closed until the recovery is complete) cannot issue transactions on private tables. We can use the existing whitelist capability for this to restrict the list of tables that members can read/write to during recovery.

**Comment by achamayou** [comment]
Solved, the user frontend is closed during recovery and member tables only have access to governance (ie. public) state.
