### ISSUE TITLE
Split logging sample app across multiple files

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#3427]
As far as I can tell, these have no dependencies on `EndpointRegistry`, so could instead be free functions. This would make it easier to split the definitions across multiple files, since the `make_` factories could be anywhere, and only the `install` needs a reference to the `EndpointRegistry`.

However, this is a breaking change, as it likely adds a namespace requirement to the calling points. I think it's worth it, but needs to be done post-2.0 and should be paired with a scan of similar methods.

**Comment by achamayou** [comment]
It seems to me that you can have definitions across however many files you want, even for methods? I don't know if the impact of the breaking change is worth the fairly marginal benefit (as far as I can tell). It's possible I am missing something.

**Comment by eddyashton** [comment]
You can split across multiple files, but it's pretty ugly? Essentially you're passing around an extra unnecessary argument. I _think_ this lets you do arbitrary divisions more cleanly? But I'll validate that with a sample before investing too much time in it (and see if I can make it a non-breaking change for existing code).

**Comment by eddyashton** [comment]
Actually there is a dependency on `EndpointRegistry`, since our fluent `.install()` pattern needs a reference to the registry. So they can't trivially be made free functions. But of course the real body is the handler, which can already be trivially moved to other files. So this original issue is moot. But we should split our logging sample across multiple files to show this is possible + best practice for developers.

**Comment by achamayou** [comment]
Not going to invest in samples before container re-design.
