### ISSUE TITLE
cchost command not found

### ISSUE THREAD

**Issue by DavidZhongSyd** [microsoft/CCF#3462]
**Describe the bug**
https://microsoft.github.io/CCF/main/operations/run_setup.html says "The ccfciteam/ccf-app-run container can be run to setup an environment containing the cchost binary". However, after I run "docker pull ccfciteam/ccf-app-ci:1.0.17", the container says "cchost: command not found". Do I need to manually set the PATH to have the cchost included? If it does, may I ask the location of the cchost command? Thanks. 

**To Reproduce**
[run in local terminal]
docker pull ccfciteam/ccf-app-ci:1.0.17
sudo docker run -it ccfciteam/ccf-app-ci:1.0.17

[run in container]
sudo apt-get update
sudo apt-get install vim
cd ~
git clone --branch ccf-1.0.17 https://github.com/microsoft/CCF
mkdir -p CCF/samples/apps/logging/build
cd CCF/samples/apps/logging/build/
CC=$(command -v clang-8) CXX=$(command -v clang++-8) cmake ..
make
vim start_config.json  (copy https://github.com/microsoft/CCF/blob/main/samples/config/start_config.json and paste, and replace lib_jsgeneric.enclave.so.signed with ~/CCF/samples/apps/logging/build/liblogging.virtual.so)
cchost --config ./start_config.json

**Expected behavior**
Starting the First Node of sample logging application as illustrated in https://microsoft.github.io/CCF/main/operations/start_network.html

**Environment information**
ccfciteam/ccf-app-ci:1.0.17

**Additional context**
I am learning how to start the first node, and add a new node to join the network. But not sure if I am doing in the right way. Thanks.

**Comment by jumaffre** [comment]
Hi @DavidZhongSyd, the `cchost` binary is locally in the `/opt/ccf/bin/` folder and is not in the path by default:

```bash
$ docker run -ti ccfciteam/ccf-app-ci:1.0.17
...
root@1f2aabb9aaff:/# /opt/ccf/bin/cchost --version
CCF host: ccf-1.0.17

```

**Comment by DavidZhongSyd** [comment]
Thanks @jumaffre 
I am trying to start the first node. The https://microsoft.github.io/CCF/main/operations/start_network.html simply says "$ cchost --config /path/to/config/file". Does the /path/to/config/file refer to these json file below?

Complete start configuration: https://github.com/microsoft/CCF/blob/main/samples/config/start_config.json
Complete join configuration: https://github.com/microsoft/CCF/blob/main/samples/config/join_config.json
Complete recover configuration: https://github.com/microsoft/CCF/blob/main/samples/config/recover_config.json

When I copy the start_config.json, and replace the line 
  "file": "lib_jsgeneric.enclave.so.signed",
with 
    "file": "~/CCF/samples/apps/logging/build/liblogging.virtual.so",

It return error. May I ask the proper way to start the first node use cchost please? Thanks.
root@87f2f168a92e:~/CCF/samples/apps/logging/build# /opt/ccf/bin/cchost --config ./start_config.json 
INI was not able to parse {
Run with --help for more information.

**Comment by achamayou** [comment]
> https://microsoft.github.io/CCF/main/operations/run_setup.html says "The ccfciteam/ccf-app-run container can be run to setup an environment containing the cchost binary". However, after I run "docker pull ccfciteam/ccf-app-ci:1.0.17",

The ccf-app-run container does have `cchost` in its $PATH, but the ccf-app-ci container doesn't. They're different containers for different purposes (running CCF apps, vs building CCF apps).

**Comment by achamayou** [comment]
@DavidZhongSyd I think you are mixing versions here, 1.0.x used INI configs, and 2.x uses JSON. If you are referring to the main doc, that's 2.x and JSON, in which case you should use one of the 2.0.0-dev releases.
If you want to use 1.x make sure you use the version selector of the doc to get the right doc for your image.
