### ISSUE TITLE
Extend test coverage of JS + TS API

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#3503]
We don't have any systematic testing of the JS API, which leads to a few issues:

- No reference useage for fields which are available
- Incompatibilities between the fields exposed by QuickJS and V8
- Missing or inaccurate TS definitions of the interface

We should add a test which purely tries to cover the TS API surface, with some sanity checks that the returned values are plausible.

**Comment by achamayou** [comment]
This investment will go towards the new container API instead.
