### ISSUE TITLE
build_bundle.js SyntaxError

### ISSUE THREAD

**Issue by DavidZhongSyd** [microsoft/CCF#3560]
**Describe the bug**
SyntaxError when build sample npm-app

**To Reproduce**
```
docker pull ccfciteam/ccf-app-ci:2.0.0-rc0
docker run -it ccfciteam/ccf-app-ci:2.0.0-rc0

apt update
apt upgrade
apt install npm
root@48feb68717a7:/# cd ~
root@48feb68717a7:~# git clone --branch ccf-2.0.0-rc0 https://github.com/microsoft/CCF.git
root@48feb68717a7:~/CCF/tests/npm-app# npm install
root@48feb68717a7:~/CCF/tests/npm-app# npm run build

created dist/src in 8.5s
/root/CCF/tests/npm-app/build_bundle.js:1
import { readdirSync, statSync, readFileSync, writeFileSync } from "fs";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `del-cli -f dist/ && rollup --config && cp app.json dist/ && node build_bundle.js dist/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-16T04_14_34_835Z-debug.log
```

**Expected behavior**
https://microsoft.github.io/CCF/main/build_apps/js_app_bundle.html
Convert the app into a proposal-ready JSON bundle

**Environment information**
docker pull ccfciteam/ccf-app-ci:2.0.0-rc0
git clone --branch ccf-2.0.0-rc0 https://github.com/microsoft/CCF.git

**Additional context**

**Comment by eddyashton** [comment]
@DavidZhongSyd Thanks for raising. I don't recognise this error, will repro locally and investigate.

**Comment by eddyashton** [comment]
This is happening because `build_bundle.js` uses `import` syntax, which is only supported in relatively recent versions of `node`. The version of `node` that's installed on the Docker images (the default from Ubuntu 20.04) is v10.19.0, which doesn't support this syntax. There's a fix in #3561.

As a temporary workaround, you can install a more recent version of `node` inside the Docker container (eg, by using a [nodesource PPA](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04)), which will allow parse this script correctly. v10.19.0 doesn't work, v14.18.3 and v14.19.0 do work.

Additionally, we'll take another look at our Docker images - for CCF-JS app development, we probably want a more recent `node` version.

**Comment by DavidZhongSyd** [comment]
Thanks @eddyashton 

After I upgrade the node to v14.19.0, it passed the build process (`npm install, npm run build`), and I found the bundle.json under dist.

```
root@48feb68717a7:~/CCF/tests/npm-app/dist# cat bundle.json | more
{"metadata":{"endpoints":{"/jwt":{"get":{"js_module":"endpoints/jwt.js","js_function":"jwt","forwarding_required":"always","authn_policies":[],"mode":"rea
donly","openapi":{"responses":{"200":{"description":"Ok","content":{"application/json":{"schema":{"properties":{"userId":{"type":"string"}},"required":["u
serId"],"type":"object","additionalProperties":false}}}},"401":{"description":"Unauthorized","content":{"application/json":{"schema":{"properties":{"msg":
{"type":"string"}},"required":["msg"],"type":"object","additionalProperties":false}}}}},"security":[],"parameters":[]}}},"/crypto":{"get":{"js_module":"en
dpoints/crypto.js","js_function":"crypto","forwarding_required":"always","authn_policies":["user_cert"],"mode":"readonly","openapi":{"responses":{"200":{"
description":"Ok","content":{"application/json":{"schema":{"properties":{"available":{"type":"boolean"}},"required":["available"],"type":"object","additio
nalProperties":false}}}}},"security":[],"parameters":[]}}},"/generateAesKey":{"post":{"js_module":"endpoints/crypto.js","js_function":"generateAesKey","fo
rwarding_required":"always","authn_policies":["user_cert"],"mode":"readonly",
```

However, the generated bundle file bundle.json format does not quite match what is showed in
https://microsoft.github.io/CCF/main/build_apps/js_app_bundle.html#deployment

For example, the sample code in the link shows the first field is "actions" whereas the bundle.json is started with "metadata". 

Did I miss some step in converting the app into a proposal-ready JSON bundle? Thanks.

```
{
  "actions": [
    {
      "name": "set_js_app",
      "args": {
        "bundle": {
          "metadata": {
            "endpoints": {
              "/compute": {
                "post": {
                  "js_module": "math.js",
                  "js_function": "compute",
                  "forwarding_required": "never",
                  "authn_policies": [
                    "user_cert"
                  ],
   ...
```

**Comment by eddyashton** [comment]
The JSON object output by `build_bundle.js` should be used as the `args.bundle` value in the proposal, but it doesn't build a full proposal as you may wish to customise other args (eg - `disable_bytecode_cache`, any other args that are added in future). I'll edit the docs to clarify that.
