### ISSUE TITLE
Start, Join, Open Network transactions need to be signed

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#357]
Start, Join and Open Network transactions need to be signed so that they can be verified by ePBFT when replicas are catching up and the ledger is replayed.

**Comment by achamayou** [comment]
Open network transactions are member votes, so they are already signed. Join transactions are RPCs on the "nodes" frontend, so it's just a matter making the RPC check the signature the same way we do for member RPCs.

The start transaction is less straightforward, for several reasons (one which being that it contains the identity of the starting node, which would be issuing the signature!).

**Comment by ashamis** [comment]
- [ ] The Open Tx is signed
- [ ] The Join Tx is signed
- [ ] the Start Tx is signed

**Comment by jumaffre** [comment]
FYI: the Join Tx (as issued by the joining node) is not yet signed.

**Comment by achamayou** [comment]
@ashamis @jumaffre does it need to be signed by the issuing node?

**Comment by achamayou** [comment]
As discussed, there's no requirement for client signatures on these, they just need to be regular PBFT transactions, which they are now, after #460
