### ISSUE TITLE
Add ability for nodes to join without snapshot from nodes that started with snapshot

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#3574]
Follow-up from #2422 and #3573 

New nodes can currently only join from a state that's at least as recent as the starting state of the node they join from. For example, if `node 1` joins the service from `node 0`, which itself started from a snapshot at seqno `100`, then `node 1` should start from a snapshot that's at least as recent as `100` (i.e. `node 1` cannot join without a snapshot, or with a snapshot older than `100`). This is because `node 0` might not have access to the historical ledger and thus not have access to the ledger secrets before `100`. If `node 1` was allowed to join, it wouldn't be able to decrypt the ledger entries before `100` (assuming the ledger was also rekeyed at `100`). To circumvent this, we currently (as of `2.0.0-rc1`) reject `POST /node/join` requests which specify a `startup_seqno` earlier than our own. 

This is OK for current deployments of CCF where the operator has full control over all the nodes and their storage. However, to simplify operators, we should let all nodes, independently of their `startup_seqno` join an existing service, from any target node.

To do so, the target node (`node 0` in the example above) should fetch the historical ledger secrets from the historical ledger when a new node joins. This means giving the `node_frontend.h` access to the `historical_ledger_secrets` (see `historical_queries.h`) so they can be passed on to new joiners. In other words, the `POST /node/join` endpoint should be able to retrieve the historical ledger secrets up to the `startup_seqno` specified by the new joiner.

**Comment by achamayou** [comment]
This is considered fixed: the snapshots need to be reasonably fresh.
