### ISSUE TITLE
Change f in ePBFT

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#359]
f should be able to change in ePBFT (e.g. when the service is opened it will change from `f = 0` to `f > 0`) and the protocol should behave accordingly.

**Comment by ashamis** [comment]
This change should be based on the 'hook' described in https://github.com/microsoft/CCF/issues/360

**Comment by ashamis** [comment]
- [ ] Change f from 0 to 1 as part of opening the network
- [ ] The machines are able to discover the primary
- [ ] Machines attempt to start recovery
