### ISSUE TITLE
Add f to service table

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#360]
f indicates the number of faulty/malicious replicas that the consensus protocol (raft/pbft) can tolerate. f should be added to the service table, and when it is changed (when the network is opened for example) the correct hooks should be triggered (#359)

**Comment by ashamis** [comment]
- [ ] Add f to the service table
- [ ] Add a 'hook' that allows CCF to notify ePBFT that f has changed

**Comment by ashamis** [comment]
We are now planning on automatically calculating f
