### ISSUE TITLE
Document the meaning of writeset and commit evidence

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3602]
Those should be documented since they are exposed in receipts.

**Comment by achamayou** [comment]
- [ ] Add Write Set entry to the glossary pointing to https://microsoft.github.io/CCF/main/architecture/ledger.html?highlight=writeset#transaction-format
- [ ] Add Commit Evidence to the glossary and include a short summary of its function (details under https://github.com/microsoft/CCF/issues/3295)

Also:

- [ ] Receipt architecture page, motivating the high-level goals, linking to Audit and Use Apps pages
- [ ] Use Apps: cover receipts as service signatures with optional user claims
- [ ] Add detail about cert, identity of signer
- [ ] Make explicit the requirement to have the service identity
- [ ] Add a commented sample use of custom claims in the JS logging app, showing how to expose the log message directly in the receipt
- [ ] Audit: cover receipts as audit elements, potentially to be combined with a ledger, move to first position
- [ ] Add a commented sample use of a receipt with a ledger or online service to detect and blame a malicious catastrophic recovery
- [ ] Add a commented sample use of a receipt + ledger to check for inclusion

**Comment by achamayou** [comment]
Started under https://github.com/achamayou/CCF/tree/receipt_doc_changes, will tick off as PR'ed.
