### ISSUE TITLE
Cannot use `.c` sources with `add_ccf_app` CMake helper

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3637]
**Describe the bug**

> clang: error: argument unused during compilation: '-stdlib=libc++' [-Werror,-Wunused-command-line-argument]

**To Reproduce**

```cmake
add_ccf_app(myapp SRCS main.cpp other.c)
```

**Expected behavior**

`add_ccf_app` should only add C++ compile flags for C++ files. This should be possible with CMake's generator expressions. Open Enclave's targets use the same approach, e.g. `$<$<COMPILE_LANGUAGE:CXX>:-nostdinc++>`.

**Environment information**
CCF 2.0.0 rc3

**Work-around**

A work-around is to separate the C code into another library using the `add_enclave_library_c` CMake helper and link against it in `add_ccf_app` using `LINK_LIBS_ENCLAVE` / `LINK_LIBS_VIRTUAL`.

Given that there is a work-around, this is low priority and not blocking.

**Comment by achamayou** [comment]
Or extern C {}, and use the C++ flow.
