### ISSUE TITLE
Consortium-related functions should have their own class

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#364]
The `Network` class in `tests/infra/ccf.py` contains several functions related to member governance that should be moved to their own class (e.g. `Consortium`).

**Comment by achamayou** [comment]
I agree we should do this, but I think this is a general nice to have rather than something we need for TR-compliance and completeness of the new Genesis model.

**Comment by jumaffre** [comment]
True. I wanted to attach the ticket to an existing milestone. Feel free to move it to a different stream or detach it to the current one.
