### ISSUE TITLE
Add test for historical query range spanning multiple services

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#3656]
We should test that it is possible to test historical queries spanning multiple service epochs, i.e. start of range in ledger generated by previous service and end in new service ledger.

**Comment by wintersteiger** [comment]
Just checking I understand correctly. By multiple epochs, do you mean recoveries, i.e. this would be the test for the changes for #3343?

**Comment by achamayou** [comment]
@wintersteiger there are two sub-tests here, the first is historical queries themselves (ie. querying table data), the second is checking that receipts returned can be validated by the user easily, without having to keep track of the service identity history themselves.
