### ISSUE TITLE
Historical & indexing API extensions for preloading

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3668]
**Is your feature request related to a problem? Please describe.**
With paginated responses, it is common to kick off retrieval of the next page's content with the historical query API `get_store_range()` function or the `SeqnosByKey_Bucketed` indexing strategy `get_write_txs_in_range()` function, for example.

**Describe the solution you'd like**
Since the result of the existing functions is always discarded by the caller if it happened to be available already, it seems there should be functions to trigger preloading only, without doing the work necessary to return the data. 

**Describe alternatives you've considered**
Keep using the original functions. I haven't done any benchmarks on what overhead could be saved. Feel free to close this request if it's not worth the effort.

**Comment by achamayou** [comment]
This is a good idea, but there is a combined lack of user demand and dev team bandwidth on this issue.
