### ISSUE TITLE
Explain difference between `set_forwarding_required` and `set_execute_outside_consensus`

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3673]
`set_forwarding_required` is described in https://microsoft.github.io/CCF/main/build_apps/api.html as:
> Overrides whether a Endpoint is always forwarded, or whether it is safe to sometimes execute on followers.

`set_execute_outside_consensus` is described as:
> [...] indicating whether the Endpoint is executed locally, on the node receiving the request, locally on the primary or via the consensus.

Both methods are used in the logging sample, so they seem important enough to understand fully. However, I find that hard just from the API docs. There seems to be some overlap in meaning between the two, but maybe not? It's also not clear why there isn't just a single function which has a bunch of enum options.

**Comment by achamayou** [comment]
I don't think there is a legitimate use of `set_execute_outside_consensus` in CFT, it's only useful for BFT when wanting to execute a local read against a KV without going through consensus.

For all intents and purposes, setting the forwarding to Never should yield the same result. I think we can probably just remove `set_execute_outside_consensus` from the public API for now.
