### ISSUE TITLE
OpenSSL bad error handling

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#3677]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=43347&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=3aae4c9d-f0dc-5b97-1b0e-f86312395af9&l=15373

```
OSSL: Could not encode update to base64 string: error:0D08303A:lib(13):func(131):reason(58)
51: terminating with uncaught exception of type std::exception: std::exception
```

**Comment by jumaffre** [comment]
Linking to @eddyashton's investigation branch: https://github.com/eddyashton/CCF/commits/more_openssl_error_code_checks

**Comment by rengolin-ms** [comment]
It was also mentioned here: #3368

**Comment by jumaffre** [comment]
@rengolin-ms Do you happen to have a link to another instance of a similar failure but for another test in the CI?

**Comment by eddyashton** [comment]
@jumaffre The one at the bottom of #3368 is `tpcc_sgx_cft`, and includes _a_ OSSL error. I _think_ the earlier `e2e_logging_cft` failures in that test are also OSSL, but we don't have access to those logs.

**Comment by rengolin** [comment]
I've rebased @eddyashton branch on current master here: https://github.com/rengolin/CCF/tree/more_openssl_error_code_checks

**Comment by achamayou** [comment]
Not observed in quite some time, will re-open if necessary.
