### ISSUE TITLE
Cannot build C++ app with t_cose library: multiple definition of `gettimeofday'

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3685]
**Describe the bug**

> /opt/oe_lvi/ld: /opt/ccf/lib/libquickjs.enclave.a(stub_time.c.o): in function `gettimeofday':
/__w/1/s/build/../src/enclave/stub_time.c:7: multiple definition of `gettimeofday'; /opt/openenclave/lib/openenclave/enclave/liboelibc.a(gettimeofday.c.o):/source/openenclave/3rdparty/musl/musl/src/time/gettimeofday.c:6: first defined here

**To Reproduce**
Use `ccfciteam/ccf-app-ci:2.0.0-rc4` as base image and try to build a CCF app.

**Expected behavior**
It should build without adding further flags that would allow multiple definitions.

**Additional context**
The full invocation:
> /opt/oe_lvi/clang++-10 -fPIC -O2 -g -DNDEBUG  -link-lvi-mitigation -shared -Wl,-soname,libapp.enclave.so -o libapp.enclave.so CMakeFiles/app.enclave.dir/src/main.cpp.o    /opt/openenclave/lib/openenclave/enclave/liboeenclave-lvi-cfg.a  /opt/openenclave/lib/openenclave/enclave/liboesnmalloc-lvi-cfg.a  /opt/openenclave/lib/openenclave/enclave/liboecore-lvi-cfg.a  /opt/openenclave/lib/openenclave/enclave/liboesyscall-lvi-cfg.a  /opt/ccf/lib/libccf.enclave.a    /opt/openenclave/lib/openenclave/enclave/liboecryptoopenssl.a  /opt/openenclave/lib/openenclave/enclave/libopensslssl.a  /opt/openenclave/lib/openenclave/enclave/libopensslcrypto.a  /opt/openenclave/lib/openenclave/enclave/liboelibc.a  /opt/openenclave/lib/openenclave/enclave/liboesyscall.a  /opt/openenclave/lib/openenclave/enclave/liboecore.a  /opt/ccf/lib/libquickjs.enclave.a  /opt/ccf/lib/libccfcrypto.enclave.a  /opt/ccf/lib/libhttp_parser.enclave.a  /opt/ccf/lib/libsss.enclave.a  /opt/ccf/lib/libccf_endpoints.enclave.a  /opt/ccf/lib/libccf_kv.enclave.a  /opt/openenclave/lib/openenclave/enclave/liboeenclave-lvi-cfg.a  /opt/openenclave/lib/openenclave/enclave/liboelibcxx-lvi-cfg.a  /opt/openenclave/lib/openenclave/enclave/liboecryptoopenssl-lvi-cfg.a  /opt/openenclave/lib/openenclave/enclave/libopensslssl-lvi-cfg.a  /opt/openenclave/lib/openenclave/enclave/libopensslcrypto-lvi-cfg.a  /opt/openenclave/lib/openenclave/enclave/liboelibc-lvi-cfg.a  /opt/openenclave/lib/openenclave/enclave/liboesyscall-lvi-cfg.a  /opt/openenclave/lib/openenclave/enclave/liboecore-lvi-cfg.a  -nostdlib  -nodefaultlibs  -nostartfiles  -Wl,--no-undefined,-Bstatic,-Bsymbolic,--export-dynamic,-pie,--build-id  -Wl,-z,noexecstack  -Wl,-z,now  -Wl,-gc-sections  -lgcc

**Comment by achamayou** [comment]
@letmaik did you enable time.edl?

**Comment by letmaik** [comment]
> @letmaik did you enable time.edl?

I'm not building CCF from source, it's just the one from the public `ccf-app-ci` Docker image.

**Comment by letmaik** [comment]
Update: It has nothing to do with Docker, also reproduces on the host. I use the QCBOR and t_cose libraries and if I remove t_cose then the issue disappears but I don't see why. I created a minimal repro here: https://github.com/letmaik/ccf-repro-1

**Comment by letmaik** [comment]
Looks like the OE symbol isn't weak anymore?

```
$ nm -a /opt/openenclave/lib/openenclave/enclave/liboelibc.a | grep gettimeofday
0000000000000000 t .text.oe_SYS_gettimeofday_impl
0000000000000000 T oe_SYS_gettimeofday_impl
                 U oe_SYS_gettimeofday_impl
gettimeofday.c.o:
0000000000000000 t .text.gettimeofday
0000000000000000 T gettimeofday
0000000000000000 a gettimeofday.c

$ nm -a /opt/ccf/lib/libquickjs.enclave.a | grep gettimeofday
                 U gettimeofday
0000000000000000 t .text.gettimeofday
0000000000000000 T gettimeofday
```

**Comment by achamayou** [comment]
@letmaik I don't think that works, because quickjs calls `gettimeofday`, not `clock_gettime`.

**Comment by achamayou** [comment]
@letmaik the implementation from oelibc does, but that's not something we want to pick up?

**Comment by letmaik** [comment]
Confirmed.
