### ISSUE TITLE
Indexing error

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3703]
**Describe the bug**
During load testing, at some point, the service crashes and the log contains thousands of the following messages (one for each time the index is queried, I think):
> 12:46:45.423 | ERROR    | infra.remote:log_errors:77 - /.../workspace/sandbox_0/out: 2022-03-25T11:33:33.117094Z -0.001 0   [fail ] egies/seqnos_by_key_bucketed.cpp:227 | A file that SeqnosByKey public:entry requires is missing. Re-indexing.

**To Reproduce**
Log a lot of transactions through one endpoint and simultaneously ask for seqnos by index through a second endpoint. I don't have a standalone example at the moment.

**Environment information**
CCF 2.0.0-rc4
DC8 VM with `--worker-threads 0`

**Comment by iamhardikat11** [comment]
I am a Novice Open Source Contributor, I am willing to solve this bug, can you explain more on this.
