### ISSUE TITLE
Remove ServiceStatus.RECOVERING

### ISSUE THREAD

**Issue by wintersteiger** [microsoft/CCF#3714]
During discussion of #3679 @jumaffre pointed out that we could remove `ServiceStatus.RECOVERING` ([here](https://github.com/microsoft/CCF/blob/843714229fc7c74a47fe3472ed2abdc201b568d1/include/ccf/service/tables/service.h#L16)) because it is essentially equivalent to `ServiceStatus.OPENING && previous_service_identity_version != std::nullopt`. 

I think this is correct, but the separate state is still valuable as it conveys a clear intention, e.g. in the `transition_service_to_open` proposals, which would be much harder to read without it. Keeping it would also make it easier to change the service identity recording scheme later (e.g. in case we re-decide to keep a full table of previous identities).

**Comment by achamayou** [comment]
@wintersteiger I'm confused, this looks like a ticket for "remove A", which exclusively contains reasons why we should keep A? :)

What I am missing? What's the motivation for removing A?

**Comment by wintersteiger** [comment]
Turns out I misunderstood @jumaffre 's comment, opening a replacement issue.
