### ISSUE TITLE
Improve tooling for ServiceStatus.RECOVERING

### ISSUE THREAD

**Issue by wintersteiger** [microsoft/CCF#3717]
#3624 added the new service status `RECOVERING`. We should improve support for this in `ledger_viz.py` and `ledger.py`, as well as other parts of the code that need to or should distinguish between `OPENING` and `RECOVERING`.

**Comment by jumaffre** [comment]
I think I'd prefer for the `RECOVERING` status to be subsumed by the long-existing `OPENING` status, unless there's a strong reason for it to exist. The main reason for this is that unifying both first service open and recovery helps keep both flow consistent (e.g. hooks triggered by this specific status) and is easier to maintain/harder to break.

**Comment by iamhardikat11** [comment]
I am Novice Open Source Programmer. Looking to Find New Opportunities. Can you describe more on this Issue?
