### ISSUE TITLE
Store should be compacted when using ePBFT

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#373]
As it stands, the KV store is never compacted when using ePBFT as the consensus algorithm. This means that:

1. The KV will grow indefinitely
2. The global hooks will never be called. For example, the network will never be opened to users.

**Comment by jumaffre** [comment]
As discussed with @ashamis and @olgavrou yesterday, we need to add this as part of the integration work with ePBFT. More specifically, we'll need to do it on every Replica once they are sure that something has been globally committed. We'll need a new callback for this from ePBFT to CCF to compact the KV store, at a specific version.

Because ePBFT does not know about the version of the store when processing a request (since Requests can be batched into a unique ePBFT's SeqNo), we will need to capture the kv::Version in exec_command() the same way that we do for the Merkle Root. Then, once the corresponding message (i.e. Pre_prepare) is committed, we can call the new callback into CCF to compact the store at that specific version. This means that we will only compact at the end of a batch of Requests, which I believe is absolutely fine.

**Comment by olgavrou** [comment]
@ashamis can we close this issue?

**Comment by ashamis** [comment]
Completed with #405
