### ISSUE TITLE
Node-endorsed certificates are never renewed

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#3743]
The new `set_node_certificate_validity` proposal action renews the endorsed node certificate but does not renew the self-signed node certificate. This means that RPC interfaces that use the self-signed node certificate are never refreshed and clients will eventually get validation errors when the certificate expires. 

After discussion with @eddyashton, to fix this, we have multiple options:
1. Bundle the self-signed certificate renewal with the existing `set_node_certificate_validity` proposal action. 
2. Decouple the renewal of the two certificates, to cater for more flexible deployment scenarios and be more flexible if/when we introduce different types of endorsements.
3. Have the self-signed certificate automatically renew (using the host's time) since it is only meant to be used by operators.

Since this is to be fixed for 2.x, I'm leaning towards 1. but happy to discuss this further.

**Comment by lynshi** [comment]
I think 2 is a bit more extensible. In fact, maybe `set_node_certificate_validity` should take an argument for the name of the RPC interface(s) for which to refresh the certificate.

As of now we understand that there should be one "primary" RPC interface and one for operators, but (correct me if I'm wrong) this isn't necessarily prescribed in the documentation and it's implied a network can have as many interfaces as desired. If this is the case, then the proposals should be as flexible as possible as well, otherwise why not default to only two interfaces (one node-endorsed, one service-endorsed) by design?

**Comment by lynshi** [comment]
Relatedly, suppose someone defines 2 service-endorsed interfaces and 2 node-endorsed interfaces. Would the certificates presented by each type of interface be the same (e.g. would the 2 service-endorsed interfaces present the same certificate)?

**Comment by jumaffre** [comment]
@lynshi Many thanks for your input on this. 

One thing to note is that the node certificate isn't only used for the TLS RPC interface. It's also recorded in the ledger (https://microsoft.github.io/CCF/main/audit/builtin_maps.html#nodes-endorsed-certificates) and the corresponding private key is used to sign the Merkle root and the signature is also recorded in the ledger (https://microsoft.github.io/CCF/main/audit/builtin_maps.html#_CPPv4N3ccf13NodeSignature3sigE). Consequently, the endorsed node certificate is also included in every transaction receipt (see https://microsoft.github.io/CCF/main/use_apps/verify_tx.html#write-receipts). 

My point is that I'm not sure we should tie `set_node_certificate_validity` to each RPC interface as the node certificate is used for other purposes. Alternatively, the proposal action could take the enum value of the endorsement type (see https://microsoft.github.io/CCF/main/operations/configuration.html#endorsement), i.e. either `Node`, `Service` or maybe `All`, so that we can have one single action for all certificate renewal while not tying the proposal to the name of the RPC interfaces.

**Comment by jumaffre** [comment]
After an attempt to implement the solution described above (a variant of point 2. as described in the issue description), I've realised that this option is not feasible. This is because the private identity key of each node never leaves the node's enclave and so only a given node can issue a self-signed certificate for itself. It is not possible to renew the self-signed certificate for an arbitrary node from a proposal since this proposal will only be executed on a the primary node at the time. I will fix this using the first approach (point 1. above).

**Comment by lynshi** [comment]
Makes sense! Please let me know if that requires a constitution change and I'll make the update accordingly.

**Comment by jumaffre** [comment]
> Makes sense! Please let me know if that requires a constitution change and I'll make the update accordingly.

@lynshi This will not require any constitution change as this is handled entirely by the core framework code.
