### ISSUE TITLE
Enabling debug or trace with non-unsafe releases hangs

### ISSUE THREAD

**Issue by caleteeter** [microsoft/CCF#3757]
**Describe the bug**
Inability to enable debug or trace logging for non-unsafe packages.

**To Reproduce**
Create a new app-dev prepped VM, start the sandbox (sandbox.sh) passing a package (e.g., $HOME/CCF/tests/js-authentication).  When starting with -l debug  or -l trace, the startup hangs and exception thrown.

![image](https://user-images.githubusercontent.com/8452367/162447919-5b05fa17-8097-4cce-9f9c-15acdb57b622.png)

**Expected behavior**
Expected to get enhanced logging.

**Environment information**
Used the latest 2.0.0-rc6 package (https://github.com/microsoft/CCF/releases/download/ccf-2.0.0-rc6/ccf_2.0.0_rc6_amd64.deb)

**Comment by jumaffre** [comment]
@caleteeter Thanks for raising this bug. This is an issue that has recently surfaced within the team as well (https://github.com/microsoft/CCF/issues/3753). 

With release builds (i.e. non-unsafe), it is currently expected that the log level on the host cannot be set to a value lower than `info` (i.e. only `info`, `error` and `fail` are allowed). This is a limitation that we hope to address by the first non release-candidate `2.0.0` release. Note that you will be able to set a more verbose logging level on the host for unsafe builds, as you've probably already found out.

In the meantime, we've made the `sandbox.sh` more verbose and quicker to react to early failures such as this one (see https://github.com/microsoft/CCF/pull/3759). This will be available from `2.0.0-rc7`.

**Comment by caleteeter** [comment]
@jumaffre thanks for confirming this, it would be good to have this listed in the main doc site, as its a bit confusing that I can set log levels that don't work for non-unsafe builds.

Additionally, when I run unsafe builds (with sandbox) using -v and -l debug, I see the messages (including debug) as the ccfhost starts but I don't see the log stream I expect when calling governance functions for instance.  I am debugging the JWT key refresh which should happen after some proposals, but not sure why I can't see the lower levels logs for this.  This should be logged as part of node state changes.
