### ISSUE TITLE
Not clear how to configure logging

### ISSUE THREAD

**Issue by caleteeter** [microsoft/CCF#3761]
**Describe the bug**
Unclear how to enable logging.  When starting the node with the sandbox script, there is an option (-l) that can be used to set the normal info, trace, debug type logging.  After figuring out that trace/debug level are enabled via the unsafe builds, I can see detailed logs at startup on the console.  What I am missing is once running (single node in virtual mode), I don't see logs for the node that I expect, when issuing governance transactions (changes).  Where should I expect to see these logs?

**To Reproduce**
Start a virtual node (single) with -l debug -v flags.

**Expected behavior**
Trying to understand how to view node logs after startup.

**Environment information**
2.0.0-rc0

**Comment by achamayou** [comment]
@caleteeter all node logs are captured in the `out` file under the node's workspace, so by default for the sandbox under `$HOME/workspace/sandbox_0/out`.

**Comment by caleteeter** [comment]
Thanks @achamayou
