### ISSUE TITLE
Re-organise documentation

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#382]
CCF documentation has grown mostly organically, and recent changes to the governance section have highlighted the fact that the structure is hard to navigate. Following discussions with @eddyashton and @jumaffre, I think we should go towards the following top-level structure:

- Introduction
  - Include a diagram showing all actors and their roles in a CCF service
- Quickstart (what's now Getting Started, streamlined to some extent)
- Members
  - Governance
  - Add/Remove members
  - Add/Remove users
  - Update code
  - Accept a catastrophic recovery
  - Members RPC reference
- Operators
  - Start a service
  - Add/Remove nodes
  - Catastrophic recovery
  - Management RPC reference
- Developers
  - Building a CCF application
  - Sample C++ App
  - Sample Lua App
  - C++ API
  - Lua API
- Users
  - Users RPC reference
- Glossary

I will start this change soon, but please use this ticket to discuss this change, provide suggestions etc.

**Comment by jumaffre** [comment]
Looks great! I'd say move Operators before Members (as people are most likely to want to start a service first). Also, under Members, I think that Add/Remove users and members can be the same page. 

As discussed, we should also create a new Design/Contributors section to add design documentation of CCF.
