### ISSUE TITLE
Support `make_read_only_endpoint` to be used with historical query adapter

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3872]
https://github.com/microsoft/CCF/blob/1430f4dc48184ad0002176e2bc8557600299ee9f/samples/apps/logging/logging.cpp#L844-L848

I'm assuming the reason why the historical query adapter is written around `EndpointContext` instead of `ReadOnlyEndpointContext` is to give more flexibility in case something has to written to the KV when a historical query was made. Even though a rare use case, it may exist.

From a dev perspective though it seems odd that this means I have to disable the static guarantees that come from using `make_read_only_endpoint`. It would be nice if the adapter somehow supported read-only endpoint functions as well.

**Comment by achamayou** [comment]
@letmaik that's a good point, we could have `read_only_adapter_v1` and `write_only_adapter_v1` I suppose?
