### ISSUE TITLE
Links to deprecated python client in docs

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#3876]
https://microsoft.github.io/CCF/main/use_apps/python_tutorial.html states that the python client has been deprecated, however, this docs page is still referenced to at the top of the following pages:
- https://microsoft.github.io/CCF/main/use_apps/verify_quote.html
- https://microsoft.github.io/CCF/main/use_apps/verify_tx.html
- https://microsoft.github.io/CCF/main/architecture/merkle_tree.html

**Comment by jumaffre** [comment]
Well spotted. While the client classes have been removed from the `ccf` Python package, the package still exists and contains the utility to verify a node's quote and to parse/verify the ledger. I'll issue a PR to fix this shortly.
