### ISSUE TITLE
Polyfill TypeScript documentation is no longer included 

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#3903]
The polyfill for the `ccf-app` TypeScript package is no longer included under https://microsoft.github.io/CCF/main/js/ccf-app/, but is for 1.x: https://microsoft.github.io/CCF/release/1.x/js/ccf-app/modules/polyfill.html

Edit: tracked [here ](https://github.com/TypeStrong/typedoc/issues/1948) and will be fixed in TypeDoc v0.23. Thanks @letmaik!

**Comment by achamayou** [comment]
That doesn't seem solved despite 0.23 being out?

**Comment by eddyashton** [comment]
Still excluded because it contains no exports. Raised with TypeDoc here: https://github.com/TypeStrong/typedoc/issues/2007

**Comment by eddyashton** [comment]
Resolved in Typedoc 0.23.9, and now live on our docs page again.
