### ISSUE TITLE
A newly elected leader must not advance the commit index until a transaction in the new term commits

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#3950]
It is not safe for a newly elected leader to advance the commit index in terms prior to the one it has been elected in. They must instead wait until at least one transaction has been emitted on the new term, and observe its commit.

This is to make sure that any node that could win a subsequent election has the same suffix, and cannot potentially cause a rollback of previously committed transactions.

In practice, this should happen quickly, because a newly elected leader starts their term by sending a signature. The current logic does not however correctly wait for this, and will treat past signatures as committable.

Another way to think about this is that a newly elected node should only ever commit its own signatures in the current term, never those emitted in a previous term.

**Comment by eddyashton** [comment]
This is described in section 5.4.2 and figure 8 of [the Raft paper](https://raft.github.io/raft.pdf).

**Comment by achamayou** [comment]
Closing in favour #3971.
