### ISSUE TITLE
A joining node should try to connect to a set of nodes

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#398]
At the moment, the joining node only connects to a given node (`--target-rpc-address`) to join the network. When the service is open, it is possible that the join protocol takes a long time since members have to trust the joining node. In that case, some nodes fail and the joining node will not be able to join the network.

Instead, we should pass to the joining node a list of node addresses to connect to when joining.

**Comment by achamayou** [comment]
Although this is probably still nice to have, it's also likely the case that the dynamic DNS used to front the service (or an internal equivalent if node 2 node traffic is on a separate network) can be used for joining, as opposed to an interface specific to a particular node.

ie. `--target-rpc-address tpal.region.cloudapp.azure.com`

**Comment by achamayou** [comment]
Much like #397, this is in a slightly intermediary use case.
