### ISSUE TITLE
Separate/tag application logging from framework logging

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#4013]
Some users have expressed interest in being able to differentiate application-specific logging from framework-level logging.

This is easier to do in js_generic than for C++ applications, but something to investigate.

**Comment by achamayou** [comment]
We may want to look at logging libraries such as https://github.com/odygrd/quill, on platforms that aren't as restricted as SGX.

**Comment by eddyashton** [comment]
Application code from both JS and C++ is now tagged with `[app]`.
