### ISSUE TITLE
Bundle script for TS based applications fails on Windows OS.

### ISSUE THREAD

**Issue by caleteeter** [microsoft/CCF#4019]
**Describe the bug**
When bundling the Typescript sample application (/tests/npm-app) on a Windows system, the resulting bundled application fails when proposing to the network.  The issue is caused by the file path referenced in the name of the modules section of the bundle.  The `\\` should in fact be `/`.

example:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/8452367/178066789-9221e71b-988c-4643-b98e-88007850aa12.png">

**To Reproduce**
On a Windows system, clone the repo, run `npm run build` and include the bundled output from dist/ in a proposal for the js app. 

**Expected behavior**
Deployment of the bundle should complete if built on Windows or Linux based system.

**Environment information**
CCF version 2.0.0

**Additional context**

**Comment by jumaffre** [comment]
Fixed in #4020.
