### ISSUE TITLE
Move integration tests for ePBFT into CCF

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#403]
These tests could in consequence also test Raft.

We need to be able to test that (based on, but not limited to, the current things that are tested):

1. PBFT is setup successfully and requests are being processed
2. each of the requests that are being processed are not being processed out of order on any replica
3. by making the replicas sleep (stop accepting or sending any messages) for a random or specific amount of time we can trigger and test view changes and rollbacks
4. the client proxy is working correctly
5. the ledger is being written to and played back successfully
6. when f = 0 is set, requests are able to be processed without a full consensus round

**Comment by achamayou** [comment]
1. That is tested by any of the existing end to end tests. Running them against an ePBFT-enabled CCF should be enough.
2. Some of the tests already check state against backups/followers, so I think that's effectively already tested too. We can make sure of that and trivially modify the tests if necessary.
3. The best way to do this is to connect nodes via a pass through TCP proxy we can control.
4. Can you elaborate on this?
5. This is tested by adding nodes late.
6. Like 1, this is tested by being able to start up successfully.

**Comment by olgavrou** [comment]
The client proxy is responsible for 
- sending out the requests
- collecting the replies and when it has a sufficient amount replying to the client that issued them (which in our case would be a specific CCF node)
- retransmitting any requests that haven't been processed successfully

ePBFT has a separate test for the client proxy. It is however configured by default in CCF so if messages are not processed it could be accounted to the client proxy. Might not need anything extra but it is noted here as a reminder to make sure it is working as it should.

**Comment by achamayou** [comment]
It sounds like this can all be covered by unit tests. In integration tests, I would expect the correct processing of transactions to be enough evidence that it works. If you have specific integration tests in mind though, feel free to add them on the Issue of course.

**Comment by achamayou** [comment]
@olgavrou I believe this largely complete, with the exception of the pbft_controller_test, which I assume is an oversight since it's not run by the CI?

**Comment by olgavrou** [comment]
I think that the `pbft_controller_test` can be deleted actually @ashamis ?
