### ISSUE TITLE
Add CCF benchmark to TechEmpower/FrameworkBenchmarks

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#4030]
Now that we support HTTP (i.e. non-HTTPS) interfaces, we could add CCF to https://github.com/TechEmpower/FrameworkBenchmarks so that we have a reputable benchmark of our HTTP server implementation.

**Comment by rutvikk05** [comment]
Hello @jumaffre! I would like to work on this issue. Could you give me an idea on how to add CCF to the FrameWorkBenchmarks?
