### ISSUE TITLE
Support for gRPC

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#4034]
Now that we have (experimental) support for [HTTP/2](https://github.com/microsoft/CCF/issues/3342), we are able to build a gRPC sample application.

Depends on #3893 

Tasks:
- [x] Link libprotobuf for payload serialisation/deserialisation
- [x] Create gRPC adapter, similar to `ccf::json_adapter()` (to deserialise [gRPC header frame](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md))
- [ ] Stream support
   - [ ] Server -> Client: see https://github.com/microsoft/CCF/issues/4325
   - [ ] Client -> Server: see #4683

**Comment by jumaffre** [comment]
Using this issue to outline implications of gRPC stream support for CCF as discussed with @eddyashton. Further issues will be created for separate tasks. 

Bidirectional gRPC stream support requires both client (client -> server) and server (server -> client) streaming. While both are separate features (i.e. an endpoint can either support client streaming, server streaming or both), the design of both are discussed here.

**Client Streaming**

The first implication is that we should dispatch to an endpoint before the request has been entirely sent by the client (as detected [here](https://github.com/microsoft/CCF/blob/4b86f87786ae2970c7dc8f1cd6f1a41fdf2a4c27/src/http/http2.h#L142)). This is fine as the dispatching is done based on the `:path:` header, and we can dispatch when all headers have been received (i.e. when the first data frame is received). 

Then, we need to expose a new `Stream` object to the application endpoint (possibly created with a new `make_stream_endpoint()` or similar) so that the app can read from the stream as more data is received from the client. Because we currently don't have a way to yield execution from within the enclave and get called back when more data is available, it is probably preferable to call the endpoint for any new data that's received in, rather than wait from within the endpoint directly (like [here](https://groups.google.com/g/grpc-io/c/AlwaSuDTcoM/m/ep8V6S0oAgAJ)). We can revisit this when we have better async runtime support in the enclave.

**Server Streaming**

Assuming that client streaming has already been implemented, server streaming will require detaching the `Stream` object from the endpoint so that it can be written to asynchronously, e.g. from the indexer. 

-- 

Note that there's still much to explore in this area and that gRPC streaming will have to be implemented incrementally. Because of this, it's probably preferable to create a new type of interface that would abide by these rules so that the production interfaces (HTTP/1 and even unary HTTP/2) remain untouched.

**Comment by eddyashton** [comment]
> we currently don't have a way to yield execution from within the enclave

I've thought about this a little more, and wonder if we can support this in a limited way, to simplify these changes. I was hoping we could get it cheaply from C++20 coroutines - turn the handling of every ringbuffer message into a coroutine, so it can yield onto some pending task queue. To be clear this would give us asynchrony without (or independently from) concurrency. However C++20 coroutines don't work as I expected, so this is harder.

<details>

```
Task bar(TaskQueue& tq)
{
  std::cout << "  Beginning bar" << std::endl;
  co_await tq.schedule();
  std::cout << "  Ending bar" << std::endl;
}

main1()
{
  TaskQueue tq;
  std::cout << "AAA" << std::endl;
  Task t1 = bar(tq);
  std::cout << "BBB" << std::endl;
  tq.advance_all();
  std::cout << "Done" << std::endl;
}
```

Outputs:
```
AAA
  Beginning bar
BBB
  Ending bar
Done
```

Cool, as expected.

But what if we want to 'go async' somewhere down the stack?

```
void baz(TaskQueue& tq)
{
  std::cout << "  Beginning baz" << std::endl;
  bar();
  std::cout << "  Ending baz" << std::endl;
}
```

Outputs:
```
AAA
  Beginning baz
  Beginning bar
  Ending baz # WAT
BBB
  Ending bar
Done
```

So the way I see this now, is that the whole stack needs to have explicit knowledge of all called functions' coroutineness. That may be manageable, but is not what I expected.
</details>

**Comment by jumaffre** [comment]
Closing this issue as the remaining work (streaming) is covered by #4325 and #4683.
