### ISSUE TITLE
Investigate support for AMD SEV-SNP attestation

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#4035]
CCF should support requesting, and verifying SEV-SNP attestations.

Work Breakdown:

Attestation verification in standalone library (similar to OpenEnclave functionality)
- [x] Get a scriptable way to get and connect to an ACI container
- [x] Get quotes from the SEV-SNP platform
- [x] Parse quotes for verification
- [x] Write function to verify the quote (using AMD root of trust and certificate chain)

Follow-up work has been broken down in #4068, #4069, #4070, #4071, #4072.

**Comment by DomAyre** [comment]
Attestation verification in standalone library (similar to OpenEnclave functionality)
- [ ] Get a scriptable way to get and connect to an ACI container
- [ ] Get quotes from the SEV-SNP platform
- [ ] Parse quotes for verification
- [ ] Write function to verify the quote (using AMD root of trust and certificate chain)

Integrate library with CCF 
- [ ] Runtime check for presence of SEV-SNP platform 
- [ ] Verify node's quote when joining network using library
- [ ] Write example for how a user would verify a node

CI for CCF integration
- [ ] Add appropriate tests for implementation

[Optional?] 
- [ ] Support networks with SGX and SEV-SNP nodes in

**Comment by jumaffre** [comment]
I believe this is effectively done and follow-up tickets have been created to cover the work necessary to complete AMD SEV-SNP support for CCF.
