### ISSUE TITLE
CI setup for SEV-SNP enabled ACI

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#4070]
Once #4068 is complete, we should create an ACI setup to test the SEV-SNP variant of CCF in the CI. 

- [x] 1. Add SEV-SNP ACI CI agent (https://github.com/microsoft/CCF/pull/4171)
- [ ] #4619
- [ ] #4621
- [ ] #4620
- [ ] #4622

Risk: We may want to de-risk this early to make sure it is possible to the spin-up a SEV-SNP enabled ACI container with the existing version of the `azure-mgmt-containerinstance`.

**Comment by DomAyre** [comment]
Basic CI running as of https://github.com/microsoft/CCF/pull/4171

Additional tests for functionality should probably wait for/be done as part of changes to the attestation verification in https://github.com/microsoft/CCF/issues/4188 and https://github.com/microsoft/CCF/issues/4193

**Comment by achamayou** [comment]
@DomAyre the pool/jobs are only in the Daily build, but not in the CI, is that correct?

**Comment by achamayou** [comment]
@DomAyre can we close this, and roll the remaining items into a freshly named ticket?
