### ISSUE TITLE
CCF build failed from source code Oct 4, 2019

### ISSUE THREAD

**Issue by chantong-ubs** [microsoft/CCF#413]
Followed instruction from https://microsoft.github.io/CCF/getting_started.html. The build failed at "Building CCF". See attached file screen output

**Comment by chantong-ubs** [comment]
Screen output
[building-ccf.txt](https://github.com/microsoft/CCF/files/3691686/building-ccf.txt)

**Comment by achamayou** [comment]
@chantong-ubs sorry, the build instructions may be unclear, you will need to check out submodules (git clone —recursive) to get all the files you need for a build.

I will update the documentation.

**Comment by chantong-ubs** [comment]
I was using download source zip file, not using git clone. What's the right way to get latest source code?
    On Friday, October 4, 2019, 02:48:08 PM EDT, Amaury Chamayou <notifications@github.com> wrote:  
 
 
@chantong-ubs sorry, the build instructions may be unclear, you will need to check out submodules (git clone —recursive) to get all the files you need for a build.

I will update the documentation.

**Comment by achamayou** [comment]
Running git clone --recursive https://github.com/microsoft/CCF.git should give you a checkout with  submodules.

**Comment by chantong-ubs** [comment]
Thanks. Followed the getting start guide, I can build CCF https://microsoft.github.io/CCF/getting_started.html.
The instruction for creating a new network is not clear https://microsoft.github.io/CCF/start_network.html.How to generate member-certs for 5 members?$ cchost --enclave-file /path/to/enclave_library --enclave-type debug
--node-address node_ip:node_port --rpc-address rpc_ip:rpc_port
--public-rpc-address public_rpc_ip:public_rpc_port --ledger-file /path/to/ledger
--node-cert-file /path/to/node_certificate --quote-file /path/to/quote
start --network-cert-file /path/to/network_certificate --gov-script /path/to/lua/governance_script
--member-certs member_certificates_glob




    On Friday, October 4, 2019, 06:24:23 PM EDT, Amaury Chamayou <notifications@github.com> wrote:  
 
 
Running git clone --recursive https://github.com/microsoft/CCF.git should give you a checkout with submodules.

**Comment by achamayou** [comment]
@chantong-ubs The easiest way to do that is to run `./keygenerator --name=member1`, under the build directory, this will generate a public/private key pair for a member with filenames prefixed with "member1".

Alternatively, you should be able to use openssl, `openssl ecparam -name secp384r1`, but that isn't covered in our tests at the moment.

**Comment by chantong-ubs** [comment]
All these should be in the document, but it's not there and I need to ask. After building CCF no error, I ran into 2 problems
Problem #1,-----------------------------------+ ./cchost --enclave-file ./libluagenericenc.so.signed --enclave-type debug --node-address 10.0.0.4:44180 --rpc-address 10.0.0.4:25000 --public-rpc-address 13.82.180.233:25000 --ledger-file 0.log --node-cert-file 0.pem --quote-file quote0.bin start --network-cert-file network_cert.pem --gov-script ./madrec_gov.lua --app-script ./madrec_app.lua --member-certs member1_cert.pem
01:19:27:609944 tid(0x7f79133b4bc0) (H)[ERROR]enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1) (oe_result_t=OE_PLATFORM_ERROR)[../host/sgx/sgxload.c oe_sgx_create_enclave:535]01:19:27:609985 tid(0x7f79133b4bc0) (H)[ERROR]:OE_PLATFORM_ERROR[../host/sgx/create.c oe_sgx_build_enclave:558]01:19:27:610178 tid(0x7f79133b4bc0) (H)[ERROR]:OE_PLATFORM_ERROR[../host/sgx/create.c oe_create_enclave:681]2019-10-08T01:19:27.610208Z        [fatal] ../src/host/enclave.h:74             | Could not create enclave: OE_PLATFORM_ERRORterminate called after throwing an instance of 'std::logic_error'  what():  Fatal: 2019-10-08T01:19:27.610208Z        [fatal] ../src/host/enclave.h:74             | Could not create enclave: OE_PLATFORM_ERROR
./create-new-network.sh: line 20: 10968 Aborted                 (core dumped) ./cchost --enclave-file ./libluagenericenc.so.signed --enclave-type debug --node-address $host_ip:$raft_port --rpc-address $host_ip:$tls_port --public-rpc-address $pub_host_ip:$tls_port --ledger-file $node_id.log --node-cert-file $node_id.pem --quote-file quote$node_id.bin start --network-cert-file network_cert.pem --gov-script ./madrec_gov.lua --app-script ./madrec_app.lua --member-certs member1_cert.pem
Problem #2,------------------------------------OK, after I generated 5 member key stores and follow the document, but it did not recognize more than one member keys. I followed the doc https://microsoft.github.io/CCF/start_network.html
[Shell command line]
./cchost --enclave-file ./libluagenericenc.so.signed --enclave-type debug --node-address $host_ip:$raft_port --rpc-address $host_ip:$tls_port --public-rpc-address $pub_host_ip:$tls_port --ledger-file $node_id.log --node-cert-file $node_id.pem --quote-file quote$node_id.bin start --network-cert-file network_cert.pem --gov-script ./madrec_gov.lua --app-script ./madrec_app.lua --member-certs member*_cert.pem

[Shell command line - debug]+ ./cchost --enclave-file ./libluagenericenc.so.signed --enclave-type debug --node-address 10.0.0.4:44180 --rpc-address 10.0.0.4:25000 --public-rpc-address 13.82.180.233:25000 --ledger-file 0.log --node-cert-file 0.pem --quote-file quote0.bin start --network-cert-file network_cert.pem --gov-script ./madrec_gov.lua --app-script ./madrec_app.lua --member-certs member1_cert.pem member2_cert.pem member3_cert.pem member4_cert.pem member5_cert.pem
[Error Response]The following arguments were not expected: member5_cert.pem member4_cert.pem member3_cert.pem member2_cert.pemRun with --help for more information.

    On Monday, October 7, 2019, 05:40:26 PM EDT, Amaury Chamayou <notifications@github.com> wrote:  
 
 
Reopened #413.

**Comment by chantong-ubs** [comment]
Please ignore the problem #1. After I restarted the Azure VM, no more problem on OE-PLATFORM_ERROR. Not sure why.
There were few problems related to documentation errors. I'm still go through step by step.For "Add Users" step, the document 1. Did not use ".pem" file extension2. Misspell "user_cert"3. Did not mention about gov script+ ./memberclient --cert member1_cert.pem --privk member1_privk.pem --rpc-address 10.0.0.4:25000 --ca network_cert.pem add_user --user-cert user1_cert.pem{"error":{"code":-32603,"message":"[INTERNAL_ERROR]: Could not find gov script: pass"},"id":0,"jsonrpc":"2.0"}
    On Monday, October 7, 2019, 09:34:06 PM EDT, Chan Tong <chantong00@yahoo.com> wrote:  
 
  All these should be in the document, but it's not there and I need to ask. After building CCF no error, I ran into 2 problems
Problem #1,-----------------------------------+ ./cchost --enclave-file ./libluagenericenc.so.signed --enclave-type debug --node-address 10.0.0.4:44180 --rpc-address 10.0.0.4:25000 --public-rpc-address 13.82.180.233:25000 --ledger-file 0.log --node-cert-file 0.pem --quote-file quote0.bin start --network-cert-file network_cert.pem --gov-script ./madrec_gov.lua --app-script ./madrec_app.lua --member-certs member1_cert.pem
01:19:27:609944 tid(0x7f79133b4bc0) (H)[ERROR]enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1) (oe_result_t=OE_PLATFORM_ERROR)[../host/sgx/sgxload.c oe_sgx_create_enclave:535]01:19:27:609985 tid(0x7f79133b4bc0) (H)[ERROR]:OE_PLATFORM_ERROR[../host/sgx/create.c oe_sgx_build_enclave:558]01:19:27:610178 tid(0x7f79133b4bc0) (H)[ERROR]:OE_PLATFORM_ERROR[../host/sgx/create.c oe_create_enclave:681]2019-10-08T01:19:27.610208Z        [fatal] ../src/host/enclave.h:74             | Could not create enclave: OE_PLATFORM_ERRORterminate called after throwing an instance of 'std::logic_error'  what():  Fatal: 2019-10-08T01:19:27.610208Z        [fatal] ../src/host/enclave.h:74             | Could not create enclave: OE_PLATFORM_ERROR
./create-new-network.sh: line 20: 10968 Aborted                 (core dumped) ./cchost --enclave-file ./libluagenericenc.so.signed --enclave-type debug --node-address $host_ip:$raft_port --rpc-address $host_ip:$tls_port --public-rpc-address $pub_host_ip:$tls_port --ledger-file $node_id.log --node-cert-file $node_id.pem --quote-file quote$node_id.bin start --network-cert-file network_cert.pem --gov-script ./madrec_gov.lua --app-script ./madrec_app.lua --member-certs member1_cert.pem
Problem #2,------------------------------------OK, after I generated 5 member key stores and follow the document, but it did not recognize more than one member keys. I followed the doc https://microsoft.github.io/CCF/start_network.html
[Shell command line]
./cchost --enclave-file ./libluagenericenc.so.signed --enclave-type debug --node-address $host_ip:$raft_port --rpc-address $host_ip:$tls_port --public-rpc-address $pub_host_ip:$tls_port --ledger-file $node_id.log --node-cert-file $node_id.pem --quote-file quote$node_id.bin start --network-cert-file network_cert.pem --gov-script ./madrec_gov.lua --app-script ./madrec_app.lua --member-certs member*_cert.pem

[Shell command line - debug]+ ./cchost --enclave-file ./libluagenericenc.so.signed --enclave-type debug --node-address 10.0.0.4:44180 --rpc-address 10.0.0.4:25000 --public-rpc-address 13.82.180.233:25000 --ledger-file 0.log --node-cert-file 0.pem --quote-file quote0.bin start --network-cert-file network_cert.pem --gov-script ./madrec_gov.lua --app-script ./madrec_app.lua --member-certs member1_cert.pem member2_cert.pem member3_cert.pem member4_cert.pem member5_cert.pem
[Error Response]The following arguments were not expected: member5_cert.pem member4_cert.pem member3_cert.pem member2_cert.pemRun with --help for more information.

    On Monday, October 7, 2019, 05:40:26 PM EDT, Amaury Chamayou <notifications@github.com> wrote:  
 
 
Reopened #413.

**Comment by jumaffre** [comment]
@chantong-ubs Many thanks for reporting this issue and I'm glad that you managed to resolve the `OE_PLATFORM_ERROR` issue. I will update the documentation according to your feedback, so that it benefits other users as well.

Regarding the governance script, the `{"code":-32603,"message":"[INTERNAL_ERROR]: Could not find gov script: pass"},"id":0,"jsonrpc":"2.0"}` error you are seeing is due to the governance script you are using (`madrec_gov.lua`) that is now outdated. Your `quorum` script should be replaced by the `pass` script. The rules of your consortium may vary but for a strict majority rule, you should be able to copy-paste the `pass` script in our example `gov.lua` file (https://github.com/microsoft/CCF/blob/master/src/runtime_config/gov.lua#L6-L45) in your `madrec_gov.lua` file.

**Comment by jumaffre** [comment]
@chantong-ubs The documentation (https://microsoft.github.io/CCF/getting_started.html and https://microsoft.github.io/CCF/start_network.html) has been updated based on your feedback. Many thanks!
