### ISSUE TITLE
Lua applications do not support notifications

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#415]
Lua applications do not yet support notifications like C++ applications do.

**Comment by eddyashton** [comment]
I'm not sure if we want to support this? Lua applications also don't support hooks or non-kv (node-local) state. I think these limitations are fine - the lua app is closer to the pure, minimal API we want to expose.

We've not found many use cases for notifications, so I don't think its worth exposing this (or other complexities) to the Lua app until they're firmly established in the C++ application model.

**Comment by achamayou** [comment]
@eddyashton agreed, notifications exist for a very narrow purpose at the moment, it's not clear that there is a use-case for them being part of the general programming model.
