### ISSUE TITLE
Multi-container: Dispatch incoming requests efficiently to appropriate executor

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4156]
For initial implementation (with HTTP transport), we can simply iterate through all registered executors, and choose the first match. Additionally, we can queue all client requests and actually provide them on polls from each executor, if that's easier for now. With gRPC, we should be able to dispatch and queue as each request comes in.

Eventually I think we should use [r3](https://github.com/c9s/r3) for this, though I haven't worked out exactly how/when we compile the prefix trie.

**Comment by eddyashton** [comment]
Still trying to work out how we do this efficiently. The problem is that each executor can be registered for a unique but overlapping set of paths, so we might have an initial registration of something like this:

```
{
  "A": [               "POST /foo/B", "POST /foo/C", ...],
  "B": ["POST /foo/A",                "POST /foo/C", ...],
  "C": ["POST /foo/A", "POST /foo/B",                ...],
  ...
}
```

(Note that if we use r3, then I think the slugs/templates in this don't make it any more complex. If we don't, then they are probably an additional complexity).

Then separately, we want some kind of priority for each URL for fair dispatch, so we can move an executor to the end of the queue once it has handled a request.

So when a `POST /foo/B` request, we might have an initial executor list of `["A", "C", ...]`, decide to dispatch to `"A"`, and update this list to `["C", ..., "A"]`.

The problem is, we'd _also_ like A to move to the back of the list for `POST /foo/C` requests, so that `["A", "B", ...]` bcomes `["B", ... "A"]`.

So we can obviously do better than a linear scan through either executors or URLs, with a table lookup (or r3 dispatch) - modified rarely, going from URLs to a collection of supporting executors. But then it looks like we have a linear pass through that collection of executors, with associated locking, to re-prioritize. I'm wondering if there's some kind of sparse multi-heap that can do this better.

**Comment by eddyashton** [comment]
2 more thoughts:

- We could think of a single ordered list of all executors, so that we're only bumping an executor to the end of one list. But I can't see how to do dispatch in that model (ie - efficient lookup from URL to the collection of supporting executors), that doesn't devolve to maintaining some separate sorted collection which must also be updated.
- The case above is pessimal and unrealistic. In most cases we expect to have multiple executors implementing the same _set_ of endpoints. If we can canonicalise this set, we can map it to a single ordered collection of supporting executors, and the update cost is then linear in the number of these sets rather than the total number of endpoints.

**Comment by eddyashton** [comment]
After discussion with @achamayou, its clear that much of the complexity here comes from allowing multiple different executor code IDs to register for _overlapping_ sets of URLs. There isn't actually a strong use case for this - it may be useful for live upgrading executors, but not critical.

If we instead think about a single configuration of "external executor dispatch metadata" (whether that's _stored_ as a single document or how it's keyed in the KV doesn't fundamentally matter, just that we can enforce global properties like unambiguous dispatch on it), then it's clearer that we can build dispatch tables from this to single buckets of executors. New executor instances are trivially assigned to such a bucket, and each dispatch decision only affects a single bucket.

From there, we will assume initially that dispatch is _purely_ determined by governance and executor code ID, and save the additional complexity of per-executor (instance) URLs/dispatch for later. Even within that, we can take a stepped approach - allowing executor instances to register for a _single_ URL (permitted by their attestation's dispatch constraints) allows some work balancing amongst homogeneous dispatchers (ie - caps on how many serve operation `/foo`), without introducing the additional dispatch complexity of registering for a subset of URLs. If and when we have an ask for that, we can determine whether linear lookup within the buckets defined above is too inefficient.

**Comment by eddyashton** [comment]
Problems with r3:

- No releases [since 2015](https://github.com/c9s/r3/tags) (1.3.4 - current default branch is `2.0`, but untagged/unreleased)
- Inline use of zmalloc

It looks like the latter dependency was removed in 2018, so I'll try a more recent untagged commit. But the library will need to be extremely nice to justify this level of inclusion awkwardness.

**Comment by achamayou** [comment]
@eddyashton possible alternatives:

https://github.com/nginx/nginx/blob/a64190933e06758d50eea926e6a55974645096fd/src/core/ngx_radix_tree.h
https://github.com/lighttpd/lighttpd2/blob/850aea7a5d761e17cca5966a0d5434dee4bd942d/include/lighttpd/radix.h
https://github.com/lpereira/lwan/blob/master/src/lib/lwan-trie.h

**Comment by achamayou** [comment]
Related to external executors, not currently an area of active work.
