### ISSUE TITLE
Multi-Container: Build a long-lived Tx context

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4157]
To actually implement the server-side API defined in #4153, CCF needs to persists a `Tx` across multiple incoming requests. This is awkward if we think of it as an app in the current HTTP model, so may require pushing some implementation up the stack. That in turn may require separating executor traffic from client traffic very early.

**Comment by MahatiC** [comment]
@eddyashton looks like we can close this as we have tickets for other follow-ups?

**Comment by eddyashton** [comment]
Yes, this should have been closed with #4218.
