### ISSUE TITLE
Multi-Container: Build an initial demo

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4158]
Most of the work for this is covered by other tickets, but using this as a hold-all for remaining work towards an MVP demo.

Additional work I see for this demo specifically:
- Writing a simple executor, and some infra help to operate it
- Breaks from our intended gRPC API for basic gRPC compatibility (ie - no streaming responses means polling requests, no long-lived gRPC blocking server calls means regular Ready polling by clients)
- Timers and timeouts for pending client requests, to check that additional error handling can be added in future

**Comment by shokouedamsr** [comment]
- [ ] Document the python test and turn it into a sample.
