### ISSUE TITLE
Multi-Container: Separate executor traffic from client traffic

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4161]
For a first-pass, I think we have executors speaking to CCF over the client API, interleaved with client traffic. Eventually we want to expose these separately, both for API clarity (clients can't call executor 'endpoints', and vice versa), protocol clarity (executor traffic is always gRPC), and dispatch efficiency (the earlier we recognise executor requests, the earlier we can do something custom for them).

**Comment by achamayou** [comment]
Not under active consideration, as the work on external executor is suspended.
