### ISSUE TITLE
Signed RPCs on Read handlers fail with TX_FAILED_TO_REPLICATE on backups

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#417]
When issuing signed transactions on `Read` handlers against a follower, transactions fail with `TX_FAILED_TO_REPLICATE`. This is because the client signature is recorded in the ledger (https://github.com/microsoft/CCF/blob/master/src/node/rpc/frontend.h#L930) no matter if the target node is the primary or a backup. 

I guess this explains why the `balance` endpoint of the small bank application is marked as `Write` (in that case, the transaction is forwarded without being committed).

**Comment by eddyashton** [comment]
This describes the same problem outlined in #215, but this gives a more general and concise description.
