### ISSUE TITLE
Missing dependency: build claims it "cannot find protobuf compiler"

### ISSUE THREAD

**Issue by TheBankster** [microsoft/CCF#4206]
**Describe the bug**
CCF will not compile for lack of "protobuf compiler".

**To Reproduce**
Attempt the build-from-source steps and observe a compilation error:

-- CCF version = ccf-3.0.0-dev2-29-geb9da017
-- CCF release version = 3.0.0
-- CCF version suffix = dev2-29-geb9da017
-- Debian package will include suffix: 3.0.0~dev2-29-geb9da017
-- CMAKE_INSTALL_PREFIX is '/opt/ccf'
-- Looking for crypto library - found
-- Looking for dl library - found
-- QuickJS prefix: /home/zb/ccf/3rdparty/exported/quickjs version: 2021-03-27
-- Using sss at /home/zb/ccf/3rdparty/internal/sss
CMake Error at cmake/common.cmake:12 (_message):
  Cannot find protobuf compiler: /opt/protoc/bin/protoc
Call Stack (most recent call first):
  src/apps/external_executor/protobuf/CMakeLists.txt:10 (message)

**Expected behavior**
Build completing successfully. Note that I can run "protoc" on the machine, but it is not in the directory where the build is looking for it.

**Environment information**
Fresh Ubuntu LTS 20.04 running in a Microsoft Azure VM.

**Additional context**
N/A
[CMakeOutput.log](https://github.com/microsoft/CCF/files/9530799/CMakeOutput.log)
[CMakeError.log](https://github.com/microsoft/CCF/files/9530800/CMakeError.log)

**Comment by jumaffre** [comment]
@TheBankster thanks for raising this. `protoc` was recently added to our dependencies to be able to build gRPC apps. You can install it on your system by re-running the [steps described here](https://microsoft.github.io/CCF/main/contribute/build_setup.html#environment-setup).

Separately, may I ask why you are building CCF from source? Building the entire framework from source isn't what we recommend to our users and instead provide a CCF debian package on our release page (latest one is currently [2.0.7](https://github.com/microsoft/CCF/releases/tag/ccf-2.0.7)) to build applications. The steps described on [this separate, minimal repo](https://github.com/microsoft/ccf-app-template) should help you get started in a much quicker way. In the meantime, I will make sure this is more clearly signposted on this repository.

**Comment by TheBankster** [comment]
Hello, thank you for that information. The reason I was building CCF from source is because I wanted to step through some of its governance logic, since I am working on building per-application governance and wanted to see how much I can learn from the existing code. Looking closer at the log, the root cause of the error appears to be a compilation failure, with protobuf being a downstream failure in the reporting path. I suppose it's not super urgent, but it would be good to have the compilation of CCF from source work per the instructions given. Once you get it working, please update me.

**Comment by TheBankster** [comment]
The build is running now. This issue can be closed. Thank you.
