### ISSUE TITLE
Metrics should be moved out of `EndpointRegistry`, and managed as a SubSystem

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4207]
The per-endpoint metrics (number of calls, error, retries) has been a weird bridge between the `Frontend` and the `EndpointRegistry` for a while - primarily owned and updated by the `Frontend`, but available for the `EndpointRegistry` to call. It currently lives on the `EndpointRegistry`, meaning its implementation is visible to all apps, and they could even call `increment_metrics_*`. We have a better way to own + expose things like this now - as a `subsystem`. I think this should even be a private subsystem, as the only use case we have for exposing individual metrics is in the `node_frontend`.

**Comment by achamayou** [comment]
@eddyashton I think we need to revisit whether metrics are worth keeping or not, now that we are going to log per-endpoint. @lynshi what do you think?

**Comment by achamayou** [comment]
- [ ] Check endpoint logging is comprehensive enough, and if so, remove `/api/metrics` now that users have confirmed that it is unused.

**Comment by eddyashton** [comment]
Resolved by #6283.
