### ISSUE TITLE
Expose a way for indexing strategies to get the commit evidence of the TxID.

### ISSUE THREAD

**Issue by plietar** [microsoft/CCF#4248]
**Is your feature request related to a problem? Please describe.**
See #4247

**Describe the solution you'd like**
In order to compute a receipt, an indexing strategy needs the signature, the inclusion proof and the commit evidence.
The first two are covered by #4247.

Because indexing strategies are only called with globally committed transactions, I believe it would be safe to pass that evidence as a new argument to `handle_committed_transaction`, or alternatively provide a way to compute it lazily if doing it for every transaction is too expensive.

**Comment by achamayou** [comment]
Not under active consideration.
