### ISSUE TITLE
Add a public interface to create a KV Store for unit tests.

### ISSUE THREAD

**Issue by plietar** [microsoft/CCF#4263]
**Is your feature request related to a problem? Please describe.**
We have a CCF app, where parts of our code take in a `kv::Tx` argument and perform operations on it.
We'd like to write unit tests for this component, but there is no public API in `ccf_kv` to create a `Tx` out of thin air.

**Describe the solution you'd like**
- Define a new abstract class `kv::WritableStore` with a small subset of `kv::Store`'s methods (`create_tx` is probably all I need). This class would be an extension of the already public `kv::ReadOnlyStore`.
- Add a `std::unique_ptr<kv::WritableStore> kv::create_store()` function that creates a concrete `kv::Store` and returns it.

Our unit tests would now be able to create a store, create transactions and call the code being tested with it.

This is a common pattern inside the CCF code base already, where unit tests default-construct a `kv::Store`, eg. https://github.com/microsoft/CCF/blob/main/src/node/test/history.cpp#L72-L76

**Describe alternatives you've considered**
I could probably mock the Tx class in my project with my own implementation, but even the simplest possible version still needs to support typed maps, singletons, serialization, ... which would lead to a lot of duplicated code between CCF KV and the mock.

**Additional context**
The `kv::Store` used to be defined in public headers, until #3632. I understand the change, and the desire to make everything hidden by default, but I think having the bare minimum available would be worth it.

**Comment by eddyashton** [comment]
@plietar Thanks for speccing this out - this is a very sensible addition to the framework.

I was wary of exposing a `Tx` directly, as this requires giving the test writer access to a `commit()` function, and they'll still need to have some common code for specifying transactions, mimicking the commit flow, etc. Approaching from the other end, we could write a stub that allowed you to put your entire app inside a unit test (ie - we'd call `make_user_endpoints`), and specify the test flow as individual HTTP requests and assertions on the responses. This would test the entire parsing and execution flow, independently of network transmission/node spin-up, but still doesn't support testing snippets/components of your code in isolation.

I'll give this a little more thought and get back to you.

**Comment by plietar** [comment]
You're right, I hadn't considered the fact that a bare `Tx` has no way of committing.

> they'll still need to have some common code for specifying transactions, mimicking the commit flow, etc

Is there much to do other than exposing ComittableTx and calling its `commit()` function?

----

I'd initially thought I didn't care about concurrent transactions, and in this restricted test API anything that fails to commit should eg. throw an exception. However, I've reconsidered that, and I think there might be cases where a fallible commit is useful in tests. Concurrency in this case is actually just one test thread creating multiple transactions in order to exhibit a particular edge-case.

For example I may be interested in testing what happens in this scenario:
```c++
auto tx1 = store->create_tx();
auto tx2 = store->create_tx();
foo(tx1);
foo(tx2);
EXPECT_EQ(tx2.commit(), CommitResult::SUCCESS); // Tx2 is committed first, despite having been executed second.
EXPECT_EQ(tx1.commit(), CommitResult::FAIL_CONFLICT);
```

If `foo` only writes to the Tx, both transactions would succeed, which may be undesirable depending on the application. I'd like to be able to write a unit test that makes sure the foo function has the right read-dependencies to block this.

----

I don't think we currently have a strong need for request-level testing, since I can do most of it with end-to-end tests. It certainly makes some tests cheaper to write, but wouldn't be as much of an improvement IMO compared to the ability to create a `Store` and `Tx`.

**Comment by achamayou** [comment]
Although this would be nice, we don't have the bandwidth to build and maintain this extra interface. We'll focus on improving end to end test support instead.
