### ISSUE TITLE
CCF should contain a member-accessible table to bootstrap app-level governance

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#431]
We want to support multiple roles within a CCF app. Some users are admins and can access certain endpoints, others are unprivileged normal users. Eventually, we may support this by offering multiple app frontends, but then it is awkward to grant them access to the same tables.

The problem is bootstrapping these in-app permissions. All users are created with the same permissions, how do we determine which are admins? I believe the solution is to create a new table in the member frontend, mapping UserIDs to json objects. The members can propose and vote on writes to this table, setting arbitrary properties for a specific user (eg - declaring that they are an admin). Then the app can read from this table to determine an initial set of admins, and further alterations to add/remove admins or make any other app-level governance decisions can be made by the current admins.

**Comment by achamayou** [comment]
Addressed by creating the user_data table.
