### ISSUE TITLE
Create app dev Docker image for JS

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#4364]
We should create a new `ccf/app/dev` Docker image that includes NodeJS so that app developers don't have to build an image manually (e.g. https://github.com/microsoft/ccf-app-template/blob/main/.devcontainer/Dockerfile) to reduce development friction.

We can either include NodeJS in the existing image `ccf/app/dev` image (easy to do but bloats the dev image for C++ developers) or release a new `ccf/app/dev-js` image (that first needs to be added to https://github.com/microsoft/mcr/blob/main/teams/ccf/ccf.yml and https://github.com/microsoft/mcrdocs/tree/main/teams/ccf), as well as our ACR instance.

**Comment by achamayou** [comment]
I'm not sure we want to do that, we'll need to stay on top of node versions. Can this perhaps be done in ccf app samples, decoupled from CCF versions?

**Comment by achamayou** [comment]
This is covered by the dev container in https://github.com/microsoft/ccf-app-samples now.
