### ISSUE TITLE
Random number / id generation solution

### ISSUE THREAD

**Issue by RokasAidukas-Centric** [microsoft/CCF#4366]
Hi, whilst working with CCF (Typescript app), I could not find a solution anywhere that would allow me to generate random IDs or random numbers. 

My problem was that I wanted to create objects in the KV and using UUIDs as their keys, however I tried using many different libraries: [nanoid](https://github.com/ai/nanoid), [crypto](https://nodejs.org/api/crypto.html) from node.js, [crypto-js](https://github.com/brix/crypto-js), [uuid](https://github.com/uuidjs/uuid), [uuidjs](https://github.com/LiosK/UUID.js) and none of them worked for me, the only lib that didn't cause any breaking issues was [uuid](https://github.com/uuidjs/uuid), but worked is put loosely since it didn't give me any errors but the UUIDs it generated were basically all filled with zeroes. Which then I realized Math.random() also doesn't work (always returns 0), since it was the fallback method for [uuid](https://github.com/uuidjs/uuid).

At the most minimal sense, even a solution like `Math.random()` or better yet, a random ID (in a UUID form ideally) generator would be nice to have. Basically since I looked around the API and I only saw methods to generate things like RSA keys, AES keys, etc, but not something simple as generating secure IDs.

Of course I may have totally missed something, in which case do let me know if you guys have anything similar implemented.

Thanks!

**Comment by achamayou** [comment]
@RokasAidukas-Centric `Math.random()` should be fixed in [3.0.0-dev6](https://github.com/microsoft/CCF/releases/tag/ccf-3.0.0-dev6) #4313, could you give another try and let us know if you hit any issues?

**Comment by RokasAidukas-Centric** [comment]
@achamayou of course, will let you know.

**Comment by RokasAidukas-Centric** [comment]
Works like a charm! Thanks @achamayou!
