### ISSUE TITLE
Add a test for QuickJS runtime options

### ISSUE THREAD

**Issue by MahatiC** [microsoft/CCF#4371]
As mentioned here https://github.com/microsoft/CCF/pull/4344#discussion_r998019139

**Comment by MahatiC** [comment]
@achamayou Julien pointed out the existing test for this https://github.com/microsoft/CCF/blob/main/tests/js-custom-authorization/custom_authorization.py#L43-L69

The test values don't seem to match with the defaults set in the code though.  I'm not yet sure at this point how the default values were derived.

**Comment by achamayou** [comment]
@MahatiC the idea is to allocate _a lot less_ than the limit, check it works, and _more_ than the limit, and check it fails.

**Comment by achamayou** [comment]
For the stack size limit, an (large) recursive call is probably the best way to go.

**Comment by MahatiC** [comment]
Sure that makes sense, and I assume the current default heap size of 100 * 1024 * 1024 in the code was derived empirically?

**Comment by achamayou** [comment]
Yes, I think it was our default enclave heap size for a long time.

**Comment by achamayou** [comment]
Done in #5594  and #5668
