### ISSUE TITLE
Avoid users' builds failing because they did not check out submodules

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#439]
Follow up from #413 

- [x] --recursive is only mentioned in the NoSGX section, but it applies either way
- [x] let's see if we can add a bit of logic to CMake to give a helpful error message "Your checkout is missing submodules, please run git submodule update --remote --init, or clone a fresh repository with git clone --recursive"

**Comment by eddyashton** [comment]
I think the recommended submodule command should be `git submodule update --recursive --remote --init`. We don't actually have any recursive submodule dependencies at the moment, but we may in future.

**Comment by achamayou** [comment]
Good point, and I also think we don't want --remote, we want the recorded commit at that version instead.

**Comment by achamayou** [comment]
First item addressed by #460
