### ISSUE TITLE
Investigate skipped tests

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4405]
We're still skipping a surprising number of tests in the CI, often due to `Missing required methods`, and I believe this is unintentional.

In particular, it looks like the `js` tests are skipping most of their tests due to the wrong app running.

We should ensure we're actually running the tests we intend to most of the time, and perhaps revisit some of the requirements - rather than skipping if a requirement isn't met, we could modify the network so the requirement is met (eg - add or remove nodes, change the app).

**Comment by achamayou** [comment]
Let's also make sure the wrappers are disabled outside the suite.
