### ISSUE TITLE
Offline TxID committed checking

### ISSUE THREAD

**Issue by jeffa5** [microsoft/CCF#4455]
**Is your feature request related to a problem? Please describe.**

When we have a transaction id of something we're waiting to be committed, and the latest committed transaction id we can't easily confirm the status of the transaction id locally, we need to ask the node to confirm it.

e.g. given a transaction id of `3.5` and a committed transaction id of `3.6` we can't tell whether our transaction id was committed or dropped since we don't know if `3.6` is the first txid in term `3` or whether the term started earlier (it could be `2.5` that was committed).

**Describe the solution you'd like**

A function available to c++ code that exposes the highest seqno a node has seen in a given raft term, something like

```c++
ApiResult get_last_committed_txid_for_view_v1(ccf::View& view, ccf::SeqNo& seqno);
```

**Describe alternatives you've considered**

Just asking nodes for the status of a transaction id but this includes round trips and doesn't enable offline checking.

**Comment by achamayou** [comment]
I'm not sure I understand the offline bit. If this function existed, wouldn't you still need to query the service to know the highest committed txid for a view? For the current view, it doesn't seem like it would help at all?

We could extend the /commit endpoint, so that /commit?view_history=true returns something like

```
committed: 5.18
views:
  - 2.1
  - 3.15
  - 5.17
```

which would allow a client to work out if anything transaction X.Y where Y <= 18 is committed. That still requires a call though?

**Comment by jeffa5** [comment]
Yes, so I was imagining that it requires a call to get the initial data but then that can be kept and used for checking multiple different txids over time, with periodic refreshes.

That commit endpoint looks reasonable, just might get to be quite large and you might already have a partial cache. It would be nicest at first to have this in the C++ as initially described so that we can make our own endpoints with it and work out a best way to use it.

**Comment by heidihoward** [comment]
I think a commit view history endpoint (containing the TxIDs where the views changed) would at least be helpful for testing/benchmarking. It would still require a call to the endpoint but a single call could be used to determine if many TxIDs were committed.

**Comment by achamayou** [comment]
We can have both, it's typically the case that we expose a  C++ API for people who want nobuiltin (or gRPC now, I guess), and then a generic endpoint that returns the C++ call's output in JSON, for end-to-end testing and folks who want built-ins.
