### ISSUE TITLE
ci-checks.sh -f fails with write permission error

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/CCF#4512]
**Describe the bug**
Before submitting a PR you can run `./scripts/ci-checks.sh -f` to fix any linting/formatting issues. However when running this you receive an error and it does not fix the formatting errors.

**To Reproduce**
- Add an extra line in README.md markdown file
- run `./scripts/ci-checks.sh -f` 
- Look in the output

```
[error] Unable to write file: README.md
[error] EACCES: permission denied, open 'README.md'
```

**Expected behavior**
The script should fix simple linting/formatting issues

**Environment information**
This is a permissions devcontainer issue 

**Additional context**
This is really low priority!

**Comment by achamayou** [comment]
@ross-p-smith is this something that happens only in devcontainers? I'm confused as to why the files mounted there would not be writeable, or README.md would be different from the rest of the files in the repo?

ci-checks.sh will not attempt to elevate, it only ever runs as the current user, so this sounds like a devcontainer set up issue? We don't do anything special permission-wise there, afaict.

**Comment by achamayou** [comment]
Cannot reproduce.
