### ISSUE TITLE
Update TLA+ base image to have some dependencies included

### ISSUE THREAD

**Issue by DomAyre** [microsoft/CCF#4532]
Things like these that aren't upgraded frequently (ie. unlike the nightly tla build) are best put in the base image eventually, rather than installed every time.

_Originally posted by @achamayou in https://github.com/microsoft/CCF/pull/4523#discussion_r1020296025_

**Comment by achamayou** [comment]
In light of the recent issues with out of date dependencies in images being flagged by internal systems, I think we no longer want to do this.
