### ISSUE TITLE
Revisit Raft batching behaviour

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4544]
Discussed briefly in #4415:

> I think the original batching logic is really covering 2 things; splitting a large AE into manageable chunks, and deciding to eagerly send AEs
> We should separate out the last part. I think the latter is a feature worth keeping, but we should be eagerly (ie - inline during replicate) sending AEs for committable entries, and nothing else. For the former, I think the dynamic heuristic approach we have at the moment has risky pessimal cases and is poorly measured - we should either implement a simpler approach based on known tx counts ("remove it entirely" is ~~this~~ #4415, but maybe "only send 1000 txs at a time" is reasonable too?), or find a way to accurately measure all historical tx sizes (likely an in-enclave cache paired with some communication protocol with the host).

**Comment by achamayou** [comment]
After investigation, the current situation seems like a reasonable way to make replication safe against large entries without impacting performance too much.
