### ISSUE TITLE
Guide on deploying CCF in a multi region environment

### ISSUE THREAD

**Issue by julian-trustgrid** [microsoft/CCF#4574]
Not specifically a feature request but I want to get some insights on how can CCF support multi-region deployment. To give some context, we are looking at CCF as a private blockchain solution where the nodes are distributed across different geographic locations.

**Comment by achamayou** [comment]
@julian-trustgrid CCF nodes communicate with each other over the network, there is no obstacle to distributing them across regions. We've run experiments in the past between the UK South and East US regions in Azure for example.

Depending on the maximum latencies involved, you may want to tweak consensus config: https://microsoft.github.io/CCF/main/operations/configuration.html#consensus

Message timeout for example, should be sufficiently greater than the typical maximum roundtrip, to avoid unnecessary retransmission. Similarly, election delay needs to be a multiple of message timeout to avoid primary instability.

**Comment by kjsoni** [comment]
@achamayou Please let us know what is the ideal number of nodes if we use the raft algorithm. We have read it is supposed to have a 5 or max 7 number of CCF nodes if we use the raft algo. Is it possible to have 100 or 1000 CCF nodes? For e.g. If we have 100 nodes, then we will have 1 primary and the rest 99 as secondary. Would that work?
thanks

**Comment by achamayou** [comment]
@kjsoni the number of nodes you need to run is determined by the number of simultaneous failures you want to be able to tolerate. To be robust to _f_ failures, you need to run _2f+1_ nodes. In other words, if you want your system to keep running if any 2 nodes go down, you need to run 5 in total.

Apart from availability, there is a performance impact to running more nodes. Because backup nodes can serve reads, your read throughput will scale linearly with the number of nodes. But your write throughput will decrease somewhat as you increase the number of nodes, as the primary spends more time handling replication.

You can probably run 100 or even 1000 nodes, although we haven't tried. You would only do that if you wanted to be robust to 49 or 499 nodes crashing at once, or if you had such a read-intensive application that you needed this many backups to serve all the traffic.

**Comment by julian-trustgrid** [comment]
@achamayou  thanks for clearing this up. I have another question - if you have a geographically distributed ccf nodes:

1 node in US
1 node in India
1 node in Singapore
1 node in EU
1 node in Australia

Me / or my service, is currently hosted in Australia, how do I make sure that when I issue a `Get` that it hits the node deployed in Australia? Is there a specific configuration we have to look at for this?

Thanks heaps

**Comment by kjsoni** [comment]
@achamayou Thanks for your earlier reply.

I also want to confirm that, is it fair to say that increasing the number of nodes in CCF, would have a direct impact on the election process when the primary/leader node dies. For e.g., if we have 100 CCF nodes running and if the primary node dies, any of the secondary nodes can become a leader. They are not elected on a first come basis, but they have to go through a voting process, and only when the majority of the secondary nodes have been voted, does the one with the most votes gets elected. My understanding is that during edge cases (when multiple secondary nodes have an equal vote or put their hand up at exactly the same time) this process can be quite complex and time-consuming. Is this the right assumption? thanks

**Comment by achamayou** [comment]
@julian-trustgrid I think I am probably misunderstanding your question, but you should be able to target the network address (DNS or IP) of the node you are running in Australia? If you are worried about forwarding, this is something the app [can control](https://microsoft.github.io/CCF/main/audit/builtin_maps.html#_CPPv4N3ccf9endpoints18ForwardingRequiredE).

@kjsoni yes, elections require that the majority of nodes vote for the candidate node. The vote resolution logic on each node is quite simple though, it's just a comparison to check if their log is more recent than the candidate. On the candidate node, receiving 50 network messages containing votes isn't especially problematic.

What may happen with enough nodes, is more election contention: multiple candidates running for elections simultaneously, with equally up to date logs. They could split votes, and if enough nodes are unavailable that neither group can get a majority, cause a further timeout and another election round.

There's an interesting calculation to be done here, with the typical round trip time, election timeout, number of nodes and fraction that's unavailable to get to a probability of election conflicts, and to work out how the average number of election timeouts may increase as the number of nodes and round trip time increase.

**Comment by julian-trustgrid** [comment]
> 

That makes sense, thank you @achamayou

**Comment by kjsoni** [comment]
Thanks, @achamayou for your clarification.

**Comment by julian-trustgrid** [comment]
Closing this issue now, thanks @achamayou
