### ISSUE TITLE
Followers should be able to forward signed user commands to the leader

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#46]
This allows signature verification to be offloaded to the followers, and leaves all leader resources free for transaction processing.

**Comment by achamayou** [comment]
The main functionality is complete (#75)

Still to do

    Write better unit tests for it [in progress now]
    Make the join protocol work with this new async behaviour
    Support redirection for all frontends (i.e. management, members and nodes)

**Comment by jumaffre** [comment]
The corresponding unit tests have been written as part of https://github.com/microsoft/CCF/pull/82.

**Comment by jumaffre** [comment]
This feature is now fully complete as https://github.com/microsoft/CCF/pull/75 and https://github.com/microsoft/CCF/pull/87 have been merged. 

I am currently implementing the synchronous join protocol but it is a different feature than this one (even though it is using some of the code introduced in this feature).
