### ISSUE TITLE
JS KV Access - clarify read-only restrictions in different execution contexts

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4630]
We enforce some read/write restrictions on KV access from JS, so that (for instance) governance actions can only write to governance tables, and not private or application tables.

The error message when code attempts to write to a disallowed table is unclear ("Cannot call delete on read-only map"). We should improve this error message to explain exactly why this table is read-only. We should also explain this restriction, and the reason behind it, in the docs.

I think there are additional restrictions we should be enforcing here too, to prevent even _read_ access to certain tables in certain contexts (eg - you shouldn't read from _private_ application tables in any governance).

I think the table looks like this:

```
    // Enforce the following access:
    //
    //                                 Namespace of Table
    //           ______________| INTERNAL  GOVERNANCE  APPLICATION
    //           ______________|  PUB|PRIV   PUB|PRIV   PUB|PRIV
    //            gov validate |   RO|X       RO|X       RO|X
    //   Kind     gov resolve  |   RO|X       RO|X       RO|X
    //    of      gov apply    |   RO|X       RW|X       RO|X
    // Execution  app endpoint |   RO|RO      RO|RO      RW|RW
    //            module exec  |   - |-       - |-       - |-
    //
```

(An `X` is illegal, not even readable, so calling `ccf.kv["your_map_name_here"]` should throw a useful error message. The `-`s in module exec are where `ccf.kv` doesn't even exist. A reminder that this is user-written code, so _could_ try to access the KV, and will currently fail with some kind of null property error, but we could potentially make more explicit)

WIP branch is here: https://github.com/eddyashton/CCF/tree/js_read_only_explanations

Note that we're talking here purely about JS, but the application restrictions will (and should) also be enforced for external executors, or any other execution engine where we have the ability to do so.

**Comment by achamayou** [comment]
Also linking #3992, which was trying to clarify that.

**Comment by eddyashton** [comment]
> @eddyashton this looks good to me, definitely useful to document and give clear error messages about. Although the apply context doesn't have direct write access to internal tables, I believe some of the C++ FFI calls it is allowed to will in fact write there, and so perhaps this is RO (*), with a clarification?

This is a really good point - I'd thought the internal namespace was purely signatures/node-triggered operations, but there are secrets and shares in there that we expect to happen in governance application. I think I'd prefer to say that `internal` tables in `gov apply` are actually read/write then - we _expect_ them to be modified purely by FFI rather than directly, but not clear that we should forbid direct modification.

Further clarification is messy - I'd like to talk purely about what you can do in JS (or equivalently sandboxed code) running in CCF, and accept that it doesn't apply to C++ apps.  Technically the C++ FFI isn't constrained by _any_ of these rules, so an innocuous-looking JS call that's implemented as an FFI in any of these contexts _could_ write to any map. We avoid that by not defining such calls in those contexts, but that enforcement is orthogonal. And on the other side, app endpoints written in C++ aren't prevented from writing to tables that should be RO. Will discuss in detail when the docs exist, but I lean towards a short blanket "doesn't apply to C++ code" rather than a more thorough explanation of the exceptions/caveats.

**Comment by achamayou** [comment]
> but not clear that we should forbid direct modification.
> accept that it doesn't apply to C++ apps.

There are two separate things here, the security guarantee (can we prevent an attacker from doing this), and usage safety (can we minimise the chance that a well-meaning user will have an accident). I think things like the RO type in C++ are very useful for the latter, and so is banning direct internal table modification from `apply().` If we have no reason to suspect a particular operation will end well, because it's virtually guaranteed to break some invariants, it is useful for us to communicate it in the interface.

**Comment by eddyashton** [comment]
>  usage safety (can we minimise the chance that a well-meaning user will have an accident)

I agree in principle, but we don't even have the usage safety in the current C++ API. Providing this would require another abstraction layer - a context-aware wrapper around the KV which gave different access to tables because it knows its executing an app endpoint. This is of course possible, but not something we've invested in yet.
