### ISSUE TITLE
Multi-container: Expose current versioned node API over gRPC

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4666]
CCF currently exposes wrappers for several builtin features (primarily consensus state), defined in `base_endpoint_registry.h`. For feature parity, we should also expose these over gRPC for isolated business logic containers.

While doing so, we can rename/namespace these for clarity, and we may also decide some are unnecessary (eg - `get_untrusted_host_time_v1` may be unnecessary, as executors can instead get untrusted time from their own host). We may drop the `_vN` suffix, but should look at how versioning in gRPC is usually done.

**Comment by achamayou** [comment]
Not under active consideration, as the work on external executors is suspended.
