### ISSUE TITLE
Multi-container: Write an attestation sidecar

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4667]
Every business logic/executor container must be able to fetch its attestation, bound to its freshly generated key-pair, to submit as part of the registration protocol.

We can demonstrate how to do this in samples, but for simplicity we can also create a simple sidecar which does this and publish it with the releases. Examples of fetching this attestation on SNP exist already in [CCF](https://github.com/microsoft/CCF/blob/main/include/ccf/pal/attestation.h#L80) and [elsewhere](https://github.com/microsoft/confidential-sidecar-containers/blob/main/tools/get-snp-report/get-snp-report.c), and the latter is already packaged in a [sample sidecar container](https://github.com/microsoft/confidential-sidecar-containers/tree/main/examples/skr).

**Comment by takuro-sato** [comment]
Subtickets:
- [ ] https://github.com/microsoft/CCF/issues/4804
