### ISSUE TITLE
Multi-container: Write a JS shim container for cheap migration of existing CCF apps

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4668]
CCF JS apps are currently written against an API that runs within a CCF enclave, in a custom QuickJS-backed runtime, exposing global functions to access the KV/other CCF features. With the isolated business logic/remote executor model, it will be possible to write richer JS apps which speak to a CCF node over a new gRPC API.

To enable simple migration of apps written in the old format, to be deployed in the new style, we should write a shim container. This will expose an API compatible with the old internal CCF model, and invoke the scripts as defined by their existing metadata, but internally convert those to gRPC calls and communicate over the new API.

**Comment by eddyashton** [comment]
Another option, rather than writing a shim on which an existing unmodified app could run, is to define a translation process from the old style to the new style API, which may be as simple as adding a main gRPC dispatching loop. The difference here would be in whether we were maintaining support for the old API indefinitely, with extensions to the shim, or defining a run-once translation and expecting that apps were then iteratively upgraded to directly use new gRPC features.

**Comment by achamayou** [comment]
Not under active consideration, as the work on external executors is suspended.
