### ISSUE TITLE
Replace node-to-node forwarding with HTTP redirection

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4670]
CCF nodes will forward messages to a primary, if they believe it is a write request but they are currently a backup. Today they do this over node-to-node channels, which has some shortcomings (#4625).

A simpler and more consistent solution would be to use standard HTTP redirection rather than forwarding. Each node can respond to requests it can't handle (eg - a write on a backup) with a redirect HTTP response. Note that this redirection loses session consistency - the client must re-establish a new session with the targeted primary. We believe that's a fair tradeoff, and long-lived sessions containing writes should be targeting the primary already rather than wastefully forwarding via a backup.

We previously believed that this would require each node to have a unique publicly accessible name, known to each other node, so that we could redirect directly to them. That does not fit with deployment models where all nodes are hidden behind a single public load balancer. However, we've since come up with a solution where that is not necessary - if the load balancer can distinguish requests to `write.service.com` from `read.service.com`, and direct traffic to the appropriate node (dynamically detect the primary), then we can use redirection even where each node has no public name. Additionally, this model ensures that all traffic remains controlled and shaped by the load balancer.

We'll have to carefully consider the migration path/deprecation period for forwarding. Node configuration will need to be able to specify different kinds of redirect behaviour ("redirect to this node's unique name" vs "redirect to this service's `write` name"), and we should try to test the latter multi-name load balancer solution in our CI.

**Comment by achamayou** [comment]
It does not look like most CCF deployments will be able to use a sufficiently configurable load balancer for us to be able to do this.
