### ISSUE TITLE
Full SNP Attestation Verification

### ISSUE THREAD

**Issue by DomAyre** [microsoft/CCF#4673]
The main SNP attestation fields (`measurement` and `host_data`) are currently verified to give a reasonable level of confidence in the integrity of a joining SNP node for experimental support. However for 4.x, we want full support which involves having a high level of confidence that we verify all fields that could be relevant and making sure our validation is robust.

Issues required to deliver this:

- [x] #4193 
- [x] #4538 
- [x] #4539 
- [x] #4540 
- [ ] #4541 
- [x] Test for mutated host_data and measurement

**Comment by jumaffre** [comment]
Closing this issue as only #4541 is remaining, and can be tracked separately.
