### ISSUE TITLE
Full SNP CI Coverage

### ISSUE THREAD

**Issue by DomAyre** [microsoft/CCF#4674]
In order to deliver production quality support for SNP, we must have reliable and stable CI coverage of CCF on SNP.

Issues required to deliver this:

- [x] #4675 
- [x] #4620 
- [x] #4190
- [x] #4827 
- [x] #4072 
- [x] #4444 
- [ ] SNP LTS Test
- [x] Improve ACI deployment time

Improvements:

- [x] Fix npm on fileshare issue to re-enable modules test
- [x] Tighten the security policy
- [x] Display container logs before cleaning up (see https://learn.microsoft.com/en-us/azure/container-instances/container-instances-get-logs)

Also our CI coverage should be stable, which requires:
- [x] #4446 (Using a fileshare works as a workaround but we need to fix for real deployments, too slow and no symlink support causes many issues)

**Comment by achamayou** [comment]
Also performance tests.

**Comment by achamayou** [comment]
npm fileshare issue no longer a problem because I/O error is fixed and switched to local disk.
