### ISSUE TITLE
CI workflow to build a CCF container ready for running tests for a specific revision

### ISSUE THREAD

**Issue by DomAyre** [microsoft/CCF#4675]
It would be helpful to perform a single build of CCF for a given revision (typically for a PR) and then build that into an image that can be used by other CI jobs.

This is especially useful for testing where we dynamically deploy executors for each test (SNP)

Todo:

- [x] Github action to push container (identical to current CI container) to ACR 
https://github.com/microsoft/CCF/pull/4692
- [x] ~Github action~ Scheduled task in ACR to cleanup containers ~(runs manually)~
- [x] Use dynamically built image in CCF SNP pipeline
https://github.com/microsoft/CCF/pull/4698
- [x] Modify container to have a build of CCF
https://github.com/microsoft/CCF/pull/4702
- [x] Speed up building with more powerful executor
https://github.com/microsoft/CCF/pull/4722
    - [x] Speed up image building
    https://github.com/microsoft/CCF/pull/4737

**Comment by achamayou** [comment]
https://learn.microsoft.com/en-us/azure/container-registry/container-registry-auto-purge

**Comment by DomAyre** [comment]
Yeah I found this and it's set up to purge any images older than 1d

**Comment by achamayou** [comment]
@DomAyre if there isn't already, a quick mention + pointer in the internal doc would be great.
