### ISSUE TITLE
Remove redundant HTTP APIs

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4687]
Since we now expose governance tables in a uniform manner from the KV (#4659), we can remove some of the existing endpoints which are basic handwritten wrappers. This should also reduce the scope of #4669.

**Comment by achamayou** [comment]
@eddyashton we can deco them in 4.x, but they need to stay in 3.x for compatibility purposes of course.

**Comment by achamayou** [comment]
Candidates for De-duplication:

- [/gov/code](https://microsoft.github.io/CCF/main/governance/member_rpc_api.html#get--gov-code)
  - Replaced by [/gov/kv/nodes/code_ids](https://microsoft.github.io/CCF/main/governance/member_rpc_api.html#get--gov-kv-nodes-code_ids)
- [/gov/jwt_keys/all](https://microsoft.github.io/CCF/main/governance/member_rpc_api.html#get--gov-jwt_keys-all)
- [/gov/members](https://microsoft.github.io/CCF/main/governance/member_rpc_api.html)
- [/gov/proposals](https://microsoft.github.io/CCF/main/governance/member_rpc_api.html#get--gov-proposals)
