### ISSUE TITLE
Current state of JS date time

### ISSUE THREAD

**Issue by RokasAidukas-Centric** [microsoft/CCF#4691]
Hello, I wanted to check what is the current state of receiving current date / time on JS applications? I am currently using ccf:3.0.0-dev6 version and wanted to know how to print a current timestamp? The default behaviour is that new Date().getTime() or similar implementations return 0. I checked what I could find in your documentation and also found this issue https://github.com/microsoft/CCF/issues/2468 but did not quite understand how it is used at the moment and whether it is possible at the moment. 

Is it possible to do it at the moment or do you offer any workarounds if not? Thanks!

**Comment by eddyashton** [comment]
@RokasAidukas-Centric Sorry for the slow response on this one. The current state in recent releases is that `Date.now()` will return 0.

That will change shortly, as we've had several requests to support this, so are now tracking that here: https://github.com/microsoft/CCF/issues/4826
