### ISSUE TITLE
Add Issue to Project workflow does not work

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#4711]
Details under https://github.com/microsoft/CCF/actions/runs/3651895005/jobs/6169646891

> Personal access tokens with fine grained access do not support the GraphQL API

**Comment by shokouedamsr** [comment]
Updated ubuntu version in the script + allowed org access to PAT: https://github.com/microsoft/CCF/pull/4714

**Comment by achamayou** [comment]
@shokouedamsr closing this, and opening a new issue to kick off the job.
