### ISSUE TITLE
Partitions test failures

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#4777]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=58776&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=2cd8c971-f488-5a92-7f18-3405fd4d3e8a
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=58752&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=3aae4c9d-f0dc-5b97-1b0e-f86312395af9

Not always in the same test, but always a failure to achieve primary unanimity.

Bizarrely, the post mortem detailed output (/consensus) always indicates unanimity.

Possibilities:

- Our timeout is somehow just too short. One way to check that would be log the time convergence takes, perhaps per scenario, and look at the distribution.
- There's something wrong with /network that causes it to report incorrect, or delayed information.
- ???

**Comment by achamayou** [comment]
Two more suggestions from @eddyashton:

> remove the log_capture in wait_for_primary, to get more detailed information
> Add min_view to the "Waiting up to... for all nodes" log line

**Comment by eddyashton** [comment]
#4778.

**Comment by achamayou** [comment]
```
$ cat 67 | grep "Primary unanimity" | cut -d "|" -f 3 | cut -d : -f 3 | cut -d ' ' -f 6 | sort -g
0.37s
0.40s
0.41s
0.41s
0.41s
0.41s
0.48s
0.48s
0.48s
0.48s
0.48s
0.53s
0.53s
0.53s
0.53s
0.53s
0.56s
0.60s
0.63s
0.64s
0.75s
0.76s
0.80s
0.89s
0.91s
0.99s
1.05s
1.11s
1.15s
1.15s
1.16s
1.16s
1.17s
1.22s
1.27s
1.27s
1.28s
1.51s
1.63s
1.64s
1.64s
1.74s
1.93s
1.94s
1.94s
1.99s
2.05s
2.05s
2.17s
2.22s
2.32s
2.45s
2.52s
2.52s
2.64s
2.67s
2.72s
2.75s
2.87s
2.89s
3.25s
3.97s
4.05s
4.23s
4.24s
4.29s
4.43s
4.55s
5.53s
5.53s
5.72s
5.77s
5.88s
5.97s
6.12s
6.16s
6.24s
6.29s
6.35s
6.59s
7.11s
7.70s
7.71s
8.09s
9.98s
10.02s
19.49s
20.73s
25.86s
30.17s
```

So the median is about 2 seconds, but there's a fairly long tail up to 30 seconds.

**Comment by achamayou** [comment]
Interestingly, we mostly seem to wait 15 seconds for unanimity, and occasionally 150:

```
$ cat 67 | grep "Waiting up to" | grep unanimity | cut -d "|" -f 3 | cut -d : -f 3 | cut -d ' ' -f 6 | sort -g
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
15.0s
150.0s
150.0s
150.0s
150.0s
150.0s
150.0s
150.0s
150.0s
150.0s
150.0s
```

**Comment by achamayou** [comment]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=58818&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=bb1a7e6d-8f5b-56e4-638c-b498b20b4b62
