### ISSUE TITLE
Cut a new dev release (ccf-4.0.0-dev3)

### ISSUE THREAD

**Issue by jeffa5** [microsoft/CCF#4782]
Could a new dev release be cut? It seems that the `TCP_NODELAY` PR was actually merged after the last dev release, so the change notes are wrong at https://github.com/microsoft/CCF/releases/tag/ccf-4.0.0-dev2

**Comment by achamayou** [comment]
Thank you for catching that, https://github.com/microsoft/CCF/releases/tag/ccf-4.0.0-dev3 is out now.
