### ISSUE TITLE
Add benchmark for `range` on maps

### ISSUE THREAD

**Issue by jeffa5** [microsoft/CCF#4788]
**Is your feature request related to a problem? Please describe.**

Currently the `range` function on maps isn't public but could be in the future. Additionally, with Champ maps the range performance isn't optimised and switching to RBMaps for `range`-heavy applications may be desirable.

**Describe the solution you'd like**

A benchmark for the `range` function, similar to that for the `foreach` function to monitor performance between different maps, and compared to `std::map`.

**Describe alternatives you've considered**

Not having the benchmarks.

**Additional context**

RBMaps aren't yet fully ready since they lack support for `remove` operations but that could be implemented to fully realise the range performance.

**Comment by achamayou** [comment]
Will done as part of #3088.
