### ISSUE TITLE
Join protocol (quote verification) halts Raft heatbeats

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#480]
The quote verification function when a new node joins the network takes a significant amount of time (roughly 2 secs). Since this is performed on the primary of the network (and that the enclave is, for now, single-threaded), the verification halts the processing of ring buffer messages, including the `tick` required by Raft to send heartbeats to backups. 

Since our most of our tests use a Raft election timeout within the same order of magnitude (1.5 secs), we can get unlucky (the Raft timeout is chosen randomly between 1.5secs and 3secs) and an election will be triggered by a backup node when another backup joins.

**Comment by achamayou** [comment]
Mitigated for now by longer raft timeouts, the right long term solution is to move away from sequential execution, which is WIP.
