### ISSUE TITLE
Applications cannot register endpoints under `.well-known` paths

### ISSUE THREAD

**Issue by plietar** [microsoft/CCF#4810]
Since CCF 3.x, applications can register endpoints under any directory, not just `/app`, except directories reserved by CCF (eg. `/gov`, `/node`, ...). We were hoping to use this to register an endpoint at `/.well-known/did.json` in order to give our service a resolvable [`did:web` identitifier](https://w3c-ccg.github.io/did-method-web/).

Unfortunately it seems `.well-known` is one of the reserved prefix, because it is used by the ACME client that is built-in to CCF. The entire directory is reserved, regardless of whether ACME is enabled. The ACME client only needs to register endpoints under the `/.well-known/acme-challenge` sub-directory, but because of CCF's architecture, an "actor" must bind to an entire top-level directory.

https://github.com/microsoft/scitt-ccf-ledger/issues/53#issuecomment-1375348575

**Comment by achamayou** [comment]
@plietar are you planning to use the ACME client at the same time that you register `.well-known/did.json`?

**Comment by achamayou** [comment]
A possible solution may be to move the `acme-challenge/{token}` handler to the CommonEndpointRegistry as `.well-known/acme-challenge/{token}`, because that will also be exposed at the top-level since #3893. At which point the `.well-known` actor can be scrapped altogether, and registering `.well-known/did.json` should become possible.

**Comment by plietar** [comment]
I don't think we have any plans on using the ACME client anytime soon. @letmaik might know more.

Moving the acme-challenge to CommonEndpointRegistry would work for us I think.

**Comment by MahatiC** [comment]
Moving `.well-known/acme-challenge` to `CommonEndpointRegistry` sounds good to me
