### ISSUE TITLE
Handle `CompactedVersionConflict` during external execution

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4815]
Background for this behaviour is (way back) in #1615, and the fix #1617.

When we have a long-lived transaction that straddles a commit (and compaction of the in-memory KV roll), its possible to request a handle on a map at a version which is no longer available - we're reading at version 10, but the KV has been compacted and only contains maps back to version 12. That's not a problem if we already have a handle to a view on that map (its lifetime is extended by any `Tx` still using it), but is a problem for newly requested views. We resolved that by throwing a custom exception type (`CompactedVersionConflict`) in this scenario, and re-executing the transaction through the normal conflict resolution/retry logic in `frontend.h`.

That does not interact well with external execution. Its currently possible for external execution to create transactions straddling a commit boundary (essentially, creating long-lived, interleaved transactions, that previously didn't occur because we're single threaded). I think this is happening very occasionally in the existing `external_executor` test during `test_multiple_executors`, and definitely since #4809 - I've got regular repros there by running in a loop. With a bunch of extra debug logging, the failure point looks like this:

```
2023-01-10T16:40:28.445102Z -0.002 0   [fail ] ../src/node/rpc/frontend.h:599       | Transaction execution conflicted with compaction: Unable to retrieve state over map wiki_descriptions at 94
2023-01-10T16:40:28.445131Z -0.002 0   [fail ] ../src/node/rpc/frontend.h:376       | Retry #1 for POST /externalexecutor.protobuf.KV/Get
2023-01-10T16:40:28.445137Z -0.002 0   [fail ] ../src/node/rpc/frontend.h:599       | Transaction execution conflicted with compaction: Unable to retrieve state over map wiki_descriptions at 94
2023-01-10T16:40:28.445141Z -0.002 0   [fail ] ../src/node/rpc/frontend.h:376       | Retry #2 for POST /externalexecutor.protobuf.KV/Get
...
2023-01-10T16:40:28.453851Z -0.010 0   [fail ] ../src/node/rpc/frontend.h:376       | Retry #29 for POST /externalexecutor.protobuf.KV/Get
2023-01-10T16:40:28.454912Z -0.011 0   [fail ] ../src/node/rpc/frontend.h:599       | Transaction execution conflicted with compaction: Unable to retrieve state over map wiki_descriptions at 94
2023-01-10T16:40:28.454920Z -0.011 0   [fail ] ../src/node/rpc/frontend.h:645       | Consistent conflicts
```

Because the detached `Tx` that's used for this actual `get` is _not_ reset, as soon as we see it once we're going to see it every time, and reach the retry limit. Hitting that limit results in a `503` error going to the executor in response to their `GET`.

Don't have a complete plan to fix this yet, so what follows is some initial thoughts:

Ideally, we'd be able to leverage the existing retry logic to fix this - perhaps catching the `CompactedVersionConflict` inside the `external_executor` app. The problem with that is that we still need to signal to the calling _executor_ that the _entire transaction_ is being re-executed, and they need to blow up their stack and start over - any local state/partial response they've built up should be discarded. The simplest model for this is probably some kind of try-catch at the top-level of the executor's dispatch loop, and a retry can look equivalent to a fresh request as far as they're concerned. There's a danger though that this hides other errors, and results in the original caller never getting a response (eg - if a parsing error or other exception type results in an unexpected gRPC error, we shouldn't lose an in-progress request idle in our queues).

We don't want to impose a large error-handling expectation on every KV access by every executor.

Even when a node decides that an externally-dispatched request needs to be retried (whether that's inline during the `Get` that threw a `CompactedVersionConflict`, or later in response to an executor informing it that _it_ has given up), its not clear to me _how_ we reuse the existing retry loop, since that relies on the original calling context still being on the stack. I hope we don't have to detach/replace that too, because the implications for how we find the correct response stream are extremely nasty.

A potential option is to avoid retries and treat a single instance of these conflicts as a fatal error for this request, responding with that to the caller. I think that will unacceptably inflate error rates on CCF services, since externally executed requests which straddle commit points (even though they're pure reads!) will be extremely common.

**Comment by eddyashton** [comment]
Some more early thoughts:

- We discussed on the initial issue the option to do a partial truncation, and keep some of the historical roll on compaction. That's an opinionated optimisation - trading off increased memory use (longer roll, perhaps redundant, kept for longer) for fewer instances of this error. That trade-off might make a lot more sense now, for external executors. But its only a partial mitigation, and feels like punting on the core issue.

- We've considered requiring transactions to declare their accessed tables up-front, so we can take a handle to all of them. That would resolve this, but is a major change to the programming model - forbids the use of dynamically generated table names. In particular, for external executors, we can't even easily delay to "the first view you request must list all tables you will request", as we potentially could for inline apps, because that's _still_ after an async dispatch step after we've already likely read dispatch + auth tables.

- A heavy-handed fix would be to pre-request handles for _all_ tables, on the first call to `get_view`, where we currently fetch those lazily. This is another memory cost (increasing number of stored maps), but only while a `Tx` persists. A big risk here is that  the cost of doing this might look acceptable to our sample apps, but be absurdly expensive for real applications with many dynamically created tables.

**Comment by eddyashton** [comment]
Deterministic (convoluted and contrived) repro is here:
https://github.com/eddyashton/CCF/blob/external_executor_conflict_repro/tests/external_executor/external_executor.py#L473

**Comment by achamayou** [comment]
> trading off increased memory use (longer roll, perhaps redundant, kept for longer) for fewer instances of this error.

+1 for that

Another heavy-handed fix might be to blow up the connection. There is probably handling for that already, but of course doing a new TLS handshake every time isn't particularly cheap. Then again, keeping a longer roll may reduce the occurrence rate enough that it's an acceptable strategy?

**Comment by eddyashton** [comment]
Had a productive discussion on this offline. There's a few angles to fix, which can be implemented separately. I'll break this into separate tasks when I've scoped them a little better:

- [ ] Retrying an incoming transaction should be rewritten as an async task rather than a single while loop, so it can be triggered internally by the `external_executor` app (which has taken a full copy of the original request context).
- [ ] Sample BL containers should demonstrate, with comments, the best practice try-catch behaviour (roughly; don't need to check each call, a try-catch for gRPC errors at the top-level should be sufficient, and BLs should assume that CCF is handling retries itself - an exception implies this BL can forget about any in-progress request).

Then non-critical but helpful mitigations to reduce the number of conflicts now that we have long-lived transactions:
- [ ] Lengthen the minimum roll, keeping a signature-range of old entries on compaction.
- [ ] Explore a sparse roll, persisting versions for active Txs.
- [ ] Explore pre-fetching handles based on the map-names fetched in a previous conflicting run.
- [ ] Store metadata across conflicts (kind of conflict, execution time), to report a verbose error to users.
