### ISSUE TITLE
Fix encoding of sign() JS API function 

### ISSUE THREAD

**Issue by takuro-sato** [microsoft/CCF#4816]
We are aiming to make the JS crypto API to follow the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) in behavior.
To do so, https://github.com/microsoft/CCF/issues/2735 changed `ccf.crypto.verifySignature` to accept  IEEE P1363 as signature's encoding format from  DER when `ECDSA` is used.
But recently added `ccf.crypto.sign` doesn't follow it and creates DER encoded signature and we need to fix it.
Also we haven't checked encoding to use for `EdDSA`, so we need to check it from  [Web Crypto API spec](https://w3c.github.io/webcrypto/).

**Comment by achamayou** [comment]
@takuro-sato we need to check for RSA too.

**Comment by takuro-sato** [comment]
## TODOs
- [ ] Sign with P1363 encoding for ECDSA
- [ ] Check if the encoding for RSA and EdDSA is compatible with Web Crypto API (and fix if not)
