### ISSUE TITLE
Startup scripts should work on Windows

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#483]
Getting started scripts are only available in Bash. We either need to point users at Azure Cloud Shell so they can use these from Windows, or create a powershell equivalent.

We could/should also download oe-engine in this script, rather than requiring users to do so separately.

The verbose OE output should be dumped to a file, and we should display the actual SSH target clearly in the shell

**Comment by achamayou** [comment]
It’s probably useful to make explicit our use of the default ssh key, some users may not have one.
