### ISSUE TITLE
CCF needs a better sample app

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#484]
Our current samples are tied into this repo, so its not obvious how a customer builds an app in a separate codebase leveraging CCF as a framework. We should create a sample repo that developers can use as a template, submoduling CCF and including the necessary CMake. Eventually this will be a good test of our public API, but its worth creating as an example even before the API is reduced.

Also our main Logging sample app is too simple and doesn't showcase the key differentiators of CCF. We ideally want to demonstrate ownership transfer, with private state access being both granted and revoked for specific users, and also the live scripting in the Lua execution engine allowing contracts to be cheaply created/modified in a running service.

**Comment by achamayou** [comment]
Addressed by https://github.com/microsoft/EVM-for-CCF
