### ISSUE TITLE
Install start_test_network.sh and make it usable by user apps 

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#493]
The `start_test_network.sh` introduced by https://github.com/microsoft/CCF/pull/491 currently requires a fresh build of CCF in the `build/` directory. 

This is not convenient for users who just want to deploy their applications. We should change this so that the script can be run "out of the box", for example when including CCF as a submodule.

**Comment by achamayou** [comment]
One element of this is probably making the infra stuff pip installable into the venv.

**Comment by jumaffre** [comment]
This seems to be broken since the addition of the `common` directory. I'll get it fixed and check that this issue is resolved as well.

**Comment by achamayou** [comment]
I think there are two use-cases for this:

1. Install start_test_network along with a sample app (logging) in the install bundle for users to try
2. Make it possible users to call that script and point it as their application build

We want to support both of those.

**Comment by achamayou** [comment]
This is effectively complete, we have at least two users who do that already. It's still the case that we should ship a demo app in the install package, but that's tracked in #1028.
