### ISSUE TITLE
Create a way for a test to validate a network has been opened

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#495]
Currently there is a sleep in the end_to_end_pbft test where we wait for all the nodes to open the network. We need to create a way to check that the network has been opened on all the nodes rather than sleeping.

**Comment by achamayou** [comment]
We have this: https://github.com/microsoft/CCF/blob/master/tests/infra/ccf.py#L373, it's already done automatically as part of open_network and start_all_nodes.

**Comment by ashamis** [comment]
> We have this: https://github.com/microsoft/CCF/blob/master/tests/infra/ccf.py#L373, it's already done automatically as part of open_network and start_all_nodes.

We discussed this offline - this is something that is needed from the pbft side. I am hoping to send a PR for this in a couple of hours
