### ISSUE TITLE
`sandbox.sh` defaults to virtual mode instead of sgx

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#4966]
Similar to https://github.com/microsoft/CCF/issues/4892, `sandbox.sh --help` reports that the sandbox defaults to release and sgx but instead it defaults to virtual mode. 

This is low prority as the sandbox can still be ran in sgx mode by explicitly passing `-t sgx -e release`

**Comment by achamayou** [comment]
We think this can be resolved by what was suggested in #4273
