### ISSUE TITLE
Multi-Container: Build infra to run the executors in docker containers

### ISSUE THREAD

**Issue by MahatiC** [microsoft/CCF#4979]
As a stopgap solution (for #4261) until we have a stable ACI/confidential pods, build out infra to spin up external executors inside docker containers.

Todo:
- [ ] #5018 (WikiCacherExecutor)
- [ ] Update to cover the LoggingExecutor
- [ ] Centralise framework for use in other tests

**Comment by jumaffre** [comment]
https://github.com/microsoft/CCF/blob/main/tests/infra/remote_shim.py#L62 may serve as inspiration to get this working both locally and in docker-out-of-docker in the CI, and can also be used to run the CCF node itself within a container (which may help for BL container to CCF node communication).

**Comment by achamayou** [comment]
Not under active consideration, as work on external executors is suspended.
