### ISSUE TITLE
How to make a performance test for CCF

### ISSUE THREAD

**Issue by wheatli** [microsoft/CCF#4981]
I clone the latest version (3.0.5), and would like to make a performance test. How can I make to do this, is there any perf-test tools?

**Comment by eddyashton** [comment]
Hi @wheatli. CCF exposes a standard HTTPS interface, so any HTTP performance testing tools should be useable. There's a discussion of various tools we've tried, and the tradeoffs of each, [here](https://github.com/microsoft/CCF/discussions/2324#discussioncomment-3661060). We're also considering adding [support for Diablo](https://github.com/microsoft/CCF/issues/4981), for comparison with other blockchain benchmarks.

Our own performance tests use some custom clients that support HTTP pipelining (for the reasons described [here](https://github.com/microsoft/CCF/issues/4929#issuecomment-1415702203)), and the results are published [here](https://github.com/microsoft/CCF/issues/1063). Those are testing some sample apps with relatively simple workloads, and its likely a real application would have different characteristics, but they demonstrate a baseline of what is possible. If you want to base a performance test off of these tools, you can look at the [documentation for Piccolo](https://microsoft.github.io/CCF/main/architecture/performance/index.html), or see if our [`scenario_perf_client`](https://github.com/microsoft/CCF/blob/main/src/clients/perf/scenario_perf_client.cpp) is rich enough for your needs/a helpful starting point for your own tool.

The `sandbox.sh` utility that is shipped with each CCF release should be sufficient to spin up a local test network for performance testing, but let us know if you think there are any features missing from this.
