### ISSUE TITLE
Reduce size of CCF runtime container images

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#4987]
Similar to #4955 but for the existing CCF runtime container images. 

The rationale for this is that unlike SGX enclave where the TCB was the CCF C++ enclave code, SNP extends the TCB to the CCF runtime container and the corresponding images should be as minimal as possible (they're currently 192MB and based on ubuntu 20.04).

**Comment by achamayou** [comment]
Although this remains an item of interest, the direction we are taking will be to release packages only, not images, and let teams 
 who deploy CCF handle the target image and dependencies.
