### ISSUE TITLE
Fix 'CCF Github Threading' pipeline failure

### ISSUE THREAD

**Issue by takuro-sato** [microsoft/CCF#4994]
[CCF Github Threading](https://dev.azure.com/MSRC-CCF/CCF/_build?definitionId=13&_a=summary) has been failing.
examples: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=64322&view=logs&j=b2f97161-5795-5a8b-6b22-fc2704b56b5b&t=792a4181-50f1-5335-10af-3ab4628fda2a

## Reproducing locally
```bash
$ mkdir build && cd build
$ cmake -GNinja -DCOMPILE_TARGET=virtual -DWORKER_THREADS=2  ..
$ ninja
# reconfiguration_test_cft fails sometimes
$ sudo ./tests.sh --VV  --no-compress-output  --verbose -R reconfiguration_test_cft
# partitions fails everytime, and it takes shorter time.
$ sudo ./tests.sh -VV  --no-compress-output --verbose -L partitions -C partitions
```
## Investigation using ASAN

There is an error to be investigated
- [x] https://github.com/microsoft/CCF/issues/5050
- [x] https://github.com/microsoft/CCF/issues/5098
- [x] https://github.com/microsoft/CCF/issues/5099

## Investigation using TSAN

- https://github.com/microsoft/CCF/pull/4998
- https://github.com/microsoft/CCF/pull/5073
- [x] https://github.com/microsoft/CCF/issues/5074
- [x] https://github.com/microsoft/CCF/issues/5117
- https://github.com/microsoft/CCF/pull/5146
- https://github.com/microsoft/CCF/pull/5142
- https://github.com/microsoft/CCF/pull/5149

## Investigation in the classic way (with print debug etc)

Currently Multithread CI test fails often so it's not hard to reproduce.

- https://github.com/microsoft/CCF/pull/5035
- https://github.com/microsoft/CCF/pull/5036
- [x] https://github.com/microsoft/CCF/issues/5051
- https://github.com/microsoft/CCF/pull/5055 (Makes debug easier)
- [x] https://github.com/microsoft/CCF/issues/5077

**Comment by eddyashton** [comment]
GitHub Threading pipeline is relatively green now! We will track new failures in isolated issues.
