### ISSUE TITLE
Custom serialization of transaction id in response

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#4996]
The response sent to the client following a locally committed transaction includes the transaction id in a custom header `x-ms-transaction-id`. 

Many APIs return a `Location` header that points to a newly created resource. See also https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#741-post and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location as references. 

Other APIs may return a JSON body with the ID of the new entry, e.g., `{"id": "...", "prop1":...}`.

Both cases can be implemented with CCF's experimental `locally_commited_func` callback that can be set on an endpoint. The default behaviour of that callback (if not set) is to set the `x-ms-transaction-id` header.

The external executors currently don't support this feature but it would be great to have it as it enables development of APIs that conform to best practices.

**Comment by eddyashton** [comment]
We can do this. Brief design notes:

We'll need to separate these actions into separate gRPC API calls:

- `Commit`
- `Respond`

Calling any KV-involved actions _after_ `Commit` will throw an error, calling `Respond` before `Commit` will throw an error (probably, or at least if done without an explicit "I don't want to apply these writes" flag), and for users who don't want this precision we'll keep a combined `CommitAndRespond` call (the equivalent of the current `EndTx`). `Commit` will return the assigned TxID only (ie - it will _not_ explicitly report conflicts in a success-response, those become exceptions like any other KV-operation might throw, and should be handled by popping to the same bit of the callstack).

**Comment by achamayou** [comment]
@letmaik external executors are shelved now, and it is possible to do this with `locally_commited_func`.
