### ISSUE TITLE
Diagrams not appearing correctly in docs

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#5045]
CCF docs diagrams are not rendering for me today (on edge or chrome). See screenshot below:

![image](https://user-images.githubusercontent.com/1835251/220632188-bb69694f-8c56-4d8f-80c3-bba4618e1e5d.png)

**Comment by eddyashton** [comment]
This is due to an issue with `sphinxcontrib-mermaid`: https://github.com/mgaitan/sphinxcontrib-mermaid/issues/110

We'll hopefully get a new release and fix shortly, else we could potentially fix this by modifying the `mermaid_init_js` in `conf.py`.

**Comment by heidihoward** [comment]
Seems to working now

**Comment by Belmogodx** [comment]
@heidihoward what changed to get them to work any ideas?

**Comment by eddyashton** [comment]
> @heidihoward what changed to get them to work any ideas?

@Belmogodx - There was a new [`0.8.1 `release of `sphinxcontrib-mermaid`](https://github.com/mgaitan/sphinxcontrib-mermaid/releases/tag/0.8.1), which [pinned to an earlier release of `mermaid`](https://github.com/mgaitan/sphinxcontrib-mermaid/commit/2eaff4220ade181ad9d8e6148f76498c0c0671f2). The CCF docs are built with the latest `sphinxcontrib-mermaid`, so are now using that pinned version, which references a `mermaid.js` that's still available on `unpkg.com`. As discussed in [the linked issue](https://github.com/mgaitan/sphinxcontrib-mermaid/issues/110), a better fix may be to change the CDN used from `unpkg.com` to `jsdelivr.net`, but in either case the diagrams in the CCF docs should now be rendered correctly.
