### ISSUE TITLE
EnclaveTime Header should be a public header

### ISSUE THREAD

**Issue by sidmore** [microsoft/CCF#5049]
**Describe the bug**
Trying to add validation of NBF and EXP claims presented in a JWT token which is now possible by getting enclave time. This is currently a private header and referenceable as #include "ccf/_private/enclave/enclave_time.h". 

**To Reproduce**
encalve_time.h should not be a private header please look at the attachment for the path

**Expected behavior**
Ideally should be a public header and refrenceable as #include "ccf/enclave/enclave_time.h"

**Environment information**
CCF Ver 2.0.16

**Additional context**
![PrivateHeader](https://user-images.githubusercontent.com/29606792/220686130-5c89b879-90be-4c8e-a2ea-ac5d6aec7db8.png)

**Comment by achamayou** [comment]
@sidmore there is no such thing as enclave time, this an internal implementation header containing functionality for the enclave to read time passed in from the host.

Please use [get_untrusted_host_time_v1](https://microsoft.github.io/CCF/main/build_apps/api.html#_CPPv4N3ccf20BaseEndpointRegistry26get_untrusted_host_time_v1ER8timespec), available from https://github.com/microsoft/CCF/blob/release/2.x/include/ccf/base_endpoint_registry.h#L177.

**Comment by sidmore** [comment]
awesome @achamayou sounds good closing this.
