### ISSUE TITLE
Confusing wording in README: "data is executed"

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#508]
> Microsoft has taken this approach in developing CCF: using TEE technology, the enclave of each node in the network (where cryptographically protected data is executed)...

The part in parentheses sounds weird. How can you *execute* data?

**Comment by achamayou** [comment]
That's definitely quite confusing! I think the intention might have been to say "executed over", but I suspect we really want to shrink the README and have it be more like some pointers to the full doc and the various CIs etc. Having a business intro on there doesn't seems like an audience mismatch.
