### ISSUE TITLE
Explain/reference what a "ledger" is in the README

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#509]
Ledger is a term that appears many times in the README but it's not explained or referenced. I think this is one of those words which you just can't understand from context.

Related to that, the section title "A flexible confidentiality layer for any multi-party computation application or blockchain ledger to build upon" may create the impression that "ledger" is a blockchain-only concept, but then the second paragraph talks about "Ledger providers" as if this is something you *always* need. Without having background on these topics the reader is now a bit lost/confused.

**Comment by achamayou** [comment]
Sounds like a good addition to the glossary!

**Comment by achamayou** [comment]
This is well covered by https://microsoft.github.io/CCF/developers/ledger.html now.
