### ISSUE TITLE
Definition of Merkle tree and leaves

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#5103]
I tried to find a reference to the definition of CCF's Merkle tree including the leaf format and the closest I could find was:
- https://microsoft.github.io/CCF/main/architecture/merkle_tree.html (tree structure)
- https://microsoft.github.io/CCF/main/use_apps/verify_tx.html#receipt-verification (leaf format)

Are those the best references at the moment?

Context: https://github.com/ietf-scitt/draft-steele-cose-merkle-tree-proofs/pull/3

**Comment by achamayou** [comment]
Yes, the description given in the verification that reads "when applicable" is missing a link to https://microsoft.github.io/CCF/main/build_apps/kv/api.html#_CPPv4N2kv9EntryTypeE, for ledger audit purposes. For receipt consumers, the endpoint emits the right fields, and so "when applicable/present" is a more reasonable description.

The CCF Merkle tree is not a public API or format, only the ledger (*) and the receipts (**) are. It could change in the future.

(*) Compatibility guarantee spelled out under https://microsoft.github.io/CCF/main/build_apps/release_policy.html#operations-compatibility
(**) verification can be performed offline, using method described in https://microsoft.github.io/CCF/main/use_apps/verify_tx.html#receipt-verification - this has changed before, and could change again, without invalidating past receipts.
