### ISSUE TITLE
Support the same endpoints for the JS and C++ logging app samples

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#5104]
It might be useful for benchmarking if the JS and C++ logging app samples supported the same set of endpoints. Likewise for the public and private message logs within each sample. 

I've not fully compared the differences, but a few I've noticed are: 
* C++ logging supports ``private/historical`` only whereas JS logging supports both ``private/historical`` and ``public/historical``
* C++ logging supports ``public/historical/range`` only whereas JS logging supports both ``public/historical/range`` and ``private/historical/range``
* C++ logging supports ``private/historical/sparse`` and JS logging does not

**Comment by achamayou** [comment]
Benchmarking is now done on the basic app.
