### ISSUE TITLE
Add sample JSON to operator RPC API

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#512]
https://microsoft.github.io/CCF/operators/operator_rpc_api.html

This includes a weirdly formatted table of the schema, but mostly people just want to see an example JSON. For the schema itself, I would probably be happy with the JSON schema dumped/referenced somewhere.

**Comment by achamayou** [comment]
What we have now is somewhat temporary until HTTP support gets better, at which point we'll use OpenAPI (https://swagger.io/docs/specification/about/)

**Comment by achamayou** [comment]
#583

**Comment by eddyashton** [comment]
Added these in #1119.
