### ISSUE TITLE
Mermaid diagrams not visible in dark-mode docs

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#5129]
Currently looks like this:

![image](https://user-images.githubusercontent.com/6000239/226589005-df73dac6-ed70-4675-84a8-d6091cbb5088.png)

I'm sure I fixed this a while ago, but whatever I did has rotted.

**Comment by achamayou** [comment]
That may be a sequence-diagram specific issue, the flowcharts are at least legible (if not particularly sleek-looking):

![image](https://user-images.githubusercontent.com/4016369/226619483-365c45ea-38f2-437c-9fa3-cf9487b21e35.png)
