### ISSUE TITLE
CLI help text for --member-cert confusing

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#515]
```
  --gov-script FILE=gov.lua REQUIRED
                              Path to Lua file that defines the contents of the gov_scripts table
  --member-cert TEXT=[] ... REQUIRED
                              Consortium member certificates
```
Looking at this, it's not clear that `--member-cert` is also a file, like `--gov-script`. If the `TEXT=[] ...` part can't be changed, then at least the help text should mention "Paths to ...".

**Comment by eddyashton** [comment]
Changed to `FILE` in #518.
