### ISSUE TITLE
Update ACI SEV-SNP configuration from files

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#5164]
Following https://github.com/microsoft/hcsshim/pull/1708, we'll need to update https://microsoft.github.io/CCF/main/operations/configuration.html#environment as the UVM reference info, VCEK certificates and security policy will be soon specified via files rather than environment variables.

**Comment by KenGordon** [comment]
See https://github.com/microsoft/hcsshim/pull/1708

**Comment by KenGordon** [comment]
See also https://github.com/microsoft/confidential-sidecar-containers/pull/23 (untested draft) which is to match this change for the SKR via MAA case.
