### ISSUE TITLE
Raft votes need to advertise their commit_idx instead of their last_idx

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#520]
When there is an election in Raft, nodes currently send their `last_idx` to indicate their state. Nodes compare their `last_idx`s to decide whether to vote for a candidate or not.

This can lead to nodes being elected even though they are further behind. If node (A) is at `last_idx` 2 but `commit_idx` 1 and node (B) is at `last_idx` 2 and `commit_idx` 2, then node (A) can win an election even though it will immediately after rollback to it's `commit_idx` 1, leaving the follower ahead of the leader.

This can be fixed by using `commit_idx` instead of `last_idx` to vote.

**Comment by achamayou** [comment]
No impact other than performance effectively (the window of loss on election is greater than it could be).
