### ISSUE TITLE
CCF node to write its pid to file

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#522]
Regarding this discussion [here](https://github.com/microsoft/CCF/pull/503#discussion_r342006860)
it would be nice to be able to tell the CCF nodes to write their process id to a file on startup, e.g. by passing a `--pidfile` argument

**Comment by jumaffre** [comment]
You can already retrieve the pid from the sealed secrets file created by each node when starting/joining a network. E.g. `sealed_secrets.20191105114613.22017` (`22017` is pid).

**Comment by achamayou** [comment]
Finding that file is slightly involved though, it'd be better for the remotes (and for the average daemonisation tool) to have node.pid somewhere deterministic.
