### ISSUE TITLE
Pin version of OpenSSL in SNP/virtual images

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#5225]
As this is currently set to the version installed on the `ubuntu:20.04` runtime Docker image, as installed via other dependencies (TBC).

**Comment by achamayou** [comment]
It's good to make sure, in our playbooks and .deb dependency constraints that we set a minimum OpenSSL version. But we don't want to pin to a specific patch, users being able to upgrade OpenSSL without picking up a new CCF is an important benefit of the move to containers (as opposed to monolithic SGX enclaves).
