### ISSUE TITLE
Log level ordering unclear in CLI helptext

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#523]
```
-l,--host-log-level TEXT in {debug,fail,fatal,info,trace}=info
                              Only emit host log messages above that level
```
The list seems to be alphabetically ordered, but it should be ordered by severity. Is trace > debug?

**Comment by achamayou** [comment]
Trace is more detailed than debug. We pass them in the right order https://github.com/microsoft/CCF/blob/master/src/host/main.cpp#L83 but CLI11 “helpfully” orders them alphabetically.

**Comment by achamayou** [comment]
Amusingly add_set is now deprecated in favour of more generic custom validators. There’s no way to control the ordering though, and it seems quite deliberately sorted to be able to do a binary search. I think we might have to live with that one.

**Comment by letmaik** [comment]
OK, not a big deal. You could repeat it in the help text in correct order but it's not worth it I think.
