### ISSUE TITLE
Make a `historical::adapter_v4` which allows customisation of the response for every error category

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#5241]
The current historical adapter (v3) is inconsistent in whether the callbacks set response bodies (app controlled format), or whether the adapter does itself (our error format + contents). Specifically, we dictate the error format when transactions are not currently available, and when historical service endorsements are not currently available.

To make the adapter more usefully generic, we should remove any calls to `ctx->set` in its body, and defer all of that to app-controlled callbacks. This will let applications use the adapter, while fully controlling their API surface.

**Comment by maxtropets** [comment]
Closed in #6322 6322
