### ISSUE TITLE
Handle failures in Piccolo

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#5289]
Current piccolo uses all responses, whether successful or not, in its performance calculations. I added a workaround for steady state benchmarking  (see `error_on_failure`) but we will need to handle this properly if we want to do experiments with node failures. We would also need to add reconnection logic to the submitter.

**Comment by heidihoward** [comment]
Linking to https://github.com/microsoft/CCF/pull/5407

**Comment by heidihoward** [comment]
Fixed in https://github.com/microsoft/CCF/pull/5407

**Comment by achamayou** [comment]
Failover to a different address on disconnection is in #5501
