### ISSUE TITLE
Resume trace validation from trace file suffix

### ISSUE THREAD

**Issue by lemmy** [microsoft/CCF#5290]
@eddyashton suggests to work around the current disparity between the TLA+ spec and its implementation in the area of bootstrapping the initial configurations by restricting trace validation to a known-good suffix of the log file.

To implement this workaround, we need to modify the `Traceccfraft.tla` file's next-state relation. The modified relation should match the behavior of ccfraft's `Next` formula for the specified number of lines that should be omitted from the log file.  More precisely, Traceccfraft's `TraceSpec` definition will look something like:

```tla

TraceSpec ==
    TraceInit /\ [][ 
                       IF l < 42
                       THEN l' = l + 1 /\ Next
                       ELSE TraceNext
                    ]_<<l, vars>>
```

Clearly, this approach will quickly become infeasible because of state-space explosion.  To mitigate, the log file could be partially matched while l < 42.  However, this might end up being more work than modeling configurations according to `raft.h`.

**Comment by achamayou** [comment]
This is more or less what [StartState](https://github.com/microsoft/CCF/pull/5828/files#diff-f72a34d202ec743abd93cf9ebdfa3b2d5ef7bba962620e7015972ff8f445112bR459) and [JoinState](https://github.com/microsoft/CCF/pull/5828/files#diff-f72a34d202ec743abd93cf9ebdfa3b2d5ef7bba962620e7015972ff8f445112bR474) do.

I doubt there is a way to generalise that unless the spec is substantially modified to drop older log entries. Deciding the initial state of the log will inevitably require a scan of all the trace lines so far.

If the spec compacted its log like the implementation does, it may be possible to backtrack from a starting point, until enough entries have been found to fill in the gap between log index and commit index for each node in active configs.

**Comment by achamayou** [comment]
We've lined up the spec and the implementation now, via the bootstrap `command` in the driver.
