### ISSUE TITLE
Custom key type for kv not compiling

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#531]
**Describe the bug**

Using a custom key type as described in the [docs](https://microsoft.github.io/CCF/developers/kv/kv_how_to.html#custom-key-and-value-types) doesn't work.

**To Reproduce**
```cc
  struct CustomKey {
    uint64_t foo;
    std::string bar;

    bool operator==(const CustomKey& other) const
    {
        return foo == other.foo && bar == other.bar;
    }

    MSGPACK_DEFINE(foo, bar);
  };
```

Compiler output:
```
In file included from ../../../src/app/app.cpp:3:
In file included from ../../../external/CCF/src/enclave/appinterface.h:4:
In file included from ../../../external/CCF/src/tls/../ds/logger.h:15:
In file included from ../../../external/CCF/3rdparty/nlohmann/json.hpp:68:
In file included from /.../include/openenclave/3rdparty/libcxx/unordered_map:408:
/.../include/openenclave/3rdparty/libcxx/__hash_table:868:5: error: static_assert failed due to requirement '__check_hash_requirements<CustomKey, hash<CustomKey> >::value' "the specified hash does not meet the Hash requirements"
```

**Expected behavior**
It should compile.

**Environment information**
CCF: eaafc9d36a10364bbf5c338444e9222ae931c135
Compiler: Clang 7.1.0

**Comment by jumaffre** [comment]
Good catch! It is also necessary to define a hash function for the `CustomKey` class, which is rather unfortunate. We'll update the docs accordingly.

**Comment by letmaik** [comment]
I switched to `std::pair<uint64_t,std::pair>` for now which works fine. I guess that wouldn't strictly count as "custom" key type, but it's good enough.

**Comment by achamayou** [comment]
Key serialisation is now user defined, but I don't think that's well documented (yet).
