### ISSUE TITLE
Authorization header

### ISSUE THREAD

**Issue by kristupaslozoraitis** [microsoft/CCF#5419]
Hello, is it possible to make a fetch request with Authorization header because now when I try to send a fetch request with a bearer token in authorization header I'm getting CORS error that  HeaderDisallowed. Can you edit configuration of CCF to add some CORS rules?

**Comment by achamayou** [comment]
@kristupaslozoraitis do you mean a request from a client to a CCF application?

CCF is largely agnostic to headers, so the client should be able to pass what it wants, including an Authorization header, and the handler code can set any response headers it would like, including Access-Control-Allow-Origin, to the appropriate value.

The exception to that is if you use jwt authentication policy, in which case CCF will try to interpret the Authorization header, but your application can still set Access-Control-Allow-Origin (and access Origin if set by the client).

If this isn't helpful, can you provide more detail about the requests you are making, and the responses the client wants to see?

**Comment by kristupaslozoraitis** [comment]
So if authentication policy is set to jwt, authorization header should be allowed to send. Other concern is how can I set Access-Control-Allow-Origin header?

**Comment by achamayou** [comment]
Clients are always allowed to send an Authorization header, and the handler code can always access it [like any other header](https://microsoft.github.io/CCF/main/build_apps/api.html#_CPPv4NK3ccf10RpcContext19get_request_headersEv). It's just that if you set the jwt auth policy, it's interpreted and checked as well.

Also see [sample](https://microsoft.github.io/CCF/main/build_apps/example_cpp.html#application-endpoints). The same page demonstrates the use of [](set_response_header) a little further down, which you can use to set "Access-Control-Allow-Origin".

**Comment by kristupaslozoraitis** [comment]
@achamayou  My application is created using typescript. Is there any samples with typescript how can I set Access-Control-Allow-Origin header. And I am trying to make a fetch request from react application and getting this error 
![image](https://github.com/microsoft/CCF/assets/65513238/b8e010b2-5975-44ea-a2ec-f83e8e5249d2)

**Comment by achamayou** [comment]
@kristupaslozoraitis please the see [this page](https://microsoft.github.io/CCF/main/js/ccf-app/interfaces/endpoints.Response.html), which contains a sample of a response including headers.

**Comment by kristupaslozoraitis** [comment]
@achamayou Strange.. Added headers to response and if I try to make a request using postman I see that the header was added, but if I try to make a request from web api using fetch, options doesn't return my added header.

Postman request:
![image](https://github.com/microsoft/CCF/assets/65513238/196ce8e2-3ff7-420e-b9ba-d9860014079b)

Web Api request:
![image](https://github.com/microsoft/CCF/assets/65513238/234b5b0f-d5e0-4309-a16b-fb4ee4160711)

**Comment by achamayou** [comment]
Unless you have specific code in your application handle that differentiates on User Agent or something like that, CCF will not produce different responses for different clients. I suggest logging on the server side, but I can't offer much on the client side.

**Comment by achamayou** [comment]
There seems to be another CORS flow called "Pre-flighted requests" https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests

Perhaps this is what your browser is trying to do? That seems to require more headers and an OPTIONS endpoint.

**Comment by kristupaslozoraitis** [comment]
@achamayou Yes, I guess Pre-flighted request is happening first. So should I just add more headers to response or I need to create additional endpoint for an options?
