### ISSUE TITLE
CCF Node HTTPS

### ISSUE THREAD

**Issue by kristupaslozoraitis** [microsoft/CCF#5425]
Hello, I am hosting CCF Node on Azure Virtual Machine and I would like to connect SSL certificate (probably self-signed) but I don't find any samples of network configuration how should I do that. Can someone provide me a config how to enforce SSL certificate to CCF network? Thanks

**Comment by achamayou** [comment]
@kristupaslozoraitis that's specific to the client you use, with curl it will be the --cacert option, in Python you will want [`context.load_cert_chain`](https://github.com/microsoft/CCF/blob/cd330415053d4ace4d7e89812d0ad2998e9b3745/tests/infra/clients.py#L766), with OpenSSL [SSL_CTX_set_cert_store](https://github.com/microsoft/CCF/blob/main/src/tls/ca.h#L64) etc.

**Comment by kristupaslozoraitis** [comment]
@achamayou And what if I am calling from the web API the node url and I am getting invalid cert authority? I thought that when you are creating CCF network you should add some additional properties to this configuration https://github.com/microsoft/CCF/blob/main/samples/config/start_config.json

**Comment by kristupaslozoraitis** [comment]
@achamayou Is bind address of this section should be different IP than your creating node address? 
![image](https://github.com/microsoft/CCF/assets/65513238/1cc01c00-7595-42d0-bad2-ec906b5e8355)

**Comment by achamayou** [comment]
@achamayou it should be an address to which the traffic going to the DNS record you have setup will eventually be routed. So if you have DNS -> Public IP - routed -> Private IP (very typical in Azure), you should bind to Private IP.

**Comment by kristupaslozoraitis** [comment]
@achamayou  I am trying to get an endorsement from Let's Encrypt, but when I create the network, it still creates with the some custom ssl where CCF creates on its own with the validity of 1 day

**Comment by achamayou** [comment]
@kristupaslozoraitis it is not possible for me to guess what has gone wrong without looking at the configuration.

It is worth noting that the configuration allows you to specify multiple rpc_interfaces, and to configure how each one must be configured (`endorsement`). Are you querying rpc interfaces where `endorsement.authority` was set to "ACME"? Were they pointing at a valid configuration? Did you follow the [configuration instructions](https://microsoft.github.io/CCF/main/operations/certificates.html#acme-endorsed-tls-certificates)?

If the answer to all of the above is yes, can you share your configuration, and the relevant log output?

**Comment by kristupaslozoraitis** [comment]
@achamayou  The configuration looks like this:
`{
    "enclave": {
        "file": "/opt/ccf_sgx/lib/libjs_generic.enclave.so.signed",
        "type": "Release",
        "platform": "SGX"
    },
    "network": {
        "node_to_node_interface": {
            "bind_address": "...:6600",
            "published_address": "...:6600"
        },
        "rpc_interfaces": {
            "acme_endorsed_interface": {
                "bind_address": "...:443",
                "published_address": "...:443",
                "authority": "ACME",
                "acme": {
                    "my-acme-cfg": {
                        "ca_certs": [
                            "-----BEGIN CERTIFICATE-----\nMIIE\n-----END CERTIFICATE-----\n"
                        ],
                        "directory_url": "https://acme-staging-v02.api.letsencrypt.org/directory",
                        "service_dns_name": "domain.com",
                        "alternative_names": [
                            "domain.com"
                        ],
                        "terms_of_service_agreed": true,
                        "challenge_type": "http-01",
                        "challenge_server_interface": "acme_challenge_server_interface"
                    }
                }
            },
            "acme_challenge_server_interface": {
            "bind_address": "...:80",
            "endorsement": {
               "authority": "Unsecured"
               }      
           }
        }
    },
    "node_certificate": {
        "subject_name": "CN=domain.com",
        "subject_alt_names": [
            "iPAddress:...",
            "dNSName:domain.com"
        ],
        "curve_id": "Secp384R1",
        "initial_validity_days": 1
    },
    "command": {
        "type": "Start",
        "service_certificate_file": "/home/azureuser/service_cert.pem",
        "start": {
            "constitution_files": [
                "/opt/ccf_sgx/bin/validate.js",
                "/opt/ccf_sgx/bin/apply.js",
                "/opt/ccf_sgx/bin/resolve.js",
                "/opt/ccf_sgx/bin/actions.js"
            ],
            "members": [
                {
                    "certificate_file": "/home/azureuser/cert.pem",
                    "encryption_public_key_file": "/home/azureuser/cert_enc_pubk.pem"
                }
            ],
            "initial_service_certificate_validity_days": 1
        }
    }
}`

**Comment by kristupaslozoraitis** [comment]
@achamayou When I creating CCF network using ACME endorsement, does "node_certificates" configuration still needed and in "command" section "service_certificate_file" should change to something else or not? Thank you

**Comment by achamayou** [comment]
> When I creating CCF network using ACME endorsement, does "node_certificates" configuration still needed

Yes, "node_certificate" configures aspect of the identity of rpc_interfaces configured with "endorsement.authority" set to "Node". It is mandatory, as per the [schema](https://github.com/microsoft/CCF/blob/62921134e03edeea76e685dd184af7bbfee86bfe/doc/host_config_schema/cchost_config.json#L404).

> in "command" section "service_certificate_file" should change to something else or not?

I don't think I understand the question. "service_certificate_file" is path to which the first node ("command.type" "Start") will write the service certificate. This is unrelated to the endorsements you configure per rpc_interface.

**Comment by kristupaslozoraitis** [comment]
@achamayou Also.. What certificate I should add to "ca_certs" sections because I don't understand.. Should it be some self-signed or I have to generate from lets encrypt using for example certbot? Thank you

**Comment by achamayou** [comment]
@kristupaslozoraitis please see schema [description](https://github.com/microsoft/CCF/blob/62921134e03edeea76e685dd184af7bbfee86bfe/doc/host_config_schema/cchost_config.json#L184C21-L184C162).
