### ISSUE TITLE
Improve parquet file writer

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#5491]
Our Piccolo submitter produces slightly weird parquet files. We can improve them in multiple ways:

- [ ] Compress the data written
- [x] Write in fewer RowGroups
- [ ] Don't write encoding statistics
- [ ] Stream output

**Comment by achamayou** [comment]
Although these changes would likely improve the speed at which we produce the files, compression may actually slow down the submitter during testing.

Outside of some one-off manual benchmark runs, the parquet file creation time has not been a material problem so far. I think we can revisit various improvements to piccolo at the next benchmark campaign, but for the foreseeable future we will not make these changes.
