### ISSUE TITLE
In TLS client connections, the node cert endorsed by the network cert should be presented

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#552]
At the moment, we present a different certificate endorsed by the network certificate with a different `CN` for the member, user and node frontends. 

Instead, we should only present the node certificate, endorsed by the network certificate for all frontends. Note that the dispatch to the proper frontend is already done via prefixing each request. 

Before a node has joined a network (e.g. still waiting for the join request to go through and the members to trust a node), only the (non-endorsed) node network should be presented to peers.

This will help us get rid of the `--insecure` hackery currently required by curl.

**Comment by jumaffre** [comment]
When this is implemented, the open/close state of a frontend will no longer depend on whether a matching certificate is installed in the `RPCSessions` object.

**Comment by jumaffre** [comment]
Some notes:
- `mbedtls` does not support parsing of v3 extensions (e.g. subject alternative name) from a CSR (https://github.com/ARMmbed/mbedtls/issues/2912). This means that when signing a node's CSR, the CA (network certificate) needs to specify the subject alternative name instead of reading it from the CSR. 
- `mbedtls` (2.16.2) only supports parsing of subject alternative name that is `DNS=` (so no `IPAddress=`). This is not an issue for curl with its default backend but will be when used if we use our current mbedtls clients (when http-enabled). Note that the current version of `mbedtls` supports `otherName=` so I guess that it will eventually support all 9 types (https://tools.ietf.org/html/rfc5280#section-4.2.1.6).

Also, the following command is particularly helpful to find out the certificate presented by a server:
```
echo | openssl s_client -showcerts -connect ip:port 2>/dev /null | openssl x509 -inform pem -noout -text
```

**Comment by achamayou** [comment]
I think we're mostly interested in vanilla curl, which is by far the most abundantly present curl in nature :)

**Comment by jumaffre** [comment]
> I think we're mostly interested in vanilla curl, which is by far the most abundantly present curl in nature :)

Exactly. Based on this, we'll probably have to drop `mbedtls` from our clients (i.e. the performance client) if we do not want to setup a DNS for our performance environment.

**Comment by jumaffre** [comment]
Implementing this now: we will not be able to use the `IPAddress=` in the `SAN` because of the join protocol that imposes mbedtls on the client side (i.e. joining node).

**Comment by achamayou** [comment]
That’s quite painful...
