### ISSUE TITLE
Reaching snapshots directory

### ISSUE THREAD

**Issue by kristupaslozoraitis** [microsoft/CCF#5525]
Hello, I don't understand how can I copy snapshots files from primary node virtual machine to a new node virtual machine or how to point to read-only snapshots directory, otherwise I cannot make a disaster recovery process. Thanks

**Comment by kristupaslozoraitis** [comment]
@jumaffre I tried to recover without snapshots files but when I try to open network for recovery I am getting error `Unable to open service: Previous service identity does not match`

**Comment by kristupaslozoraitis** [comment]
Do I need manually to create a copy of service cert? Because if I am making recovery with snapshots this problem doesn't occur. So I don't understand what is the difference

**Comment by jumaffre** [comment]
@kristupaslozoraitis Glad that you managed to get the recovery working with a snapshot! 

For each recovery, you will have to submit the service certificate of the very _latest_ defunct service. For example, if service `1` was started, crashed, and service `2` was recovered from ledger/snapshots from service `1`, then the `transition_service_to_open` proposal will need `previous_service_identity = service 1 certificate`. If service `3` is recovered from service `2`, then `transition_service_to_open` will need `previous_service_identity = service 2 certificate` (i.e. not the certificate from service `1`). 

Note that we currently require that when a snapshot is used for recovery, it must have been generated by the very latest service (see https://github.com/microsoft/CCF/issues/4528). So when recovering service `3` from service `2`, only snapshots from service `2` will be OK to use.

**Comment by kristupaslozoraitis** [comment]
@jumaffre Also after submitting the last recovery share, the nodes which were joined to primary crashed with the error `Exception while processing message <consensus::ledger_no_entry_range:1107064419> of size 17`

**Comment by achamayou** [comment]
@kristupaslozoraitis can you provide additional information, or repro instructions?

**Comment by achamayou** [comment]
Please re-open if necessary.
