### ISSUE TITLE
`test_forced_snapshot` test fails in multi-threading build

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#5549]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=74501&view=logs&jobId=b2f97161-5795-5a8b-6b22-fc2704b56b5b&j=b2f97161-5795-5a8b-6b22-fc2704b56b5b&t=dc823001-22f8-5fe4-e4ef-64577c82408f

**Comment by achamayou** [comment]
Failure not observed recently.
