### ISSUE TITLE
Large requests can cause an election

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#557]

**Comment by ashamis** [comment]
@achamayou @jumaffre - Do you know if there a test that reproducers the original issue? If not I claim this is done as a result of the thing work, do you agree?

**Comment by ashamis** [comment]
Discussed this offline.

There are currently no tests. This bug should be closed when we create a test that has an RPC that takes a long time to process and we validate that an election did not occur

**Comment by achamayou** [comment]
This isn't actionable until threading is reenabled, which is blocked on #1368.
