### ISSUE TITLE
Missing JS KV-store documentation

### ISSUE THREAD

**Issue by davidchuyaya** [microsoft/CCF#5590]
**Is your feature request related to a problem? Please describe.**
CCF [KV store documentation](https://microsoft.github.io/CCF/main/build_apps/kv/index.html) is only available for C++ and not for Javascript or Typescript.
I was briefly confused when my JS app was crashing because I used `.entries()` to iterate through a CCF map, then realized (by looking through a TS app example) that I was supposed to use `.forEach()` with a functional syntax, which is described [here](https://microsoft.github.io/CCF/main/build_apps/kv/kv_how_to.html#foreach) but just for C++.

**Describe the solution you'd like**
A page describing the API for Javascript.

**Describe alternatives you've considered**
I read through sample JS and TS apps.

**Comment by davidchuyaya** [comment]
Relatedly, it seems `console.log()` does not print at all, although the [doc here](https://microsoft.github.io/CCF/main/build_apps/logging.html) says it does, and `console.error()` only prints when the sandbox is shut down through Ctrl+C.

**Comment by achamayou** [comment]
@davidchuyaya the TS/JS doc is a bit hard to find, because it's built with a separate tool, but [does exist](https://microsoft.github.io/CCF/main/js/ccf-app/modules/kv.html). The entry point is the relatively discrete ccf-app link on the page about [building JS apps](https://microsoft.github.io/CCF/main/build_apps/js_app_ts.html#dependencies).

**Comment by achamayou** [comment]
@davidchuyaya can you provide a repro for console.log()?

**Comment by davidchuyaya** [comment]
See here: https://github.com/davidchuyaya/ccf-console-log-bug

**Comment by achamayou** [comment]
@davidchuyaya thank you, I misunderstood your question.

The logs from the various CCF nodes the sandbox starts go to a file under their respective node directories. If you start just one node, that's `workspace/sandbox_0/out`, as can be inferred from the command being run:

`08:59:15.255 | INFO     | infra.remote:start:446 - [127.0.0.1] cd /home/amchamay/ccf-console-log-bug/workspace/sandbox_0 && ./cchost --config 0.config.json --enclave-log-level info 1> /home/amchamay/ccf-console-log-bug/workspace/sandbox_0/out 2> /home/amchamay/ccf-console-log-bug/workspace/sandbox_0/err (env: dict_keys(['UBSAN_OPTIONS', 'TSAN_OPTIONS', 'ASAN_OPTIONS']))`

This could probably be made more clear in the output of sandbox.sh. The log does contain the expected output:

```
$ grep Hello sandbox_0/out 
2023-08-25T08:59:23.737564Z -0.003 0   [info ][app] ../src/js/wrap.cpp:93           | Hello log!
2023-08-25T08:59:25.208332Z -0.002 0   [fatal][app] ../src/js/wrap.cpp:1677         | Hello error!
```

Separately, the test infra (which the sandbox uses under the hood), will extract any `[fail]` and `[fatal]` log lines from any node log it ran, and bring them to the attention of the user running the test. This is why you see the second line re-printed on shutdown. I hope this helps.

If you would like to adjust the sandbox output, please do feel free to open a PR with proposals, it will be genuinely welcome.
