### ISSUE TITLE
Add unit test for TLS (SSL) stack

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#561]
At the moment, our TLS stack does not have any unit test and is only tested via end-to-end tests. We should add unit tests for it to test corner cases.

**Comment by achamayou** [comment]
We have https://github.com/drwetter/testssl.sh now, and mbedtls has its own test suite run in Open Enclave CI. If there are specific scenarios we think are missed and warrant tests in our repo, let's open individual tickets for those.

**Comment by rengolin** [comment]
#3270 implemented this issue, even if just a little. The `testssl.sh` test is still far more useful.
