### ISSUE TITLE
Consensus should be selectable at runtime

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#562]
- [x] Remove define switch
- [x] Add a runtime --consensus switch
- [x] Pass switch to enclave/nodestate
- [x] Apply necessary changes from there
- [ ] Make parameters to consensus configurable

**Comment by olgavrou** [comment]
- [ ] when pbft is the selected consensus we don't need to pass in the raft config info via cli or to the enclave/nodestate

**Comment by achamayou** [comment]
Isn't there going to be message and election timeouts for PBFT? If so, I think we can just rename them generically.
