### ISSUE TITLE
CCF configuration verification

### ISSUE THREAD

**Issue by kristupaslozoraitis** [microsoft/CCF#5652]
Hello, is there any possibilities to verify cchost configuration file validity that every values are correct, before executing cchost ? Thanks

**Comment by eddyashton** [comment]
@kristupaslozoraitis Yes - cchost has a `--check` argument which does exactly this, checking that the given config file matches the required JSON Schema for a configuration file. This will detect missing required fields, unexpected fields where additional fields are not permitted, values of the wrong type, etc. The schema used for this is in the repo [here](https://github.com/microsoft/CCF/blob/main/doc/host_config_schema/cchost_config.json), so you can also use it with any other JSON Schema validation tools. (note - be sure to use version matching your CCF release, as the configuration schema changes between some releases)

**Comment by achamayou** [comment]
Doc link: https://microsoft.github.io/CCF/main/operations/configuration.html#configuration
