### ISSUE TITLE
Message reordering breaks raft.h is_new_follower logic

### ISSUE THREAD

**Issue by lemmy** [microsoft/CCF#5676]
The introduction of the `is_new_follower` flag in #2189 has led to a behavior change in which a follower will truncate its log upon receiving its first AppendEntries message after transitioning to a follower state:

https://github.com/microsoft/CCF/blob/d6efe6664045968dc4f191b9ae672e686f05279b/src/consensus/aft/raft.h#L126-L135

However, this change is vulnerable to message reordering when AppendEntries messages do not arrive in order. This vulnerability can result in two potential issues:

In cases where the AppendEntries messages are not processed in the correct order, the follower's log may not be truncated adequately. This can lead to a violation of liveness.  Alternatively, in situations where the log is truncated too aggressively, it may cause a safety violation. Could this issue be related to https://github.com/microsoft/CCF/issues/5674?!

[Message omission](https://github.com/microsoft/CCF/issues/2577), if implemented, will also mess with `is_new_follower`.

Set milestone to "TLA+ Trace Validation" it was found as part of partially validating a scenario generated by `raft_scenario_gen.py`.  The scenario fails validation because ccfraft.tla does *not* model `is_new_follower`.

**Comment by eddyashton** [comment]
After further investigation, and discussion with @achamayou, we think this is not an issue for the implementation for 2 reasons:
- We don't have message reordering of messages between 2 nodes, due to the design of the node-to-node channels. We may have omissions. but not shuffles. This makes the optimistic `next_idx` advancement safe - a primary will only change what it sends to the backup after receiving a response, similar to in classic Raft.
- This rollback behaviour doesn't happen when processing all AEs, but only when we've processed a _matching_ AE (ie - one that extends our log, that we're going to ACK). The liveness issue of not truncating enough is thus not possible - "not enough" means you retain a non-matching suffix, so you will NACK this AE. For the safety issue, the primary would need to emit an AE that started _before_ the end of the receiver's matching suffix - the `find_highest_possible_match` probing procedure is believed to be safe in this regard, and will not produce a too-low AE message.

**Comment by lemmy** [comment]
Do we want to align the spec by changing the spec to ordered message delivery?

https://github.com/microsoft/CCF/blob/d545a6af5617535ee1e9bf79323ca240bf7f40ef/tla/Network.tla#L66-L84

**Comment by achamayou** [comment]
@lemmy yes, although there can definitely be gaps/messages missing, due to the send pipelining.

**Comment by lemmy** [comment]
@achamayou This sounds as if CCF handles [message omission](https://github.com/microsoft/CCF/issues/2577).  Can you clarify?

**Comment by achamayou** [comment]
@lemmy for some definition of omission: if an AE is nacked with a previous Index for example, the primary will re-send from that previous Index those effectively missing (presumed dropped) messages. Likewise, the primary keeps tabs on when it gets acks (`CheckQuorum`) and will step down if it doesn't hear back from enough backups, quickly enough. That's also something that would happen if messages were dropped.

We haven't implemented `PreVote` yet, so in situations where a node can send but not receive messages, it can cause repeated elections that affect liveness.

So I think it's fair to say that the implementation handles some omission cases, but not all. I believe we handle all omission cases to do with safety, and it's specifically liveness that isn't as good as it could be.

**Comment by heidihoward** [comment]
> @achamayou This sounds as if CCF handles [message omission](https://github.com/microsoft/CCF/issues/2577). Can you clarify?

I think its useful to separate safety and liveness here.
 
**Safety** - CCF today should be safe in the presence of any number of message omissions, and thus the safety invariants in the spec should hold with unordered message delivery.

**Liveness** - CCF today provides best-effort liveness in the presence of message omission but we hope to improve this in the future (Prevote etc). I aim to show liveness properties hold provided f+1 nodes are not omission faulty.

**Comment by eddyashton** [comment]
> push a mandatory patch that always responds positively to PreVote

I believe this will be sufficient to provide a safe upgrade story, but we can also do slightly better: push an update that always responds _accurately_ to PreVote. This falls into our usual upgrade pattern - push a release which _accepts but does not emit_ some new message, and only later introduce a version which actually emits it. So if 4.final nodes respond correctly to PreVote messages, they safely participate in elections started by either 4.0 or 5.0 nodes. But all 4.x nodes, including 4.final, will start their own election _without_ PreVote. The liveness benefits of PreVote (fewer spurious elections, eternally ratchetting terms) only land on 5.0, but mixed networks before then still hold safe elections.

**Comment by achamayou** [comment]
@eddyashton agreed, this is a little more complicated, but preferable.

**Comment by achamayou** [comment]
Resolved by #5716
