### ISSUE TITLE
getCommit interface needs to be made consensus-agnostic

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#57]
We should take this opportunity to introduce JSON Schema.

**Comment by jumaffre** [comment]
Should we re-purpose this issue to also include the generic consensus interface that we want for both Raft and PBFT?

**Comment by achamayou** [comment]
Issues are cheap, so let's keep this about the RPC I think, and open a different one for the internal consensus interface.

**Comment by ashamis** [comment]
I am moving this to the improvement milestone. Please tell me if I am wrong but it does not appear to be required for current ePBFT milestone?

**Comment by achamayou** [comment]
@ashamis it's not required, but I think we can agree it'd be awkward to expose "Index" and "Term" when using ePBFT. It's a fairly cheap item in any case, I'll squeeze it in somewhere.

**Comment by achamayou** [comment]
Non longer relevant, superseded by CommitID naming change.
