### ISSUE TITLE
Update gh actions to node16

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#5701]
The following warning is provided by gh actions: 

The following actions uses node12 which is deprecated and will be forced to run on node16: actions/upload-artifact@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

https://github.com/microsoft/CCF/actions/runs/6354665333

**Comment by achamayou** [comment]
@heidihoward `v3` seems [backwards compatible](https://github.com/actions/upload-artifact/releases/tag/v3.0.0) with `v2`, so updating `@v2` to `@v3` should fix this.

**Comment by heidihoward** [comment]
Fixed alongside #5707
