### ISSUE TITLE
Investigate using larger runners for gh actions

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#5703]
TLA+ models in the gh actions ci are taking a long time compared to locally (one model takes 16sec in codespaces and >3mins in the ci with the same configuration) . The standard gh runners are 2-cores[1] but larger runners are available. Let's wait for https://github.com/microsoft/CCF/pull/5702 to merge before considering this

[1] https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by achamayou** [comment]
@heidihoward runner groups need to be created at the org level, which we don't have access to: https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/managing-larger-runners

We do have a 1ES GHA pool though (gha-virtual-ccf-sub), which could be used for that purpose.
