### ISSUE TITLE
JS interpreter reuse can lead to memory violations by caching constructed state

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#5718]
First noticed, and most likely to occur, for cached KV map handles:

```
globalThis.myTable = ccf.kv["foo"];
```

Within our interpreter code, this is constructing a `kv_map_handle_class_id` object in the JS runtime, containing a `KVMap::Handle*`. If that is accessed in a future invocation, it will likely be invalid.

This is also possible, though potentially non-fatal, for any object-like things we return:
- ccf.consensus
- ccf.kv
- ccf.crypto
- ccf.request

**Comment by eddyashton** [comment]
Partial fix (for TypeScript apps going via `typedKv`) in #5717. For full fix, we need to track and invalidate any raw accesses.

**Comment by achamayou** [comment]
Full fix in #5740
