### ISSUE TITLE
Caller lookup and multi-certs

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#575]
Currently we identify callers (both members and users) by the TLS certificate they connected with. Internally this is mapped to a unique ID, but this is never exposed (though members could read it directly). It would be convenient if this was exposed so that app-level ACLs could talk more efficiently about _IDs_ rather than passing entire certs all the time. Proposed solution is a `whoami` RPC, and perhaps `whois [CERT]`.

On a related point, the single-cert identification is insufficient for long term deployments. Certs will expire, and users may also have legitimate needs for multiple keys (from multiple devices). This could be handled in app logic, with active member participation to ensure liveness, but its likely to be repeated in many apps. Instead we should abstract this within CCF - each ID is mapped to a list of valid certs, though each cert still gives a single ID. Then the above is even more valuable; permissions for user 'Bob' remain valid when he moves to a new device and generates an entirely key, without any app-specific logic, provided he can convince a member to update the service with his new key. Particular services may restrict this further with their governance script - perhaps new certs are supported but the signing key must match, perhaps the old certs are always culled so only the latest is valid.

**Comment by achamayou** [comment]
The proposed now exist, let's open specific issues to track long lived identities if/when driven by user requirements.
