### ISSUE TITLE
Expose lua execution limit to luageneric app

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#576]
Our lua interpreter has a customisable execution limit, restricting the number of instructions steps the VM can take before it throws an error. We should expose this so that it is configurable by member governance (increased or disabled entirely). We could also make the error message clearer, as it seems our current build doesn't actually produce a useful callstack.

**Comment by achamayou** [comment]
There is no user requirement for this at the moment, and we are transitioning to Javascript.
