### ISSUE TITLE
The unwrap function is not available in typescript/javascript

### ISSUE THREAD

**Issue by beejones** [microsoft/CCF#5768]
**Is your feature request related to a problem? Please describe.**
My app needs to return wrapped payloads (keys). These wrapped payloads are passed to other endpoints and need to be unwrapped. The unwrap function is not available in typescript.
It is also necessary for testing. If you create a wrapped key, you want to unwrap it in unit tests.

**Describe the solution you'd like**
Expose the crypto.unwrap function to @microsoft/ccf-app/crypto.

**Describe alternatives you've considered**
The alternative is building another wrap function on my own.

**Comment by achamayou** [comment]
@beejones can you clarify which algorithms and key sizes you need support for?

**Comment by beejones** [comment]
I am planning to use RSA-OAEP-AES-KWP.

**Comment by beejones** [comment]
Please review my PR:
https://github.com/microsoft/CCF/pull/5792

**Comment by achamayou** [comment]
Closed by #5792, and released in 5.0.0-dev6, thank you @beejones!
