### ISSUE TITLE
CI failure observed

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#5791]
This CI run unexpectedly failed: https://github.com/microsoft/CCF/pull/5778/checks?check_run_id=18090858685. Rerunning it fixed it

**Comment by heidihoward** [comment]
As did https://github.com/microsoft/CCF/pull/5790/checks?check_run_id=18092504269

**Comment by achamayou** [comment]
The first one is a disk full error, we'd added local disk to the 1ES executors to take care of this, but they do not seem to be mounted in the expected location anymore. As a workaround, I've shorted the max duration for executors to 1 day (down from 7), which will hopefully address the issue.

The second issue is an unfortunate byproduct of a build being canceled during the run of the ctest partitions step, which happens as root to be able to update iptables. When this happens, even the blocks that are normally executed on failure to clean up are not run, leaving a bunch of files owned by root under build.

One solution would be a pre-emptive cleanup step run as root, another would be to switch to a way to do network chaos testing without elevating.

**Comment by achamayou** [comment]
Accidentally closed as a result of auto-completing the wrong ticket.
