### ISSUE TITLE
Add a longer simulation run to the daily build

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#5829]
Using:

```tla
TLCSet("exit", TLCGet("duration") > atoi(IOEnv.YOUR_TIMEOUT))
```

_Originally posted by @lemmy in https://github.com/microsoft/CCF/issues/5827#issuecomment-1805908792_

**Comment by achamayou** [comment]
Would something like `IF IOEnv.YOUR_TIMEOUT # "" THEN atoi(IOEnv.YOUR_TIMEOUT) ELSE 10` not work? What's the behaviour of IOEnv if the variable isn't defined? Very worst case, we can always stick a default export in `tlc.sh`.

**Comment by lemmy** [comment]
`"YOUR_TIMEOUT" \in DOMAIN IOEnv THEN atoi(IOENV.YOUR_TIMEOUT) ELSE 10`

related: https://github.com/microsoft/CCF/blob/56ee39ea04b5d34592cb16080a5ad537c946724e/tla/consensus/Traceccfraft.tla#L61
