### ISSUE TITLE
OpenAPI coverage for all framework-level RPCs

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#583]
Once we have REST support (#582), we'd like to expose an endpoint describing our API in OpenAPI format.

As a first pass, I think we should extend the schema-generation method we already have (`listMethods`) to return a (barebones) OpenAPI document.

As a possible end-goal, we should investigate Swagger's codegen systems and see if it is possible to _start_ with an OpenAPI spec, and generate the skeleton of a CCF app with API pre-documented and enforced.

**Comment by wing328** [comment]
You may also consider using OpenAPI Generator (https://github.com/OpenAPITools/openapi-generator), which is a fork of Swagger Codegen. For the reasons behind the fork, please refer to https://github.com/OpenAPITools/openapi-generator/blob/master/docs/qna.md

Disclosure: I'm the top contributor to both OpenAPI Generator and Swagger Codegen.

**Comment by achamayou** [comment]
@wing328 thank you for the suggestion! I think it's likely we won't look at this until after the end of year holidays, but we will certainly look into the OpenAPI Generator.

**Comment by achamayou** [comment]
Re-focusing, there's a separate and more ambitious discussion to be had about generally making it easy for user apps to expose OpenAPI schemas or specify them for validation. Let's get the framework surface covered first.

**Comment by achamayou** [comment]
Interestingly, OpenAPI v3.1 will be fully JSON-schema compatible: https://apisyouwonthate.com/blog/openapi-v31-and-json-schema-2019-09

The extension that integrates the best with the rest of our doc is https://github.com/sphinx-contrib/openapi/blob/master/docs/index.rst, but we could also have the application serve something Redoc-like directly (three-pane layout with samples).

**Comment by achamayou** [comment]
This is essentially done, we just need to move the documentation over. Discussion at #1662.
