### ISSUE TITLE
CCF Crashing without logs

### ISSUE THREAD

**Issue by kristupaslozoraitis** [microsoft/CCF#5882]
Hello,

I experienced very interesting thing with CCF. When starting a CCF with one node, after **24-48 hours** every time it crashes and **any logs** have not appeared. Could you provide me more info how should I troubleshoot this problem or maybe you know this failure and in the near future it is going to be fixed? Thank you for your insights.

Additional info:
The application was uploaded.
The JWT issuer with auto refresh and JWT CA Cert bundle was uploaded.
Acme staging configuration was set up.

**Comment by kristupaslozoraitis** [comment]
In addition, the error appeared after it's crashed
`libc++abi: terminating with uncaught exception of type serialized::InsufficientSpaceException: Insufficient space (read string: 10 < 7089336936480899072)`
What this error could mean? And what could be the reason?

**Comment by eddyashton** [comment]
@kristupaslozoraitis When you say that no logs have appeared, do you mean that the node output stops? The node should continue to write to stdout and stderr up to the point where it crashes, including error information if it catches a fatal error and at least hinting at what may have led to the crash (ie - what the node was doing recently) for other crashes.

The insufficient space exception says that something is trying to read a 7 _exabyte_ string, when only 10 bytes were presented. This is likely from some kind of memory corruption or missing IO validation, as the requested length is implausible. I note that this number is a plausible ASCII string itself (hex `6262626200000000`, so `bbbb\0\0\0\0` in ASCII), but I don't know how that would be passed to the wrong argument - this is not a crash we have observed on any other CCF systems, with some nodes running continuously for several months.

Can you share some more details:
- What version of CCF are you using?
- What is the tail of the node output?
- Is the node under active load when it crashes, or idle?
- Is the node exposed to the public internet?

These might help us identify whether this is an IO validation or data load problem.

**Comment by kristupaslozoraitis** [comment]
@eddyashton Yes, the node output stops. Giving you more details:

- CCF Version `ccf-4.0.12`
- Most of the time last output before crash was:
![image](https://github.com/microsoft/CCF/assets/65513238/1b22186d-935b-439f-8b18-d81ba7cfb6ee)
`kid` is anonymized

But also sometimes last output has been:
![image](https://github.com/microsoft/CCF/assets/65513238/23468b56-95ec-4f3f-89c3-978ae70cce52)

- I would say that the node was under idle state
- Node is exposed publicly

**Comment by eddyashton** [comment]
@kristupaslozoraitis Thanks, I think I've worked out what the problem is (missing validation means some unexpected traffic on node ports can bring down a node) - will publish a fix shortly.
