### ISSUE TITLE
CCF Raft behaviour when setting the term on NACKs differs from Raft

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#5927]
This was known for some time, spotted by @heidihoward earlier when reviewing the implementation, and brought to light again by #5924. It is not believed to be an issue, at the time this is being written, but it does warrant extra scrutiny.

**Raft**: term of the current, as provided previously on the send append entries.

![image](https://github.com/microsoft/CCF/assets/4016369/59b105e2-ee40-4817-8dc6-98bec922214b)

From https://raft.github.io/raft.pdf (wouldn't it be nice if there was a way to link to a section in a paper?).

**CCF implementation**: [term of the last index in the backup's log](https://github.com/microsoft/CCF/blob/e5a7106a03686e5da881c1ec9f182d3a468159de/src/consensus/aft/raft.h#L1348), [same in the spec, with additional prevLogIndex fix in this PR](https://github.com/microsoft/CCF/blob/e5a7106a03686e5da881c1ec9f182d3a468159de/tla/consensus/ccfraft.tla#L778).

The questions we would like to resolve are:

1. Does this affect safety?
2. Does this affect liveness?

The existing verification work suggests that the answer to 1. may be "no", but 2. remains more open.

**Comment by achamayou** [comment]
Following discussion with @heidihoward @eddyashton @lemmy, we will:

1. Update the spec to not drop those messages when they are stale
2. Look at adding stats and nack injection in the sim, to better understand if this may cause a liveness issue. This is lower priority.

**Comment by lemmy** [comment]
> Following discussion with @heidihoward @eddyashton @lemmy @nacrooks, we will:
> 
> 2. Look at adding stats and nack injection in the sim, to better understand if this may cause a liveness issue. This is lower priority.

For future reference, https://github.com/microsoft/CCF/blob/4d6f8e2dfa407c2d27a2be8840ddf11ea58f1d71/tla/consensus/SIMCoverageccfraft.tla#L49-L64 shows how to collect statistics for a spec.  A more complex example is at https://github.com/tlaplus/Examples/tree/master/specifications/ewd998#statistics.

**Comment by achamayou** [comment]
This was found to be a potential safety issue, details captured in #5991, investigated further in #6001, and addressed in #6016.

The issue was resolved by removing the unnecessarily aggressive rollback behaviour, rather aligning the NACK term value with that in Raft.
