### ISSUE TITLE
Unexpected error when running sandbox script

### ISSUE THREAD

**Issue by aamar-shahzad** [microsoft/CCF#5950]
**Describe the bug**
Have issue to start the sandbox when added external library to [https://github.com/dpilger26/NumCpp](url)

**To Reproduce**
Added `NumCpp` in `3rdpart` as submodule
included the `add_subdirectory(3rdparty/NumCpp)` in CmakeList.txt
**Expected behaviour
It need to bootstart the network usign sandbox script in virtual model
but getting following error
![image](https://github.com/microsoft/CCF/assets/51914039/a2936696-6500-4907-b5dd-11030c8349aa)

[04:21:21.910] Please raise a bug if the issue is unexpected: https://github.com/microsoft/CCF/issues/new?assignees=&labels=bug&template=bug_report.md&title=Unexpected%20error%20when%20running%20sandbox%20script
make: *** [Makefile:87: run-virtual] Error 1`

**Environment information**
I am run in dev container in linux Os.

**Comment by achamayou** [comment]
Unless given overrides via -n, the sandbox will attempt to start a node listening on port 8000 on 127.0.0.1. Can you check if there is another process already listening on that port?
