### ISSUE TITLE
Certificates output to disk should not be null-terminated

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#601]
Because `mbedtls` requires PEM strings to be null-terminated to be parsed, we currently store certificates to disk with a null-terminator.

We should review our current implementation and have the `Pem` class enforce that raw PEM objects (not null-terminated, e.g. created via `openssl`) are null-terminated when parsed by `mbedtls`.

**Comment by achamayou** [comment]
We should not write them out that way (anymore), but we should still accept them in `Pem` if they are.

**Comment by achamayou** [comment]
Users/members certs are no longer null-terminated, but node/network certs still are.

**Comment by achamayou** [comment]
This doesn't seem to be a problem at all.
