### ISSUE TITLE
Need modern API equivalent of the classic gov/kv/modules API

### ISSUE THREAD

**Issue by gaurav137** [microsoft/CCF#6117]
With the classic APIs one can invoke `gov/kv/endpoints` to know the JS app endpoint details and `gov/kv/modules` to know the JS app modules. In the modern APIs `gov/service/javascript-app` is mapping to `gov/kv/endpoints` but there is no `gov/kv/modules` equivalent.

We need a `gov/kv/modules` equivalent in the modern API to be able to expose the details of the JS application that is currently deployed on CCF.  Scenario is that members that are joining the consortium are expected to review the code behind the constitution and the JS APP that is currently deployed before activating their membership. And after doing that review any `set_constitution` and `set_js_app` proposals in the future. Thus we need to expose the same information via the modern APIs as what one would review in a `set_constitution` and `set_js_app` proposal.

**Comment by achamayou** [comment]
Done: https://microsoft.github.io/CCF/main/governance/gov_api_schemas/2024-07-01.html#get--gov-service-js-modules
