### ISSUE TITLE
Find a way to restore or replace cimetrics

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#6126]
We disabled `cimetrics` in #6125, to avoid use of `METRICS_MONGO_CONNECTION`.

We should look at restoring `cimetrics`, either with improved auth to mongo, or by finding an alternative storage mechanism.

**Comment by achamayou** [comment]
I looks like bencher.dev may be [what we want](https://bencher.dev/console/projects/ccf/perf?branches=47a2cef2-2400-4286-ae79-fb17c98b2c23&testbeds=1e6f6a27-eb58-4f16-8d01-0148fbaed70e&benchmarks=7baac671-8a7c-4968-a7dc-aea6fbbec759%2Ced8e5432-5ebc-49dd-89b9-9839fed1d945%2C68e15d7c-3859-49de-8d94-92cb3331d075%2Cea38e096-f614-4907-b33d-749020d68afa%2C09034135-5114-49ea-b270-03a98fbc0bb7&measures=bc9fb376-9a85-478a-97fd-ebd7703c9663&start_time=1712758465000&end_time=1715350465000&key=true&reports_per_page=4&branches_per_page=8&testbeds_per_page=8&benchmarks_per_page=8&reports_page=1&branches_page=1&testbeds_page=1&benchmarks_page=1&report=cc1a7aa5-d97b-43aa-bc3a-a8237a8e0868&clear=true).

Test job: https://github.com/microsoft/CCF/blob/bencher_experiment/.github/workflows/bencher.yml, works on ubuntu 20.04 using a 1ES pool.

The json adapter supports both latency and throughput, and the format is very simple: https://bencher.dev/docs/explanation/adapters/#-json

I think we would move the performance tests to GHA for simplicity, and we would start with just running on main. The setup for PRs on branches seems to need a bit of care to avoid exposing secrets, but we may be able to do without it and just check periodically.

**Comment by achamayou** [comment]
[pi_basic_virtual_cft](https://bencher.dev/console/projects/ccf/perf?branches=47a2cef2-2400-4286-ae79-fb17c98b2c23&testbeds=1e6f6a27-eb58-4f16-8d01-0148fbaed70e&benchmarks=2c9d4ba9-c6c8-43dd-a5ed-27b9d04918f4&measures=61344be9-e1b4-4c7d-b707-1d54c82119eb&start_time=1712770903000&end_time=1715362903000&key=true&reports_per_page=4&branches_per_page=8&testbeds_per_page=8&benchmarks_per_page=8&reports_page=1&branches_page=1&testbeds_page=1&benchmarks_page=1)

**Comment by achamayou** [comment]
Saving the last copy of the trend plots before we drop the storage account:

![image](https://github.com/microsoft/CCF/assets/4016369/a6b51129-6eb7-4a8b-b819-393e29282c30)

**Comment by achamayou** [comment]
After review with @eddyashton, we want in addition:

- [ ] check the way MT numbers are reported, they look low
- [ ] add TPCC

**Comment by eddyashton** [comment]
> take a look at Basic too, which seems to have dropped, perhaps because of programmability

Fiddling locally, I'm seeing ~56k with the current `basic` (with programmability). If I remove the `DynamicJSEndpointRegistry::find_endpoint`, which even with empty tables is doing a few KV lookups, I get back to 61k. I think we should fork a separate `programmability` app, to retain `basic` as a minimal perf test.

**Comment by achamayou** [comment]
@eddyashton agreed, that'd be useful for clarity, especially since further changes are coming for programmability. It's going to increase build times though, so I think we may want to find something we can sacrifice too.
