### ISSUE TITLE
Sample for JS API extension

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#6277]
We have C++ APIs allowing apps to build JS extensions, exposing their own functionality in the global namespace of a JS interpreter. We should provide clearer samples of how an app should do this (currently all extensions are framework level).

**Comment by achamayou** [comment]
I suggest we remove https://github.com/microsoft/CCF/issues/2970 as part of this, since it never saw usage and the new mechanism seems better.

**Comment by eddyashton** [comment]
Done in #6289
