### ISSUE TITLE
Gov API versioning for 5.0.0 (final)

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#6280]
We currently support 2 gov APIs.
- [x] We will mark the old ("Classic") API as deprecated in 5.0, and remove it in 6.0.
- [x] The new API takes a version-string, and we currently only have a preview version. Since the contents of this API are now much firmer, we should replace it with a non-preview API version-string.
- [x] We should take a canonical description of the API (OpenAPI, or TypeSpec, or both) back into this repo to live alongside (and be kept up-to-date with) the corresponding CCF source.

**Comment by achamayou** [comment]
Link: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/confidentialledger/Microsoft.ManagedCcf

**Comment by achamayou** [comment]
Goals:

1. Support one API
2. Have that API as close to Azure Standards as possible, in case:
  a. Services want to expose (some of) it
  b. Services want to use SDK generation tooling to handle governance
