### ISSUE TITLE
Support for WebSockets

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#629]
As of today, CCF only supports framed JSON-RPC and HTTP. The former is fast but not ideal for client compatibility while the latter causes a large per-request overhead (i.e. HTTP header). 

CCF should also support WebSocket endpoints to maximise requests throughput. 

Tasks:
- [x] Add a WebSocket client to `clients.py`. 
- [x] Support for WebSocket handshake.
- [x] Support for deserialisation of WebSocket frames on CCF side.
- [x] Support for specific user defined handlers (rather than forward to http definition when possible)
- [ ] Protocol-level close and heartbeats
- [ ] Support for masked traffic
- [ ] Stricter negotiation check (*)
- [ ] Client documentation

(*) ws_upgrade.h:53

Our logic does not check for the Connection header, and does not check what protocol the client is requesting an upgrade to: https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism#Upgrading_to_a_WebSocket_connection

**Comment by achamayou** [comment]
Looking at https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers, I think there's a number of restrictions we can place on WebSockets support, at least initially.

1. Client masking. This is clearly a complete waste of time and space on a TLS connection. While it's nice to add for compatibility with existing clients, it isn't necessary at first.
2. WebSockets-level fragmentation, ie. supporting multiple frames with FIN 0 followed by a FIN 1. Same as above, there's no clear use case for that in the context of CCF clients (none of the popular client libraries I've looked at even implement it), so it does not need to be there in the initial implementation.
3. binary/text opcode distinction, we can restrict ourselves to binary.
4. The sub-protocol feature may be a nice way to expose the supported FlatBuffer schemas, we don't need to use it at first, but it's potentially something to look into.

**Comment by achamayou** [comment]
Most of this went in with #1193 and #1211, but there are still a few bit and pieces that need sorting out before it's really complete (listed as tickboxes in the OP).

**Comment by achamayou** [comment]
In the absence of user interest for WebSockets, I am shelving this. We will discuss removing support altogether, to reduce TCB and build/test times.
