### ISSUE TITLE
Dynamically configure historical cache limit in logging app

### ISSUE THREAD

**Issue by maxtropets** [microsoft/CCF#6299]
#6282 introduced fixed logging app cache limit to test it out in historical perf test.

It's better to make it callable from the client. A nice thing to have would be to somehow verify cache shrinking in e2e tests.

https://github.com/microsoft/CCF/pull/6282#discussion_r1656896898

**Comment by achamayou** [comment]
For now, since this is a global setting, let's make this a node configuration setting that the operator can set at startup. We can revisit it if there is a need for something more specific (but might need to have separate cache quotas for the C++ and programmable endpoints for example).
