### ISSUE TITLE
Perf tests failing in debug builds

### ISSUE THREAD

**Issue by maxtropets** [microsoft/CCF#6421]
```
cd build
cmake -GNinja -DCOMPILE_TARGET=virtual -DCMAKE_BUILD_TYPE=Debug ..
ninja
./tests.sh -VV -R "pi_basic|historical_query_perf_test"
```

Why? It's quite confusing to see those failing when developing with debug build, took me some time figuring that out when working on another feature.

Any of the following I'd consier satisfying
* we exclude them from CMake in debug
* we fix them to pass in debug

**Comment by achamayou** [comment]
The perf tests do tend to exceed their timeouts in debug, on account of being much slower that way.

In CI, they are selected out with -LE, but when doing local runs, it's easy to forget to do that/annoying to have to do it.

A possibility is to use the same mechanism we use with partition tests (which require being run with elevated privileges) to exclude them from the default set of tests, and specifically enable them in the Bencher pipeline, by creating a [configuration](https://github.com/microsoft/CCF/blob/main/CMakeLists.txt#L1420). When we want to run them (i.e. in the bencher pipeline), we will need to pass an extra [-C e2eperf](https://github.com/microsoft/CCF/blob/main/.github/workflows/ci.yml#L95), or whatever we call the configuration.
