### ISSUE TITLE
`openapi` property name in the bundle.json gets returned as `openApi` by `/gov/service/javascript-app` and not `openapi`

### ISSUE THREAD

**Issue by gaurav137** [microsoft/CCF#6434]
`openapi` property name in the bundle.json gets returned as `openApi` by `/gov/service/javascript-app` endpoint but the original value was not `open_api` ie in snake case. So we should fix the `javascript-app` endpoint to not return `openApi` but `openapi`. The convention seems to be that what was in snake case in bundle.json has become camel case in the API response.

**Comment by achamayou** [comment]
This seems like a subset of #6433?
