### ISSUE TITLE
COSE signing wrappers

### ISSUE THREAD

**Issue by maxtropets** [microsoft/CCF#6445]
Introduce `cose_sign1` wrapper using t_cose and qcbor.

Will accept protected headers and raw payload (detached) to sign.

Note. It seems there's no way to pass custom protected headers to `t_cose`, neither [single-step](https://github.com/laurencelundblade/t_cose/blob/master/examples/t_cose_basic_example_psa.c#L219) or [two-step](https://github.com/laurencelundblade/t_cose/blob/master/examples/t_cose_basic_example_psa.c#L404) signing example demonstrate that. Hence, we've made a more complex version based on the latter one, with patched headers setting, which replaced the original call to `t_cose_sign1_encode_parameters`.

**Comment by achamayou** [comment]
@maxtropets suggest expanding the issue with the goal we're trying to achieve (safe C++ interface to sign COSE payloads, to be used internally by CCF when signing (and verifying) merkle root).
