### ISSUE TITLE
When node hits `StartupSeqnoIsOld` it can exit instead of looping endlessly

### ISSUE THREAD

**Issue by gaurav137** [microsoft/CCF#6471]
When incorrectly starting a node with an older snapshot and the target the `StartupSeqnoIsOld` error gets printed by cchost but the process does not exit. Since this is a non-recoverable failure cchost could exit. Currently while adding a new node in join mode if this issue is hit then when the orchestration logic starts the new node its not easy to figure out why the node is not connecting to the network . If the process had exited then failure would be more apparent.

**Comment by achamayou** [comment]
Yes, agreed.
