### ISSUE TITLE
Support COSE receipts in CCF

### ISSUE THREAD

**Issue by maxtropets** [microsoft/CCF#6477]
```[tasklist]
### Tasks
- [ ] get_cose_sign1_signature() API in historical queries
- [ ] get_cbor_merkle_proof() API in historical queries
```

**Comment by achamayou** [comment]
API names and shapes may vary :)

**Comment by maxtropets** [comment]
Do we need a specific API call to get sign1_signature? Isn't it just enough to populate `TxReceiptImpl` with the value?

**Comment by achamayou** [comment]
@maxtropets we need a specific API to construct the proof, and add it to a uhdr param in the signature. That's what users will want to get in the end.

**Comment by maxtropets** [comment]
Just to clarify the final structure of the CBOR in question

```
[] - array
{} - map
() - sequence

COSE [
  phdr {
    ...
  }
  uhdr {
    leaf: int -> arr [
        wsd: bstr
        ce: tstr
        cd: bstr
    ]
    path: int -> arr [
        [left: bool, root: bstr]
        [left: bool, root: bstr]
        ...
        [left: bool, root: bstr]
    ]
  }
  payload (null)
  sig (
    bytes
  )
]
```

**Comment by maxtropets** [comment]
Discussed with @achamayou, due to the [RFC](https://datatracker.ietf.org/doc/draft-ietf-cose-merkle-tree-proofs/) still being developed at the moment we will provide two separate things to the caller.

- `leaf` and `path` encoded as a `bstr .cbor`
- `cose_sign1` of a merkle root

The caller's ought to enclose the proof into the `cose_sign1` unprotected headers section. This will allow to avoid issuing new CCF releases for each RFC change until it's finalised. Afterwards we might discuss providing an API for a ready-to-go COSE receipt compilation.
