### ISSUE TITLE
Run TLA+ consensus/consistency from vscode

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#6490]
At the moment, users cannot run the TLA+ specs in codespaces out of the box due to the shared [StatsFile.tla](https://github.com/microsoft/CCF/blob/main/tla/StatsFile.tla). It would be great if we could support this, we have at least three options:
* Remove `StatsFile.tla` as this was mostly used for cimetrics
* Duplicate `StatsFile.tla` between the consensus and consistency directories
* (If possible) Modify the devcontainer settings so the TLA+ vscode plugin knows to look in `/tla` for the modules

We would also need to add `tlc2.tool.impl.Tool.cdot=true` to the devcontainer

**Comment by lemmy** [comment]
> At the moment, users cannot run the TLA+ specs in codespaces out of the box due to the shared [StatsFile.tla](https://github.com/microsoft/CCF/blob/main/tla/StatsFile.tla). It would be great if we could support this, we have at least three options:
> 
> * Remove `StatsFile.tla` as this was mostly used for cimetrics
> * Duplicate `StatsFile.tla` between the consensus and consistency directories
> * (If possible) Modify the devcontainer settings so the TLA+ vscode plugin knows to look in `/tla` for the modules

The module `StatsFile` does not seem to be a dependency of the consistency spec.

> We would also need to add `tlc2.tool.impl.Tool.cdot=true` to the devcontainer

I recommend rewriting `ccfraft` without using `cdot`, as the incomplete implementation of `cdot` may lead to subtle issues under (non-trivial) refinement:

https://github.com/microsoft/CCF/blob/3cf06afea57ed15114810748aa4a6a892e330b4c/tla/consensus/ccfraft.tla#L1101-L1102

**Comment by achamayou** [comment]
@heidihoward is this still an issue with `StatsFile.tla` gone?

In general, it's relatively straightforward to guarantee that things we run in the CI are reproducible by users (modulo unfortunately the stuff that requires Azure resources like the SNP tests): they can pull the image and run the same commands. Checking that something works in VS Code is not something we can practically check in CI, as far as I can tell.

**Comment by heidihoward** [comment]
There's now a new challenge as the environment variables introduced last week need to be set

**Comment by achamayou** [comment]
The invocation seems to set the environment, to provide cwd, but allows no other env var customisation: https://github.com/tlaplus/vscode-tlaplus/blob/35a53385b33c5374100e7c1bce10a9b8ead8ca59/src/tla2tools.ts#L157
