### ISSUE TITLE
Drop SECP256K1 support

### ISSUE THREAD

**Issue by maxtropets** [microsoft/CCF#6592]
https://github.com/microsoft/CCF/issues/6588#issuecomment-2437966165

**Comment by maxtropets** [comment]
@achamayou says
https://github.com/microsoft/CCF/issues/6588#issuecomment-2441342250

Let's prove and close if that's the case

**Comment by achamayou** [comment]
Not present in https://github.com/microsoft/SymCrypt/blob/907622c6658877014ea3fea336e2efa407864fdc/lib/ec_internal_curves.c#L583
nor in https://github.com/microsoft/SymCrypt/blob/907622c6658877014ea3fea336e2efa407864fdc/unittest/lib/openssl_implementations.cpp#L1108

Probably good to ask to confirm, but seems very likely it's not supported.

**Comment by achamayou** [comment]
It's definitely not in the list of supported curves: https://github.com/microsoft/SymCrypt/blob/main/inc/symcrypt.h#L7463

**Comment by achamayou** [comment]
I think this ticket turns into "Drop SECP256K1 support in CCF", since:

1. we don't have an approved crypto provider that implements it on Azure Linux
2. we are no aware of any usage
