### ISSUE TITLE
Formally define public headers/API

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#66]

**Comment by olgavrou** [comment]
Regarding the discussion here: https://github.com/microsoft/CCF/pull/781#discussion_r374558463

Right now we make specific checks on `deserialise` depending on the consensus. We should abstract this away, for example having each consensus pass a lambda to `deserialise` or a define a deserialise lambda at table creation, which lambda will be called after deserialise has happened (or something else entirely). 

That way the consensus assumptions will be separated from the function call.
