### ISSUE TITLE
e2e test timeout

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#661]
Possibly related to #659 

small_bank_sigs_forwarding test times out occasionally 

cmake info

> BUILD_END_TO_END_TESTS:BOOL=ON
> BUILD_SMALLBANK:BOOL=ON
> BUILD_TESTS:BOOL=ON
> CMAKE_BUILD_TYPE:STRING=Debug
> CMAKE_INSTALL_PREFIX:PATH=/usr/local
> COLORED_OUTPUT:BOOL=ON
> COVERAGE:BOOL=OFF
> CRYPTO_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcrypto.so
> DEBUG_CONFIG:BOOL=OFF
> DISABLE_QUOTE_VERIFICATION:BOOL=OFF
> EVERCRYPT_PREFIX:PATH=[...]/hacl-star/evercrypt
> EXTENSIVE_TESTS:BOOL=OFF
> FOUND_CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++-8
> FOUND_CMAKE_C_COMPILER:FILEPATH=/usr/bin/clang-8
> HTTP:BOOL=OFF
> NO_STRICT_TLS_CIPHERSUITES:BOOL=OFF
> OE_PREFIX:PATH=/opt/openenclave
> PBFT:BOOL=OFF
> SAN:BOOL=OFF
> SERVICE_IDENTITY_CURVE_CHOICE:STRING=secp384r1
> TARGET:STRING=sgx
> USE_NLJSON_KV_SERIALISER:BOOL=OFF
> USE_NULL_ENCRYPTOR:BOOL=OFF
> 

attaching logs
[out_client.log](https://github.com/microsoft/CCF/files/3989355/out_client.log)
[out0.log](https://github.com/microsoft/CCF/files/3989356/out0.log)
[out1.log](https://github.com/microsoft/CCF/files/3989357/out1.log)

**Comment by achamayou** [comment]
Almost certainly related to #700 and #704, so closing as duplicate.
