### ISSUE TITLE
Automated GitHub releases

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#664]
We should make use of https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops to automate the GitHub release process.

As I see it: 
1. When we're happy with a release, push a `vX.y` tag to `master` and kick off a build.
2. Have a Azure Pipelines task trigger for such tag on the build configuration we want to ship (e.g. SGX HTTP RAFT). 
3. Attach the assets we want to attach to the issue (i.e. `cchost`, `libluageneric.so`), along with a list of all the commits since the last release and create a draft GitHub release,
4. Edit the draft PR and release it (manually).

**Comment by achamayou** [comment]
Longer term I think we want a .deb that would install headers/source in the right place, as well as the .so and binaries, and would depend on the appropriate openenclave .deb, but at first I agree this is a good set of first steps.

**Comment by jumaffre** [comment]
As discussed today, the plan is to:
1. Re-purpose the performance test jobs to run the entire suite of tests (include performance) when a job is run against a tagged (`v*`) `master` build (reason: we want to ship a `Release` build). 
2. Have the CFT HTTP and FTCP flavours of the (new) release jobs run `ninja install` once the rest of the tasks have successfully completed, tarball the output directory, and publish it as a Azure Pipelines artefact.
3. Create a new "GitHub Release" job that only runs on tagged (`v*`) `master` builds and which waits for the release jobs to successfully complete. This job should download the tarballs from step 2 and publish them to GitHub using [Azure Pipelines GitHub Release Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops).

Also, for v0.7, CCF builds should default to using HTTP. FTCP should still be available via the `-DFTCP` cmake option.

**Comment by achamayou** [comment]
@jumaffre 

1. a. s/re-purpose/extend, we also want perf numbers for the release.
2. a. check that the install target includes libluageneric.so
3. a. As discussed, that can also wait on relevant Debug and SAN jobs.
