### ISSUE TITLE
Support JS constitution scripts

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#669]
We should support JS scripts for the constitution, for proposals, and for vote ballots. This will involve replacing the lua interpreter in the member frontend with a JS interpreter, and replacing our sample scripts with JS alternatives.

**Comment by achamayou** [comment]
After discussion with @eddyashton, @letmaik and @jumaffre, these are the main differences with the current Lua governance we have now that I think we want to implement in the Javascript replacement.

First, proposals become a static list of actions rather than a script returning a list of actions. We've not seen any use of the dynamic nature of proposals (ie. their use of KV state as input), on the contrary users so far prefer idempotent actions (#1791, #2169). But we know that it makes error reporting and handling difficult, since actions are not materialised and validation can only happen at voting time.

So this:

```
$ cat new_member.json
{
  "parameter": {
    "cert": "-----BEGIN CERTIFICATE-----\nMIIBdzCCARygAwIBAgIURwD6S1/rcb2TbHhQLnTNh/7WyYYwCgYIKoZIzj0EAwIw\nEjEQMA4GA1UEAwwHbWVtYmVyNDAeFw0yMDEwMjkxNjI2NTNaFw0yMTEwMjkxNjI2\nNTNaMBIxEDAOBgNVBAMMB21lbWJlcjQwVjAQBgcqhkjOPQIBBgUrgQQACgNCAARG\nwqj2ZD7vA+h4KoTdh3if3tVO/yks+xtLU1tXAFsbeWSQfDxK3nnA65uX6n/25A20\nJcAQMDHYH2NdLOLra9lxo1MwUTAdBgNVHQ4EFgQUQQDC71N60r/a9c+EGXrzr5l6\nIDQwHwYDVR0jBBgwFoAUQQDC71N60r/a9c+EGXrzr5l6IDQwDwYDVR0TAQH/BAUw\nAwEB/zAKBggqhkjOPQQDAgNJADBGAiEAkvP0AuAU7y0b3z4rhvoOkCBKoH4G3vh/\nPJpLFdWcEu4CIQCSnEYpDaDTP2zoWTheqchZ+/BdTzM2j2s9ILpvSVYMxg==\n-----END CERTIFICATE-----\n",
    "encryption_pub_key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvYKesV5xoT2XnGhLkeqZ\neSC2KsjNUvdjqPrTERk/hp64Xd30SGjdj2HytG3hfCy5hBhc9muQMXoOAOBgxwMA\nQRu7KCANPZNCLEWKR5DZc8YzE+rHX1/8WxhhtV/bvr90selV0BfLWLLJYDxnyo3D\nyioYXNw6Ij2sYBt8MTPNPti3jRJ7LmMow/VrJD9Ww1FKWCyxa7/iCxSsbmrwdv8m\nBVf/+d3p+ivxb6gBvtTimj+fj1OdRkGHElZSaBFWmQISga3Ki4vnP4W1iw/ujaza\n3gItLPrEnD0lxGBaCSs+XVm2l8nsn3HJDZYMP5u3jWB3MWsBwna0o+KUon4KaS1k\nlwIDAQAB\n-----END PUBLIC KEY-----\n",
    "member_data": null
  },
  "script": {
    "text": "\n    tables, args = ...\n    return Calls:call(\"new_member\", args)\n    "
  }
}

$ scurl.sh https://<ccf-node-address>/gov/proposals --cacert network_cert --key member1_privk --cert member1_cert --data-binary @add_member.json -H "content-type: application/json"
{
  "proposal_id": "d4ec2de82267f97d3d1b464020af0bd3241f1bedf769f0fee73cd00f08e9c7fd",
  "proposer_id": 1,
  "state": "OPEN"
}
```

Becomes:

```
$ cat new_member.json
[
    {
        "call": "new_member",
        "args": 
        [
            "-----BEGIN CERTIFICATE-----\nMIIBdzCCARygAwIBAgIURwD6S1/rcb2TbHhQLnTNh/7WyYYwCgYIKoZIzj0EAwIw\nEjEQMA4GA1UEAwwHbWVtYmVyNDAeFw0yMDEwMjkxNjI2NTNaFw0yMTEwMjkxNjI2\nNTNaMBIxEDAOBgNVBAMMB21lbWJlcjQwVjAQBgcqhkjOPQIBBgUrgQQACgNCAARG\nwqj2ZD7vA+h4KoTdh3if3tVO/yks+xtLU1tXAFsbeWSQfDxK3nnA65uX6n/25A20\nJcAQMDHYH2NdLOLra9lxo1MwUTAdBgNVHQ4EFgQUQQDC71N60r/a9c+EGXrzr5l6\nIDQwHwYDVR0jBBgwFoAUQQDC71N60r/a9c+EGXrzr5l6IDQwDwYDVR0TAQH/BAUw\nAwEB/zAKBggqhkjOPQQDAgNJADBGAiEAkvP0AuAU7y0b3z4rhvoOkCBKoH4G3vh/\nPJpLFdWcEu4CIQCSnEYpDaDTP2zoWTheqchZ+/BdTzM2j2s9ILpvSVYMxg==\n-----END CERTIFICATE-----\n",
            "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvYKesV5xoT2XnGhLkeqZ\neSC2KsjNUvdjqPrTERk/hp64Xd30SGjdj2HytG3hfCy5hBhc9muQMXoOAOBgxwMA\nQRu7KCANPZNCLEWKR5DZc8YzE+rHX1/8WxhhtV/bvr90selV0BfLWLLJYDxnyo3D\nyioYXNw6Ij2sYBt8MTPNPti3jRJ7LmMow/VrJD9Ww1FKWCyxa7/iCxSsbmrwdv8m\nBVf/+d3p+ivxb6gBvtTimj+fj1OdRkGHElZSaBFWmQISga3Ki4vnP4W1iw/ujaza\n3gItLPrEnD0lxGBaCSs+XVm2l8nsn3HJDZYMP5u3jWB3MWsBwna0o+KUon4KaS1k\nlwIDAQAB\n-----END PUBLIC KEY-----\n"
        ]
    }
]

$ scurl.sh https://<ccf-node-address>/gov/proposals --cacert network_cert --key member1_privk --cert member1_cert --data-binary @add_member.json -H "content-type: application/json"
{
  "proposal_id": "d4ec2de82267f97d3d1b464020af0bd3241f1bedf769f0fee73cd00f08e9c7fd",
  "proposer_id": 1,
   "state": "OPEN"
}
```

Note that we deliberately use positional arguments here to keep the interface generic. Our built-in actions may choose to take a single object instead with named fields. 

A proposal is a list, and can contain any number of actions:

```
$ cat new_members.json
[
    {
        "call": "new_member",
        "args": 
        [
            "-----BEGIN CERTIFICATE-----\nMIIBdzCCARygAwIBAgIURwD6S1/rcb2TbHhQLnTNh/7WyYYwCgYIKoZIzj0EAwIw\nEjEQMA4GA1UEAwwHbWVtYmVyNDAeFw0yMDEwMjkxNjI2NTNaFw0yMTEwMjkxNjI2\nNTNaMBIxEDAOBgNVBAMMB21lbWJlcjQwVjAQBgcqhkjOPQIBBgUrgQQACgNCAARG\nwqj2ZD7vA+h4KoTdh3if3tVO/yks+xtLU1tXAFsbeWSQfDxK3nnA65uX6n/25A20\nJcAQMDHYH2NdLOLra9lxo1MwUTAdBgNVHQ4EFgQUQQDC71N60r/a9c+EGXrzr5l6\nIDQwHwYDVR0jBBgwFoAUQQDC71N60r/a9c+EGXrzr5l6IDQwDwYDVR0TAQH/BAUw\nAwEB/zAKBggqhkjOPQQDAgNJADBGAiEAkvP0AuAU7y0b3z4rhvoOkCBKoH4G3vh/\nPJpLFdWcEu4CIQCSnEYpDaDTP2zoWTheqchZ+/BdTzM2j2s9ILpvSVYMxg==\n-----END CERTIFICATE-----\n",
            "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvYKesV5xoT2XnGhLkeqZ\neSC2KsjNUvdjqPrTERk/hp64Xd30SGjdj2HytG3hfCy5hBhc9muQMXoOAOBgxwMA\nQRu7KCANPZNCLEWKR5DZc8YzE+rHX1/8WxhhtV/bvr90selV0BfLWLLJYDxnyo3D\nyioYXNw6Ij2sYBt8MTPNPti3jRJ7LmMow/VrJD9Ww1FKWCyxa7/iCxSsbmrwdv8m\nBVf/+d3p+ivxb6gBvtTimj+fj1OdRkGHElZSaBFWmQISga3Ki4vnP4W1iw/ujaza\n3gItLPrEnD0lxGBaCSs+XVm2l8nsn3HJDZYMP5u3jWB3MWsBwna0o+KUon4KaS1k\nlwIDAQAB\n-----END PUBLIC KEY-----\n"
        ]
    },
    {
        "call": "new_member",
        "args": 
        [
            "-----BEGIN CERTIFICATE-----\nMIIBdzCCARygAwIBAgIURwD6S1/rcb2TbHhQLnTNh/7WyYYwCgYIKoZIzj0EAwIw\nEjEQMA4GA1UEAwwHbWVtYmVyNDAeFw0yMDEwMjkxNjI2NTNaFw0yMTEwMjkxNjI2\nNTNaMBIxEDAOBgNVBAMMB21lbWJlcjQwVjAQBgcqhkjOPQIBBgUrgQQACgNCAARG\nwqj2ZD7vA+h4KoTdh3if3tVO/yks+xtLU1tXAFsbeWSQfDxK3nnA65uX6n/25A20\nJcAQMDHYH2NdLOLra9lxo1MwUTAdBgNVHQ4EFgQUQQDC71N60r/a9c+EGXrzr5l6\nIDQwHwYDVR0jBBgwFoAUQQDC71N60r/a9c+EGXrzr5l6IDQwDwYDVR0TAQH/BAUw\nAwEB/zAKBggqhkjOPQQDAgNJADBGAiEAkvP0AuAU7y0b3z4rhvoOkCBKoH4G3vh/\nPJpLFdWcEu4CIQCSnEYpDaDTP2zoWTheqchZ+/BdTzM2j2s9ILpvSVYMxg==\n-----END CERTIFICATE-----\n",
            "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvYKesV5xoT2XnGhLkeqZ\neSC2KsjNUvdjqPrTERk/hp64Xd30SGjdj2HytG3hfCy5hBhc9muQMXoOAOBgxwMA\nQRu7KCANPZNCLEWKR5DZc8YzE+rHX1/8WxhhtV/bvr90selV0BfLWLLJYDxnyo3D\nyioYXNw6Ij2sYBt8MTPNPti3jRJ7LmMow/VrJD9Ww1FKWCyxa7/iCxSsbmrwdv8m\nBVf/+d3p+ivxb6gBvtTimj+fj1OdRkGHElZSaBFWmQISga3Ki4vnP4W1iw/ujaza\n3gItLPrEnD0lxGBaCSs+XVm2l8nsn3HJDZYMP5u3jWB3MWsBwna0o+KUon4KaS1k\nlwIDAQAB\n-----END PUBLIC KEY-----\n"
        ]
    },
]
```

**Comment by eddyashton** [comment]
Looks good, glad to have this in writing.

Wanted to clarify a minor point.

> Note that we deliberately use positional arguments here to keep the interface generic. Our built-in actions may choose to take a single object instead with named fields.

How do you suggest actions are written, and how are the args converted for them? Are you suggesting we can write `def new_user(cert, pubk)`, and propose calling it with:
```
{
  "call": "new_user",
  "args": ["pretend this is a cert PEM", "pretend this is a pubk PEM"]
}
```
(ie - args is _always_ a list, and we convert this list into multiple function call arguments)

or
```
def new_user(args)
  cert = args[0]
  pubk = args[1]
```
(ie - actions always get a single argument, which may be a list or object)

FWIW, I prefer the latter, because then the sensible thing to do is for args to be an object essentially giving nested named args. If we insist `args` in the proposal JSON is a list, then we can end up with `"args": [0, 5, 1, 5, 0, 2, 2]` confusion.

**Comment by achamayou** [comment]
I think we don't actually want generic positional arguments and it's ok to demand an object instead, because actions end up looking like this:

```
function new_user(args, read_write_tx)
{
  const user_id = digest(args.user_cert)
  read_write_tx["users"].put(user_id, args)
}
```

their validator takes an `args` and returns an optional error.

**Comment by achamayou** [comment]
Discussed with @sylvanc, who's happy with the design. Will go with

```
function resolve(proposer_id, proposal, votes) {
  ...
  return resolution.PASS
  // return resolution.PENDING
  // return resolution.REJECT
}
```

and automatic proposal removal on constitution/code_id changes. That makes all validation final as well.

**Comment by achamayou** [comment]
Starting a list of items we've set aside in PRs so as not to forget them:

- [ ] Actions ought to be idempotent as much as possible https://github.com/microsoft/CCF/pull/2372#discussion_r604298687
- [ ] When `apply()` fails, the exception details should be stored in `proposal_info`
- [ ] When a proposal completes, it should be deleted from `proposals`
- [ ] When a proposal completes, the `proposal_info` details for other non-`Open` proposals should be deleted
- [ ] When a proposal completes, the details of the votes, including exceptions where applicable should be stored in `proposal_info`

**Comment by achamayou** [comment]
proposal| notes
--- | ---
set_js_app | TBD
remove_js_app | TBD
set_member | #2396
remove_member | #2396
patch_member | TBD
set_user | #2396
remove_user | #2396
patch_user | TBD
set_ca_cert | TBD
remove_ca_cert | TBD 
set_jwt_issuer | TBD
remove_jwt_issuer | TBD
set_jwt_public_signing_keys | TBD
transition_node_to_trusted | TBD
remove_node | TBD
add_node_code | TBD
remove_node_code | TBD
transition_network_to_open | TBD
trigger_ledger_rekey | TBD
trigger_recovery_share_refresh | TBD
set_recovery_threshold | TBD
