### ISSUE TITLE
Refactor endpoint->frontend->handler flow for fully generic apps

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#681]
This is a brief design for a possible end goal of HTTP-related refactoring, if we want to support fully generic apps and multiple dynamically installed frontends. The aim is to separate and fully define the stages between receiving a raw-byte command buffer, and executing the user-defined handler for the contained command. In particular for JS apps where we'd like to delegate as much HTTP parsing and processing as possible to existing JS libraries, we should examine what needs to be extracted by earlier steps and how we minimise it.

- The Endpoints do less parsing. They don't try to extract actors or methods, they simply construct an implementation (ie - HttpRpcContext) which is exposed to everything below as an abstract `RpcContext`
- Some of the execution logic is hoisted out of each `Frontend`, into a central `ExecutionCoordinator` (with a better name)
- `ExecutionCoordinator` manages a set of `Frontend`s, and `process`es `RpcContext`s. For each command, it:
  - iterates through the `Frontend`s asking each if it wants to process this command, accepting the first. The `Frontend`s may choose to repeat the existing path-based dispatch, but they may also just check if the caller's cert is in their accepted callers.
  - delegates to this `Frontend` to ask if the command is correctly signed, and if it should be forwarded.
  - delegates to this `Frontend` to _execute_ the contained command. Again this may extract the method from the path as we currently do, but could also pass directly to an interpreter. This is wrapped in the existing "commit the result, retry on conflicts" code.

**Comment by achamayou** [comment]
ExecutionCoordinator -> RpcDispatcher perhaps?

**Comment by achamayou** [comment]
@eddyashton is there anything missing for this still? I think we're essentially there?

**Comment by eddyashton** [comment]
Yeah I think the core of this is done - we do only the necessary frame parsing, and leave the body/query/header interpretation to handlers. The remaining item was to move execution decisions from the frontend to a query-each-handler model, but I think we're heading in a more useful direction with the specify-properties-per-handler approach. Closing this issue.
