### ISSUE TITLE
Utility to verify node's quote

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#683]
It should be possible for members to verify the quote of a given node via a host-only utility (i.e. without requiring to spin up an enclave). This is especially useful before opening the network since the quote of the first node is never verified.

The utility should: 
1. Run `getQuotes` against a given node to retrieve its quote.
2. Verify the collateral associated with the quote (once the call is supported by OE). 
3. Verify the identity of the node quoted (hash the node's cert and verify the quoted data).
4. Verify the quote's `mrenclave` against a trusted enclave measurement.

**Comment by achamayou** [comment]
Open Enclave already has oecertdump: https://github.com/openenclave/openenclave/tree/master/tests/tools/oecertdump

We should:

1. Ask/help with making it part of the release (it's an internal test tool right now)
2. Write a small wrapper script that runs getQuotes, getCode, executes verification (3/4 in @jumaffre's comment) and displays a nice summary

**Comment by achamayou** [comment]
A more minimal and perhaps better starting point: https://github.com/openenclave/openenclave/pull/2865

**Comment by achamayou** [comment]
Link https://github.com/openenclave/openenclave/issues/2724

**Comment by jumaffre** [comment]
Waiting for the `host_verify` utility to be release as part of Open Enclave to be able to test this.

**Comment by achamayou** [comment]
What's still missing is that `host_verify` does not display mrenclave, that needs to be done.

**Comment by achamayou** [comment]
@jumaffre could you open an issue on the openenclave side and link it here?

**Comment by jumaffre** [comment]
https://github.com/openenclave/openenclave/issues/3455

**Comment by achamayou** [comment]
Change complete upstream (thank you @jumaffre!), pending release now.
