### ISSUE TITLE
KV local hooks execution should affect transaction commit success

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#687]
Local hooks on the KV store can have side effects that should be cancelled when the KV is rolled back.  We currently have three local hooks to:
1. Update Raft configuration, handled properly by Raft, as Raft handles the rollbacks on the store. 
2. Update PBFT configuration, which should be handled when https://github.com/microsoft/CCF/issues/457 is implemented. 
3. Update ledger secrets when re-keying/recovering, which is not currently handled.

There may be different options to solve this, depending on whether we plan to add many more local hooks to CCF or let app developers add their own local hooks.

**Comment by achamayou** [comment]
There's one more, which is the history/merkle tree, and is handled correctly too.

**Comment by jumaffre** [comment]
As discussed with @achamayou, I originally thought that changing the `ccf.secrets` table hook a global hook would solve the issue of managing secrets, etc. However, a more robust way to do this would be:
1. Keep the `ccf.secrets` table as a local hook to update the encryption key for the `N+1` version.
2. Make the `TxEncryptor` a "syncable" object, i.e. it implements `compact()`, `rollback()` to be triggered from `kv.h`. 
3. Have the local hooks return a status code that is propagated all the way up to `Store::deserialise()`. 

That way, if the primary is malicious and writes garbage in the `ccf.secrets` table, the hook on the backups will fail and the network won't make progress. This is much better than the global hook approach where the hook will be triggered too late for a malicious primary to be detected and recovered from nicely.

**Comment by jumaffre** [comment]
Re-titling this issue as the top two items from the list have been addressed in #699.

**Comment by achamayou** [comment]
As discussed, the current model for hooks is fundamentally unsound, because it lacks an ordering guarantee. Instead, what's currently done by hooks must be done inline, either shortly before or in replicate(), where error handling will correctly invalidate the transaction.
