### ISSUE TITLE
Expose ringbuffer load metrics

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#688]
We have very few indications of load on each node. One cause of performance degradation that we can easily measure is overloads on the ringbuffer - either when we have spend a lot of time fragmenting and reconstructing large messages, or when we're constantly overfilling the ringbuffer and queuing pending work.

We should add some debug logging of these events and any other low-hanging perf indicators.

**Comment by achamayou** [comment]
I think we probably want a conflict/retry counter in the KV as well

**Comment by eddyashton** [comment]
Note for whoever implements this to avoid the obvious gotcha - the enclave shouldn't log these events directly, since that will cause ringbuffer writes that may cause recursive logging. We'll need to count these events and dump them in a message once-per-tick, or similar.

**Comment by eddyashton** [comment]
Added tracking of ringbuffer load in #1480. Still a little crude, but we have `enclave_load.log` and `host_load.log` files summarising all ringbuffer messages, and `plot_node_load.py` to plot them.
