### ISSUE TITLE
Store::deserialise() should be able to deserialise without committing

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#694]
Related to #693 we need to be able to deserialise incoming data so that we can reason with it but not necessarily commit it.

I think the easiest way to do this is pass an extra argument `bool commit` to `Store::deserialise()` (defaults to `true`) and if it's `false` then omit committing and updating the history.

Also, to use the writes that were produced by `Map::deserialise()` (called by `Store::deserialise()`) we can add a `DeserialiseHook` that only takes the write set and can use it.

Pbft can register a deserialise hook that takes the requests and pre-prepares and at a later point, execute.

Please let me know if anyone has a more obvious way to achieve this

**Comment by achamayou** [comment]
It seems to me the history update could happen regardless, since derived tables have been updated at this point. I don't think we need a hook, the rest of the Tx can just read from the requests table.
