### ISSUE TITLE
Python infrastructure should be packaged

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#695]
Currently we have a large set of Python files for spinning up and operating CCF networks, and we make these accessible by fiddling with PYTHONPATH. These should be packaged as a wheel or egg so they can be more easily redeployed/reused.

**Comment by achamayou** [comment]
See https://github.com/jumaffre/cimetrics/ for an example, although we don't want to publish to PyPI here.

**Comment by achamayou** [comment]
TPAL is making use of several elements of the Python infra, in particular the client and the governance logic. We should at least package this much to avoid duplication.

**Comment by achamayou** [comment]
Now published as https://pypi.org/project/ccf/, thanks @jumaffre!
