### ISSUE TITLE
App-defined error codes are not applied correctly

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#718]
It seems that the refactoring introduced in https://github.com/microsoft/CCF/pull/701 causes the application-defined error codes to break. This should be investigated and fixed to revert the previous (and correct) behaviour.

**Comment by achamayou** [comment]
We're going to standard HTTP error codes, it's not clear how much value there is in supporting custom codes. Let's revisit this once the Better Rest support milestone is closed.

**Comment by eddyashton** [comment]
I've removed the existing app-defined error codes in #921, and I believe we should close this issue as they're now something we don't intend to support. Apps are free to define whatever error codes + encoding they like in the response body and headers, but these are opaque to the framework which only sees standard HTTP error codes.
