### ISSUE TITLE
PBFT does not handle HTTP signatures

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#720]
HTTP signatures are not handled by PBFT. A fix could be hacked up quickly but I believe that we should wait until plain JSON-RPC is deprecated to build a more elegant solution. 

I'll add a placeholder signature for now so that the members' votes are "signed" and we can merge our logging end-to-end tests. Of course, the `voting_history` test would fail if it was run with that configuration (i.e. PBFT + HTTP).

**Comment by achamayou** [comment]
let's wait until aft we deprecate FTCP

**Comment by achamayou** [comment]
Fixed now, both consensus variants go through process_command() where signatures are handled.
