### ISSUE TITLE
Pbft should store requests in the kv even if the request didn't execute and commit successfully

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#763]
If for any reason while executing a request the transaction fails to commit, then the request is not stored in the kv. Pbft should detect when a frontend is responding with an error and store the request into the kv anyway.

**Comment by ashamis** [comment]
This is issue is partially resolved by #1064 and will be fully resolved by #1065. I am closing this as it now is a duplicate of 2 separate items
