### ISSUE TITLE
Versioned documentation

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#770]
We should make sure that our documentation is versioned so that it stays in sync with our releases as well as `master`. 

https://sphinxcontrib-versioning.readthedocs.io/en/latest/index.html seems to be the way to go. However, it does not seem to be actively maintained and I had to apply the patches described [here ](https://github.com/sphinx-contrib/sphinxcontrib-versioning/issues/70) to get it working locally (see for changes required to CCF: https://github.com/microsoft/CCF/compare/master...jumaffre:versioned_docs?expand=1). 

The (experimental) command I then ran was: `$ sphinx-versioning build -r versioned_docs -w versioned_docs -W sometag sphinx/source ./build/html`, which built the default docs (`versioned_docs`) and the one pointed by `sometag`.

```
$ ll ./build/html
_images        design         index.html         operators       sometag
_sources       developers     introduction.html  quickstart      users
_static        genindex.html  members            search.html     versioned_docs
concepts.html  glossary.html  objects.inv        searchindex.js
```

![image](https://user-images.githubusercontent.com/42961061/73562903-f87ae780-4453-11ea-9506-ffe42c7f0d43.png)

Let's keep an eye on the `sphinxcontrib-versioning` repo until these issues are fixed and we should hopefully be able to set this up for `v0.8`.

**Comment by achamayou** [comment]
Is sphinxcontrib-versioning what the Python doc uses for multiple releases of the interpreter?

**Comment by achamayou** [comment]
Waiting on https://github.com/sphinx-contrib/sphinxcontrib-versioning/pull/78

**Comment by achamayou** [comment]
Let’s give https://github.com/Holzhaus/sphinx-multiversion/ a try when we pick this up.
