### ISSUE TITLE
Code quality::CCF should have contributor guidelines for TODO code markers 

### ISSUE THREAD

**Issue by douglasism** [microsoft/CCF#776]
(Continuing my campaign to make new friends...)

**Description**
There are approximately 100 TODOs in ccf/src alone. Some of these are following an unstated convention for sub-classification: TODO(#label), while others have links to representative issues: https://github.com/microsoft/CCF/issues/59 (great!). There are a few without qualification that seem critical.

**Improvement**
At the very least, TODOs that are critical should be labeled so and have an associated bug tracking them.

For code quality and team efficiency, the recommendation is to adopt and publish simple project guidelines. For example:

Policy:
1) All TODOs that constitute a bug **must** be labeled so and have a link to its issue #.
2) All TODOs **should** be labeled and be linked to an issue #.

//TODO(#label) https://github.com/microsoft/CCF/issues /#
labels::subset of https://github.com/microsoft/CCF/labels ?

**Comment by achamayou** [comment]
@douglasism that's an excellent idea, I will see if I find a way to automatically check for that. The TODOs are largely leftovers from the pre-ticket era for this project, we shouldn't add any more without tickets and we should work our way through the old ones as well.

**Comment by achamayou** [comment]
@douglasism I have done a pass over the code to remove the TODOs and convert them to tickets. In the process of doing this, it has become clear to me that many of our TODOs were particularly stale and missing necessary context if they are to be addressed.
I think the brevity encouraged by the format is a bug, not a feature.

For the month ahead, we'll stay TODO-free and use tickets for all issue-tracking. If that isn't satisfactory, I'll re-open a discussion and we'll decide what can be done instead. Having all the issues in one place should facilitate prioritisation though.
