### ISSUE TITLE
Due to logging macro overloading, exception handling is incorrect in enclaves

### ISSUE THREAD

**Issue by douglasism** [microsoft/CCF#782]
**Description**
For non-enclave builds, logger.h overloads the logging functionality by throwing exceptions when LOG_FATAL_FMT events are logged. With enclave builds (#ifdef INSIDE_ENCLAVE), logger.h outputs the message, but does not throw an exception.  Code that is written with the expectation that LOG_FATAL_FMT will throw an exception, will not function correctly in the enclave. For example:

```
  void KeyAesGcm::encrypt(
...
  {
    int rc = mbedtls_gcm_crypt_and_tag(
      reinterpret_cast<mbedtls_gcm_context*>(ctx),
      MBEDTLS_GCM_ENCRYPT,
...
      tag);
    if (rc != 0)
    {
      LOG_FATAL_FMT(tls::error_string(rc));
    }
  }
```

With the current implementation, the host will log the event for the enclave, resulting in a thrown exception -- in the host. But the host is untrusted, and it could ignore fatal errors from the enclave, perhaps leaving the enclave in a vulnerable state if it wishes. In effect, the enclave is delegating its some of its control flow to the untrusted host.

**To Reproduce**
Log fatal events in the enclave, while ignoring them in the host.

**Expected behavior**
Control flow should not be affected by logging. My recommendation is to remove the embedded exception logic from the logging macro, and have functions explicitly and separately control the flow.

This is somewhat related to #777.

**Comment by achamayou** [comment]
@douglasism this is a good point, I will remove the throwing from the host variant of LOG_FATAL_FMT, and add it explicitly where necessary. Logging should only log.
