### ISSUE TITLE
Investigate why SigHttpRpcTlsClient::gen_rpc is producing transactions that fail to verify

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#787]
Once this is fixed, the condition in smallbank.cmake that turns off the tests that need signatures should be removed at least for CFT.

**Comment by eddyashton** [comment]
https://github.com/microsoft/CCF/pull/852#discussion_r380307030

`KeyPair::sign` does not use SHA256 by default, so we claimed SHA256 but signed an incompatible digest. This is fixed - `sign` now takes the hashing algo to use, and HTTP signatures use SHA256.
