### ISSUE TITLE
Member ack should work with the HTTP signature scheme and be over the merkle tree root rather than a nonce

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#791]
- [ ] fix ack over HTTP and re-enable memberclient test
- [ ] ack should be over root of the tree, rather than nonce, nonce table can be removed etc

**Comment by jumaffre** [comment]
Once this is done, we should re-enable the signed performance tests: https://github.com/microsoft/CCF/blob/e82685393e0c28470d2c9bfc956109aa8e063d80/samples/apps/smallbank/smallbank.cmake#L60
