### ISSUE TITLE
CCF core does not securely erase unused secrets from memory

### ISSUE THREAD

**Issue by douglasism** [microsoft/CCF#793]
**Description**
For hardening and defense-in-depth goals, enclaves should erase secrets from memory when they are no longer in use.  While the core property of TEEs is memory isolation that protects secrets, enclaves are still at risk from classic framework and application code flaws that may expose memory. One way to reduce the risk from these flaws is to limit the presence of secrets in enclave memory, be it the heap or stack.
 
**Example**
There are several variants of this problem. Below is one example of an object that does not securely erase itself when deleted.
 
```
  struct LedgerSecret
  {
    std::vector<uint8_t> master; // Referred to as "sd" in TR

    bool operator==(const LedgerSecret& other) const
    {
      return master == other.master;
    }

    LedgerSecret(bool random = false)
    {
      if (random)
      {
        master = tls::create_entropy()->random(32);
      }
    }

    LedgerSecret(const std::vector<uint8_t>& ledger_master_) :
      master(ledger_master_)
    {}
  };
```
 
**Recommendation**
In many instances, securely erasing secrets is accomplished by zeroing heap allocations prior-to freeing the memory, and by zeroing (or avoiding the use of) stack locations. A common approach is to create smart objects for secrets (similar to smart-pointers) that erase secrets when the objects are deleted.
 
**Warning**
The implementation of the erasing code may need to be platform-specific, given that aggressive compilers may remove the zeroization code during optimization.

**Comment by achamayou** [comment]
@douglasism there is a somewhat related dicussion going on in the OpenEnclave SDK: https://github.com/openenclave/openenclave/pull/2383

I am not convinced that there is any value in doing this, because a host can kill an enclave at any time. Either enclave memory is leaked on shutdown (it isn't as far as I know!), or it's not.

Do you have a particular attack in mind?

**Comment by douglasism** [comment]
Hello @achamayou. Sorry this is so long…  https://github.com/openenclave/openenclave/issues/2373 (which  https://github.com/openenclave/openenclave/pull/2383 spun off of) focuses on the *initial* zeroization of freshly allocated memory. It is different from my concern, which focuses on the secure erasure of secrets from memory *after use*. While there may be some defense-in-depth benefit to enclave code if OE were to *initialize* freshly allocated memory, given that this will lessen the risk of enclave code not initializing it properly, but doing so is overkill with less benefit and will adversely affect performance. I don't recommend it. (I will comment in OE about this.)

Back to this issue of securely erasing secrets after use. Because enclave pages are encrypted in DRAM (but not in cache?, more on this is a bit), the classic benefit of erasing secrets is not as strong given that memory should not be accessible from *outside* of the enclave --- at the hardware level.  But the risk remains that enclave code will contain classic (and enclave-oriented) bugs where enclave memory is inadvertently exposed, say, by an overwrite to memory outside of the enclave, or as the result of an active attack. It is a common best-practice in TCBs to limit the risk that secrets will be found in memory by limiting their active use, and, to the point of my issue, securely erasing them when the enclave is finished using them. The SGX documentation and the TR address this.

From Intel documentation:

> Disposal of Enclave Secrets

> Enclave secrets may be safely stored outside the enclave boundary after such secrets are properly sealed. However, there are certain instances where a secret, such as the seal key, needs to be disposed of inside the enclave. The enclave writer must use the memset_s() function to clear any variable that contained secret data. The use of this function guarantees that the compiler will not optimize away the write to memory intended by this function call and thus ensuring the secret data is cleared. Using memset_s() is especially important when secret data is stored in a dynamically allocated buffer. After such a buffer is freed it could be reallocated and its previous contents, if they are not erased, may be leaked outside the enclave.
>The implementation of memset_s() is not performance optimized so the use of memset() is appropriate to initialize buffers and clear buffers that do not contain secret data.


The good news is that C++11’s memset_s is, by spec, not optimizable. So we should have a de-facto solution for the supported platforms. **Neither CCF nor its 3rd party code uses memset_s.**  (I need to understand the impetus and use of **oe_memset_s** in openenclave. I will report back.)

>memset may be optimized away (under the as-if rules) if the object modified by this function is not accessed again for the rest of its lifetime (e.g. gcc bug 8537). For that reason, this function cannot be used to scrub memory (e.g. to fill an array that stored a password with zeroes). This optimization is prohibited for memset_s: it is guaranteed to perform the memory write. Third-party solutions for that include FreeBSD explicit_bzero or Microsoft SecureZeroMemory.

Regarding unencrypted cache…this is a provocative question:
https://software.intel.com/en-us/forums/intel-software-guard-extensions-intel-sgx/topic/831308

**Comment by douglasism** [comment]
oe_memset_s looks good for zeroing secrets. I plan to verify that it's not being optimized away.

**Comment by achamayou** [comment]
@douglasism first, thank you for taking the time to write such detailed and high-quality posts. They're a pleasure to read!

I am happy to add destructors that zero out our secrets, because it's an inexpensive change, but I am not convinced that there is much of a benefit, and here is why: our important secrets are long lived, because the node and network identities need to be reasonably stable.

So if there really is a way to extract pages from a dead enclave, and considering that it's absolutely possible to kill an enclave at any time, zeroing secrets on destruction does not close our vulnerability window very much.

**Comment by douglasism** [comment]
@achamayou (Thanks for the positive comment, Amaury.)  For complex projects, I like clear guidelines and patterns to follow.  And for simplicity, the best approach is to adhere to them always. Adopt the project’s idioms, publish, and follow --- without indecision about when to apply them.  For example, smart pointers: always use them and the project has reduced the risk of memory mishandling. Any code not using smart pointers is a bug.  Writing code is a little easier when there are fewer decisions to make with each block. Handling a pointer? Use a smart pointer!

This approach applies to secrets too. The idiom I like to follow is **Secrets Are Not Orphaned or SANO**. (I just made that up.)  Define a class or template for safely handling secrets, and then always use it. It has multiple benefits. One is that it is easy to follow where the secrets are in code. Another is that coders don’t have to worry about whether they’re handling secrets correctly.

A significant element of SANO is that keys get securely wiped from memory when they go out of scope, automatically.  Another principle is that keys don’t end up on the stack. And another is that inactive keys are not held in memory. But if a secret is in use, it’s not orphaned and not in violation of SANO.
