### ISSUE TITLE
CCF should provide platform-specific implementations for secure memory erasure

### ISSUE THREAD

**Issue by douglasism** [microsoft/CCF#794]
**Is your feature request related to a problem? Please describe.**
Please see #793 for background. This feature request is specific for applications.

**Describe the solution you'd like**
A header-only, cross-platform solution that is easy for applications to adopt. This could originate from CCF or be a recommended 3rd-party solution.

**Comment by achamayou** [comment]
@douglasism could you file this against the OpenEnclave SDK please? CCF uses mbedtls as modified and released by OpenEnclave, and will only run on platforms that OpenEnclave supports, we have no plans to include platform-specific code in CCF.

**Comment by douglasism** [comment]
Please see comment https://github.com/microsoft/CCF/issues/793#issuecomment-582582422
