### ISSUE TITLE
CCF Core: Method to register & authn a member as an enclave, and set governance policy

### ISSUE THREAD

**Issue by douglasism** [microsoft/CCF#818]
This enhancement request is similar to #816

**Description**
In addition to CCF:TLS authentication, hardened services may want a second, deeper level of authentication for member interfaces. In the context of confidential computing, one natural additional level of authentication would be enclave to enclave, but not necessarily enclaves of the same services or types.

**Use Case**

1) After members have connected to a hardened service via CCF::TLS, the governance rules may stipulate that second-level authentication occurs for member interfaces (some or all). If the member is registered as an enclave, this secondary authentication could be heterogenous enclave-to-enclave, local or remote. The authentication may be mutual.

**Comment by douglasism** [comment]
Retracting this enhancement request. This can be accomplish via signed requests, in a stateless way.

**Comment by achamayou** [comment]
Members are pure identities, and their commands are all public and signed to satisfy governance verifiability. I'm not sure what properties we would get out of checking that members clients are run in enclaves?
