### ISSUE TITLE
Member RPC should only be run if node state is partOfNetwork

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#83]
We should add the capability to allow certain RPCs to be executed only when the node is `partOfNetwork`/`partOfPublicNetwork`. 

As it stands, members can issue RPCs when a node is reading the public ledger (recovery). Instead, we should still let members connect to the CCF service (i.e. TLS handshake succeeds) but their RPCs should return that the node is not in an appropriate state.

One possible solution would be to tweak the `install()` function in `frontend.h` to allow passing optional arguments corresponding to the white list of node states that a certain RPC can run against.

**Comment by achamayou** [comment]
That seems like a nice fit for a Handler::set_allowed_states(...) in the new API.
