### ISSUE TITLE
Setup daily build

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#832]
We should setup a CI nightly build to run tasks that a) take a relatively big amount of time and 2) may not necessarily need to be tested for each build. So far, these tasks include:
- Release build + full suite of tests (SGX only, with both CFT and BFT)
- An extended random test suite (after https://github.com/microsoft/CCF/issues/712). 
- TLS server test, as per https://github.com/microsoft/CCF/issues/626.

**Comment by achamayou** [comment]
I suggest we also move the coverage build there for the following reasons:

1. it slows down the build and test
2. the codecov output on PRs is more distracting than valuable, from experience, and is more suitable for a periodic review of the project than a systematic per-PR examination.

**Comment by achamayou** [comment]
I will also move the SAN build there, because post-PBFT merge, ninja w/ SAN is 5 minutes all by itself on a D16s_v3. It's good to have per build, but not so good that want slow builds.

**Comment by achamayou** [comment]
Still to be done:

1. Release build and tests
2. TLS compliance test
3. Randomised test "suite", aka end to end fuzzing (probably over the SAN build)
