### ISSUE TITLE
kv.h:: TxView dtor's strange implications

### ISSUE THREAD

**Issue by douglasism** [microsoft/CCF#835]
**Description**
kv is a complex set of classes. There is no room for code that is unnecessary and invokes thoughts of quantum superposition.

```
      virtual ~TxView()
      {
        // If we are destructed, prevent future access.
        commit_version = 0;
      }

```

**Comment by achamayou** [comment]
This is very odd, I'll check with Sylvan what the history behind it is, but I do agree it needs to be removed.

**Comment by achamayou** [comment]
There's no reason for this now.
