### ISSUE TITLE
Enclave, node, and rpc code is poorly separated

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#844]
We have several classes which have gone into the `enclave::` namespace by default, but don't really belong there. I've made `http::` a top-level namespace+folder, and believe we should do the same with `rpc::`. This should probably happen with #707.

**Comment by achamayou** [comment]
@eddyashton I see a reference to that in http_rpc_context, where make_rpc_context is under "enclave". It seems to me that it should be http::make_rpc_context instead.

Am I missing something or is that simple? There is nothing else under http/ that's enclave::

**Comment by eddyashton** [comment]
Since we're exposing HTTP concepts to the abstract `RpcContext`, yes it makes sense to move it under `http::`. I think there's still some circular dependencies between `enclave/`, `node/`, and `node/rpc`, but I haven't confirmed.

**Comment by achamayou** [comment]
We may make gradual moves over time, but now that we are cutting LTS releases, the benefits of a complete reshuffle are going to be outweighed considerably by keeping patching straightforward.
