### ISSUE TITLE
It should be possible to have more than 255 consortium members

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#851]
The support for member key shares introduces a hard cap on the number of members active at a given time in the consortium: 255, as per the limitations of the `sss` library.

It should be possible for CCF to have more than 255 active members at a given time. If we stick to `sss`, we may decide to change the 1-to-1 mapping between members and recovery key shares, i.e. not all members are given a recovery key share.

Relates to https://github.com/microsoft/CCF/issues/51

**Comment by achamayou** [comment]
@jumaffre can we make this limitation explicit in the documentation? We have separately agreed that not all members should have a share, which changes this slightly to "it should be possible to have more than 255 members with a share".

In the absence of a likely use case in the near future, I think documenting the limitation is sufficient, keeping an open-ended issue does not seem necessary.
