### ISSUE TITLE
add_ccf_app() should add the openenclave include directory in the cmake target include directories.

### ISSUE THREAD

**Issue by jazzybluesea** [microsoft/CCF#873]
**Describe the bug**
When trying to compile a CCF application, it does not find the openenclave header files.

**To Reproduce**
In the CCF application try to include the following files:

#include <openenclave/bits/report.h>
#include <openenclave/bits/result.h>

**Expected behavior**
add_ccf_app() should take care of updating the target include directories to include openenclave.

**Environment information**
CCF 0.7.1

**Additional context**
None.

**Comment by eddyashton** [comment]
The openenclave include directory is already added to the include paths, but only for the enclave app (_not_ for the virtual version). We'd like to be able to build the virtual versions on a machine without OE.

If you want to have a working virtual version you'll need to disable and/or stub out the code that requires OE using the `VIRTUAL_ENCLAVE` processor define:

```
#ifndef VIRTUAL_ENCLAVE
#include <openenclave/bits/result.h>
#endif

bool is_ok(int result)
{
#ifndef VIRTUAL_ENCLAVE
  return result == OE_OK;
#else
  return something_else;
#endif
}
```

Alternatively, if you don't care about the virtual build, you can tell CMake to build only the real enclave versions:

```
cmake .. -DTARGET=sgx
```
