### ISSUE TITLE
Allow control of initial CCF member count in python startup scripts

### ISSUE THREAD

**Issue by daperoni** [microsoft/CCF#889]
When starting a CCF network using the python scripts, the initial number of members and clients is fixed at 3. Members can be manually added, but it would be convenient to be able to better control initial network configuration.

A command line argument for initial member count and initial user count would enable this feature.

The python code can be modified locally to support this, but it would be nice to have this feature as part of base functionality. 

I've addressed this issue and have issued a PR.

**Comment by achamayou** [comment]
@daperoni Thank you for contributing this change!
