### ISSUE TITLE
Simplify signature of handler install

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#914]
We keep adding params to the signature of `HandlerRegistry::install` to handle new behaviour for specific RPCs - this is mostly my fault. I think we should instead have a basic install function (`install(name, func, ReadWrite)`, and set other fields explicitly. A sensible way to do this is for `install` to return an iterator/handle that we can set additional fields on, similar to `CLI11` options, so we can write `handler->execute_locally = true; handler->schema = ...;`.

**Comment by achamayou** [comment]
This probably ties in to #633 (adding a way to specify the verb etc).
