### ISSUE TITLE
Self-registered Users

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#926]
Currently, new users are only permitted to issue transactions to applications after being voted in by members through the governance process. This is expensive as it requires member intervention and does not necessarily scale well. 

Instead, one option could be to let users self-register as long as they meet certain criteria. For example, assuming that users run in an enclave, they could provide their quote (containing the hash of their public certificate in the report data) via a new _unauthenticated_ `selfRegisterWithQuote` RPC. The CCF endpoint would verify the quote, check that the public certificate from the TLS connection matches the hash of the report data and that the client enclave runs a well-known `MRENCLAVE` (registered in advance by others members or users). 

-- Implementation details below -- 

This new `selfRegisterWithQuote` could be added as a new endpoint in the user frontend. However, the granularity of our current AuthZ scheme is at the `Frontend` level. What we would need here is a specific AuthZ scheme for that new endpoint, while the other endpoints would still be protected by the current `valid_caller()` function. 

One way to do this is would be allow apps to register several `UserRpcFrontEnd`s. That way, one frontend would define most of the endpoints guarded by `valid_caller()` while a second frontend would define the `selfRegisterWithQuote` handler and bypass `valid_caller()` (by overriding it). This would cause some changes in the way `libccf` registers the `UserRpcFrontend`(s) defined by the app. More generally, splitting an application in different classes/files would also be a nice way for users to build more modular applications.

**Comment by jazzybluesea** [comment]
Thank you @jumaffre for opening this issue.  Regarding your statement "registered in advance by others members or users", could you please add some more detail on which rpc should be used pre-register the users?  Is it through the current member's mechanism to add a new user?

**Comment by jumaffre** [comment]
@jazzybluesea "registered in advance by others members or users" in the issue description refers to the `MRENCLAVE` (i.e. the version of the code and enclave configuration) of the client enclave. This could be registered by members via the propose/vote RPCs (see https://microsoft.github.io/CCF/members/proposals.html#submitting-a-new-proposal - the member RPC can be pure Lua in this case and would not require changes to the CCF binaries).

**Comment by jumaffre** [comment]
As discussed with @achamayou today, let's go for a simpler solution for now as the need for several frontends is not yet well justified. Instead, the new `selfRegisterWithQuote` RPC can be marked as "non-authorised" and the call to `valid_caller` can be skipped for it. 

With regards to registering trusted `MRENCLAVE`, we will add a new `ccf.trusted_measurements` that members can write to and that applications can read from to determine if a new client can be trusted as a new user.
