### ISSUE TITLE
TODO enforcement

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#941]
As it stands, we cannot add new `TODO`s in our codebase. This is for good reasons (we don't want to accumulate dozens/hundreds of TODOs). However, `TODO`s are also useful to provide context to a piece of code (e.g. a WIP feature). 

As discussed, what we could do is allow `TODO`s that are linked to a GitHub issue, e.g. `TODO(#666)` and then enforce the following:
- On `master` builds, all the existing `TODO`s must link to issues that are open.
- On PR builds, all the existing `TODO`s must link to issues that are open minus the ones that the PR claims to fix (using https://developer.github.com/v3/pulls/#link-relations).

**Comment by achamayou** [comment]
Link #776

**Comment by douglasism** [comment]
Great idea to add automation!

**Comment by jumaffre** [comment]
Closing this as the benefits of this are not clear after living with no `TODO`s for a few months now.
