### ISSUE TITLE
Session “consistency”: implementation should be removed (i.e. reverse 913)

### ISSUE THREAD

**Issue by douglasism** [microsoft/CCF#957]
**Preface**

(There are multiple related problems. My discussion of them will be interleaved. Also, please be aware that I do not speak with authority, that I am still learning about the design and implementation of CCF. I could totally not know what I’m talking about.)

When I first looked at [pull 913](https://github.com/microsoft/CCF/pull/913/files), I was troubled by the coding-through-TLS-session pattern that it suggests, where clients would reconnect to “view the node’s locally committed state.”  I started putting together a proposal for a command that would allow the client to `reset` or `clear` their view directly, without having to use TLS session reconnection to accomplish it. But once I began thinking about this new `clear` command and the semantics around it, I realized that some of the basic premises were off.

**Description**

To convey my ideas, it is useful to review the assertions in [CCF docs: threading](https://microsoft.github.io/CCF/developers/threading.html).  One general comment: The page mixes two types of concurrency: 1) High-level distributed-systems concurrency and 2) low-level process/thread concurrency. These two topics should be in separate sections or pages. (Another note to its authors: It may seem like I’m harsh, but please know that my bluntness is for brevity – I mean no disrespect.  It is the easiest way for me to present my opinions briefly and remotely.) 

**Consistency**

It’s helpful to make clear which type of consistency this is referring to. Based on the body of the section, consistency here is the ‘C’ in ACID (distributed systems concurrency).  This definition is a little different than the sense of consistency in the TR: *Consistency means that all nodes observe prefixes of the same series of committed transactions.* TR is describing a subset, or a base presumption, of consistency in ACID. The TR’s connotation is that the nodes all share the same set of **committed** transactions – obviously, this would be a prerequisite for advancing to a valid next-state and maintaining the broader, ACID consistency. Let’s move on to the statements in the section.

`If all commands are executed on the primary,` – This is an implementation detail that clients are shielded from knowing. The client views only an ostensibly fresh and accurate view of the application state on a node. The concurrency notes should not include a distinction between the primary and follower nodes.

`…CCF guarantees session consistency from the perspective of a TLS client connection.` This is the core design element that I am challenging. CCF should **not** provide broader guarantees beyond the single command/transaction border. A single transaction represents the central atomic block of CCF. There are no additional ACID guarantees beyond the atomicity of the transaction. CCF guarantees that the transaction, as scoped by, for example, the transact_savings function listed here, will either completely commit globally or be completely rejected and rolled back.
```
      install(
        Procs::SMALL_BANKING_TRANSACT_SAVINGS,
        json_adapter(transact_savings),
        HandlerRegistry::Write);
```
CCF should **not** guarantee TLS session consistency. Outside the scope of a single transaction, a client should **not** be able to read its previous uncommitted writes --- in the same session or not. I’ll go even further and claim that CCF should **not** guarantee the *ordering* of transactions. Guaranteeing the order has several problems. It suggests a super-transaction atomicity, where there is a stateful contract that CCF should not execute later transactions if previous ones failed. It also encourages fragile app implementations: If applications create interdependent transactions, they will have to implement logic that either checks for the previous commits of dependencies, or handles complex backtracks in the case where previous transactions didn't commit, but subsequent ones did (I don’t call them rollbacks because they won’t be that simple).

**Summary**

CCF should stick to single transaction-scoped ACID goals and make no claims about session transaction sets or transaction ordering.  [Pull 913](https://github.com/microsoft/CCF/pull/913/files) should be reversed.

I have more to say about concurrency, but I’ll stop here for now, and see how well this recommendation goes.

**Comment by ashamis** [comment]
@douglasism - I will write a longer shortly but in the mean time I am reclassifying this as an "enhancement" rather than a "bug". The request is to change functionality rather than a report of incorrect functionality.

**Comment by ashamis** [comment]
Hi @douglasism 

There are a couple of points I want to clear up:

-  ```CCF should not guarantee TLS session consistency. Outside the scope of a single transaction, a client should not be able to read its previous uncommitted writes --- in the same session or not``` => CCF does not allow any transaction read any uncommitted writes, except in the case when the key was written in the context of the same transaction "Read your own writes"

- In regards to the _contract_ that CCF provides with session consistency. If we have 2 transaction (A) & (B) we guarantee that if they are sent in the order (A) and then (B) within the same session they will be executed in the same order. We very much do no provide the guarantees on the result of their execution and if the user expects there to be a dependency they should just write a single transaction. Therefore if transaction (A) does not execute successfully we will still attempt to execute transaction (B).

We implemented session consistency because we believe that this would make it easier for CCF's users to build application on top of the platform. Just like any belief we could be wrong. Can you please expand on the motivations/ideas/goals that you have around wanting to remove session consistency.

**Comment by douglasism** [comment]
@ashamis   Hi Alex, thanks for taking the time to respond. Regarding “read your own writes”: I’m glad what you state on the doc page is not true. I suggest rephrasing it. (I have to say that I don’t usually regard documentation and comments as the truth: I tend to consult the code before making claims about its function.  But with KV, I find some of the code to be quite impenetrable.)

Regarding ordered transactions: I dislike how the network and threading context determines high-level behaviors of CCF. If controlling transaction ordering is critical for CCF clients, then this should be expressed via CCF interfaces, not through network context. Coupling transaction ordering to the TLS session locks in the implementation. It will frustrate priority handling optimizations on the leader, which is going to need all the perf help it can get.  But perhaps I'm biased due to my fondness of the bitcoin model, which treats uncommitted transactions as an unordered pool.

**Comment by ashamis** [comment]
Hi @douglasism, z are a key difference that CCF (and similar) systems have to Bitcoin is that they are not a store of value(virtual coin). In Bitcoin the unexecuted tx pool is not fully unordered, each transaction has monetary value associated with it, and as such a miner will process transactions which gives them the largest monetary return. CCF does not have said sudo-ordering.

In regards to your point of the implementation and behavior of CCF. Our goal is to provide session consistency and we leverage the implementation rather than the other way round. If a user does not want session consistency they are able to open multiple TLS connections to CCF.

**Comment by douglasism** [comment]
@ashamis Hi Alex, I wasn't equating CCF with Bitcoin. My point about the pool was to highlight that the Bitcoin design did not guarantee atomicity beyond the transaction. It was an aside -- I shouldn't have mentioned it. 

Also, I am not advocating for the reverse use-case, that is, I'm not suggesting "user does not want session consistency.”  It's natural and implied that the client is ordering its requests. My point is the framework shouldn't guarantee the ordering, especially if the implementation locks the framework to a particular TLS and threading context. My goal is to decouple CCF design from the network context.  I also find it troubling that the client is resetting its connection to reset its view.

Do you have a concrete use-case? One of the problems I have with session consistency is that if the client has to ensure the ordering, then they might want to wait for `is_globally_committed()` of tx A prior to firing tx B.

Alex, if I'm way off, I don't want to waste your time. I've made my points. If they don't persuade you to reconsider, go ahead and close this as won't-be-done.

**Comment by ashamis** [comment]
I am going to close this work item because currently we do not plan to remove session consistency and have not received any requests to do this from users of CCF. If this request does come up we can revisit this.
