### ISSUE TITLE
Sample app buildable standalone

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#959]
It is not currently easy to test that an app can be built against a CCF install before a new version of CCF is released. This means that it is possible that we release a version of CCF that cannot be used out-of-the-box to build a CCF app (like it was the case for all versions until v0.8.2). 

We could fix this by making one of our sample apps (probably `logging` as it is the one we document) buildable standalone. It would then be easy to, from our release pipeline, install CCF, checkout the _same_ repo and build the app pointing at the freshly-installed CCF.

**Comment by achamayou** [comment]
Dupe #1028
