### ISSUE TITLE
Endpoints should look like HTTP resources

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#968]
Our method names inherited from JSON-RPC are looking increasingly out-of-place. We should do a renaming pass: `/users/LOG_get_public` to `GET /users/log/public` or similar.

We're also considering changing the frontend prefixes, from `users` to `app`, and from `members` to `gov`. It would make sense to do this in the same PR.

**Comment by achamayou** [comment]
Not going to be in time for 0.9, will go in 0.9.1.

**Comment by achamayou** [comment]
We should aim for compliance with https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md as much as possible.
